INSERT INTO screenwriter VALUES ('Charlie Kauffman');
INSERT INTO screenwriter VALUES ('Mike White');
INSERT INTO screenwriter VALUES ('Paul Schrader');
INSERT INTO screenwriter VALUES ('Paul Haggis');
INSERT INTO screenwriter VALUES ('Christopher McQuarrie');
INSERT INTO screenwriter VALUES ('Mike Rich');
INSERT INTO screenwriter VALUES ('Matt Damon');
INSERT INTO screenwriter VALUES ('Ben Affleck');
INSERT INTO screenwriter VALUES ('Lawrence Kasden');
INSERT INTO screenwriter VALUES ('Brian Helgeland');
INSERT INTO screenwriter VALUES ('David Mamet');
INSERT INTO screenwriter VALUES ('William Goldman');
INSERT INTO screenwriter VALUES ('Stanley Kubrick');
INSERT INTO screenwriter VALUES ('Paul Thomas Anderson');
INSERT INTO screenwriter VALUES ('Owen Wilson');
INSERT INTO screenwriter VALUES ('Wes Anderson');
INSERT INTO screenwriter VALUES ('Eric Roth');
INSERT INTO screenwriter VALUES ('Quentin Tarantino');
INSERT INTO screenwriter VALUES ('The Coen Brothers');
INSERT INTO screenwriter VALUES ('Arthur C. Clark');
INSERT INTO screenwriter VALUES ('Noah Baumbach');
INSERT INTO screenwriter VALUES ('Herman J. Mankiewicz');
INSERT INTO screenwriter VALUES ('Orson Welles');
INSERT INTO screenwriter VALUES ('Oliver Stone');
INSERT INTO screenwriter VALUES ('Francis Ford Coppola');
INSERT INTO screenwriter VALUES ('Robert Benton');
INSERT INTO screenwriter VALUES ('Billy Wilder');
INSERT INTO screenwriter VALUES ('Cameron Crowe');
