INSERT INTO actor VALUES ('Christian Bale');
INSERT INTO actor VALUES ('Marlon Brando');
INSERT INTO actor VALUES ('Robert DiNiro');
INSERT INTO actor VALUES ('Tom Hanks');
INSERT INTO actor VALUES ('Dustin Hoffman');
INSERT INTO actor VALUES ('Phillip Seymour Hoffman');
INSERT INTO actor VALUES ('John Malkovich');
INSERT INTO actor VALUES ('Ewan McGregor');
INSERT INTO actor VALUES ('Jack Nicholson');
INSERT INTO actor VALUES ('Edward Norton');
INSERT INTO actor VALUES ('Sean Penn');
INSERT INTO actor VALUES ('Meryl Streep');
INSERT INTO actor VALUES ('Brad Pitt');
INSERT INTO actor VALUES ('Johnny Depp');
INSERT INTO actor VALUES ('Billy Crudup');
INSERT INTO actor VALUES ('George Clooney');
INSERT INTO actor VALUES ('Daniel Day Lewis');
INSERT INTO actor VALUES ('Leonardo DiCaprio');
INSERT INTO actor VALUES ('Orson Welles');
INSERT INTO actor VALUES ('Clint Eastwood');
INSERT INTO actor VALUES ('Matt Damon');
INSERT INTO actor VALUES ('Katherine Hepburn');
INSERT INTO actor VALUES ('Humphrey Bogart');
INSERT INTO actor VALUES ('Jimmy Stewart');
INSERT INTO actor VALUES ('Cary Grant');
INSERT INTO actor VALUES ('Robert Mitchum');
INSERT INTO actor VALUES ('Harrison Ford');
INSERT INTO actor VALUES ('Benicio Del Toro');
INSERT INTO actor VALUES ('Tommy Lee Jones');
INSERT INTO actor VALUES ('Viggo Mortenson');
INSERT INTO actor VALUES ('Javier Bardem');
INSERT INTO actor VALUES ('Ryan Gosling');
INSERT INTO actor VALUES ('Robert Downy Jr.');
