INSERT INTO shot VALUES ('Schindler's List', 1993, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Little Giants', 1994, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Jerry Maguire', 1996, 'Janusz Kaminski');
INSERT INTO shot VALUES ('The Lost World: Jurassic Park', 1997, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Amistad', 1997, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Saving Private Ryan', 1998, 'Janusz Kaminski');
INSERT INTO shot VALUES ('A.I. Artificial Intelligence', 2001, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Minority Report', 2002, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Catch Me if You Can', 2002, 'Janusz Kaminski');
INSERT INTO shot VALUES ('The Terminal', 2004, 'Janusz Kaminski');
INSERT INTO shot VALUES ('War of the Worlds', 2005, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Munich', 2005, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Indiana Jones and the Kingdom of the Crystal Skull', 2008, 'Janusz Kaminski');
INSERT INTO shot VALUES ('Jaws', 1975, 'Bill Butler');
INSERT INTO shot VALUES ('Rocky II', 1979, 'Bill Butler');
INSERT INTO shot VALUES ('Rocky III', 1982, 'Bill Butler');
INSERT INTO shot VALUES ('Rocky IV', 1985, 'Bill Butler');
INSERT INTO shot VALUES ('Biloxi Blues', 1988, 'Bill Butler');
INSERT INTO shot VALUES ('Sniper', 1993, 'Bill Butler');
INSERT INTO shot VALUES ('Cop and ½', 1993, 'Bill Butler');
INSERT INTO shot VALUES ('Anaconda', 1997, 'Bill Butler');
INSERT INTO shot VALUES ('Frailty', 2001, 'Bill Butler');
INSERT INTO shot VALUES ('Who''s Afraid of Virginia Woolf?', 1966, 'Haskell Wexler');
INSERT INTO shot VALUES ('In the Heat of the Night', 1967, 'Haskell Wexler');
INSERT INTO shot VALUES ('One Flew Over the Cuckoo''s Nest', 1975, 'Haskell Wexler');
INSERT INTO shot VALUES ('Coming Home', 1978, 'Haskell Wexler');
INSERT INTO shot VALUES ('Matewan', 1987, 'Haskell Wexler');
INSERT INTO shot VALUES ('Colors', 1988, 'Haskell Wexler');
INSERT INTO shot VALUES ('Three Fugitives', 1989, 'Haskell Wexler');
INSERT INTO shot VALUES ('The Babe', 1992, 'Haskell Wexler');
INSERT INTO shot VALUES ('Canadian Bacon', 1995, 'Haskell Wexler');
INSERT INTO shot VALUES ('Limbo', 1999, 'Haskell Wexler');
INSERT INTO shot VALUES ('Silver City', 2004, 'Haskell Wexler');
INSERT INTO shot VALUES ('Pi', 1998, 'Matthew Libatique');
INSERT INTO shot VALUES ('Requiem for a Dream', 2000, 'Matthew Libatique');
INSERT INTO shot VALUES ('Tigerland', 2000, 'Matthew Libatique');
INSERT INTO shot VALUES ('Phone Booth', 2002, 'Matthew Libatique');
INSERT INTO shot VALUES ('She Hate Me', 2004, 'Matthew Libatique');
INSERT INTO shot VALUES ('Everything is Illuminated', 2005, 'Matthew Libatique');
INSERT INTO shot VALUES ('Inside Man', 2006, 'Matthew Libatique');
INSERT INTO shot VALUES ('The Fountain', 2006, 'Matthew Libatique');
INSERT INTO shot VALUES ('The Number 23', 2007, 'Matthew Libatique');
INSERT INTO shot VALUES ('Iron Man', 2008, 'Matthew Libatique');
INSERT INTO shot VALUES ('Miracle at St. Anna', 2008, 'Matthew Libatique');
INSERT INTO shot VALUES ('The Sure Thing', 1985, 'Robert Elswit');
INSERT INTO shot VALUES ('The Hand That Rocks the Cradle', 1992, 'Robert Elswit');
INSERT INTO shot VALUES ('The River Wild', 1994, 'Robert Elswit');
INSERT INTO shot VALUES ('Hard Eight', 1996, 'Robert Elswit');
INSERT INTO shot VALUES ('Boogie Nights', 1997, 'Robert Elswit');
INSERT INTO shot VALUES ('Magnolia', 1999, 'Robert Elswit');
INSERT INTO shot VALUES ('Heist', 2001, 'Robert Elswit');
INSERT INTO shot VALUES ('Punch-Drunk Love', 2002, 'Robert Elswit');
INSERT INTO shot VALUES ('Gigli', 2003, 'Robert Elswit');
INSERT INTO shot VALUES ('Good Night, and Good Luck', 2005, 'Robert Elswit');
INSERT INTO shot VALUES ('Syriana', 2005, 'Robert Elswit');
INSERT INTO shot VALUES ('Michael Clayton', 2007, 'Robert Elswit');
INSERT INTO shot VALUES ('There Will Be Blood', 2007, 'Robert Elswit');
INSERT INTO shot VALUES ('Sid and Nancy', 1986, 'Roger Deakins');
INSERT INTO shot VALUES ('Barton Fink', 1991, 'Roger Deakins');
INSERT INTO shot VALUES ('Passion Fish', 1992, 'Roger Deakins');
INSERT INTO shot VALUES ('The Secret Garden', 1993, 'Roger Deakins');
INSERT INTO shot VALUES ('The Hudsucker Proxy', 1994, 'Roger Deakins');
INSERT INTO shot VALUES ('The Shawshank Redemption', 1994, 'Roger Deakins');
INSERT INTO shot VALUES ('Dead Man Walking', 1995, 'Roger Deakins');
INSERT INTO shot VALUES ('Fargo', 1996, 'Roger Deakins');
INSERT INTO shot VALUES ('Courage Under Fire', 1996, 'Roger Deakins');
INSERT INTO shot VALUES ('Kundun', 1997, 'Roger Deakins');
INSERT INTO shot VALUES ('The Big Lebowski', 1998, 'Roger Deakins');
INSERT INTO shot VALUES ('The Hurricane', 1999, 'Roger Deakins');
INSERT INTO shot VALUES ('O Brother, Where Art Thou?', 2000, 'Roger Deakins');
INSERT INTO shot VALUES ('Thirteen Days', 2000, 'Roger Deakins');
INSERT INTO shot VALUES ('The Man Who Wasn''t There', 2001, 'Roger Deakins');
INSERT INTO shot VALUES ('A Beautiful Mind', 2001, 'Roger Deakins');
INSERT INTO shot VALUES ('Intolerable Cruelty', 2003, 'Roger Deakins');
INSERT INTO shot VALUES ('House of Sand and Fog', 2003, 'Roger Deakins');
INSERT INTO shot VALUES ('The Ladykillers', 2004, 'Roger Deakins');
INSERT INTO shot VALUES ('The Village', 2004, 'Roger Deakins');
INSERT INTO shot VALUES ('Jarhead', 2005, 'Roger Deakins');
INSERT INTO shot VALUES ('No Country for Old Men', 2007, 'Roger Deakins');
INSERT INTO shot VALUES ('The Assassination of Jesse James by the Cowardly Robert Ford', 2007, 'Roger Deakins');
INSERT INTO shot VALUES ('Doubt', 2008, 'Roger Deakins');
INSERT INTO shot VALUES ('Revolutionary Road', 2008, 'Roger Deakins');
INSERT INTO shot VALUES ('A Serious Man', 2009, 'Roger Deakins');
INSERT INTO shot VALUES ('The Money Pit', 1986, 'Gordon Willis');
INSERT INTO shot VALUES ('The Devil''s Own', 1997, 'Gordon Willis');
INSERT INTO shot VALUES ('Klute', 1971, 'Gordon Willis');
INSERT INTO shot VALUES ('The Godfather', 1972, 'Gordon Willis');
INSERT INTO shot VALUES ('The Parallax View', 1974, 'Gordon Willis');
INSERT INTO shot VALUES ('The Godfather Part II', 1974, 'Gordon Willis');
INSERT INTO shot VALUES ('All the President''s Men', 1976, 'Gordon Willis');
INSERT INTO shot VALUES ('Annie Hall', 1977, 'Gordon Willis');
INSERT INTO shot VALUES ('Interiors', 1978, 'Gordon Willis');
INSERT INTO shot VALUES ('Manhattan', 1979, 'Gordon Willis');
INSERT INTO shot VALUES ('Stardust Memories', 1980, 'Gordon Willis');
INSERT INTO shot VALUES ('A Midsummer Night''s Sex Comedy', 1982, 'Gordon Willis');
INSERT INTO shot VALUES ('Zelig', 1983, 'Gordon Willis');
INSERT INTO shot VALUES ('Broadway Danny Rose', 1984, 'Gordon Willis');
INSERT INTO shot VALUES ('The Purple Rose of Cairo', 1985, 'Gordon Willis');
INSERT INTO shot VALUES ('Bright Lights, Big City', 1988, 'Gordon Willis');
INSERT INTO shot VALUES ('The Godfather Part III', 1990, 'Gordon Willis');
INSERT INTO shot VALUES ('Presumed Innocent', 1990, 'Gordon Willis');
INSERT INTO shot VALUES ('The Conformist', 1970, 'Vittorio Storaro');
INSERT INTO shot VALUES ('The Spider''s Strategem', 1970, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Last Tango in Paris', 1972, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Agatha', 1979, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Apocalypse Now', 1979, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Reds', 1981, 'Vittorio Storaro');
INSERT INTO shot VALUES ('One from the Heart', 1982, 'Vittorio Storaro');
INSERT INTO shot VALUES ('The Last Emperor', 1987, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Tucker: The Man and His Dream', 1988, 'Vittorio Storaro');
INSERT INTO shot VALUES ('New York Stories: Life Without Zoe [Francis Coppola short]', 1989, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Dick Tracy', 1990, 'Vittorio Storaro');
INSERT INTO shot VALUES ('The Sheltering Sky', 1990, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Little Buddha', 1993, 'Vittorio Storaro');
INSERT INTO shot VALUES ('Sawdust and Tinsel', 1953, 'Sven Nykvist');
INSERT INTO shot VALUES ('The Virgin Spring', 1960, 'Sven Nykvist');
INSERT INTO shot VALUES ('Through a Glass Darkly', 1961, 'Sven Nykvist');
INSERT INTO shot VALUES ('Winter Light', 1962, 'Sven Nykvist');
INSERT INTO shot VALUES ('The Silence', 1963, 'Sven Nykvist');
INSERT INTO shot VALUES ('Persona', 1966, 'Sven Nykvist');
INSERT INTO shot VALUES ('Hour of the Wolf', 1968, 'Sven Nykvist');
INSERT INTO shot VALUES ('Shame', 1968, 'Sven Nykvist');
INSERT INTO shot VALUES ('The Passion of Anna', 1969, 'Sven Nykvist');
INSERT INTO shot VALUES ('Cries and Whispers', 1972, 'Sven Nykvist');
INSERT INTO shot VALUES ('Scenes from a Marriage', 1973, 'Sven Nykvist');
INSERT INTO shot VALUES ('The Magic Flute', 1975, 'Sven Nykvist');
INSERT INTO shot VALUES ('Face to Face', 1976, 'Sven Nykvist');
INSERT INTO shot VALUES ('The Serpent''s Egg', 1977, 'Sven Nykvist');
INSERT INTO shot VALUES ('Autumn Sonata', 1978, 'Sven Nykvist');
INSERT INTO shot VALUES ('Fammy and Alexander', 1982, 'Sven Nykvist');
INSERT INTO shot VALUES ('New York Stories: Oedipus Wrecks [Woody Allen short]', 1989, 'Sven Nykvist');
INSERT INTO shot VALUES ('The Unbearable Lightness of Being', 1988, 'Sven Nykvist');
INSERT INTO shot VALUES ('Another Woman', 1988, 'Sven Nykvist');
INSERT INTO shot VALUES ('Crimes and Misdemeanors', 1989, 'Sven Nykvist');
INSERT INTO shot VALUES ('Chaplin', 1992, 'Sven Nykvist');
INSERT INTO shot VALUES ('Sleepless in Seattle', 1993, 'Sven Nykvist');
INSERT INTO shot VALUES ('What''s Eating Gilbert Grape', 1993, 'Sven Nykvist');
INSERT INTO shot VALUES ('The Tenant', 1976, 'Sven Nykvist');
INSERT INTO shot VALUES ('Celebrity', 1998, 'Sven Nykvist');
INSERT INTO shot VALUES ('Only You', 1994, 'Sven Nykvist');
INSERT INTO shot VALUES ('Cool Hand Luke', 1967, 'Conrad Hall');
INSERT INTO shot VALUES ('In Cold Blood', 1967, 'Conrad Hall');
INSERT INTO shot VALUES ('Butch Cassidy and the Sundance Kid', 1969, 'Conrad Hall');
INSERT INTO shot VALUES ('Marathon Man', 1976, 'Conrad Hall');
INSERT INTO shot VALUES ('Searching For Bobby Fischer', 1993, 'Conrad Hall');
INSERT INTO shot VALUES ('A Civil Action', 1998, 'Conrad Hall');
INSERT INTO shot VALUES ('American Beauty', 1999, 'Conrad Hall');
INSERT INTO shot VALUES ('Road to Perdition', 2002, 'Conrad Hall');
INSERT INTO shot VALUES ('Legends of the Fall', 1994, 'John Toll');
INSERT INTO shot VALUES ('The Rainmaker', 1997, 'John Toll');
INSERT INTO shot VALUES ('The Thin Red Line', 1998, 'John Toll');
INSERT INTO shot VALUES ('Almost Famous', 2000, 'John Toll');
INSERT INTO shot VALUES ('Vanilla Sky', 2001, 'John Toll');
INSERT INTO shot VALUES ('The Last Samurai', 2003, 'John Toll');
INSERT INTO shot VALUES ('Elizabethtown', 2005, 'John Toll');
INSERT INTO shot VALUES ('Gone Baby Gone', 2007, 'John Toll');
INSERT INTO shot VALUES ('Tropic Thunder', 2008, 'John Toll');
INSERT INTO shot VALUES ('Days of Heaven', 1978, 'Nestor Almendros');
INSERT INTO shot VALUES ('Goin'' South', 1978, 'Nestor Almendros');
INSERT INTO shot VALUES ('Kramer Vs. Kramer', 1979, 'Nestor Almendros');
INSERT INTO shot VALUES ('Sophie''s Choice', 1982, 'Nestor Almendros');
INSERT INTO shot VALUES ('Places in the Heart', 1984, 'Nestor Almendros');
INSERT INTO shot VALUES ('Imagine: John Lennon', 1988, 'Nestor Almendros');
INSERT INTO shot VALUES ('New York Stories: Life Lessons [Martin Scorsese short]', 1989, 'Nestor Almendros');
INSERT INTO shot VALUES ('Two English Girls', 1972, 'Nestor Almendros');
INSERT INTO shot VALUES ('A Clockwork Orange', 1971, 'John Alcott');
INSERT INTO shot VALUES ('Barry Lyndon', 1975, 'John Alcott');
INSERT INTO shot VALUES ('The Shining', 1980, 'John Alcott');
INSERT INTO shot VALUES ('No Way Out', 1987, 'John Alcott');
INSERT INTO shot VALUES ('White Water Summer', 1987, 'John Alcott');
INSERT INTO shot VALUES ('George Washington', 2000, 'Tim Orr');
INSERT INTO shot VALUES ('Pineapple Express', 2008, 'Tim Orr');
INSERT INTO shot VALUES ('Snow Angels', 2007, 'Tim Orr');
INSERT INTO shot VALUES ('Undertow', 2004, 'Tim Orr');
INSERT INTO shot VALUES ('All the Real Girls', 2003, 'Tim Orr');
INSERT INTO shot VALUES ('Citizen Kane', 1941, 'Gregg Toland');
INSERT INTO shot VALUES ('The Grapes of Wrath', 1940, 'Gregg Toland');
INSERT INTO shot VALUES ('The Best Years of Our Lives', 1946, 'Gregg Toland');
INSERT INTO shot VALUES ('The Best Years of Our Lives', 1946, 'Gregg Toland');
