INSERT INTO director VALUES ('Woody Allen');
INSERT INTO director VALUES ('Robert Altman');
INSERT INTO director VALUES ('Paul Thomas Anderson');
INSERT INTO director VALUES ('Wes Anderson');
INSERT INTO director VALUES ('Michelangelo Antonioni');
INSERT INTO director VALUES ('Michael Apted');
INSERT INTO director VALUES ('Gillian Armstrong');
INSERT INTO director VALUES ('Darren Aronofsky');
INSERT INTO director VALUES ('Ingmar Bergman');
INSERT INTO director VALUES ('Bernardo Bertolucci');
INSERT INTO director VALUES ('Luc Besson');
INSERT INTO director VALUES ('Peter Bogdanovich');
INSERT INTO director VALUES ('John Boorman');
INSERT INTO director VALUES ('Danny Boyle');
INSERT INTO director VALUES ('Robert Bresson');
INSERT INTO director VALUES ('Luis Bunuel');
INSERT INTO director VALUES ('Tim Burton');
INSERT INTO director VALUES ('James Cameron');
INSERT INTO director VALUES ('Jane Campion');
INSERT INTO director VALUES ('Frank Capra');
INSERT INTO director VALUES ('John Cassavetes');
INSERT INTO director VALUES ('Charlie Chaplin');
INSERT INTO director VALUES ('Jean Cocteau');
INSERT INTO director VALUES ('The Coen Brothers');
INSERT INTO director VALUES ('Chris Columbus');
INSERT INTO director VALUES ('Francis Ford Coppola');
INSERT INTO director VALUES ('Sofia Coppola');
INSERT INTO director VALUES ('David Cronenberg');
INSERT INTO director VALUES ('Cameron Crowe');
INSERT INTO director VALUES ('Frank Darabont');
INSERT INTO director VALUES ('Brian De Palma');
INSERT INTO director VALUES ('Vittorio De Sica');
INSERT INTO director VALUES ('Guillermo del Toro');
INSERT INTO director VALUES ('Jonathan Demme');
INSERT INTO director VALUES ('Clint Eastwood');
INSERT INTO director VALUES ('Sergei Eisenstein');
INSERT INTO director VALUES ('The Farelly Brothers');
INSERT INTO director VALUES ('Frederico Fellini');
INSERT INTO director VALUES ('Mike Figgis');
INSERT INTO director VALUES ('David Fincher');
INSERT INTO director VALUES ('Milos Forman');
INSERT INTO director VALUES ('Stephen Frears');
INSERT INTO director VALUES ('William Friedkin');
INSERT INTO director VALUES ('Samuel Fuller');
INSERT INTO director VALUES ('Mel Gibson');
INSERT INTO director VALUES ('Terry Gilliam');
INSERT INTO director VALUES ('Jean-Luc Godard');
INSERT INTO director VALUES ('Michel Gondry');
INSERT INTO director VALUES ('David Gordon Green');
INSERT INTO director VALUES ('Christopher Guest');
INSERT INTO director VALUES ('Todd Haynes');
INSERT INTO director VALUES ('Werner Herzog');
INSERT INTO director VALUES ('Alfred Hitchcock');
INSERT INTO director VALUES ('Ron Howard');
INSERT INTO director VALUES ('John Huston');
INSERT INTO director VALUES ('Peter Jackson');
INSERT INTO director VALUES ('Jim Jarmusch');
INSERT INTO director VALUES ('Jean-Pierre Jeunet');
INSERT INTO director VALUES ('Norman Jewison');
INSERT INTO director VALUES ('Spike Jonze');
INSERT INTO director VALUES ('Neil Jordan');
INSERT INTO director VALUES ('Lawrence Kasdan');
INSERT INTO director VALUES ('Elia Kazan');
INSERT INTO director VALUES ('Buster Keaton');
INSERT INTO director VALUES ('Krzysztof Kieslowski');
INSERT INTO director VALUES ('Barbara Kopple');
INSERT INTO director VALUES ('Stanley Kubrick');
INSERT INTO director VALUES ('Akira Kurosawa');
INSERT INTO director VALUES ('Neil LaBute');
INSERT INTO director VALUES ('Fritz Lang');
INSERT INTO director VALUES ('David Lean');
INSERT INTO director VALUES ('Spike Lee');
INSERT INTO director VALUES ('Mike Leigh');
INSERT INTO director VALUES ('Sergio Leone');
INSERT INTO director VALUES ('Barry Levinson');
INSERT INTO director VALUES ('Richard Linklater');
INSERT INTO director VALUES ('George Lucas');
INSERT INTO director VALUES ('Sidney Lumet');
INSERT INTO director VALUES ('David Lynch');
INSERT INTO director VALUES ('Majid Majidi');
INSERT INTO director VALUES ('Terrence Malick');
INSERT INTO director VALUES ('Louis Malle');
INSERT INTO director VALUES ('David Mamet');
INSERT INTO director VALUES ('James Mangold');
INSERT INTO director VALUES ('Michael Mann');
INSERT INTO director VALUES ('Sam Mendes');
INSERT INTO director VALUES ('Penny Marshall');
INSERT INTO director VALUES ('Hayao Miyazaki');
INSERT INTO director VALUES ('Michael Moore');
INSERT INTO director VALUES ('Errol Morris');
INSERT INTO director VALUES ('F. W. Murneau');
INSERT INTO director VALUES ('Mike Nichols');
INSERT INTO director VALUES ('Christopher Nolan');
INSERT INTO director VALUES ('Alan Parker');
INSERT INTO director VALUES ('Alan J. Pakula');
INSERT INTO director VALUES ('Alexander Payne');
INSERT INTO director VALUES ('Sam Peckinpah');
INSERT INTO director VALUES ('Arthur Penn');
INSERT INTO director VALUES ('Sean Penn');
INSERT INTO director VALUES ('Wolfgang Petersen');
INSERT INTO director VALUES ('Roman Polanski');
INSERT INTO director VALUES ('The Polish brothers');
INSERT INTO director VALUES ('Satyajit Ray');
INSERT INTO director VALUES ('Robert Redford');
INSERT INTO director VALUES ('Rob Reiner');
INSERT INTO director VALUES ('Jean Renoir');
INSERT INTO director VALUES ('Guy Ritchie');
INSERT INTO director VALUES ('David O. Russell');
INSERT INTO director VALUES ('John Sayles');
INSERT INTO director VALUES ('John Schlesinger');
INSERT INTO director VALUES ('Martin Scorsese');
INSERT INTO director VALUES ('Ridley Scott');
INSERT INTO director VALUES ('Jim Sheridan');
INSERT INTO director VALUES ('M. Night Shyamalan');
INSERT INTO director VALUES ('Bryan Singer');
INSERT INTO director VALUES ('Steven Soderbergh');
INSERT INTO director VALUES ('Steven Spielberg');
INSERT INTO director VALUES ('Oliver Stone');
INSERT INTO director VALUES ('Quentin Tarantino');
INSERT INTO director VALUES ('Andrei Tarkovsky');
INSERT INTO director VALUES ('Jacques Tati');
INSERT INTO director VALUES ('Francios Truffaut');
INSERT INTO director VALUES ('Tom Tykwer');
INSERT INTO director VALUES ('Gus Van Sant');
INSERT INTO director VALUES ('Jean Vigo');
INSERT INTO director VALUES ('Lars Von Trier');
INSERT INTO director VALUES ('Peter Weir');
INSERT INTO director VALUES ('Orson Welles');
INSERT INTO director VALUES ('Wim Wenders');
INSERT INTO director VALUES ('Billy Wilder');
INSERT INTO director VALUES ('Michael Winterbottom');
INSERT INTO director VALUES ('Robert Zemeckis');
