INSERT INTO wrote VALUES ('Synecdoche, New York', 2008, 'Charlie Kauffman');
INSERT INTO wrote VALUES ('Eternal Sunshine of the Spotless Mind', 2004, 'Charlie Kauffman');
INSERT INTO wrote VALUES ('Adaptation', 2002, 'Charlie Kauffman');
INSERT INTO wrote VALUES ('Human Nature', 2001, 'Charlie Kauffman');
INSERT INTO wrote VALUES ('Being John Malkovich', 1999, 'Charlie Kauffman');
INSERT INTO wrote VALUES ('Dead Man on Campus', 1998, 'Mike White');
INSERT INTO wrote VALUES ('Chuck & Buck', 2000, 'Mike White');
INSERT INTO wrote VALUES ('Orange County', 2002, 'Mike White');
INSERT INTO wrote VALUES ('The Good Girl', 2002, 'Mike White');
INSERT INTO wrote VALUES ('The School of Rock', 2003, 'Mike White');
INSERT INTO wrote VALUES ('Nacho Libre', 2006, 'Mike White');
INSERT INTO wrote VALUES ('Year of the Dog', 2007, 'Mike White');
INSERT INTO wrote VALUES ('Taxi Driver', 1976, 'Paul Schrader');
INSERT INTO wrote VALUES ('Raging Bull', 1980, 'Paul Schrader');
INSERT INTO wrote VALUES ('The Mosquito Coast', 1986, 'Paul Schrader');
INSERT INTO wrote VALUES ('The Last Temptation of Christ', 1988, 'Paul Schrader');
INSERT INTO wrote VALUES ('City Hall', 1996, 'Paul Schrader');
INSERT INTO wrote VALUES ('Affliction', 1997, 'Paul Schrader');
INSERT INTO wrote VALUES ('Bringing Out the Dead', 1999, 'Paul Schrader');
INSERT INTO wrote VALUES ('Crash', 2005, 'Paul Haggis');
INSERT INTO wrote VALUES ('Million Dollar Baby', 2004, 'Paul Haggis');
INSERT INTO wrote VALUES ('Flags of Our Fathers', 2006, 'Paul Haggis');
INSERT INTO wrote VALUES ('Casino Royale', 2006, 'Paul Haggis');
INSERT INTO wrote VALUES ('Letters From Iwo Jima', 2006, 'Paul Haggis');
INSERT INTO wrote VALUES ('In the Valley of Elah', 2007, 'Paul Haggis');
INSERT INTO wrote VALUES ('Quantum of Solace', 2008, 'Paul Haggis');
INSERT INTO wrote VALUES ('The Usual Suspects', 1995, 'Christopher McQuarrie');
INSERT INTO wrote VALUES ('The Way of the Gun', 2000, 'Christopher McQuarrie');
INSERT INTO wrote VALUES ('Valkyrie', 2008, 'Christopher McQuarrie');
INSERT INTO wrote VALUES ('Finding Forrester', 2000, 'Mike Rich');
INSERT INTO wrote VALUES ('The Rookie', 2002, 'Mike Rich');
INSERT INTO wrote VALUES ('Radio', 2003, 'Mike Rich');
INSERT INTO wrote VALUES ('Miracle', 2004, 'Mike Rich');
INSERT INTO wrote VALUES ('The Nativity Story', 2006, 'Mike Rich');
INSERT INTO wrote VALUES ('Good Will Hunting', 1997, 'Matt Damon');
INSERT INTO wrote VALUES ('Good Will Hunting', 1997, 'Ben Affleck');
INSERT INTO wrote VALUES ('Star Wars Episode V: The Empire Strikes Back', 1980, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Raiders of the Lost Ark', 1981, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Body Heat', 1981, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Star Wars Episode VI: Return of the Jedi', 1983, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('The Big Chill', 1983, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Silverado', 1985, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('The Accidental Tourist', 1988, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Grand Canyon', 1991, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('The Bodyguard', 1992, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Wyatt Earp', 1994, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Mumford', 1999, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('Dreamcatcher', 2003, 'Lawrence Kasden');
INSERT INTO wrote VALUES ('L.A. Confidential', 1997, 'Brian Helgeland');
INSERT INTO wrote VALUES ('Conspiracy Theory', 1997, 'Brian Helgeland');
INSERT INTO wrote VALUES ('The Postman', 1997, 'Brian Helgeland');
INSERT INTO wrote VALUES ('Payback', 1999, 'Brian Helgeland');
INSERT INTO wrote VALUES ('A Knight''s Tale', 2001, 'Brian Helgeland');
INSERT INTO wrote VALUES ('Blood Work', 2002, 'Brian Helgeland');
INSERT INTO wrote VALUES ('Mystic River', 2003, 'Brian Helgeland');
INSERT INTO wrote VALUES ('The Order', 2003, 'Brian Helgeland');
INSERT INTO wrote VALUES ('Man on Fire', 2004, 'Brian Helgeland');
INSERT INTO wrote VALUES ('The Postman Always Rings Twice', 1981, 'David Mamet');
INSERT INTO wrote VALUES ('The Verdict', 1982, 'David Mamet');
INSERT INTO wrote VALUES ('The Untouchables', 1987, 'David Mamet');
INSERT INTO wrote VALUES ('House of Games', 1987, 'David Mamet');
INSERT INTO wrote VALUES ('Things Change', 1988, 'David Mamet');
INSERT INTO wrote VALUES ('We''re No Angels', 1989, 'David Mamet');
INSERT INTO wrote VALUES ('Homicide', 1991, 'David Mamet');
INSERT INTO wrote VALUES ('Hoffa', 1992, 'David Mamet');
INSERT INTO wrote VALUES ('Glengarry Glen Ross', 1992, 'David Mamet');
INSERT INTO wrote VALUES ('Vanya on 42nd Street', 1994, 'David Mamet');
INSERT INTO wrote VALUES ('Oleanna', 1994, 'David Mamet');
INSERT INTO wrote VALUES ('American Buffalo', 1996, 'David Mamet');
INSERT INTO wrote VALUES ('The Edge', 1997, 'David Mamet');
INSERT INTO wrote VALUES ('The Spanish Prisoner', 1998, 'David Mamet');
INSERT INTO wrote VALUES ('Wag the Dog', 1998, 'David Mamet');
INSERT INTO wrote VALUES ('The Winslow Boy', 1999, 'David Mamet');
INSERT INTO wrote VALUES ('State and Main', 2000, 'David Mamet');
INSERT INTO wrote VALUES ('Hannibal', 2001, 'David Mamet');
INSERT INTO wrote VALUES ('Heist', 2001, 'David Mamet');
INSERT INTO wrote VALUES ('Spartan', 2004, 'David Mamet');
INSERT INTO wrote VALUES ('Edmond', 2005, 'David Mamet');
INSERT INTO wrote VALUES ('Redbelt', 2008, 'David Mamet');
INSERT INTO wrote VALUES ('Butch Cassidy and the Sundance Kid', 1969, 'William Goldman');
INSERT INTO wrote VALUES ('The Hot Rock', 1972, 'William Goldman');
INSERT INTO wrote VALUES ('The Stepford Wives', 1975, 'William Goldman');
INSERT INTO wrote VALUES ('The Great Waldo Pepper', 1975, 'William Goldman');
INSERT INTO wrote VALUES ('All the President''s Men', 1976, 'William Goldman');
INSERT INTO wrote VALUES ('Marathon Man', 1976, 'William Goldman');
INSERT INTO wrote VALUES ('A Bridge Too Far', 1977, 'William Goldman');
INSERT INTO wrote VALUES ('The Princess Bride', 1987, 'William Goldman');
INSERT INTO wrote VALUES ('Misery', 1990, 'William Goldman');
INSERT INTO wrote VALUES ('Chaplin', 1992, 'William Goldman');
INSERT INTO wrote VALUES ('Maverick', 1994, 'William Goldman');
INSERT INTO wrote VALUES ('The Ghost and the Darkness', 1996, 'William Goldman');
INSERT INTO wrote VALUES ('The Chamber', 1996, 'William Goldman');
INSERT INTO wrote VALUES ('Absolute Power', 1997, 'William Goldman');
INSERT INTO wrote VALUES ('The General''s Daughter', 1999, 'William Goldman');
INSERT INTO wrote VALUES ('Hearts in Atlantis', 2001, 'William Goldman');
INSERT INTO wrote VALUES ('Dreamcatcher', 2003, 'William Goldman');
