INSERT INTO movie VALUES ('Everything You Always Wanted to Know About Sex But Were Afraid to Ask', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Midsummer Night''s Sex Comedy', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Alice', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Melinda and Melinda', 2004, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Match Point', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Scoop', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Cassandra''s Dream', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Vicky Cristina Barcelona', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Delinquents', 1957, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Countdown', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('That Cold Day in the Park', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Brewster Mccloud', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Thieves Like Us', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Wedding', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Quintet', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Perfect Couple', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('H.E.A.L.T.H.', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Come Back to the Five and Dime, Jimmy Dean, Jimmy Dean', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Streamers', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('O.C. & Stiggs', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Fool For Love', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Vincent and Theo', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jazz ''34', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Prairie Home Companion', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Story of a Love Affair', 1950, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Vanquished', 1952, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Tthe Lady Without Camellias', 1953, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Girlfriends', 1955, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Cry', 1957, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('La Notte', 1961, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The eclipse', 1962, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Zabriskie Point', 1969, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Chung Kuo Cina', 1972, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Oberwald Mystery', 1980, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Identification of a Woman', 1982, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Beyond the Clouds', 1995, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Eros', 2004, DEFAULT, 'DEFAULT', 'not seen');
INSERT INTO movie VALUES ('Triple Echo', 1973, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Stardust', 1974, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Squeeze', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Agatha', 1979, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Continental Divide', 1981, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Gorky Park', 1983, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Bring on the Night', 1985, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Critical Condition', 1987, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Gorlllias in the Mist', 1988, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Class Action', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Thunderheart', 1992, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Incident at Oglala', 1992, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Blink', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Moving in the Mountain', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Nell', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Inspirations', 1997, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Me & Isaac Newton', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The World Is Not Enough', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Enigma', 2001, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Enough', 2002, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('49 Up', 2005, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Amazing Grace', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Power of the Game', 2007, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Singer and the Dancer', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Starstruck', 1982, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Mrs. Soffel', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Fires Within', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Last Days of Chez Nous', 1992, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Not Fourteen Again', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Oscar and Lucinda', 1997, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Charlotte Gray', 2001, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Unfolding Florence: The Many Lives of Florence Broadhurst', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Death Defying Acts', 2007, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Wrestler', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Crisis', 1946, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('It Rains on Our Love', 1946, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('A Ship Bound For India', 1947, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Night Is My Future', 1948, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Port of Call', 1948, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('The Devil''s Wanton', 1949, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Three Strange Loves', 1949, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('To Joy', 1950, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('This Can''t Happen Here', 1950, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Summer Interlude', 1951, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Secrets of Women', 1952, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Monika', 1953, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('A Lesson in Love', 1954, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Dreams', 1955, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Smiles of a Summer Night', 1955, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Brink of Life', 1958, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('The Magician', 1958, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('The Devil''s Eye', 1960, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('All These Women', 1964, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Hour of the Wolf', 1968, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Shame', 1968, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('The Faro Document', 1970, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('The Touch', 1970, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Face to Face', 1976, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('The Serpent''s Egg', 1977, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('The Faro Document 1979', 1979, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('From the Life of the Marionettes', 1980, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('After the Rehearsal', 1984, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('In the Presence of a Clown', 1997, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Sarabond', 2005, DEFAULT, 'Sweden', 'not seen');
INSERT INTO movie VALUES ('Before the Revolution', 1962, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Grim Reaper', 1962, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Partner', 1968, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Spider''s Strategem', 1970, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('La Luna', 1979, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Tragedy of a Rediculous Man', 1981, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Sheltering Sky', 1990, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Little Buddha', 1993, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Stealing Beauty', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Besieged', 1998, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Dreamers', 2004, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Subway', 1985, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('La Femme Nikita', 1990, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Angel-A', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Arthur and the Invisibles', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Targets', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Voyage to the Planet of Prehistoric Women', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Directed by John Ford', 1971, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('What''s Up, Doc?', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Daisy Miller', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('At Long Last Love', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Nickelodeon', 1976, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Saint Jack', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('They All Laughed', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Illegally Yours', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Texasville', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Noises Off...', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Thing Called Love', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Tom Petty and the Heartbreakers: Runnin'' Down a Dream', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Having a Wild Weekend', 1965, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Point Blank', 1967, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Hell in the Pacific', 1968, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Leo the Last', 1970, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Zardoz', 1974, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Exorcist II: The Heretic', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Excalibur', 1981, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Emerald Forest', 1985, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Where the Heart Is', 1990, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Beyond Rangoon', 1995, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Lumiere and Company', 1995, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Tailor of Panama', 2001, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('In My Country', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Tiger''s Tail', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Shallow Grave', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Beach', 2000, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Vacuuming Completely Nude in Paradise', 2001, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Millions', 2005, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Angels of the Streets', 1943, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Ladies of Bois De Boulogne', 1945, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('A Man Escaped', 1957, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Trial of Joan of Arc', 1962, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Mouchette', 1967, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('A Gentle Woman', 1969, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Four Nights of a Dreamer', 1971, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Lancelot of the Lake', 1974, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Devil Probably', 1977, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('L''argent', 1983, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Gran Casino', 1947, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Great Madcap', 1949, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Young and the Damned', 1950, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Susana', 1950, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('A Woman Without Love', 1951, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Daughter of Deceit', 1951, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Ascent to Heaven', 1952, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('El', 1952, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Brute', 1952, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Illusion Travels by Streetcar', 1953, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Adventures of Robinson Crusoe', 1954, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The River of Death', 1954, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Wuthering Heights', 1954, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('That Is the Dawn', 1955, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Death in the Garden', 1956, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Nazarín', 1958, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Fever Rises in El Pao', 1959, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Young One', 1960, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Viridiana', 1961, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Diary of a Chambermaid', 1964, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Simon of the Desert', 1965, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Mily Way', 1969, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Phantom of Liberty', 1974, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('That Obscure Object of Desire', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Mars Attacks!', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Alice in Wonderland', 2010, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Piranha II: The Spawning', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Aliens of the Deep', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sweetie', 1989, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Holy Smoke', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('In the Cut', 2003, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('To Each His Cinema', 2007, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Strong Man', 1926, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Long Pants', 1927, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('For the Love of Mike', 1927, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('That Certain Thing', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('So This Is Love?', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Manitee Idol', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Way of the Strong', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Say it With Sables', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Submarine', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Power of the Press', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Younger Generation', 1929, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Donovan Affair', 1929, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Flight', 1929, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Ladies of Leisure', 1930, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Rain Or Shine', 1930, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Dirigible', 1931, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Miracle Woman', 1931, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Platinum Blonde', 1931, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Forbidden', 1932, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('American Madness', 1932, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Bitter Tea of General Yen', 1933, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Lady For a Day', 1933, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Broadway Bill', 1934, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mr. Deeds Goes to Town', 1936, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Lost Horizon', 1937, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('You Can''t Take it With You', 1938, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Meet John Doe', 1941, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Arsenic and Old Lace', 1944, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('State of the Union', 1948, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Riding High', 1950, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Here Comes the Groom', 1951, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Hole in the Head', 1959, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Pocketful of Miracles', 1961, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Shadows', 1959, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Too Late Blues', 1961, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Pair of Boots', 1962, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Child Is Waiting', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Husbands', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Minnie and Moskowitz', 1971, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Killing of a Chinese Bookie', 1976, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Opening Night', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gloria', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Love Streams', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Big Trouble', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A King in New York', 1957, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Countess From Hong Kong', 1967, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Blood of a Poet', 1930, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Eagle Has Two Heads', 1947, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Storm Within', 1948, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Testament of Orpheus', 1960, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('A Serious Man', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Heartbreak Hotel', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Only the Lonely', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Nine Months', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Stepmom', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bicentennial Man', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Rent', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Terror', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Dementia 13', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('You''re a Big Boy Now', 1966, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Finian''s Rainbow', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Rain People', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('One From the Heart', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Rumble Fish', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Tucker: The Man and His Dream', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bram Stoker''s Dracula', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jack', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Youth Without Youth', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Marie Antoinette', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Shivers', 1975, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Rabid', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Fast Company', 1979, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Brood', 1979, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Scanners', 1981, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Videodrome', 1983, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Fly', 1986, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Dead Ringers', 1988, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Naked Lunch', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('M. Butterfly', 1993, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Eastern Promises', 2007, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Elizabethtown', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Murder a La Mod', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Greetings', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Wedding Party', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Hi Mom!', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Get to Know Your Rabbit', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sisters', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Phantom of the Paradise', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Obsession', 1976, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Carrie', 1976, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Fury', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Home Movies', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Dressed to Kill', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Body Double', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Wise Guys', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Casualties of War', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Bonfire of the Vanities', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Raising Cain', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Carlito''s Way', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Femme Fatale', 2002, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Black Dahlia', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Redacted', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Maddelena, Zero For Conduct', 1940, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Teresa Friday', 1941, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('A Garibaldian Covenent', 1942, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Children Are Watching Us', 1944, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Gates of Heaven', 1945, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Shoe-Shine', 1947, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Miracle in Milan', 1951, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Terminal Station', 1953, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Gold of Naples', 1954, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Roof', 1956, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Anna of Brooklyn', 1958, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Two Women', 1960, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Last Judgement', 1961, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Condemned of Altona', 1962, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Il Boom', 1963, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Yesterday, Today, and Tomorrow', 1963, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Marriage Italian-Style', 1964, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('A New World', 1966, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('After the Fox', 1966, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Woman Times Seven', 1967, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Amanti', 1968, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('I Girasoli', 1970, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('We Call Him Andrew', 1972, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('A Brief Vacation', 1973, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Voyage', 1974, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Cronos', 1993, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Mimic', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Devil''s Backbone', 2001, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Blade II', 2002, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Hellboy II: The Golden Army', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Caged Heat', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Crazy Mama', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Fighting Mad', 1976, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Citizen''s Band', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Last Embrace', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Melvin and Howard', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Swing Shift', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Stop Making Sense', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Something Wild', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Swimming to Cambodia', 1987, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Married to the Mob', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Beloved', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Truth About Charlie', 2002, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Neil Young: Heart of Gold', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jimmy Carter Man From Plains', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Play Misty For Me', 1971, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('High Plains Drifter', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Breezy', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Eiger Sanction', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Outlaw Josey Wales', 1976, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Gauntlet', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bronco Billy', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Firefox', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Honkytonk Man', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sudden Impact', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Pale Rider', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Heartbreak Ridge', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bird', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('White Hunter Black Heart', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Rookie', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Perfect World', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Bridges of Madison County', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Absolute Power', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Midnight in the Garden of Good and Evil', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('True Crime', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Blood Work', 2002, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Strike', 1925, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('October', 1927, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('The General Line', 1929, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('Alexander Nevsky', 1938, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('Ivan the Terrible', 1945, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('Ivan the Terrible Part II', 1958, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('Fever Pitch', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Heartbreak Kid', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Variety Lights', 1950, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The White Sheik', 1952, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('I Vitelloni', 1953, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Swindle', 1955, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Spirits of the Dead', 1969, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Casanova', 1976, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Orchestral Rehearsal', 1979, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('City of Women', 1980, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('And the Ship Sails On', 1983, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('The Voice of the Moon', 1989, DEFAULT, 'Italy', 'not seen');
INSERT INTO movie VALUES ('Stormy Monday', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Internal Affairs', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Liebestraum', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mr. Jones', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Browning Version', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('One Night Stand', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Loss of Sexual Innocence', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Miss Julie', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Hotel', 2001, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Cold Creek Manor', 2003, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Competition', 1963, DEFAULT, 'Czech Republic', 'not seen');
INSERT INTO movie VALUES ('Black Peter', 1963, DEFAULT, 'Czech Republic', 'not seen');
INSERT INTO movie VALUES ('The Loves of a Blonde', 1965, DEFAULT, 'Czech Republic', 'not seen');
INSERT INTO movie VALUES ('Taking Off', 1971, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('I Miss Sonia Henie', 1971, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Hair', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Ragtime', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Valmont', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Goya''s Ghost', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gumshoe', 1971, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Bloody Kids', 1979, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('My Beautiful Laundrette', 1985, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Walter and June', 1986, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Sammy and Rosie', 1987, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Mary Reilly', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Van', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Hi-Lo Country', 1998, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Mrs. Henderson Presents', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Cheri', 2009, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Good Times', 1967, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Night They Raided Minsky''s', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Birthday Party', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Boys in the Band', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Exorcist', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sorcerer', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Brink''s Job', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Cruising', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Deal of the Century', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('To Live and Die in L.A.', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Rampage', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Guardian', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Blue Chips', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jade', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Rules of Engagement', 2000, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bug', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('I Shot Jesse James', 1949, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Baron of Arizona', 1950, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Steel Helmet', 1951, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Fixed Bayonets', 1951, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Park Row', 1952, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Pickup on South Street', 1953, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Hell and High Water', 1954, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('House of Bamboo', 1955, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Run of the Arrow', 1957, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('China Gate', 1957, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Forty Guns', 1957, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Verboten!', 1959, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Crimson Kimono', 1959, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Underworld U.S.A.', 1961, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Merrill''s Marauders', 1962, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Naked Kiss', 1964, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Shark!', 1969, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('White Dog', 1982, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Thieves After Dark', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Street of No Return', 1989, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Man Without a Face', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Apocalypto', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('And Now For Something Completely Different', 1971, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Jabberwocky', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Time Bandits', 1981, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Monty Python''s the Meaning of Life', 1983, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('The Crimson Permanent Assurance', 1983, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Brothers Grimm', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Tideland', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('A Woman Is a Woman', 1961, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('My Life to Live', 1962, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('A Married Woman', 1964, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Alphaville, a Strange Adventure of Lemmy Caution', 1965, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Crazy Pete', 1965, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Masculine-Feminine', 1996, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Made in U.S.A.', 1966, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Two Or Three Things I Know About Her', 1967, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('La Chinoise', 1967, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Week End', 1967, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Joyful Wisdom', 1968, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('British Sounds', 1970, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('One P.M.', 1972, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Number Two', 1975, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Here and Elsewhere', 1976, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Everyman For Himself', 1979, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Passion', 1982, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('First Name: Carmen', 1984, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Hail Mary', 1985, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Detective', 1985, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Meeting Woody Allen', 1986, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Keep Your Right Up', 1987, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('King Lear', 1987, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('New Wave', 1990, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Germany Year 90 Nine Zero', 1991, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Alas For Me', 1993, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('For Ever Mozart', 1996, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('In Praise of Love', 2001, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Our Music', 2004, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Human Nature', 2001, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Science of Sleep', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Snow Angels', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Pineapple Express', 2008, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Big Picture', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('For Your Consideration', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Poison', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('I''m Not There', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Signs of Life', 1968, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Even Dwarfs Started Small', 1971, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Fata Morgana', 1971, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Great Ecstacy of Woodcarver Steiner', 1974, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Enigma of Kaspar Hauser', 1974, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Heart of Glass', 1976, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Nosferatu the Vampyre', 1979, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Cobra Verde', 1988, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Herdsmen of the Sun', 1988, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Lessons of Darkness', 1992, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Little Dieter Needs to Fly', 1997, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Wheel of Time', 2003, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Wild Blue Yonder', 2005, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Man Who Knew Too Much', 1934, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The 39 Steps', 1935, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Secret Agent', 1936, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Sabotage', 1936, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Young and Innocent', 1937, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Lady Vanishes', 1938, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Jamaica Inn', 1939, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Foreign Correspondent', 1940, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mr. & Mrs. Smith', 1941, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Suspicion', 1941, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Saboteur', 1942, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Shadow of a Doubt', 1943, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Paradise Case', 1947, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Under Capricorn', 1949, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Stage Fright', 1950, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('I Confess', 1953, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('To Catch a Thief', 1955, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Trouble With Harry', 1955, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Wrong Man', 1956, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Man Who Knew Too Much', 1956, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Marnie', 1964, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Topaz', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Family Plot', 1976, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Grand Theft Auto', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Night Shift', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gung Ho', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Parenthood', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Far and Away', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('EdTV', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Missing', 2003, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Cinderella Man', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Da Vinci Code', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('In This Our Life', 1942, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Across the Pacific', 1942, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Let There Be Light', 1946, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Key Largo', 1948, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('We Were Strangers', 1949, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Asphalt Jungle', 1950, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Red Badge of Courage', 1951, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Moulin Rouge', 1952, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Beat the Devil', 1953, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Moby Dick', 1956, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Heaven Knows, Mr. Allison', 1957, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Barbarian and the Geisha', 1958, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Roots of Heaven', 1958, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Unforgiven', 1960, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Misfits', 1961, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Freud', 1962, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The List of Adrian Messenger', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Night of the Iguana', 1964, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Bible', 1966, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Casino Royale', 1967, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Reflections in a Golden Eye', 1967, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sinful Davey', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Walk With Love and Death', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Kremiln Letter', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Fat City', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Life and Times of Judge Roy Bean', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Mackintosh Man', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Man Who Would Be King', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Wise Blood', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Phobia', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Victory', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Annie', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Under the Valcano', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Dead', 1987, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bad Taste', 1987, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Meet the Feebles', 1989, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Dead Alive', 1982, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Heavenly Creatures', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Freighteners', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Permanent Vacation', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Down by Law', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mystery Train', 1989, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Broken Flowers', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Delicatessen', 1991, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The City of Lost Children', 1995, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('40 Pounds of Trouble', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Thrill of it All', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Send Me No Flowers', 1964, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Art of Love', 1965, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Cincinnati Kid', 1965, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Russians Are Coming, the Russians Are Coming', 1966, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Thomas Crown Affair', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gally, Gally', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Fiddler on the Roof', 1971, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jesus Christ Superstar', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Rollerball', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('F.I.S.T.', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('...And Justice For All', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Best Friends', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Agnes of God', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Other People''s Money', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Only You', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bogus', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Statement', 2003, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Angel', 1981, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Company of Wolves', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('High Spirits', 1988, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('We''re No Angels', 1989, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Miracle', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Butcher Boy', 1997, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('In Dreams', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The End of the Affair', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Breakfast on Pluto', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Brave One', 2007, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('I Love You to Death', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('French Kiss', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Tree Grows in Brooklyn', 1945, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Sea of Grass', 1947, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gentleman''s Agreement', 1947, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Boomerang!', 1947, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Pinky', 1949, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Panic in the Streets', 1950, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Man on a Tightrope', 1953, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Baby Doll', 1956, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Face in the Crowd', 1957, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Wild River', 1960, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Splendor in the Grass', 1961, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('America, America', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Arrangement', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Visitors', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Three Ages', 1923, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Go West', 1925, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Battling Butler', 1926, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('College', 1927, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Cameraman', 1928, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Spite Marriage', 1929, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Scar', 1976, DEFAULT, 'Poland', 'not seen');
INSERT INTO movie VALUES ('Camera Buff', 1979, DEFAULT, 'Poland', 'not seen');
INSERT INTO movie VALUES ('Blind Chance', 1982, DEFAULT, 'Poland', 'not seen');
INSERT INTO movie VALUES ('No End', 1985, DEFAULT, 'Poland', 'not seen');
INSERT INTO movie VALUES ('Beyond JFK: The Question of Conspiracy', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Woodstock ''94', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Conversation With Gregory Peck', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('My Generation', 2000, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Havoc', 2004, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Shut Up & Sing', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sanshiro Sugata', 1943, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('The Most Beautiful', 1944, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Sanshiro Sugata Part Two', 1945, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('The Men Who Tread on the Tiger''s Tail', 1945, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('No Regrets For My Youth', 1946, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('One Wonderful Sunday', 1947, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Drunken Angel', 1948, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('The Quiet Duel', 1949, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Stray Dog', 1949, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Scandal', 1950, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('The Idiot', 1951, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Ikiru', 1952, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('I Live in Fear', 1955, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('The Lower Depths', 1957, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('The Bad Sleep Well', 1960, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Yojimbo', 1961, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Sanjuro', 1962, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('High and Low', 1963, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Red Beard', 1965, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Clickety-Clack)', 1970, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Kagemusha', 1980, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Dreams', 1990, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Rhapsody in August', 1991, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Madadayo', 1993, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Your Friends and Neighbors', 1998, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Shape of Things', 2003, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Wicker Man', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Lakeview Terrace', 2008, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Madame Butterfly', 1919, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Spiders, Part I: the golden lake', 1919, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Spiders, Part II: the diamond ship', 1920, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Wandering Image', 1920, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Destiny', 1921, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Dr. Mabuse: The Gambler', 1922, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Siegfried', 1924, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Kriemhild''s Revenge', 1924, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Spies', 1928, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Woman in the Moon', 1929, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('The Testament of Dr. Mabuse', 1933, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Liliom', 1934, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Fury', 1936, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('You Only Live Once', 1937, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('You and Me', 1938, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Return of Frank James', 1940, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Western Union', 1941, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Man Hunt', 1941, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Hangmen Also Die', 1943, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Ministry of Fear', 1944, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Woman in the Window', 1945, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Scarlet Street', 1945, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Cloak and Dagger', 1946, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Secret Beyond the Door', 1948, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('House by the River', 1950, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('American Guerilla in the Phillippines', 1950, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Rancho Notorious', 1952, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Clash by Night', 1952, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Blue Gardenia', 1953, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Big Heat', 1953, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Human Desire', 1954, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Moonfleet', 1955, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('While the City Sleeps', 1956, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Beyond a Reasonable Doubt', 1956, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Tiger of Bengal', 1959, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Indian Tomb', 1959, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Journey to the Lost City', 1959, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The 1,000 Eyes of Dr. Mabuse', 1960, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('This Happy Breed', 1944, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Blithe Spirit', 1945, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Brief Encounter', 1946, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Oliver Twist', 1948, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('The Passionate Friends', 1949, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Madeleine', 1950, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('The Sound Barrier', 1952, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Hobson''s Choice', 1954, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Summertime', 1955, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Ryan''s Daughter', 1970, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('A Passage to India', 1984, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('School Daze', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mo'' Better Blues', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jungle Fever', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Crooklyn', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Clockers', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Girl 6', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('He Got Game', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Summer of Sam', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Original Kings of Comedy', 2000, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('She Hate Me', 2004, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Miracle at St. Anna', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bleak Moments', 1971, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Naked', 1993, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Career Girls', 1997, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Happy-G-Lucky', 2008, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('The Colossus of Rhodes', 1961, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('A Fistful of Dollars', 1964, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('For a Few Dollars More', 1965, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Once Upon a Time in the West', 1968, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('A Fistful of Dynamite', 1971, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Once Upon a Time in America', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Natural', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Young Sherlock Holmes', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Tin Men', 1987, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Good Morning, Vietnam', 1987, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jimmy Hollywood', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Disclosure', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sphere', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Liberty Heights', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('An Everlasting Piece', 2000, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Envy', 2004, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Man of the Year', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('What Just Happened?', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('It''s Impossible to Learn How to Plow by Reading Books', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Newton Boys', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bad News Bears', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Fast Food Nation', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Scanner Darkly', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Me and Orson Welles', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Stage Struck', 1958, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('That Kind of Woman', 1959, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Fugitive Kind', 1959, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A View From the Bridge', 1961, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Long Day''s Journey Into Night', 1962, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Fail-Safe', 1964, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Hill', 1965, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Group', 1966, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Deadly Affair', 1966, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bye Bye Braverman', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Sea Gull', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Appointment', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Last of the Mobile Hot Shots', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Anderson Tapes', 1971, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Child''s Play', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Offence', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Serpico', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Lovin'' Molly', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Murder on the Orient Express', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Equus', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Wiz', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Just Tell Me What You Want', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Prince of the City', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Deathtrap', 1982, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Daniel', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Garbo Talks', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Power', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Moring After', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Family Business', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Q & A', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Stranger Among Us', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Guilty as Sin', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Night Falls on Manhattan', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Critical Care', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gloria', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Find Me Guilty', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Before the Devil Knows You''re Dead', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Dune', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Wild at Heart', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Inland Empire', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gid Shall Come', 1995, DEFAULT, 'Iran', 'not seen');
INSERT INTO movie VALUES ('The Father', 1996, DEFAULT, 'Iran', 'not seen');
INSERT INTO movie VALUES ('Barefoot to Heart', 2002, DEFAULT, 'Iran', 'not seen');
INSERT INTO movie VALUES ('The Willow Tree', 2005, DEFAULT, 'Iran', 'not seen');
INSERT INTO movie VALUES ('The Song of Sparrows', 2008, DEFAULT, 'Iran', 'not seen');
INSERT INTO movie VALUES ('The Silent World', 1956, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Elevator to the Gallows', 1958, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Lovers', 1958, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Zazie Dans Le Metro', 1959, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('A Very Private Affair', 1961, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Fire Within', 1963, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Viva Maria!', 1965, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Thief of Paris', 1967, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Murmur of the Heart', 1971, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Lacombe Lucien', 1974, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Damage', 1974, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Black Moon', 1975, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Pretty Baby', 1978, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Crackers', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Alamo Bay', 1985, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('May Fools', 1990, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Things Change', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Homicide', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Oleanna', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Winslow Boy', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Redbelt', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Heavy', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Thief', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Keep', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Miami Vice', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jarhead', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Revolutionary Road', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Jumpin'' Jack Flash', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Renaissance Man', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Preacher''s Wife', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Riding in Cars With Boys', 2001, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Warriors of the Wind', 1984, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Castle in the Sky', 1986, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Porco Rosso', 1992, DEFAULT, 'Japan', 'not seen');
INSERT INTO movie VALUES ('Canadian Bacon', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Big One', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sicko', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Capitalism: A Love Story', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Vernon, Florida', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Dark Wind', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Standard Operating Procedure', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Burning Soil', 1922, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Phantom', 1922, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Finances of the Grand Duke', 1924, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Tantuffe', 1926, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Faust', 1926, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('City Girl', 1930, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Tabu', 1931, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Catch-22', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Carnal Knowledge', 1971, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Day of the Dolphin', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gilda Live', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Silkwood', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Heartburn', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Biloxi Blues', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Wolf', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Birdcage', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('What Planet Are You From?', 2000, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Closer', 2004, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Charlie Wilson''s War', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Bugsy Malone', 1976, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Fame', 1980, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Shoot the Moon', 1982, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Birdy', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Angel Heart', 1987, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Come See the Paradise', 1990, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Commitments', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Road to Wellville', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Evita', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Sterile Cuckoo', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Klute', 1971, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Love and Pain and the Whole Damn Thing', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Parallex View', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Comes a Horseman', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Starting Over', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Roll Over', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Dream Lover', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Orphans', 1987, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('See You in the Morning', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Presumed Innocent', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Consenting Adults', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Citizen Ruth', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Deadly Companions', 1961, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Ride the High Country', 1962, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Major Dundee', 1965, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Ballad of Cable Hogue', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Junior Bonner', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Getaway', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Pat Garrett and Billy the Kid', 1973, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Killer Elite', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Cross of Iron', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Convoy', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Osterman', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Laft Handed Gun', 1958, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mickey One', 1965, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Chase', 1966, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Alice''s Restaurant', 1969, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Night Moves', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Four Friends', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Target', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Dead of Winter', 1987, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Penn & Teller Get Killer', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Indian Runner', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('One Or the Other', 1973, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Consequence', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Shattered', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Air Force One', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Perfect Storm', 2000, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Poseidon', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Cul-De-Sac', 1966, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Fearless Vampire Killers', 1967, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Macbeth', 1971, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('What?', 1973, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Tenant', 1976, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Pirates', 1986, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Frantic', 1988, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Bitter Moon', 1992, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Death and the Maiden', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Ninth Gate', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Oliver Twist', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Jackpot', 2001, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Astronaut Farmer', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Manure', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Parash Pather', 1958, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Music Room', 1958, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Godess', 1960, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('Two Daughters', 1961, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('Kanchenjungha', 1962, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Expedition', 1962, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Big City', 1963, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Lonely Wife', 1963, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Priest', 1965, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Coward', 1965, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Hero', 1966, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Zoo', 1967, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Adventures of Goopy and Bagha', 1968, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Adversary', 1970, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('Company Limited', 1971, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('Distant Thunder', 1973, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Golden Fortress', 1974, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Middlemen', 1976, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Chess Players', 1977, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Elephant God', 1978, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Home and the World', 1984, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('An Enemy of the People', 1989, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Branches of the Tree', 1990, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Stranger', 1991, DEFAULT, 'India', 'not seen');
INSERT INTO movie VALUES ('The Milagro Beanfield War', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Horse Whisperer', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Legend of Bagger Vance', 2000, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Sure Thing', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Ghosts of Mississippi', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Story of Us', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Alex & Emma', 2003, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Rumor Has It...', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Bucket List', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('La Chienne', 1931, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Night at the Crossroads', 1932, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Boudu Saved From Drowning', 1932, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Madame Bovary', 1933, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Toni', 1934, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('A Day in the Country', 1936, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Crime of Monsieur Lange', 1936, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Lower Depths', 1936, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('La Marseillaise', 1938, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Human Beast', 1938, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Rules of the Game', 1939, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Swamp Water', 1941, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('This Land Is Mine', 1943, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Southerner', 1945, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Diary of a Chambermaid', 1946, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Woman on the Beach', 1947, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The River', 1951, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Golden Coach', 1952, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('French Cancan', 1955, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Elena and Her Men', 1956, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Lunch on the Grass', 1959, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Elusive Corporal', 1962, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Hard Case', 1995, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Swept Away', 2002, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Revolver', 2005, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Rocknrolla', 2008, DEFAULT, 'England', 'not seen');
INSERT INTO movie VALUES ('Spanking the Monkkey', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Flirting With Disaster', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Nailed', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Return of the Secaucus 7', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Lianna', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Baby, It''s You', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Brother From Another Planet', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('City of Hope', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Passion Fish', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Men With Guns', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Casa De Los Babys', 2003, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Honeydripper', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Kind of Loving', 1962, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Billy Liar', 1963, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Far From the Madding Crowd', 1967, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Day of the Locust', 1975, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Yanks', 1979, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Honky Tonk Freeway', 1981, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Believers', 1987, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('A Question of Attribution', 1992, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Innocent', 1993, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Eye For an Eye', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Next Best Thing', 2000, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Who''s That Knocking on My Door?', 1967, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Badge 373', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Italianamerican', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('New York, New York', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Last Waltz', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('American Boy: A Profile of Steven Prince', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The King of Comedy', 1983, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Made in Milan', 1990, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Kundun', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('My Voyage to Italy', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('No Direction Home: Bob Dylan', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Shutter Island', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Dualists', 1977, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Legend', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Someone to Watch Over Me', 1987, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Black Rain', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('1492: Conquest of Paradise', 1992, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('G.I. Jane', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Kingdom of Heaven', 2005, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Good Year', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('American Gangster', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Field', 1990, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Boxer', 1997, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Get Rich Or Die Tryin''', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Praying With Anger', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Wide Awake', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Public Access', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Apt Pupil', 1998, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sex, Lies, and Videotape', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Kafka', 1991, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Underneath', 1995, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Gray''s Anatomy', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Schizopolis', 1996, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Full Frontal', 2002, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Good German', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Che', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Girlfriend Experience', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Sugarland Express', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Always', 1989, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Seizure', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mad Man of Martinique', 1979, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Hand', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Salvador', 1986, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Talk Radio', 1988, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Heaven & Earth', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('U Turn', 1997, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Any Given Sunday', 1999, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Comandante', 2003, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Alexander', 2004, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('World Trade Center', 2006, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Grindhouse', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Death-Proof', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Inglorious Basterds', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('My Name Is Ivan', 1962, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('Andrei Rublev', 1969, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('The Mirror', 1975, DEFAULT, 'Russia', 'not seen');
INSERT INTO movie VALUES ('The Big Day', 1949, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Playtime', 1967, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Traffic', 1971, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Sad Sack', 1961, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Love at Twenty', 1962, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Soft Skin', 1964, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Bride Wore Black', 1967, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Stolen Kisses', 1968, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Mississippi Mermaid', 1969, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Wild Child', 1969, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Bed & Board', 1970, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Such a Gorgeous Kid Like Me', 1972, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Story of Adele H', 1975, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Man Who Loved Women', 1977, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Green Room', 1978, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Love on the Run', 1979, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Last Metro', 1980, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('The Woman Next Door', 1981, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Confidentially Yours', 1983, DEFAULT, 'France', 'not seen');
INSERT INTO movie VALUES ('Deadly Maria', 1994, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Winter Sleepers', 1997, DEFAULT, 'Germany', 'not seen');
INSERT INTO movie VALUES ('Mala Noche', 1985, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Even Cowgirls Get the Blues', 1993, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Paranoid Park', 2007, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Milk', 2008, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Element of Crime', 1984, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Epidemic', 1988, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Europa', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Manderlay', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Boss of it All', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Antichrist', 2009, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Cars That Ate Paris', 1974, DEFAULT, 'Australia', 'not seen');
INSERT INTO movie VALUES ('The Last Wave', 1977, DEFAULT, 'Australia', 'not seen');
INSERT INTO movie VALUES ('The Year of Living Dangerously', 1982, DEFAULT, 'Australia', 'not seen');
INSERT INTO movie VALUES ('The Mosquito Coast', 1986, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Fearless', 1993, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Stranger', 1946, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Lady From Shanghai', 1948, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Macbeth', 1948, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Tragedy of Othello: The Moor of Venice', 1952, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Mr. Arkadin', 1955, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Chimes at Midnight', 1965, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Immortal Story', 1968, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Deep', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Other Side of the Wind', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('F For Fake', 1975, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Summer in the City', 1970, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Goalie''s Anxiety at the Penalty Kick', 1971, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Scarlet Letter', 1972, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Alice in the Cities', 1974, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('False Movement', 1974, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Kings of the Road', 1976, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The American Friend', 1977, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Lightening Over Water', 1980, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The State of Things', 1982, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Hammett', 1982, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Tokyo-Ga', 1985, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Notebook on Cities and Clothes', 1989, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Until the End of the World', 1991, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Faraway, So Close!', 1993, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Lisbon Story', 1994, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Brothers Skladanowsky', 1995, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Buena Vista Social Club', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Million Dollar Hotel', 2000, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Ode to Cologne: A Rock ‘n'' Roll Film', 2002, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Ten Minutes Older: The Trumpet', 2002, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Soul of a Man', 2003, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Land of Plenty', 2004, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Don''t Come Knocking', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Invisibles', 2007, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Palermo Shooting', 2008, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Bad Seed', 1934, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Major and the Minor', 1942, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Five Graves to Cairo', 1943, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Lost Weekend', 1945, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Emperor Waltz', 1948, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Foreign Affair', 1948, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Ace in the Hole', 1951, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Stalag 17', 1953, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Sabrina', 1954, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Seven Year Itch', 1955, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Spirit of St. Louis', 1957, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Love in the Afternoon', 1957, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Witness For the Prosecution', 1957, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('One, Two, Three', 1961, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Irma La Douce', 1963, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Kiss Me, Stupid', 1964, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Fortune Cookie', 1966, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Private Life of Sherlock Holmes', 1970, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Avanti!', 1972, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('The Front Page', 1974, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Fedora', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Buddy Buddy', 1981, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Butterfly Kiss', 1995, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Go Now', 1995, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Jude', 1996, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Welcome to Sarajevo', 1997, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('I Want You', 1998, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Wonderland', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('With Or Without You', 1999, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('In This World', 2002, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Code 46', 2003, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('9 Songs', 2004, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Tristam Shandy: A Cock and Bull Story', 2005, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Road to Guatanamo', 2006, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('Genova', 2008, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('The Shock Doctrine', 2009, DEFAULT, DEFAULT, 'not seen');
INSERT INTO movie VALUES ('I Wanna Hold Your Hand', 1978, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Used Cars', 1980, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Romancing the Stone', 1984, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Death Becomes Her', 1992, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('A Christmas Carol', 2009, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Legends of the Fall', 1994, DEFAULT, 'USA', 'not seen');
INSERT INTO movie VALUES ('Goin'' South', 1978, DEFAULT, 'USA', 'not seen');
