INSERT INTO actedin VALUES ('Mio in the Land of Faraway', 1987, 'Christian Bale');
INSERT INTO actedin VALUES ('Empire of the Sun', 1987, 'Christian Bale');
INSERT INTO actedin VALUES ('Henry V', 1989, 'Christian Bale');
INSERT INTO actedin VALUES ('Newsies', 1992, 'Christian Bale');
INSERT INTO actedin VALUES ('Swing Kids', 1993, 'Christian Bale');
INSERT INTO actedin VALUES ('Royal Deceit', 1994, 'Christian Bale');
INSERT INTO actedin VALUES ('Little Women', 1994, 'Christian Bale');
INSERT INTO actedin VALUES ('The Secret Agent', 1996, 'Christian Bale');
INSERT INTO actedin VALUES ('The Portrait of a Lady', 1996, 'Christian Bale');
INSERT INTO actedin VALUES ('Metroland', 1997, 'Christian Bale');
INSERT INTO actedin VALUES ('Velvet Goldmine', 1998, 'Christian Bale');
INSERT INTO actedin VALUES ('All the Little Animals', 1998, 'Christian Bale');
INSERT INTO actedin VALUES ('A Midsummer Night''s Dream', 1999, 'Christian Bale');
INSERT INTO actedin VALUES ('American Psycho', 2000, 'Christian Bale');
INSERT INTO actedin VALUES ('Shaft', 2000, 'Christian Bale');
INSERT INTO actedin VALUES ('Captain Correlli''s Mandolin', 2001, 'Christian Bale');
INSERT INTO actedin VALUES ('Equilibrium', 2002, 'Christian Bale');
INSERT INTO actedin VALUES ('Reign of Fire', 2002, 'Christian Bale');
INSERT INTO actedin VALUES ('Laurel Canyon', 2003, 'Christian Bale');
INSERT INTO actedin VALUES ('The Machinist', 2004, 'Christian Bale');
INSERT INTO actedin VALUES ('Batman Begins', 2005, 'Christian Bale');
INSERT INTO actedin VALUES ('The New World', 2005, 'Christian Bale');
INSERT INTO actedin VALUES ('Harsh Times', 2005, 'Christian Bale');
INSERT INTO actedin VALUES ('The Prestige', 2006, 'Christian Bale');
INSERT INTO actedin VALUES ('Rescue Dawn', 2007, 'Christian Bale');
INSERT INTO actedin VALUES ('3:10 to Yuma', 2007, 'Christian Bale');
INSERT INTO actedin VALUES ('I''m Not There', 2007, 'Christian Bale');
INSERT INTO actedin VALUES ('The Dark Knight', 2008, 'Christian Bale');
INSERT INTO actedin VALUES ('Terminator Salvation', 2009, 'Christian Bale');
INSERT INTO actedin VALUES ('Public Enemies', 2009, 'Christian Bale');
INSERT INTO actedin VALUES ('The Men', 1950, 'Marlon Brando');
INSERT INTO actedin VALUES ('A Streetcar Named Desire', 1951, 'Marlon Brando');
INSERT INTO actedin VALUES ('Viva Zapatal', 1952, 'Marlon Brando');
INSERT INTO actedin VALUES ('Julius Caesar', 1953, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Wild One', 1954, 'Marlon Brando');
INSERT INTO actedin VALUES ('On the Waterfront', 1954, 'Marlon Brando');
INSERT INTO actedin VALUES ('Desiree', 1954, 'Marlon Brando');
INSERT INTO actedin VALUES ('Guys and Dolls', 1955, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Teahouse of the August Moon', 1956, 'Marlon Brando');
INSERT INTO actedin VALUES ('Sayonara', 1957, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Young Lions', 1958, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Fugitive Kind', 1959, 'Marlon Brando');
INSERT INTO actedin VALUES ('One-Eyed Jacks', 1961, 'Marlon Brando');
INSERT INTO actedin VALUES ('Mutiny on the Bounty', 1962, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Ugly American', 1963, 'Marlon Brando');
INSERT INTO actedin VALUES ('Bedtime Story', 1964, 'Marlon Brando');
INSERT INTO actedin VALUES ('Morituri', 1965, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Chase', 1966, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Appaloosa', 1966, 'Marlon Brando');
INSERT INTO actedin VALUES ('A Countess From Hong Kong', 1967, 'Marlon Brando');
INSERT INTO actedin VALUES ('Reflections in a Golden Eye', 1967, 'Marlon Brando');
INSERT INTO actedin VALUES ('Candy', 1969, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Night of the Following Day', 1968, 'Marlon Brando');
INSERT INTO actedin VALUES ('Burn!', 1969, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Godfather', 1972, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Nightcomers', 1972, 'Marlon Brando');
INSERT INTO actedin VALUES ('Last Tango in Paris', 1973, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Missouri Breaks', 1976, 'Marlon Brando');
INSERT INTO actedin VALUES ('Superman', 1978, 'Marlon Brando');
INSERT INTO actedin VALUES ('Apocalypse Now', 1979, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Formula', 1980, 'Marlon Brando');
INSERT INTO actedin VALUES ('A Dry White Season', 1989, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Freshmen', 1990, 'Marlon Brando');
INSERT INTO actedin VALUES ('Christopher Columbus: The Discovery', 1992, 'Marlon Brando');
INSERT INTO actedin VALUES ('Don Juan DeMarco', 1995, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Island of Dr. Moreau', 1996, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Brave', 1997, 'Marlon Brando');
INSERT INTO actedin VALUES ('Free Money', 1998, 'Marlon Brando');
INSERT INTO actedin VALUES ('The Score', 2001, 'Marlon Brando');
INSERT INTO actedin VALUES ('Greetings', 1968, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Wedding Party', 1969, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Sam''s Song', 1969, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Bloody Mama', 1970, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Hi Mom!', 1970, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Jennifer on My Mind', 1971, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Gang That Couldn''t Shoot Straight', 1971, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Born to Win', 1971, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Mean Streets', 1973, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Bang the Drum Slowly', 1973, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Godfather Part II', 1974, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Last Tycoon', 1976, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Taxi Driver', 1976, 'Robert DiNiro');
INSERT INTO actedin VALUES ('1900', 1976, 'Robert DiNiro');
INSERT INTO actedin VALUES ('New York, New York', 1977, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Deer Hunter', 1978, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Raging Bull', 1980, 'Robert DiNiro');
INSERT INTO actedin VALUES ('True Confessions', 1981, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The King of Comedy', 1983, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Once Upon a Time in America', 1984, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Falling in Love', 1984, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Brazil', 1985, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Mission', 1986, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Angel Heart', 1987, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Untouchables', 1987, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Midnight Run', 1988, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Jacknife', 1989, 'Robert DiNiro');
INSERT INTO actedin VALUES ('We''re No Angels', 1989, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Stanley & Iris', 1990, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Goodfellas', 1990, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Awakenings', 1990, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Guilty by Suspicion', 1991, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Backdraft', 1991, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Cape Fear', 1991, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Mistress', 1992, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Night and the City', 1992, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Mad Dog and Glory', 1993, 'Robert DiNiro');
INSERT INTO actedin VALUES ('This Boy''s Life', 1993, 'Robert DiNiro');
INSERT INTO actedin VALUES ('A Bronx Tale', 1993, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Frankenstein', 1994, 'Robert DiNiro');
INSERT INTO actedin VALUES ('A Hundred and One Nights', 1995, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Casino', 1995, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Heat', 1995, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Fan', 1996, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Sleepers', 1996, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Marvin''s Room', 1996, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Copland', 1997, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Wag the Dog', 1997, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Jackie Brown', 1997, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Great Expectations', 1998, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Ronin', 1998, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Analyze This', 1999, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Adventures of Rocky and Bullwinkle', 2000, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Men of Honor', 2000, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Meet the Parents', 2000, 'Robert DiNiro');
INSERT INTO actedin VALUES ('15 Minutes', 2001, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Score', 2001, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Showtime', 2002, 'Robert DiNiro');
INSERT INTO actedin VALUES ('City by the Sea', 2002, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Analyze That', 2002, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Godsend', 2004, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Bridge of San Luis Rey', 2004, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Hide and Seek', 2005, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Meet the Fockers', 2004, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Shark Tale', 2004, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Arthur and the Invisibles', 2006, 'Robert DiNiro');
INSERT INTO actedin VALUES ('The Good Shepherd', 2006, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Stardust', 2007, 'Robert DiNiro');
INSERT INTO actedin VALUES ('What Just Happened', 2008, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Righteous Kill', 2008, 'Robert DiNiro');
INSERT INTO actedin VALUES ('Everybody''s Fine', 2009, 'Robert DiNiro');
INSERT INTO actedin VALUES ('He Knows You''re Alone', 1980, 'Tom Hanks');
INSERT INTO actedin VALUES ('Splash', 1984, 'Tom Hanks');
INSERT INTO actedin VALUES ('Bachelor Party', 1984, 'Tom Hanks');
INSERT INTO actedin VALUES ('Volunteers', 1985, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Man With One Red Shoe', 1985, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Money Pit', 1986, 'Tom Hanks');
INSERT INTO actedin VALUES ('Nothing in Common', 1986, 'Tom Hanks');
INSERT INTO actedin VALUES ('Every Time We Say Goodbye', 1986, 'Tom Hanks');
INSERT INTO actedin VALUES ('Dragnet', 1987, 'Tom Hanks');
INSERT INTO actedin VALUES ('Big', 1988, 'Tom Hanks');
INSERT INTO actedin VALUES ('Punchline', 1988, 'Tom Hanks');
INSERT INTO actedin VALUES ('The ''burbs', 1989, 'Tom Hanks');
INSERT INTO actedin VALUES ('Turner & Hooch', 1989, 'Tom Hanks');
INSERT INTO actedin VALUES ('Joe Versus the Volcano', 1990, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Bonfire of the Vanities', 1990, 'Tom Hanks');
INSERT INTO actedin VALUES ('Radio Flyer', 1992, 'Tom Hanks');
INSERT INTO actedin VALUES ('A League of Thier Own', 1992, 'Tom Hanks');
INSERT INTO actedin VALUES ('Sleepless in Seattle', 1993, 'Tom Hanks');
INSERT INTO actedin VALUES ('Phildelphia', 1993, 'Tom Hanks');
INSERT INTO actedin VALUES ('Forrest Gump', 1994, 'Tom Hanks');
INSERT INTO actedin VALUES ('Apollo 13', 1995, 'Tom Hanks');
INSERT INTO actedin VALUES ('Toy Story', 1995, 'Tom Hanks');
INSERT INTO actedin VALUES ('That Thing You Do!', 1996, 'Tom Hanks');
INSERT INTO actedin VALUES ('Saving Private Ryan', 1998, 'Tom Hanks');
INSERT INTO actedin VALUES ('You''ve Got Mail', 1998, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Green Mile', 1999, 'Tom Hanks');
INSERT INTO actedin VALUES ('Toy Story 2', 1999, 'Tom Hanks');
INSERT INTO actedin VALUES ('Cast Away', 2000, 'Tom Hanks');
INSERT INTO actedin VALUES ('Road to Perdition', 2002, 'Tom Hanks');
INSERT INTO actedin VALUES ('Catch Me If You Can', 2003, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Ladykillers', 2004, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Polar Express', 2004, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Terminal', 2004, 'Tom Hanks');
INSERT INTO actedin VALUES ('Elvis Has Left the Building', 2004, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Da Vinci Code', 2006, 'Tom Hanks');
INSERT INTO actedin VALUES ('Charlie Wilson''s War', 2007, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Great Buck Howard', 2009, 'Tom Hanks');
INSERT INTO actedin VALUES ('Angels & Demons', 2009, 'Tom Hanks');
INSERT INTO actedin VALUES ('The Graduate', 1967, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('The Tiger Makes Out', 1967, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Madigan''s Millions', 1969, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Midnight Cowboy', 1969, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('John and Mary', 1969, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Little Big Man', 1970, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Straw Dogs', 1971, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Who Is Harry Kellerman and Why Is He Saying Those Terrible Things About Me?', 1971, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Alfredo, Alfredo', 1972, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Papillon', 1973, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Lenny', 1974, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('All the President''s Men', 1976, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Marathon Man', 1978, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Straight Time', 1978, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Agatha', 1979, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Kramer Vs. Kramer', 1979, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Tootsie', 1982, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Ishtar', 1987, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Rain Man', 1988, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Family Business', 1989, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Dick Tracy', 1990, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Billy Bathgate', 1991, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Hook', 1991, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Hero', 1992, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Outbreak', 1995, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('American Buffalo', 1996, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Sleepers', 1996, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Mad City', 1997, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Wag the Dog', 1997, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Sphere', 1998, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('The Messenger: The Story of Joan of Arc', 1989, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Moonlight Mile', 2002, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Confidence', 2003, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Runaway Jury', 2003, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('I Heart Huckabees', 2004, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Finding Neverland', 2004, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Lemony Snicket''s a Series of Unfortunate Events', 2004, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('The Lost City', 2005, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Perfume: The Story of a Murderer', 2006, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Last Chance Harvey', 2008, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('The Tale of Despereaux', 2008, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Stranger Than Fiction', 2006, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Mr. Magorium''s Wonder Emporium', 2007, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Meet the Fockers', 2004, 'Dustin Hoffman');
INSERT INTO actedin VALUES ('Triple Bogey on a Par Five Hole', 1991, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('My New Gun', 1992, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Leap of Faith', 1992, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Scent of a Woman', 1992, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('My Boyfriend''s Back', 1993, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Money For Nothing', 1993, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Joey Breaker', 1993, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('The Getaway', 1994, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('When a Man Loves a Woman', 1994, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Nobody''s Fool', 1994, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Hard Eight', 1996, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Twister', 1996, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Boogie Nights', 1997, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Montana', 1998, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Next Stop Wonderland', 1998, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('The Big Lebowski', 1998, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Happiness', 1998, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Patch Adams', 1998, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('The Talented Mr.Ripley', 1999, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Flawless', 1999, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Magnolia', 1999, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('State and Main', 2000, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Almost Famous', 2000, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Punch-Drunk Love', 2002, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Red Dragon', 2002, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('25th Hour', 2002, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Love Liza', 2003, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Owning Mahoney', 2003, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Along Came Polly', 2004, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Capote', 2005, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Strangers With Candy', 2005, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Mission: Impossible III', 2006, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Charlie Wilson''s War', 2007, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('The Savages', 2007, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Before the Devil Knows You''re Dead', 2007, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Synecdoche, New York', 2008, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Doubt', 2008, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Pirate Radio', 2009, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Mary and Max', 2009, 'Phillip Seymour Hoffman');
INSERT INTO actedin VALUES ('Places in the Heart', 1984, 'John Malkovich');
INSERT INTO actedin VALUES ('The Killing Fields', 1984, 'John Malkovich');
INSERT INTO actedin VALUES ('Eleni', 1985, 'John Malkovich');
INSERT INTO actedin VALUES ('Making Mr. Right', 1987, 'John Malkovich');
INSERT INTO actedin VALUES ('The Glass Menagerie', 1987, 'John Malkovich');
INSERT INTO actedin VALUES ('Empire of the Sun', 1987, 'John Malkovich');
INSERT INTO actedin VALUES ('Dangerous Liasons', 1988, 'John Malkovich');
INSERT INTO actedin VALUES ('Miles From Home', 1988, 'John Malkovich');
INSERT INTO actedin VALUES ('The Sheltering Sky', 1990, 'John Malkovich');
INSERT INTO actedin VALUES ('Queens Logic', 1991, 'John Malkovich');
INSERT INTO actedin VALUES ('The Object of Beauty', 1991, 'John Malkovich');
INSERT INTO actedin VALUES ('Shadows and Fog', 1992, 'John Malkovich');
INSERT INTO actedin VALUES ('Of Mice and Men', 1992, 'John Malkovich');
INSERT INTO actedin VALUES ('Jennifer Eight', 1992, 'John Malkovich');
INSERT INTO actedin VALUES ('Alive', 1993, 'John Malkovich');
INSERT INTO actedin VALUES ('Heart Of Darkness', 1994, 'John Malkovich');
INSERT INTO actedin VALUES ('Beyond the Clouds', 1995, 'John Malkovich');
INSERT INTO actedin VALUES ('The Convent', 1995, 'John Malkovich');
INSERT INTO actedin VALUES ('Mary Reily', 1996, 'John Malkovich');
INSERT INTO actedin VALUES ('Mulholland Falls', 1996, 'John Malkovich');
INSERT INTO actedin VALUES ('The Ogre', 1996, 'John Malkovich');
INSERT INTO actedin VALUES ('The Portrait of a Lady', 1996, 'John Malkovich');
INSERT INTO actedin VALUES ('Con Air', 1997, 'John Malkovich');
INSERT INTO actedin VALUES ('The Man in the Iron Mask', 1998, 'John Malkovich');
INSERT INTO actedin VALUES ('Rounders', 1998, 'John Malkovich');
INSERT INTO actedin VALUES ('Time Regained', 1999, 'John Malkovich');
INSERT INTO actedin VALUES ('Being John Malkovich', 1999, 'John Malkovich');
INSERT INTO actedin VALUES ('The Messenger: The Story of Joan of Arc', 1999, 'John Malkovich');
INSERT INTO actedin VALUES ('Ladies Room', 1999, 'John Malkovich');
INSERT INTO actedin VALUES ('Shadow of the Vampire', 2000, 'John Malkovich');
INSERT INTO actedin VALUES ('Savage Souls', 2001, 'John Malkovich');
INSERT INTO actedin VALUES ('Knockaround Guys', 2001, 'John Malkovich');
INSERT INTO actedin VALUES ('I''m Going Home', 2001, 'John Malkovich');
INSERT INTO actedin VALUES ('Hotel', 2001, 'John Malkovich');
INSERT INTO actedin VALUES ('Ripley''s Game', 2002, 'John Malkovich');
INSERT INTO actedin VALUES ('Johnny English', 2003, 'John Malkovich');
INSERT INTO actedin VALUES ('A Talking Picture', 2003, 'John Malkovich');
INSERT INTO actedin VALUES ('The Libertine', 2004, 'John Malkovich');
INSERT INTO actedin VALUES ('The Hitchhiker''s Guide to the Galaxy', 2005, 'John Malkovich');
INSERT INTO actedin VALUES ('Color Me Kubrick: A True...Ish Story', 2005, 'John Malkovich');
INSERT INTO actedin VALUES ('Art School Confidential', 2006, 'John Malkovich');
INSERT INTO actedin VALUES ('Klimt', 2006, 'John Malkovich');
INSERT INTO actedin VALUES ('Eragon', 2006, 'John Malkovich');
INSERT INTO actedin VALUES ('Beowulf', 2007, 'John Malkovich');
INSERT INTO actedin VALUES ('Gardens of the Night', 2008, 'John Malkovich');
INSERT INTO actedin VALUES ('Mutant Chronicles', 2008, 'John Malkovich');
INSERT INTO actedin VALUES ('Disgrace', 2008, 'John Malkovich');
INSERT INTO actedin VALUES ('Afterwards', 2008, 'John Malkovich');
INSERT INTO actedin VALUES ('The Great Buck Howard', 2009, 'John Malkovich');
INSERT INTO actedin VALUES ('Changeling', 2008, 'John Malkovich');
INSERT INTO actedin VALUES ('Burn After Reading', 2008, 'John Malkovich');
INSERT INTO actedin VALUES ('Being Human', 1993, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Shallow Grave', 1994, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Bug Juice', 1995, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Trainspotting', 1996, 'Ewan McGregor');
INSERT INTO actedin VALUES ('The Pillow Book', 1996, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Emma', 1996, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Brassed Off', 1996, 'Ewan McGregor');
INSERT INTO actedin VALUES ('The Serpents Kiss', 1997, 'Ewan McGregor');
INSERT INTO actedin VALUES ('A Life Less Ordained', 1997, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Nightwatch', 1998, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Velvet Goldmine', 1998, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Little Voice', 1998, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Star Wars Episode I: The Phantom Menace', 1999, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Rogue Trader', 1999, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Eye of the Beholder', 1999, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Nora', 2000, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Moulin Rouge!', 2001, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Black Hawk Down', 2001, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Star Wars Episode II: Attack of the Clones', 2002, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Down With Love', 2003, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Big Fish', 2003, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Young Adam', 2004, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Star Wars Episode III: Revenge of the Sith', 2005, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Robots', 2005, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Valiant', 2005, 'Ewan McGregor');
INSERT INTO actedin VALUES ('The Island', 2005, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Stay', 2005, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Stormbreaker', 2006, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Scenes of a Sexual Nature', 2006, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Miss Potter', 2006, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Cassandra''s Dream', 2007, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Incendiary', 2008, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Deception', 2008, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Angels & Demons', 2009, 'Ewan McGregor');
INSERT INTO actedin VALUES ('I Love You Phillip Morris', 2009, 'Ewan McGregor');
INSERT INTO actedin VALUES ('The Men Who Stare at Goats', 2009, 'Ewan McGregor');
INSERT INTO actedin VALUES ('Amelia', 2009, 'Ewan McGregor');
INSERT INTO actedin VALUES ('The Cry Baby Killer', 1958, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Little Shop of Horrors', 1960, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Studs Lonigan', 1960, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Broken Land', 1962, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Raven', 1963, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Terror', 1963, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Ensign Pulver', 1964, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Flight to Fury', 1964, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Back Door to Hell', 1964, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Ride in the Whirlwind', 1965, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Shooting', 1967, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Hells Angels on Wheels', 1967, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Psych-Out', 1968, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Easy Rider', 1969, 'Jack Nicholson');
INSERT INTO actedin VALUES ('On a Clear Day You Can See Forever', 1970, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Five Easy Pieces', 1970, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Rebel Rousers', 1970, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Carnal Knowledge', 1971, 'Jack Nicholson');
INSERT INTO actedin VALUES ('A Safe Place', 1971, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The King of Marvin Gardens', 1972, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Last Detail', 1973, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Chinatown', 1974, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Passenger', 1975, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Tommy', 1975, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Fortune', 1975, 'Jack Nicholson');
INSERT INTO actedin VALUES ('One Flew Over the Cuckoo''s Nest', 1975, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Missouri Breaks', 1976, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Last Tycoon', 1976, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Goin'' South', 1978, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Shining', 1980, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Postman Always Rings Twice', 1981, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Reds', 1981, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Border', 1982, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Terms of Endearment', 1983, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Prizzi''s Hour', 1985, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Heartburn', 1986, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Witches of Eastwick', 1987, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Broadcast News', 1987, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Ironweed', 1987, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Batman', 1989, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Two Jakes', 1990, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Man Trouble', 1992, 'Jack Nicholson');
INSERT INTO actedin VALUES ('A Few Good Men', 1992, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Hoffa', 1992, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Wolf', 1994, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Crossing Guard', 1995, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Evening Star', 1996, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Mars Attacks!', 1996, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Blood and Wine', 1997, 'Jack Nicholson');
INSERT INTO actedin VALUES ('As Good as it Gets', 1997, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Pledge', 2001, 'Jack Nicholson');
INSERT INTO actedin VALUES ('About Schmidt', 2002, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Something''s Gotta Give', 2003, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Anger Management', 2003, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Departed', 2006, 'Jack Nicholson');
INSERT INTO actedin VALUES ('The Bucket List', 2007, 'Jack Nicholson');
INSERT INTO actedin VALUES ('Primal Fear', 1996, 'Edward Norton');
INSERT INTO actedin VALUES ('The Peole Vs. Larry Flynt', 1996, 'Edward Norton');
INSERT INTO actedin VALUES ('Rounders', 1998, 'Edward Norton');
INSERT INTO actedin VALUES ('American History X', 1998, 'Edward Norton');
INSERT INTO actedin VALUES ('Fight Club', 1999, 'Edward Norton');
INSERT INTO actedin VALUES ('Keeping the Faith', 2000, 'Edward Norton');
INSERT INTO actedin VALUES ('The Score', 2001, 'Edward Norton');
INSERT INTO actedin VALUES ('Frida', 2002, 'Edward Norton');
INSERT INTO actedin VALUES ('Death to Smoochy', 2002, 'Edward Norton');
INSERT INTO actedin VALUES ('Red Dragon', 2002, 'Edward Norton');
INSERT INTO actedin VALUES ('25th Hour', 2002, 'Edward Norton');
INSERT INTO actedin VALUES ('The Italian Job', 2003, 'Edward Norton');
INSERT INTO actedin VALUES ('Kingdom of Heaven', 2005, 'Edward Norton');
INSERT INTO actedin VALUES ('Down in the Valley', 2005, 'Edward Norton');
INSERT INTO actedin VALUES ('The Painted Veil', 2006, 'Edward Norton');
INSERT INTO actedin VALUES ('Pride and Glory', 2008, 'Edward Norton');
INSERT INTO actedin VALUES ('Leaves of Grass', 2009, 'Edward Norton');
INSERT INTO actedin VALUES ('Taps', 1981, 'Sean Penn');
INSERT INTO actedin VALUES ('Fast Time at Ridgemount High', 1982, 'Sean Penn');
INSERT INTO actedin VALUES ('Bad Boys', 1983, 'Sean Penn');
INSERT INTO actedin VALUES ('Racing With the Moon', 1984, 'Sean Penn');
INSERT INTO actedin VALUES ('The Falcon and the Snowman', 1984, 'Sean Penn');
INSERT INTO actedin VALUES ('Crackers', 1984, 'Sean Penn');
INSERT INTO actedin VALUES ('Shanghai Surprise', 1985, 'Sean Penn');
INSERT INTO actedin VALUES ('At Close Range', 1986, 'Sean Penn');
INSERT INTO actedin VALUES ('Colors', 1998, 'Sean Penn');
INSERT INTO actedin VALUES ('Judgement in Berlin', 1988, 'Sean Penn');
INSERT INTO actedin VALUES ('Casualties of War', 1989, 'Sean Penn');
INSERT INTO actedin VALUES ('We''re No Angels', 1989, 'Sean Penn');
INSERT INTO actedin VALUES ('State of Grace', 1990, 'Sean Penn');
INSERT INTO actedin VALUES ('Carlito''s Way', 1993, 'Sean Penn');
INSERT INTO actedin VALUES ('Dead Man Walking', 1995, 'Sean Penn');
INSERT INTO actedin VALUES ('She''s So Lovely', 1997, 'Sean Penn');
INSERT INTO actedin VALUES ('U Turn', 1997, 'Sean Penn');
INSERT INTO actedin VALUES ('The Game', 1997, 'Sean Penn');
INSERT INTO actedin VALUES ('Hugo Pool', 1997, 'Sean Penn');
INSERT INTO actedin VALUES ('Loved', 1997, 'Sean Penn');
INSERT INTO actedin VALUES ('Hurlyburly', 1998, 'Sean Penn');
INSERT INTO actedin VALUES ('The Thin Red Line', 1998, 'Sean Penn');
INSERT INTO actedin VALUES ('Sweet and Lowdown', 1999, 'Sean Penn');
INSERT INTO actedin VALUES ('Up at the Villa', 2000, 'Sean Penn');
INSERT INTO actedin VALUES ('Before Night Falls', 2000, 'Sean Penn');
INSERT INTO actedin VALUES ('The Weight of Water', 2000, 'Sean Penn');
INSERT INTO actedin VALUES ('I Am Sam', 2001, 'Sean Penn');
INSERT INTO actedin VALUES ('Mystic River', 2003, 'Sean Penn');
INSERT INTO actedin VALUES ('21 Grams', 2003, 'Sean Penn');
INSERT INTO actedin VALUES ('It''s All About Love', 2003, 'Sean Penn');
INSERT INTO actedin VALUES ('The Asssassination of Richard Nixon', 2004, 'Sean Penn');
INSERT INTO actedin VALUES ('The Intrepreter', 2005, 'Sean Penn');
INSERT INTO actedin VALUES ('All the King''s Men', 2006, 'Sean Penn');
INSERT INTO actedin VALUES ('Milk', 2008, 'Sean Penn');
INSERT INTO actedin VALUES ('Julia', 1977, 'Meryl Streep');
INSERT INTO actedin VALUES ('The Deer Hunter', 1978, 'Meryl Streep');
INSERT INTO actedin VALUES ('Manhattan', 1979, 'Meryl Streep');
INSERT INTO actedin VALUES ('Kramer Vs. Kramer', 1979, 'Meryl Streep');
INSERT INTO actedin VALUES ('The Seduction of Joe Tynan', 1979, 'Meryl Streep');
INSERT INTO actedin VALUES ('The French Lieutenant''s Woman', 1981, 'Meryl Streep');
INSERT INTO actedin VALUES ('Still of the Night', 1982, 'Meryl Streep');
INSERT INTO actedin VALUES ('Sophie''s Choice', 1982, 'Meryl Streep');
INSERT INTO actedin VALUES ('Silkwood', 1983, 'Meryl Streep');
INSERT INTO actedin VALUES ('Falling in Love', 1984, 'Meryl Streep');
INSERT INTO actedin VALUES ('Plenty', 1985, 'Meryl Streep');
INSERT INTO actedin VALUES ('Out of Africa', 1985, 'Meryl Streep');
INSERT INTO actedin VALUES ('Heartburn', 1986, 'Meryl Streep');
INSERT INTO actedin VALUES ('Ironweed', 1987, 'Meryl Streep');
INSERT INTO actedin VALUES ('A Cry in the Dark', 1988, 'Meryl Streep');
INSERT INTO actedin VALUES ('She-Devil', 1989, 'Meryl Streep');
INSERT INTO actedin VALUES ('Postcards From the Edge', 1990, 'Meryl Streep');
INSERT INTO actedin VALUES ('Defending Your Life', 1991, 'Meryl Streep');
INSERT INTO actedin VALUES ('Death Becomes Her', 1992, 'Meryl Streep');
INSERT INTO actedin VALUES ('The House of the Spirits', 1993, 'Meryl Streep');
INSERT INTO actedin VALUES ('The River Wild', 1994, 'Meryl Streep');
INSERT INTO actedin VALUES ('The Bridges of Madison County', 1995, 'Meryl Streep');
INSERT INTO actedin VALUES ('Before and After', 1996, 'Meryl Streep');
INSERT INTO actedin VALUES ('Marvin''s Room', 1996, 'Meryl Streep');
INSERT INTO actedin VALUES ('Dancing at Lughnasa', 1998, 'Meryl Streep');
INSERT INTO actedin VALUES ('One True Thing', 1998, 'Meryl Streep');
INSERT INTO actedin VALUES ('Music of the Heart', 1999, 'Meryl Streep');
INSERT INTO actedin VALUES ('The Hours', 2002, 'Meryl Streep');
INSERT INTO actedin VALUES ('Adaptation', 2002, 'Meryl Streep');
INSERT INTO actedin VALUES ('Stuck on You', 2003, 'Meryl Streep');
INSERT INTO actedin VALUES ('The Manchurian Candidate', 2004, 'Meryl Streep');
INSERT INTO actedin VALUES ('Lemony Snicket''s a Series of Unfortunate Events', 2004, 'Meryl Streep');
INSERT INTO actedin VALUES ('A Prairie Home Companion', 2006, 'Meryl Streep');
INSERT INTO actedin VALUES ('Prime', 2005, 'Meryl Streep');
INSERT INTO actedin VALUES ('Dark Matter', 2007, 'Meryl Streep');
INSERT INTO actedin VALUES ('Evening', 2007, 'Meryl Streep');
INSERT INTO actedin VALUES ('Mamma Mia!', 2008, 'Meryl Streep');
INSERT INTO actedin VALUES ('Rendition', 2007, 'Meryl Streep');
INSERT INTO actedin VALUES ('Lions For Lambs', 2007, 'Meryl Streep');
INSERT INTO actedin VALUES ('The Devil Wears Prada', 2006, 'Meryl Streep');
INSERT INTO actedin VALUES ('The Ant Bully', 2006, 'Meryl Streep');
INSERT INTO actedin VALUES ('Doubt', 2008, 'Meryl Streep');
INSERT INTO actedin VALUES ('Julie & Julia', 2009, 'Meryl Streep');
INSERT INTO actedin VALUES ('Fantastic Mr. Fox', 2009, 'Meryl Streep');
