/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainUserInterface.java
 *
 * Created on Dec 16, 2010, 4:49:29 PM
 */

package tylerhayes.filth.gui;

import java.awt.Frame;

/**
 *
 * @author tgh
 */
public class MainUserInterface extends javax.swing.JFrame {

    /** Creates new form MainUserInterface */
    public MainUserInterface() {
        initComponents();
        //maximize the window on open
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    MainMenuBar = new javax.swing.JMenuBar();
    FileMenu = new javax.swing.JMenu();
    FileMenuExit = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("FiLTH");

    FileMenu.setText("File");

    FileMenuExit.setMnemonic('x');
    FileMenuExit.setText("Exit");
    FileMenuExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        FileMenuExitActionPerformed(evt);
      }
    });
    FileMenu.add(FileMenuExit);

    MainMenuBar.add(FileMenu);

    jMenu2.setText("Edit");
    MainMenuBar.add(jMenu2);

    setJMenuBar(MainMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 273, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void FileMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_FileMenuExitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUserInterface().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu FileMenu;
  private javax.swing.JMenuItem FileMenuExit;
  private javax.swing.JMenuBar MainMenuBar;
  private javax.swing.JMenu jMenu2;
  // End of variables declaration//GEN-END:variables

}
