#!/bin/bash

filth_path=~/Projects/FiLTH
filth_temp_path=~/Projects/FiLTH/temp


# convert Word document to text file
antiword -w 120 ~/Documents/Movies/Movie_Ratings.doc > $filth_temp_path/temp

# replace special characters with ASCII
sed -i "s/'/''/g" $filth_temp_path/temp
sed -i "s/’/''/g" $filth_temp_path/temp        # (double apostrophes for SQL)
sed -i "s/Chaplin short/short/g" $filth_temp_path/temp
sed -i "s/Keaton short/short/g" $filth_temp_path/temp
sed -i "s/‘/''/g" $filth_temp_path/temp
sed -i "s/…/.../g" $filth_temp_path/temp
sed -i "s/♥/Heart/g" $filth_temp_path/temp

# replace the star ratings with corresponding integer
sed -i "s/NO STARS/0/g" $filth_temp_path/temp
sed -i "s/\*\*\*\*/8/g" $filth_temp_path/temp
sed -i "s/\*\*\*½/7/g" $filth_temp_path/temp
sed -i "s/\*\*\*/6/g" $filth_temp_path/temp
sed -i "s/\*\*½/5/g" $filth_temp_path/temp
sed -i "s/\*\*/4/g" $filth_temp_path/temp
sed -i "s/\*½/3/g" $filth_temp_path/temp
sed -i "s/½\*/1/g" $filth_temp_path/temp
sed -i "s/\*/2/g" $filth_temp_path/temp
sed -i "s/N\/A/9/g" $filth_temp_path/temp


# replace country of origin with corresponding integer
sed -i "s/USA$/1/g" $filth_temp_path/temp
sed -i "s/France$/2/g" $filth_temp_path/temp
sed -i "s/England$/3/g" $filth_temp_path/temp
sed -i "s/Canada$/4/g" $filth_temp_path/temp
sed -i "s/China$/5/g" $filth_temp_path/temp
sed -i "s/Russia$/6/g" $filth_temp_path/temp
sed -i "s/Germany$/7/g" $filth_temp_path/temp
sed -i "s/Argentina$/8/g" $filth_temp_path/temp
sed -i "s/Portugal$/9/g" $filth_temp_path/temp
sed -i "s/Spain$/10/g" $filth_temp_path/temp
sed -i "s/Mexico$/11/g" $filth_temp_path/temp
sed -i "s/Italy$/12/g" $filth_temp_path/temp
sed -i "s/Ireland$/13/g" $filth_temp_path/temp
sed -i "s/Scotland$/14/g" $filth_temp_path/temp
sed -i "s/Czech Republic$/15/g" $filth_temp_path/temp
sed -i "s/Iran$/16/g" $filth_temp_path/temp
sed -i "s/The Netherlands$/17/g" $filth_temp_path/temp
sed -i "s/Sweden$/18/g" $filth_temp_path/temp
sed -i "s/Finland$/19/g" $filth_temp_path/temp
sed -i "s/Norway$/20/g" $filth_temp_path/temp
sed -i "s/Poland$/21/g" $filth_temp_path/temp
sed -i "s/Bosnia$/22/g" $filth_temp_path/temp
sed -i "s/Japan$/23/g" $filth_temp_path/temp
sed -i "s/Taiwan$/24/g" $filth_temp_path/temp
sed -i "s/India$/25/g" $filth_temp_path/temp
sed -i "s/Greece$/26/g" $filth_temp_path/temp
sed -i "s/Israel$/27/g" $filth_temp_path/temp
sed -i "s/Lebanon$/28/g" $filth_temp_path/temp
sed -i "s/South Africa$/29/g" $filth_temp_path/temp
sed -i "s/Australia$/30/g" $filth_temp_path/temp
sed -i "s/New Zealand$/31/g" $filth_temp_path/temp
sed -i "s/Brazil$/32/g" $filth_temp_path/temp
sed -i "s/Iceland$/33/g" $filth_temp_path/temp
sed -i "s/Vietnam$/34/g" $filth_temp_path/temp
sed -i "s/Denmark$/35/g" $filth_temp_path/temp

# remove the alphabetical headers
sed "/^[A-Z]$/d" $filth_temp_path/temp > $filth_temp_path/temp2
# remove the blank lines
sed "/^$/d" $filth_temp_path/temp2 > $filth_temp_path/temp
sed "/X, Y, Z/d" $filth_temp_path/temp > $filth_temp_path/temp2
# remove the totals at the bottom
sed "/Total:/d" $filth_temp_path/temp2 > $filth_temp_path/temp
sed "/shorts$/d" $filth_temp_path/temp > $filth_temp_path/temp2

# run the movie2sql program on the resulting text
$filth_path/bin/movie2sql $filth_temp_path/temp2 > $filth_path/sql/movie.sql
