INSERT INTO filth.movie_link VALUES(7, 6, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode VII – the Force Awakens (2015) -> Star Wars: Episode VI - Return of the Jedi (1983)
INSERT INTO filth.movie_link VALUES(6, 5, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode VI - Return of the Jedi (1983) -> Star Wars: Episode V - The Empire Strikes Back (1980)
INSERT INTO filth.movie_link VALUES(5, 6, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode V - The Empire Strikes Back (1980) -> Star Wars: Episode VI - Return of the Jedi (1983)
INSERT INTO filth.movie_link VALUES(5, 4, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode V - The Empire Strikes Back (1980) -> Star Wars (1977)
INSERT INTO filth.movie_link VALUES(4, 5, 'PREDECESSOR_OF', NULL); -- Star Wars (1977) -> Star Wars: Episode V - The Empire Strikes Back (1980)
INSERT INTO filth.movie_link VALUES(4, 3, 'SUCCESSOR_TO', NULL); -- Star Wars (1977) -> Star Wars: Episode III - Revenge of the Sith (2005)
INSERT INTO filth.movie_link VALUES(3, 4, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode III - Revenge of the Sith (2005) -> Star Wars (1977)
INSERT INTO filth.movie_link VALUES(3, 2, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode III - Revenge of the Sith (2005) -> Star Wars: Episode II - Attack of the Clones (2002)
INSERT INTO filth.movie_link VALUES(2, 3, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode II - Attack of the Clones (2002) -> Star Wars: Episode III - Revenge of the Sith (2005)
INSERT INTO filth.movie_link VALUES(2, 1, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode II - Attack of the Clones (2002) -> Star Wars: Episode I - The Phantom Menace (1999)
INSERT INTO filth.movie_link VALUES(1, 2, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode I - The Phantom Menace (1999) -> Star Wars: Episode II - Attack of the Clones (2002)
