INSERT INTO filth.position VALUES(1, 'Actor');
INSERT INTO filth.position VALUES(2, 'Actress');
INSERT INTO filth.position VALUES(3, 'Cinematographer');
INSERT INTO filth.position VALUES(4, 'Director');
INSERT INTO filth.position VALUES(5, 'Screenwriter');
INSERT INTO filth.position VALUES(6, 'Producer');
INSERT INTO filth.position VALUES(7, 'Character Voice');
INSERT INTO filth.position VALUES(8, 'Narrator');
INSERT INTO filth.position VALUES(9, 'Lead Actor');
INSERT INTO filth.position VALUES(10, 'Supporting Actor');
INSERT INTO filth.position VALUES(11, 'Lead Actress');
INSERT INTO filth.position VALUES(12, 'Supporting Actress');
INSERT INTO filth.position VALUES(13, 'Small Part');
INSERT INTO filth.position VALUES(14, 'Cameo');
INSERT INTO filth.position VALUES(15, 'Editor');
