INSERT INTO filth.tag_given_to VALUES(1545, 75);  -- Star Wars: Episode I - the Phantom Menace (1999) tagged with 'Saga'
INSERT INTO filth.tag_given_to VALUES(1545, 10);  -- Star Wars: Episode I - the Phantom Menace (1999) tagged with 'Action'
INSERT INTO filth.tag_given_to VALUES(1545, 11);  -- Star Wars: Episode I - the Phantom Menace (1999) tagged with 'Adventure'
INSERT INTO filth.tag_given_to VALUES(1545, 6);  -- Star Wars: Episode I - the Phantom Menace (1999) tagged with 'Science-Fiction'
INSERT INTO filth.tag_given_to VALUES(1545, 284);  -- Star Wars: Episode I - The Phantom Menace (1999) tagged with 'outer-space'
INSERT INTO filth.tag_given_to VALUES(1546, 75);  -- Star Wars: Episode II - Attack of the Clones (2002) tagged with 'Saga'
INSERT INTO filth.tag_given_to VALUES(1546, 10);  -- Star Wars: Episode II - Attack of the Clones (2002) tagged with 'Action'
INSERT INTO filth.tag_given_to VALUES(1546, 11);  -- Star Wars: Episode II - Attack of the Clones (2002) tagged with 'Adventure'
INSERT INTO filth.tag_given_to VALUES(1546, 6);  -- Star Wars: Episode II - Attack of the Clones (2002) tagged with 'Science-Fiction'
INSERT INTO filth.tag_given_to VALUES(1547, 75);  -- Star Wars: Episode III - Revenge of the Sith (2005) tagged with 'Saga'
INSERT INTO filth.tag_given_to VALUES(1547, 10);  -- Star Wars: Episode III - Revenge of the Sith (2005) tagged with 'Action'
INSERT INTO filth.tag_given_to VALUES(1547, 11);  -- Star Wars: Episode III - Revenge of the Sith (2005) tagged with 'Adventure'
INSERT INTO filth.tag_given_to VALUES(1547, 6);  -- Star Wars: Episode III - Revenge of the Sith (2005) tagged with 'Science-Fiction'
INSERT INTO filth.tag_given_to VALUES(1548, 75);  -- Star Wars (1977) tagged with 'Saga'
INSERT INTO filth.tag_given_to VALUES(1548, 10);  -- Star Wars (1977) tagged with 'Action'
INSERT INTO filth.tag_given_to VALUES(1548, 11);  -- Star Wars (1977) tagged with 'Adventure'
INSERT INTO filth.tag_given_to VALUES(1548, 6);  -- Star Wars (1977) tagged with 'Science-Fiction'
INSERT INTO filth.tag_given_to VALUES(1549, 75);  -- Star Wars: Episode V - the Empire Strikes Back (1980) tagged with 'Saga'
INSERT INTO filth.tag_given_to VALUES(1549, 10);  -- Star Wars: Episode V - the Empire Strikes Back (1980) tagged with 'Action'
INSERT INTO filth.tag_given_to VALUES(1549, 11);  -- Star Wars: Episode V - the Empire Strikes Back (1980) tagged with 'Adventure'
INSERT INTO filth.tag_given_to VALUES(1549, 6);  -- Star Wars: Episode V - the Empire Strikes Back (1980) tagged with 'Science-Fiction'
INSERT INTO filth.tag_given_to VALUES(1550, 75);  -- Star Wars: Episode VI - Return of the Jedi (1983) tagged with 'Saga'
INSERT INTO filth.tag_given_to VALUES(1550, 10);  -- Star Wars: Episode VI - Return of the Jedi (1983) tagged with 'Action'
INSERT INTO filth.tag_given_to VALUES(1550, 11);  -- Star Wars: Episode VI - Return of the Jedi (1983) tagged with 'Adventure'
INSERT INTO filth.tag_given_to VALUES(1550, 6);  -- Star Wars: Episode VI - Return of the Jedi (1983) tagged with 'Science-Fiction'
INSERT INTO filth.tag_given_to VALUES(1546, 284);  -- Star Wars: Episode II - Attack of the Clones (2002) tagged with 'outer-space'
INSERT INTO filth.tag_given_to VALUES(1547, 284);  -- Star Wars: Episode III - Revenge of the Sith (2005) tagged with 'outer-space'
INSERT INTO filth.tag_given_to VALUES(1547, 271);  -- Star Wars: Episode III - Revenge of the Sith (2005) tagged with 'corruption'
INSERT INTO filth.tag_given_to VALUES(1548, 284);  -- Star Wars (1977) tagged with 'outer-space'
INSERT INTO filth.tag_given_to VALUES(1549, 284);  -- Star Wars: Episode V - The Empire Strikes Back (1980) tagged with 'outer-space'
INSERT INTO filth.tag_given_to VALUES(1550, 284);  -- Star Wars: Episode VI - Return of the Jedi (1983) tagged with 'outer-space'
INSERT INTO filth.tag_given_to VALUES(3869, 10);  -- Star Wars: Episode VII – the Force Awakens (2015) tagged with 'action'
INSERT INTO filth.tag_given_to VALUES(3869, 11);  -- Star Wars: Episode VII – the Force Awakens (2015) tagged with 'adventure'
INSERT INTO filth.tag_given_to VALUES(3869, 6);  -- Star Wars: Episode VII – the Force Awakens (2015) tagged with 'science-fiction'
INSERT INTO filth.tag_given_to VALUES(3869, 75);  -- Star Wars: Episode VII – the Force Awakens (2015) tagged with 'saga'
INSERT INTO filth.tag_given_to VALUES(3869, 392);  -- Star Wars: Episode VII – the Force Awakens (2015) tagged with 'feminine'
INSERT INTO filth.tag_given_to VALUES(4, 32);  -- 8 1/2 tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(4, 1);
INSERT INTO filth.tag_given_to VALUES(9, 38);  -- 13 Going on 30 tagged with 'New York City'
INSERT INTO filth.tag_given_to VALUES(9, 392);  -- 13 Going on 30 (2004) tagged with 'feminine'
INSERT INTO filth.tag_given_to VALUES(9, 27);
INSERT INTO filth.tag_given_to VALUES(9, 2);
INSERT INTO filth.tag_given_to VALUES(14, 60);  -- 25th Hour tagged with 'Based-on-book'
INSERT INTO filth.tag_given_to VALUES(14, 1);
INSERT INTO filth.tag_given_to VALUES(14, 25);
INSERT INTO filth.tag_given_to VALUES(14, 38);  -- 25th Hour (2002) tagged with 'new-york-city'
INSERT INTO filth.tag_given_to VALUES(14, 175);  -- 25th Hour (2002) tagged with 'drug-dealing'
INSERT INTO filth.tag_given_to VALUES(14, 59);  -- 25th Hour (2002) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(14, 58);  -- 25th Hour (2002) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(47, 2);
INSERT INTO filth.tag_given_to VALUES(47, 305);  -- Airheads (1994) tagged with 'hostage-situation'
INSERT INTO filth.tag_given_to VALUES(47, 25);  -- Airheads (1994) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(47, 391);  -- Airheads (1994) tagged with 'masculine'
INSERT INTO filth.tag_given_to VALUES(278, 1);  -- Bully (2001) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(278, 25);  -- Bully (2001) tagged with 'Crime'
INSERT INTO filth.tag_given_to VALUES(278, 29);  -- Bully (2001) tagged with 'Dark'
INSERT INTO filth.tag_given_to VALUES(278, 63);  -- Bully (2001) tagged with 'Graphic'
INSERT INTO filth.tag_given_to VALUES(278, 48);  -- Bully (2001) tagged with 'Disgusting'
INSERT INTO filth.tag_given_to VALUES(278, 60);  -- Bully (2001) tagged with 'Based-on-book'
INSERT INTO filth.tag_given_to VALUES(278, 308);  -- Bully (2001) tagged with 'graphic-sexual-content'
INSERT INTO filth.tag_given_to VALUES(278, 245);  -- Bully (2001) tagged with 'disturbing'
INSERT INTO filth.tag_given_to VALUES(278, 328);  -- Bully (2001) tagged with 'friend(s)/friendship'
INSERT INTO filth.tag_given_to VALUES(278, 326);  -- Bully (2001) tagged with 'teenager(s)'
INSERT INTO filth.tag_given_to VALUES(278, 167);  -- Bully (2001) tagged with 'murder'
INSERT INTO filth.tag_given_to VALUES(278, 207);  -- Bully (2001) tagged with 'based-on-a-true-story'
INSERT INTO filth.tag_given_to VALUES(278, 227);  -- Bully (2001) tagged with 'sexual-female-nudity'
INSERT INTO filth.tag_given_to VALUES(278, 58);  -- Bully (2001) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(278, 226);  -- Bully (2001) tagged with 'sexual-nudity'
INSERT INTO filth.tag_given_to VALUES(278, 225);  -- Bully (2001) tagged with 'nudity'
INSERT INTO filth.tag_given_to VALUES(278, 59);  -- Bully (2001) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(278, 347);  -- Bully (2001) tagged with 'revenge'
INSERT INTO filth.tag_given_to VALUES(302, 1);  -- The Cat's Meow (2002) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(302, 81);  -- The Cat's Meow (2002) tagged with 'Based-on-play'
INSERT INTO filth.tag_given_to VALUES(302, 21);  -- The Cat's Meow (2002) tagged with 'Period'
INSERT INTO filth.tag_given_to VALUES(302, 121);  -- The Cat's Meow (2002) tagged with '1920''s'
INSERT INTO filth.tag_given_to VALUES(302, 167);  -- The Cat's Meow (2002) tagged with 'murder'
INSERT INTO filth.tag_given_to VALUES(302, 237);  -- The Cat's Meow (2002) tagged with 'upper-class'
INSERT INTO filth.tag_given_to VALUES(302, 118);  -- The Cat's Meow (2002) tagged with '20th-century'
INSERT INTO filth.tag_given_to VALUES(302, 25);  -- The Cat's Meow (2002) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(302, 236);  -- The Cat's Meow (2002) tagged with 'social-classes'
INSERT INTO filth.tag_given_to VALUES(302, 59);  -- The Cat's Meow (2002) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(302, 58);  -- The Cat's Meow (2002) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(1409, 1);  -- Santa Sangre (1990) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(1409, 29);  -- Santa Sangre (1990) tagged with 'Dark'
INSERT INTO filth.tag_given_to VALUES(1409, 48);  -- Santa Sangre (1990) tagged with 'Disgusting'
INSERT INTO filth.tag_given_to VALUES(1409, 167);  -- Santa Sangre (1990) tagged with 'murder'
INSERT INTO filth.tag_given_to VALUES(1409, 347);  -- Santa Sangre (1990) tagged with 'revenge'
INSERT INTO filth.tag_given_to VALUES(1409, 50);  -- Santa Sangre (1990) tagged with 'spiritual/religion'
INSERT INTO filth.tag_given_to VALUES(1409, 233);  -- Santa Sangre (1990) tagged with 'non-sexual-male-nudity'
INSERT INTO filth.tag_given_to VALUES(1409, 309);  -- Santa Sangre (1990) tagged with 'graphic-violence'
INSERT INTO filth.tag_given_to VALUES(1409, 231);  -- Santa Sangre (1990) tagged with 'non-sexual-female-nudity'
INSERT INTO filth.tag_given_to VALUES(1409, 25);  -- Santa Sangre (1990) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(1409, 230);  -- Santa Sangre (1990) tagged with 'non-sexual-nudity'
INSERT INTO filth.tag_given_to VALUES(1409, 225);  -- Santa Sangre (1990) tagged with 'nudity'
INSERT INTO filth.tag_given_to VALUES(1409, 63);  -- Santa Sangre (1990) tagged with 'graphic'
INSERT INTO filth.tag_given_to VALUES(1409, 245);  -- Santa Sangre (1990) tagged with 'disturbing'
INSERT INTO filth.tag_given_to VALUES(1409, 61);  -- Santa Sangre (1990) tagged with 'arts/entertainment'
INSERT INTO filth.tag_given_to VALUES(1409, 371);  -- Santa Sangre (1990) tagged with 'circus'
INSERT INTO filth.tag_given_to VALUES(1532, 12);  -- Spellbound (2002) tagged with 'Documentary'
INSERT INTO filth.tag_given_to VALUES(1532, 242);  -- Spellbound (2002) tagged with 'education'
INSERT INTO filth.tag_given_to VALUES(1532, 326);  -- Spellbound (2002) tagged with 'teenager(s)'
INSERT INTO filth.tag_given_to VALUES(347, 1);  -- A Clockwork Orange (1971) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(347, 6);  -- A Clockwork Orange (1971) tagged with 'Science-Fiction'
INSERT INTO filth.tag_given_to VALUES(347, 25);  -- A Clockwork Orange (1971) tagged with 'Crime'
INSERT INTO filth.tag_given_to VALUES(347, 29);  -- A Clockwork Orange (1971) tagged with 'Dark'
INSERT INTO filth.tag_given_to VALUES(347, 46);  -- A Clockwork Orange (1971) tagged with 'Psychological'
INSERT INTO filth.tag_given_to VALUES(347, 60);  -- A Clockwork Orange (1971) tagged with 'Based-on-book'
INSERT INTO filth.tag_given_to VALUES(347, 63);  -- A Clockwork Orange (1971) tagged with 'Graphic'
INSERT INTO filth.tag_given_to VALUES(347, 299);  -- A Clockwork Orange (1971) tagged with 'future'
INSERT INTO filth.tag_given_to VALUES(347, 308);  -- A Clockwork Orange (1971) tagged with 'graphic-sexual-content'
INSERT INTO filth.tag_given_to VALUES(347, 227);  -- A Clockwork Orange (1971) tagged with 'sexual-female-nudity'
INSERT INTO filth.tag_given_to VALUES(347, 176);  -- A Clockwork Orange (1971) tagged with 'gangs'
INSERT INTO filth.tag_given_to VALUES(347, 183);  -- A Clockwork Orange (1971) tagged with 'rape'
INSERT INTO filth.tag_given_to VALUES(347, 226);  -- A Clockwork Orange (1971) tagged with 'sexual-nudity'
INSERT INTO filth.tag_given_to VALUES(347, 225);  -- A Clockwork Orange (1971) tagged with 'nudity'
INSERT INTO filth.tag_given_to VALUES(347, 59);  -- A Clockwork Orange (1971) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(347, 58);  -- A Clockwork Orange (1971) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(338, 1);  -- Citizen Kane (1941) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(338, 8);  -- Citizen Kane (1941) tagged with 'Mystery'
INSERT INTO filth.tag_given_to VALUES(338, 32);  -- Citizen Kane (1941) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(338, 237);  -- Citizen Kane (1941) tagged with 'upper-class'
INSERT INTO filth.tag_given_to VALUES(338, 22);  -- Citizen Kane (1941) tagged with 'biography'
INSERT INTO filth.tag_given_to VALUES(338, 236);  -- Citizen Kane (1941) tagged with 'social-classes'
INSERT INTO filth.tag_given_to VALUES(338, 369);  -- Citizen Kane (1941) tagged with 'journalism/reporter(s)'
INSERT INTO filth.tag_given_to VALUES(338, 388);  -- Citizen Kane (1941) tagged with 'business/money'
INSERT INTO filth.tag_given_to VALUES(339, 33);  -- City Lights (1931) tagged with 'Comedy-Drama'
INSERT INTO filth.tag_given_to VALUES(339, 18);  -- City Lights (1931) tagged with 'Romance'
INSERT INTO filth.tag_given_to VALUES(339, 32);  -- City Lights (1931) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(339, 68);  -- City Lights (1931) tagged with 'Silent'
INSERT INTO filth.tag_given_to VALUES(520, 1);  -- The English Patient (1996) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(520, 18);  -- The English Patient (1996) tagged with 'Romance'
INSERT INTO filth.tag_given_to VALUES(520, 37);  -- The English Patient (1996) tagged with 'World War II'
INSERT INTO filth.tag_given_to VALUES(520, 60);  -- The English Patient (1996) tagged with 'Based-on-book'
INSERT INTO filth.tag_given_to VALUES(520, 122);  -- The English Patient (1996) tagged with '1930''s'
INSERT INTO filth.tag_given_to VALUES(520, 123);  -- The English Patient (1996) tagged with '1940''s'
INSERT INTO filth.tag_given_to VALUES(520, 227);  -- The English Patient (1996) tagged with 'sexual-female-nudity'
INSERT INTO filth.tag_given_to VALUES(520, 118);  -- The English Patient (1996) tagged with '20th-century'
INSERT INTO filth.tag_given_to VALUES(520, 21);  -- The English Patient (1996) tagged with 'period'
INSERT INTO filth.tag_given_to VALUES(520, 226);  -- The English Patient (1996) tagged with 'sexual-nudity'
INSERT INTO filth.tag_given_to VALUES(520, 225);  -- The English Patient (1996) tagged with 'nudity'
INSERT INTO filth.tag_given_to VALUES(520, 17);  -- The English Patient (1996) tagged with 'war'
INSERT INTO filth.tag_given_to VALUES(520, 59);  -- The English Patient (1996) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(520, 58);  -- The English Patient (1996) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(3873, 1);  -- The Revenant (2015) tagged with 'drama'
INSERT INTO filth.tag_given_to VALUES(3873, 117);  -- The Revenant (2015) tagged with '19th-century'
INSERT INTO filth.tag_given_to VALUES(3873, 207);  -- The Revenant (2015) tagged with 'based-on-a-true-story'
INSERT INTO filth.tag_given_to VALUES(3873, 47);  -- The Revenant (2015) tagged with 'intense'
INSERT INTO filth.tag_given_to VALUES(3873, 309);  -- The Revenant (2015) tagged with 'graphic-violence'
INSERT INTO filth.tag_given_to VALUES(3873, 233);  -- The Revenant (2015) tagged with 'non-sexual-male-nudity'
INSERT INTO filth.tag_given_to VALUES(3873, 347);  -- The Revenant (2015) tagged with 'revenge'
INSERT INTO filth.tag_given_to VALUES(3873, 366);  -- The Revenant (2015) tagged with 'native-american(s)'
INSERT INTO filth.tag_given_to VALUES(3873, 223);  -- The Revenant (2015) tagged with 'survival'
INSERT INTO filth.tag_given_to VALUES(3873, 21);  -- The Revenant (2015) tagged with 'period'
INSERT INTO filth.tag_given_to VALUES(3873, 58);  -- The Revenant (2015) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(3873, 63);  -- The Revenant (2015) tagged with 'graphic'
INSERT INTO filth.tag_given_to VALUES(3873, 230);  -- The Revenant (2015) tagged with 'non-sexual-nudity'
INSERT INTO filth.tag_given_to VALUES(3873, 225);  -- The Revenant (2015) tagged with 'nudity'
INSERT INTO filth.tag_given_to VALUES(3873, 60);  -- The Revenant (2015) tagged with 'based-on-book(s)'
INSERT INTO filth.tag_given_to VALUES(3873, 59);  -- The Revenant (2015) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(3873, 391);  -- The Revenant (2015) tagged with 'masculine'
INSERT INTO filth.tag_given_to VALUES(3663, 1);  -- New York, New York (1977) tagged with 'drama'
INSERT INTO filth.tag_given_to VALUES(3663, 208);  -- New York, New York (1977) tagged with 'music'
INSERT INTO filth.tag_given_to VALUES(3663, 262);  -- New York, New York (1977) tagged with 'marriage'
INSERT INTO filth.tag_given_to VALUES(3663, 123);  -- New York, New York (1977) tagged with '1940''s'
INSERT INTO filth.tag_given_to VALUES(3663, 124);  -- New York, New York (1977) tagged with '1950''s'
INSERT INTO filth.tag_given_to VALUES(3663, 61);  -- New York, New York (1977) tagged with 'arts/entertainment'
INSERT INTO filth.tag_given_to VALUES(3663, 118);  -- New York, New York (1977) tagged with '20th-century'
INSERT INTO filth.tag_given_to VALUES(3663, 21);  -- New York, New York (1977) tagged with 'period'
INSERT INTO filth.tag_given_to VALUES(153, 60);  -- Band of Outsiders (1964) tagged with 'Based-on-book'
INSERT INTO filth.tag_given_to VALUES(153, 1);  -- Band of Outsiders (1964) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(153, 25);  -- Band of Outsiders (1964) tagged with 'Crime'
INSERT INTO filth.tag_given_to VALUES(153, 32);  -- Band of Outsiders (1964) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(153, 171);  -- Band of Outsiders (1964) tagged with 'robbery'
INSERT INTO filth.tag_given_to VALUES(153, 169);  -- Band of Outsiders (1964) tagged with 'stealing'
INSERT INTO filth.tag_given_to VALUES(153, 59);  -- Band of Outsiders (1964) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(153, 58);  -- Band of Outsiders (1964) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(147, 48);  -- Bad Education (2004) tagged with 'Disgusting'
INSERT INTO filth.tag_given_to VALUES(147, 63);  -- Bad Education (2004) tagged with 'Graphic'
INSERT INTO filth.tag_given_to VALUES(147, 1);  -- Bad Education (2004) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(147, 308);  -- Bad Education (2004) tagged with 'graphic-sexual-content'
INSERT INTO filth.tag_given_to VALUES(147, 319);  -- Bad Education (2004) tagged with 'child-sexual-abuse'
INSERT INTO filth.tag_given_to VALUES(147, 187);  -- Bad Education (2004) tagged with 'catholic/catholicism'
INSERT INTO filth.tag_given_to VALUES(147, 125);  -- Bad Education (2004) tagged with '1960''s'
INSERT INTO filth.tag_given_to VALUES(147, 126);  -- Bad Education (2004) tagged with '1970''s'
INSERT INTO filth.tag_given_to VALUES(147, 49);  -- Bad Education (2004) tagged with 'offensive'
INSERT INTO filth.tag_given_to VALUES(147, 318);  -- Bad Education (2004) tagged with 'child-abuse'
INSERT INTO filth.tag_given_to VALUES(147, 317);  -- Bad Education (2004) tagged with 'abuse'
INSERT INTO filth.tag_given_to VALUES(147, 50);  -- Bad Education (2004) tagged with 'spiritual/religion'
INSERT INTO filth.tag_given_to VALUES(147, 118);  -- Bad Education (2004) tagged with '20th-century'
INSERT INTO filth.tag_given_to VALUES(147, 21);  -- Bad Education (2004) tagged with 'period'
INSERT INTO filth.tag_given_to VALUES(147, 259);  -- Bad Education (2004) tagged with 'homosexuality'
INSERT INTO filth.tag_given_to VALUES(283, 1);  -- Cache (2005) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(283, 8);  -- Cache (2005) tagged with 'Mystery'
INSERT INTO filth.tag_given_to VALUES(283, 46);  -- Cache (2005) tagged with 'Psychological'
INSERT INTO filth.tag_given_to VALUES(928, 12);  -- Last Train Home (2010) tagged with 'Documentary'
INSERT INTO filth.tag_given_to VALUES(928, 263);  -- Last Train Home (2010) tagged with 'family'
INSERT INTO filth.tag_given_to VALUES(928, 238);  -- Last Train Home (2010) tagged with 'lower-class'
INSERT INTO filth.tag_given_to VALUES(928, 287);  -- Last Train Home (2010) tagged with 'social-injustice'
INSERT INTO filth.tag_given_to VALUES(928, 236);  -- Last Train Home (2010) tagged with 'social-classes'
INSERT INTO filth.tag_given_to VALUES(991, 1);  -- M (1931) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(991, 25);  -- M (1931) tagged with 'Crime'
INSERT INTO filth.tag_given_to VALUES(991, 3);  -- M (1931) tagged with 'Thriller'
INSERT INTO filth.tag_given_to VALUES(991, 32);  -- M (1931) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(991, 46);  -- M (1931) tagged with 'Psychological'
INSERT INTO filth.tag_given_to VALUES(991, 168);  -- M (1931) tagged with 'serial-killer'
INSERT INTO filth.tag_given_to VALUES(991, 318);  -- M (1931) tagged with 'child-abuse'
INSERT INTO filth.tag_given_to VALUES(991, 167);  -- M (1931) tagged with 'murder'
INSERT INTO filth.tag_given_to VALUES(991, 317);  -- M (1931) tagged with 'abuse'
INSERT INTO filth.tag_given_to VALUES(1228, 32);  -- Pandora's Box (1929) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(1228, 68);  -- Pandora's Box (1929) tagged with 'Silent'
INSERT INTO filth.tag_given_to VALUES(1228, 1);  -- Pandora's Box (1929) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(1228, 81);  -- Pandora's Box (1929) tagged with 'Based-on-play'
INSERT INTO filth.tag_given_to VALUES(1228, 59);  -- Pandora's Box (1929) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(1228, 58);  -- Pandora's Box (1929) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(1242, 1);  -- The Passion of Anna (1970) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(1242, 43);  -- The Passion of Anna (1970) tagged with 'slow'
INSERT INTO filth.tag_given_to VALUES(1242, 30);  -- The Passion of Anna (1970) tagged with 'depressing'
INSERT INTO filth.tag_given_to VALUES(1242, 225);  -- The Passion of Anna (1970) tagged with 'nudity'
INSERT INTO filth.tag_given_to VALUES(1242, 226);  -- The Passion of Anna (1970) tagged with 'sexual-nudity'
INSERT INTO filth.tag_given_to VALUES(1242, 228);  -- The Passion of Anna (1970) tagged with 'brief-sexual-female-nudity'
INSERT INTO filth.tag_given_to VALUES(1242, 15);  -- The Passion of Anna (1970) tagged with 'unconventional'
INSERT INTO filth.tag_given_to VALUES(1242, 262);  -- The Passion of Anna (1970) tagged with 'marriage'
INSERT INTO filth.tag_given_to VALUES(1262, 1);  -- Pi (1998) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(1262, 4);  -- Pi (1998) tagged with 'Independent'
INSERT INTO filth.tag_given_to VALUES(1262, 32);  -- Pi (1998) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(1262, 3);  -- Pi (1998) tagged with 'Thriller'
INSERT INTO filth.tag_given_to VALUES(1262, 38);  -- Pi (1998) tagged with 'New York City'
INSERT INTO filth.tag_given_to VALUES(1262, 29);  -- Pi (1998) tagged with 'Dark'
INSERT INTO filth.tag_given_to VALUES(1262, 389);  -- Pi (1998) tagged with 'obsession'
INSERT INTO filth.tag_given_to VALUES(1375, 25);  -- Road to Perdition (2002) tagged with 'Crime'
INSERT INTO filth.tag_given_to VALUES(1375, 1);  -- Road to Perdition (2002) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(1375, 60);  -- Road to Perdition (2002) tagged with 'Based-on-book'
INSERT INTO filth.tag_given_to VALUES(1375, 77);  -- Road to Perdition (2002) tagged with 'Mafia'
INSERT INTO filth.tag_given_to VALUES(1375, 337);  -- Road to Perdition (2002) tagged with 'on-the-run'
INSERT INTO filth.tag_given_to VALUES(1375, 329);  -- Road to Perdition (2002) tagged with 'parenthood'
INSERT INTO filth.tag_given_to VALUES(1375, 263);  -- Road to Perdition (2002) tagged with 'family'
INSERT INTO filth.tag_given_to VALUES(1375, 174);  -- Road to Perdition (2002) tagged with 'gangster'
INSERT INTO filth.tag_given_to VALUES(1375, 122);  -- Road to Perdition (2002) tagged with '1930''s'
INSERT INTO filth.tag_given_to VALUES(1375, 118);  -- Road to Perdition (2002) tagged with '20th-century'
INSERT INTO filth.tag_given_to VALUES(1375, 21);  -- Road to Perdition (2002) tagged with 'period'
INSERT INTO filth.tag_given_to VALUES(1375, 59);  -- Road to Perdition (2002) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(1375, 58);  -- Road to Perdition (2002) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(1375, 379);  -- Road to Perdition (2002) tagged with 'father-son'
INSERT INTO filth.tag_given_to VALUES(1375, 391);  -- Road to Perdition (2002) tagged with 'masculine'
INSERT INTO filth.tag_given_to VALUES(3871, 10);  -- Casino Royale (2006) tagged with 'action'
INSERT INTO filth.tag_given_to VALUES(3871, 76);  -- Casino Royale (2006) tagged with 'espionage'
INSERT INTO filth.tag_given_to VALUES(3871, 141);  -- Casino Royale (2006) tagged with 'mi6'
INSERT INTO filth.tag_given_to VALUES(3871, 274);  -- Casino Royale (2006) tagged with 'james-bond'
INSERT INTO filth.tag_given_to VALUES(3871, 244);  -- Casino Royale (2006) tagged with 'terrorism'
INSERT INTO filth.tag_given_to VALUES(3871, 60);  -- Casino Royale (2006) tagged with 'based-on-book(s)'
INSERT INTO filth.tag_given_to VALUES(3871, 136);  -- Casino Royale (2006) tagged with 'government-agency'
INSERT INTO filth.tag_given_to VALUES(3871, 59);  -- Casino Royale (2006) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(3871, 58);  -- Casino Royale (2006) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(3871, 391);  -- Casino Royale (2006) tagged with 'masculine'
INSERT INTO filth.tag_given_to VALUES(3878, 12);  -- 56 Up (2012) tagged with 'documentary'
INSERT INTO filth.tag_given_to VALUES(3878, 55);  -- 56 Up (2012) tagged with 'series'
INSERT INTO filth.tag_given_to VALUES(3880, 1);  -- The Drop (2014) tagged with 'drama'
INSERT INTO filth.tag_given_to VALUES(3880, 77);  -- The Drop (2014) tagged with 'organized-crime'
INSERT INTO filth.tag_given_to VALUES(3880, 171);  -- The Drop (2014) tagged with 'robbery'
INSERT INTO filth.tag_given_to VALUES(3880, 64);  -- The Drop (2014) tagged with 'based-on-short-story'
INSERT INTO filth.tag_given_to VALUES(3880, 38);  -- The Drop (2014) tagged with 'new-york-city'
INSERT INTO filth.tag_given_to VALUES(3880, 25);  -- The Drop (2014) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(3880, 169);  -- The Drop (2014) tagged with 'stealing'
INSERT INTO filth.tag_given_to VALUES(3880, 59);  -- The Drop (2014) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(3880, 58);  -- The Drop (2014) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(3670, 34);  -- Irrational Man (2015) tagged with 'drama-comedy'
INSERT INTO filth.tag_given_to VALUES(3670, 243);  -- Irrational Man (2015) tagged with 'teaching/teacher'
INSERT INTO filth.tag_given_to VALUES(3670, 25);  -- Irrational Man (2015) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(3670, 242);  -- Irrational Man (2015) tagged with 'education'
INSERT INTO filth.tag_given_to VALUES(3670, 167);  -- Irrational Man (2015) tagged with 'murder'
INSERT INTO filth.tag_given_to VALUES(3671, 1);  -- A Most Violent Year (2014) tagged with 'drama'
INSERT INTO filth.tag_given_to VALUES(3671, 127);  -- A Most Violent Year (2014) tagged with '1980''s'
INSERT INTO filth.tag_given_to VALUES(3671, 25);  -- A Most Violent Year (2014) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(3671, 38);  -- A Most Violent Year (2014) tagged with 'new-york-city'
INSERT INTO filth.tag_given_to VALUES(3671, 118);  -- A Most Violent Year (2014) tagged with '20th-century'
INSERT INTO filth.tag_given_to VALUES(3671, 21);  -- A Most Violent Year (2014) tagged with 'period'
INSERT INTO filth.tag_given_to VALUES(3671, 262);  -- A Most Violent Year (2014) tagged with 'marriage'
INSERT INTO filth.tag_given_to VALUES(3671, 388);  -- A Most Violent Year (2014) tagged with 'business/money'
INSERT INTO filth.tag_given_to VALUES(3671, 391);  -- A Most Violent Year (2014) tagged with 'masculine'
INSERT INTO filth.tag_given_to VALUES(2, 57);  -- 3:10 to Yuma tagged with 'Remake'
INSERT INTO filth.tag_given_to VALUES(2, 16);
INSERT INTO filth.tag_given_to VALUES(2, 1);
INSERT INTO filth.tag_given_to VALUES(2, 21);  -- 3:10 to Yuma (2007) tagged with 'period'
INSERT INTO filth.tag_given_to VALUES(2, 117);  -- 3:10 to Yuma (2007) tagged with '19th-century'
INSERT INTO filth.tag_given_to VALUES(2, 171);  -- 3:10 to Yuma (2007) tagged with 'robbery'
INSERT INTO filth.tag_given_to VALUES(2, 169);  -- 3:10 to Yuma (2007) tagged with 'stealing'
INSERT INTO filth.tag_given_to VALUES(2, 25);  -- 3:10 to Yuma (2007) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(2, 391);  -- 3:10 to Yuma (2007) tagged with 'masculine'
INSERT INTO filth.tag_given_to VALUES(3633, 7);  -- Castle in the Sky (1986) tagged with 'animation'
INSERT INTO filth.tag_given_to VALUES(3633, 11);  -- Castle in the Sky (1986) tagged with 'adventure'
INSERT INTO filth.tag_given_to VALUES(3633, 10);  -- Castle in the Sky (1986) tagged with 'action'
INSERT INTO filth.tag_given_to VALUES(3633, 5);  -- Castle in the Sky (1986) tagged with 'fantasy'
INSERT INTO filth.tag_given_to VALUES(3633, 382);  -- Castle in the Sky (1986) tagged with 'pirates'
INSERT INTO filth.tag_given_to VALUES(3645, 27);  -- How to Steal a Million (1966) tagged with 'romantic-comedy'
INSERT INTO filth.tag_given_to VALUES(3645, 170);  -- How to Steal a Million (1966) tagged with 'burglary'
INSERT INTO filth.tag_given_to VALUES(3645, 61);  -- How to Steal a Million (1966) tagged with 'arts/entertainment'
INSERT INTO filth.tag_given_to VALUES(3645, 250);  -- How to Steal a Million (1966) tagged with 'light'
INSERT INTO filth.tag_given_to VALUES(3645, 2);  -- How to Steal a Million (1966) tagged with 'comedy'
INSERT INTO filth.tag_given_to VALUES(3645, 169);  -- How to Steal a Million (1966) tagged with 'stealing'
INSERT INTO filth.tag_given_to VALUES(3645, 25);  -- How to Steal a Million (1966) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(3655, 34);  -- Payback (1999) tagged with 'drama-comedy'
INSERT INTO filth.tag_given_to VALUES(3655, 347);  -- Payback (1999) tagged with 'revenge'
INSERT INTO filth.tag_given_to VALUES(3655, 182);  -- Payback (1999) tagged with 'prostitution'
INSERT INTO filth.tag_given_to VALUES(3655, 171);  -- Payback (1999) tagged with 'robbery'
INSERT INTO filth.tag_given_to VALUES(3655, 167);  -- Payback (1999) tagged with 'murder'
INSERT INTO filth.tag_given_to VALUES(3655, 77);  -- Payback (1999) tagged with 'organized-crime'
INSERT INTO filth.tag_given_to VALUES(3655, 60);  -- Payback (1999) tagged with 'based-on-book'
INSERT INTO filth.tag_given_to VALUES(3655, 25);  -- Payback (1999) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(3655, 169);  -- Payback (1999) tagged with 'stealing'
INSERT INTO filth.tag_given_to VALUES(3655, 59);  -- Payback (1999) tagged with 'based-on-previously-written-material'
INSERT INTO filth.tag_given_to VALUES(3655, 58);  -- Payback (1999) tagged with 'based-on-something'
INSERT INTO filth.tag_given_to VALUES(3659, 2);  -- The Italian Job (1969) tagged with 'comedy'
INSERT INTO filth.tag_given_to VALUES(3659, 171);  -- The Italian Job (1969) tagged with 'robbery'
INSERT INTO filth.tag_given_to VALUES(3659, 77);  -- The Italian Job (1969) tagged with 'organized-crime'
INSERT INTO filth.tag_given_to VALUES(3659, 169);  -- The Italian Job (1969) tagged with 'stealing'
INSERT INTO filth.tag_given_to VALUES(3659, 25);  -- The Italian Job (1969) tagged with 'crime'
INSERT INTO filth.tag_given_to VALUES(3659, 387);  -- The Italian Job (1969) tagged with 'chase'
INSERT INTO filth.tag_given_to VALUES(1027, 1);  -- Marty (1955) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(1027, 18);  -- Marty (1955) tagged with 'Romance'
INSERT INTO filth.tag_given_to VALUES(1027, 32);  -- Marty (1955) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(1027, 38);  -- Marty (1955) tagged with 'New York City'
INSERT INTO filth.tag_given_to VALUES(1027, 251);  -- Marty (1955) tagged with 'uplifting'
INSERT INTO filth.tag_given_to VALUES(1002, 2);  -- Making a Living (1914) tagged with 'Comedy'
INSERT INTO filth.tag_given_to VALUES(1002, 14);  -- Making a Living (1914) tagged with 'Short'
INSERT INTO filth.tag_given_to VALUES(1002, 32);  -- Making a Living (1914) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(1002, 68);  -- Making a Living (1914) tagged with 'Silent'
INSERT INTO filth.tag_given_to VALUES(931, 1);  -- L'atalante (1934) tagged with 'Drama'
INSERT INTO filth.tag_given_to VALUES(931, 18);  -- L'atalante (1934) tagged with 'Romance'
INSERT INTO filth.tag_given_to VALUES(931, 32);  -- L'atalante (1934) tagged with 'Black-and-White'
INSERT INTO filth.tag_given_to VALUES(931, 262);  -- L'atalante (1934) tagged with 'marriage'
INSERT INTO filth.tag_given_to VALUES(931, 266);  -- L'atalante (1934) tagged with 'at-sea'
INSERT INTO filth.tag_given_to VALUES(846, 15);  -- Jackass: The Movie (2002) tagged with 'Unconventional'
INSERT INTO filth.tag_given_to VALUES(846, 2);  -- Jackass: The Movie (2002) tagged with 'Comedy'
INSERT INTO filth.tag_given_to VALUES(846, 352);  -- Jackass: The Movie (2002) tagged with 'sophmoric'
INSERT INTO filth.tag_given_to VALUES(846, 84);  -- Jackass: The Movie (2002) tagged with 'gross-out'
INSERT INTO filth.tag_given_to VALUES(846, 391);  -- Jackass: The Movie (2002) tagged with 'masculine'
