INSERT INTO filth.country VALUES ('USA');
INSERT INTO filth.country VALUES ('France');
INSERT INTO filth.country VALUES ('England');
INSERT INTO filth.country VALUES ('Canada');
INSERT INTO filth.country VALUES ('China');
INSERT INTO filth.country VALUES ('Russia');
INSERT INTO filth.country VALUES ('Germany');
INSERT INTO filth.country VALUES ('Argentina');
INSERT INTO filth.country VALUES ('Portugal');
INSERT INTO filth.country VALUES ('Spain');
INSERT INTO filth.country VALUES ('Mexico');
INSERT INTO filth.country VALUES ('Italy');
INSERT INTO filth.country VALUES ('Ireland');
INSERT INTO filth.country VALUES ('Scotland');
INSERT INTO filth.country VALUES ('Czech Republic');
INSERT INTO filth.country VALUES ('Iran');
INSERT INTO filth.country VALUES ('The Netherlands');
INSERT INTO filth.country VALUES ('Sweden');
INSERT INTO filth.country VALUES ('Finland');
INSERT INTO filth.country VALUES ('Norway');
INSERT INTO filth.country VALUES ('Poland');
INSERT INTO filth.country VALUES ('Bosnia');
INSERT INTO filth.country VALUES ('Japan');
INSERT INTO filth.country VALUES ('Taiwan');
INSERT INTO filth.country VALUES ('India');
INSERT INTO filth.country VALUES ('Greece');
INSERT INTO filth.country VALUES ('Israel');
INSERT INTO filth.country VALUES ('Lebanon');
INSERT INTO filth.country VALUES ('South Africa');
INSERT INTO filth.country VALUES ('Australia');
INSERT INTO filth.country VALUES ('New Zealand');
INSERT INTO filth.country VALUES ('Brazil');
INSERT INTO filth.country VALUES ('Iceland');
INSERT INTO filth.country VALUES ('Vietnam');
INSERT INTO filth.country VALUES ('Denmark');
INSERT INTO filth.country VALUES ('Belgium');
INSERT INTO filth.country VALUES ('Switzerland');
INSERT INTO filth.country VALUES ('Austria');
INSERT INTO filth.country VALUES ('Kazakhstan');
INSERT INTO filth.country VALUES ('Algeria');
INSERT INTO filth.country VALUES ('Palestine');
INSERT INTO filth.country VALUES ('Nepal');
INSERT INTO filth.country VALUES ('Georgia');
INSERT INTO filth.country VALUES ('Macedonia');
INSERT INTO filth.country VALUES ('Cuba');
INSERT INTO filth.country VALUES ('Czechoslovakia');
INSERT INTO filth.country VALUES ('Puerto Rico');
INSERT INTO filth.country VALUES ('Hungary');
INSERT INTO filth.country VALUES ('Yugoslavia');
INSERT INTO filth.country VALUES ('Nicaragua');
INSERT INTO filth.country VALUES ('USSR');
INSERT INTO filth.country VALUES ('Ivory Coast');
INSERT INTO filth.country VALUES ('Wales');
INSERT INTO filth.country VALUES ('South Korea');
INSERT INTO filth.country VALUES ('Chile');
INSERT INTO filth.country VALUES ('Cambodia');
INSERT INTO filth.country VALUES ('Estonia');
INSERT INTO filth.country VALUES ('Mauritania');
