INSERT INTO filth.country VALUES (1, 'USA');
INSERT INTO filth.country VALUES (2, 'France');
INSERT INTO filth.country VALUES (3, 'England');
INSERT INTO filth.country VALUES (4, 'Canada');
INSERT INTO filth.country VALUES (5, 'China');
INSERT INTO filth.country VALUES (6, 'Russia');
INSERT INTO filth.country VALUES (7, 'Germany');
INSERT INTO filth.country VALUES (8, 'Argentina');
INSERT INTO filth.country VALUES (9, 'Portugal');
INSERT INTO filth.country VALUES (10, 'Spain');
INSERT INTO filth.country VALUES (11, 'Mexico');
INSERT INTO filth.country VALUES (12, 'Italy');
INSERT INTO filth.country VALUES (13, 'Ireland');
INSERT INTO filth.country VALUES (14, 'Scotland');
INSERT INTO filth.country VALUES (15, 'Czech Republic');
INSERT INTO filth.country VALUES (16, 'Iran');
INSERT INTO filth.country VALUES (17, 'The Netherlands');
INSERT INTO filth.country VALUES (18, 'Sweden');
INSERT INTO filth.country VALUES (19, 'Finland');
INSERT INTO filth.country VALUES (20, 'Norway');
INSERT INTO filth.country VALUES (21, 'Poland');
INSERT INTO filth.country VALUES (22, 'Bosnia');
INSERT INTO filth.country VALUES (23, 'Japan');
INSERT INTO filth.country VALUES (24, 'Taiwan');
INSERT INTO filth.country VALUES (25, 'India');
INSERT INTO filth.country VALUES (26, 'Greece');
INSERT INTO filth.country VALUES (27, 'Israel');
INSERT INTO filth.country VALUES (28, 'Lebanon');
INSERT INTO filth.country VALUES (29, 'South Africa');
INSERT INTO filth.country VALUES (30, 'Australia');
INSERT INTO filth.country VALUES (31, 'New Zealand');
INSERT INTO filth.country VALUES (32, 'Brazil');
INSERT INTO filth.country VALUES (33, 'Iceland');
INSERT INTO filth.country VALUES (34, 'Vietnam');
INSERT INTO filth.country VALUES (35, 'Denmark');
INSERT INTO filth.country VALUES (36, 'Belgium');
INSERT INTO filth.country VALUES (37, 'Switzerland');
INSERT INTO filth.country VALUES (38, 'Austria');
INSERT INTO filth.country VALUES (39, 'Kazakhstan');
INSERT INTO filth.country VALUES (40, 'Algeria');
INSERT INTO filth.country VALUES (41, 'Palestine');
INSERT INTO filth.country VALUES (42, 'Nepal');
INSERT INTO filth.country VALUES (43, 'Georgia');
INSERT INTO filth.country VALUES (44, 'Macedonia');
INSERT INTO filth.country VALUES (45, 'Cuba');
INSERT INTO filth.country VALUES (46, 'Czechoslovakia');
INSERT INTO filth.country VALUES (47, 'Puerto Rico');
INSERT INTO filth.country VALUES (48, 'Hungary');
INSERT INTO filth.country VALUES (49, 'Yugoslavia');
INSERT INTO filth.country VALUES (50, 'Nicaragua');
INSERT INTO filth.country VALUES (51, 'USSR');
INSERT INTO filth.country VALUES (52, 'Ivory Coast');
INSERT INTO filth.country VALUES (53, 'Wales');
INSERT INTO filth.country VALUES (54, 'South Korea');
INSERT INTO filth.country VALUES (55, 'Chile');
INSERT INTO filth.country VALUES (56, 'Cambodia');
INSERT INTO filth.country VALUES (57, 'Estonia');
INSERT INTO filth.country VALUES (58, 'Mauritania');
INSERT INTO filth.country VALUES (59, 'Peru');
INSERT INTO filth.country VALUES (60, 'Colombia');
INSERT INTO filth.country VALUES (61, 'Jordan');
INSERT INTO filth.country VALUES (62, 'Romania');
INSERT INTO filth.country VALUES (63, 'Rwanda');
