INSERT INTO country VALUES ('USA');
INSERT INTO country VALUES ('France');
INSERT INTO country VALUES ('England');
INSERT INTO country VALUES ('Canada');
INSERT INTO country VALUES ('China');
INSERT INTO country VALUES ('Russia');
INSERT INTO country VALUES ('Germany');
INSERT INTO country VALUES ('Argentina');
INSERT INTO country VALUES ('Portugal');
INSERT INTO country VALUES ('Spain');
INSERT INTO country VALUES ('Mexico');
INSERT INTO country VALUES ('Italy');
INSERT INTO country VALUES ('Ireland');
INSERT INTO country VALUES ('Scotland');
INSERT INTO country VALUES ('Czech Republic');
INSERT INTO country VALUES ('Iran');
INSERT INTO country VALUES ('The Netherlands');
INSERT INTO country VALUES ('Sweden');
INSERT INTO country VALUES ('Finland');
INSERT INTO country VALUES ('Norway');
INSERT INTO country VALUES ('Poland');
INSERT INTO country VALUES ('Bosnia');
INSERT INTO country VALUES ('Japan');
INSERT INTO country VALUES ('Taiwan');
INSERT INTO country VALUES ('India');
INSERT INTO country VALUES ('Greece');
INSERT INTO country VALUES ('Israel');
INSERT INTO country VALUES ('Lebanon');
INSERT INTO country VALUES ('South Africa');
INSERT INTO country VALUES ('Australia');
INSERT INTO country VALUES ('New Zealand');
INSERT INTO country VALUES ('Brazil');
INSERT INTO country VALUES ('Iceland');
INSERT INTO country VALUES ('Vietnam');
INSERT INTO country VALUES ('Denmark');
INSERT INTO country VALUES ('Belgium');
INSERT INTO country VALUES ('Switzerland');
INSERT INTO country VALUES ('Austria');
INSERT INTO country VALUES ('Kazakhstan');
INSERT INTO country VALUES ('Algeria');
INSERT INTO country VALUES ('The Palestinian Territories');
INSERT INTO country VALUES ('Nepal');
INSERT INTO country VALUES ('Georgia');
INSERT INTO country VALUES ('Macedonia');
INSERT INTO country VALUES ('Cuba');
INSERT INTO country VALUES ('Czechoslovakia');
INSERT INTO country VALUES ('Puerto Rico');
INSERT INTO country VALUES ('Hungary');
INSERT INTO country VALUES ('Yugoslavia');
INSERT INTO country VALUES ('Nicaragua');
INSERT INTO country VALUES ('USSR');
INSERT INTO country VALUES ('Ivory Coast');
INSERT INTO country VALUES ('Wales');
