INSERT INTO crew_person VALUES (DEFAULT, 'd''Arrast', 'Harry', 'd''Abbadie');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Doty', 'Douglas', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stewart', 'Donald', 'Ogden');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Saunders', 'John', 'Monk');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hubbard', 'Lucien', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jackson', 'Joseph', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Howard', 'Sidney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Burke', 'Edwin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Heath', 'Percy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hoffenstein', 'Samuel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'St. Johns', 'Adela', 'Rogers');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Murfin', 'Jane', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jones', 'Grover', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'McNutt', 'William', 'Slavens');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Green', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Levien', 'Sonya', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Heerman', 'Victor', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mason', 'Sarah', 'Y.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Riskin', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lord', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'MacArthur', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Goodrich', 'Frances', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hackett', 'Albert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Grashin', 'Mauri', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Krasna', 'Norman', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Caesar', 'Arthur', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Young', 'Waldemar', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Balderston', 'John', 'L.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Abdullah', 'Achmed', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jennings', 'Talbot', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Furthman', 'Jules', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wilson', 'Carey', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Nichols', 'Dudley', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Robinson', 'Casey', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hatch', 'Eric', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ryskind', 'Morris', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Collings', 'Pierre', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gibney', 'Sheridan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Raine', 'Norman', 'Reilly');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Herald', 'Heinz', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Herczeg', 'Geza', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Parker', 'Dorothy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Campbell', 'Alan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Carson', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Delmar', 'Vina', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Veiller', 'Anthony', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mahin', 'John', 'Lee');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Connelly', 'Marc', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Every', 'Dale', 'Van');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Epstein', 'Julius', 'J.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Coffee', 'Lenore', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Dalrymple', 'Ian', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wead', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hill', 'Elizabeth', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schary', 'Dore', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shaw', 'George', 'Bernard');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sherriff', 'R.', 'C.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'West', 'Claudine', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Maschwitz', 'Eric', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Buchman', 'Sidney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brackett', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Reisch', 'Walter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bennett', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Harrison', 'Joan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Burnside', 'Norman', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sturges', 'Preston', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Trumbo', 'Dalton', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sherwood', 'Robert', 'E.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Johnson', 'Nunnally', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jarrico', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Finkel', 'Abem', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Chandlee', 'Harry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Koch', 'Howard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tunberg', 'Karl', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ware', 'Darrell', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Dunne', 'Philip', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hellman', 'Lillian', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Oppenheimer', 'George', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Burnett', 'W.', 'R.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Butler', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hartman', 'Don', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lardner Jr.', 'Ring', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kanin', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Powell', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pressburger', 'Emeric', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Froeschel', 'George', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wimperis', 'Arthur', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Swerling', 'Jo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ackland', 'Rodney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hilton', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shaw', 'Irwin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Coward', 'Noel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Scott', 'Allan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hammett', 'Dashiell', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Epstein', 'Philip', 'G.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Russell', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ross', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Flournoy', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Foster', 'Lewis', 'R.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Trotti', 'Lamar', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cady', 'Jerome', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Connell', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lehman', 'Gladys', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Chandler', 'Raymond', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Dratler', 'Jay', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Reinhardt', 'Betty', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Druten', 'John', 'Van');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cavett', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brecher', 'Irving', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Finkelhoffe', 'Fred', 'F.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Holmes', 'Milton', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kurnitz', 'Harry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schweizer', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Connolly', 'Myles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Yordan', 'Philip', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Maltz', 'Albert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Atlas', 'Leopold', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Endore', 'Guy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stevenson', 'Philip', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'MacDougall', 'Ranald', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Slesinger', 'Tess', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Davis', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Panama', 'Norman', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Frank', 'Melvin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Prevert', 'Jacques', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Box', 'Muriel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Box', 'Sydney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Benson', 'Sally', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Havelock-Allan', 'Anthony', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Neame', 'Ronald', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Amidei', 'Sergio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Polonsky', 'Abraham', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kanin', 'Garson', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sheldon', 'Sidney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Franci', 'Adolfo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Viola', 'C.', 'G.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Zavattini', 'Cesare', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Paxton', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Murphy', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hart', 'Moss', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wechsler', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cube', 'Irmgard', 'Von');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Vincent', 'Allen', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Partos', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brand', 'Millen', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Breen', 'Richard', 'L.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Foreman', 'Carl', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pirosh', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Clarke', 'T.E.B.', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hayes', 'Alfred', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pagliero', 'Marcello', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rossellini', 'Roberto', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Levitt', 'Helen', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Loeb', 'Janice', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Meyers', 'Sidney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mannheimer', 'Albert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Maddow', 'Ben', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Marshman Jr.', 'D.', 'M.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kellogg', 'Virginia', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schoenfeld', 'Bernard', 'C.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Samuels', 'Lesser', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Agee', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ophuls', 'Max', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Natanson', 'Jacques', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wyler', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Williams', 'Tennessee', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wilson', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brown', 'Harry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lerner', 'Alan', 'Jay');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Newman', 'Walter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Greene', 'Clarence', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rouse', 'Russell', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Nugent', 'Frank', 'S.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schnee', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'MacDougall', 'Roger', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Dighton', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mackendrick', 'Alexander', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Steinbeck', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Boehm', 'Sydney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rattigan', 'Terence', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Deutsch', 'Helen', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Guthrie Jr.', 'A.', 'B.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ambler', 'Eric', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Taradash', 'Daniel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kaufman', 'Millard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rolfe', 'Sam', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bloom', 'Harold', 'Jack');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Comden', 'Betty', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Green', 'Adolph', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hayes', 'John', 'Michael');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kingsley', 'Dorothy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Roberts', 'Stanley', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Taylor', 'Samuel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lehman', 'Ernest', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schulberg', 'Budd', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Davies', 'Valentine', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brodney', 'Oscar', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rose', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Osborn', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Fuchs', 'Daniel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lennart', 'Isobel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Chayefsky', 'Paddy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ludwig', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shavelson', 'Melville', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rose', 'Jack', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sperling', 'Milton', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lavery', 'Emmet', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Marquet', 'Henri', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Corwin', 'Norman', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Guiol', 'Fred', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Moffat', 'Ivan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Poe', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Perelman', 'S.', 'J.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lewin', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lamorisse', 'Albert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pinelli', 'Tullio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stone', 'Andrew', 'L.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rose', 'Reginald', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Boulle', 'Pierre', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Campbell', 'R.', 'Wright');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Goff', 'Ivan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Roberts', 'Ben', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Flaiano', 'Ennio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wells', 'George', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gershe', 'Leonard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gay', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gidding', 'Nelson', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mankiewicz', 'Don', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kanin', 'Fay', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Young', 'Nedrick', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Smith', 'Harold', 'Jacob');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bowers', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Grant', 'James', 'Edward');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mayes', 'Wendell', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Paterson', 'Neil', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Anderson', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Diamond', 'I.A.L.', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Moussy', 'Marcel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shapiro', 'Stanley', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Richlin', 'Maurice', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kennaway', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lambert', 'Gavin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Forbes', 'Bryan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Duras', 'Marguerite', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Carroll', 'Sidney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mann', 'Abby', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Axelrod', 'George', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Fabbri', 'Diego', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Montanelli', 'Indro', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Henning', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rondi', 'Brunello', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Inge', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Yoshov', 'Valentin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Chukhrai', 'Grigori', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bolt', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gibson', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Nabokov', 'Vladimir', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Foote', 'Horton', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Perry', 'Eleanor', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'de Concini', 'Ennio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Giannetti', 'Alfredo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Monaster', 'Nate', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kaufman', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Reinhardt', 'Wolfgang', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Robbe-Grillet', 'Alain', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Osborne', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ravetch', 'Irving', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Frank Jr.', 'Harriet', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ephron', 'Phoebe', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ephron', 'Henry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bourguignon', 'Serge', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tudal', 'Antoine', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bernari', 'Carlo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Campanile', 'Pasquale', 'Festa');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Franciosa', 'Massimo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Loy', 'Nanni', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schulman', 'Arnold', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Webb', 'James', 'R.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Anhalt', 'Edward', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Walsh', 'Bill', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'DaGradi', 'Don', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'George', 'Peter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Southern', 'Terry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stone', 'Peter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tarloff', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Age', null, null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Scarpelli', 'Furio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Monicelli', 'Mario', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rappeneau', 'Jean-Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mnouchkine', 'Ariane', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Boulanger', 'Daniel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'De Broca', 'Philippe', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hayes', 'Raphael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hampton', 'Orville', 'H.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Owen', 'Alun', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gardner', 'Herb', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pierson', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mann', 'Stanley', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kohn', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Raphael', 'Frederic', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Demy', 'Jacques', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Coen', 'Franklin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Guerra', 'Tonino', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Salvioni', 'Giorgio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'D''Amico', 'Suso', 'Cecchi');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Davies', 'Jack', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Annakin', 'Ken', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Naughton', 'Bill', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bond', 'Edward', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ardrey', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Uytterhoeven', 'Pierre', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Johnston', 'Clint', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Peters', 'Don', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Strick', 'Joseph', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Haines', 'Fred', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Silliphant', 'Stirling', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pearce', 'Donn', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Willingham', 'Calder', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Newman', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lear', 'Norman', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Semprun', 'Jorge', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stern', 'Stewart', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Harris', 'Vernon', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Goldman', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Simon', 'Neil', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Clarke', 'Arthur', 'C.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brooks', 'Mel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Solinas', 'Franco', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wallach', 'Ira', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Thompson', 'Robert', 'E.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Salt', 'Waldo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hale', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Boland', 'Bridget', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Badalucco', 'Nicola', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Medioli', 'Enrico', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Visconti', 'Luchino', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mazursky', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tucker', 'Larry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Green', 'Walon', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Taylor', 'Renee', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bologna', 'Joseph', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Goodman', 'David', 'Zelag');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kramer', 'Larry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'North', 'Edmund', 'H.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wexler', 'Norman', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rohmer', 'Eric', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Joyce', 'Adrien', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Segal', 'Erich', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'McMurtry', 'Larry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pirro', 'Ugo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bonicelli', 'Vittorio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tidyman', 'Ernest', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gilliatt', 'Penelope', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Petri', 'Elio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Raucher', 'Herman', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lewis', 'Andy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lewis', 'Dave', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Elder', 'Lonne', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Puzo', 'Mario', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Allen', 'Jay', 'Presson');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Forslund', 'Bengt', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'McCloy', 'Terence', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Clark', 'Chris', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'de Passe', 'Suzanne', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Larner', 'Jeremy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sargent', 'Alvin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bridges', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Blatty', 'William', 'Peter');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Towne', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shagan', 'Steve', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ward', 'David', 'S.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Katz', 'Gloria', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Huyck', 'Willard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Greenfeld', 'Josh', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Richard', 'Jean-Louis', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schiffman', 'Suzanne', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Getchell', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Barry', 'Julian', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Dehn', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Richler', 'Mordecai', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Allan', 'Ted', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hauben', 'Lawrence', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Goldman', 'Bo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Maccari', 'Ruggero', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Risi', 'Dino', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hill', 'Gladys', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tacchella', 'Jean-Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bernstein', 'Walter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Butler', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Zapponi', 'Bernadino', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Meyer', 'Nicholas', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brickman', 'Marshall', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Laurents', 'Arthur', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shaffer', 'Peter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Carriere', 'Jean-Claude', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gelbart', 'Larry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Carlino', 'Lewis', 'John');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Slade', 'Bernard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'May', 'Elaine', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Washburn', 'Deric', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jones', 'Robert', 'C.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Milius', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Burns', 'Allan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Veber', 'Francis', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Danon', 'Marcello', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Poiret', 'Jean', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Curtin', 'Valerie', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gray', 'Mike', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cook', 'T.S.', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Aurthur', 'Robert', 'Alan');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tesich', 'Steve', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hardy', 'Jonathan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stevens', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Marcus', 'Lawrence', 'B.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'DeVore', 'Christopher', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bergren', 'Eric', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rickman', 'Tom', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gruault', 'Jean', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gore', 'Christopher', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Richter', 'W.', 'D.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Meyers', 'Nancy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shyer', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'Harvey', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Thompson', 'Ernest', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pinter', 'Harold', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Potter', 'Dennis', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Weller', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Griffiths', 'Trevor', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Luedtke', 'Kurt', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Guare', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gordon', 'Steve', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Welland', 'Colin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stewart', 'Donald', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Edwards', 'Blake', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schisgal', 'Murray', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stewart', 'Douglas', 'Day');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mathison', 'Melissa', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Briley', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Russell', 'Willy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Harwood', 'Ronald', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Benedek', 'Barbara', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lasker', 'Lawrence', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Parkes', 'Walter', 'F.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ephron', 'Nora', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Arlen', 'Alice', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Austin', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Robinson', 'Bruce', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Fuller', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ganz', 'Lowell', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mandel', 'Babaloo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Friedman', 'Bruce', 'Jay');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Nava', 'Gregory', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Thomas', 'Anna', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Petrie Jr.', 'Daniel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Condon', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Roach', 'Janet', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schrader', 'Leonard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Meyjes', 'Menno', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Puenzo', 'Luis', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bortnik', 'Aida', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wallace', 'Earl', 'W.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kelley', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gale', 'Bob', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stoppard', 'Tom', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'McKeown', 'Charles', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Anderson', 'Hesper', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Medoff', 'Mark', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Henley', 'Beth', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gideon', 'Raynold', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Evans', 'Bruce', 'A.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jhabvala', 'Ruth', 'Prawer');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Price', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kureishi', 'Hanif', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Boyle', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hogan', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shadie', 'Ken', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cornell', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Peploe', 'Mark', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jonsson', 'Reidar', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brannstrom', 'Brasse', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Berglund', 'Per', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Herr', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hasford', 'Gustav', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Dearden', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Huston', 'Tony', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shanley', 'John', 'Patrick');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Galati', 'Frank', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Edzard', 'Christine', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Phelan', 'Anna', 'Hamilton');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kaufman', 'Philip', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hampton', 'Christopher', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bass', 'Ronald', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Morrow', 'Barry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Foner', 'Naomi', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ross', 'Gary', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Spielberg', 'Anne', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Shelton', 'Ron', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cleese', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kovic', 'Ron', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Robinson', 'Phil', 'Alden');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Simon', 'Roger', 'L.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Uhry', 'Alfred', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Connaughton', 'Shane', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schulman', 'Tom', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Blake', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pileggi', 'Nicholas', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Zaillian', 'Steven', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kazan', 'Nicholas', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Westlake', 'Donald', 'E.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rubin', 'Bruce', 'Joel');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stillman', 'Whit', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Conroy', 'Pat', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Johnston', 'Becky', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Flagg', 'Fannie', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sobieski', 'Carol', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Holland', 'Agnieszka', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tally', 'Ted', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sklar', 'Zachary', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'LaGravenese', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kasdan', 'Meg', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Khouri', 'Callie', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Toback', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Barnes', 'Peter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Friedenberg', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Tolkin', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Peoples', 'David', 'Webb');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'George', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Enright', 'Nick', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cocks', 'Jay', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Nicholson', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'George', 'Terry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Arch', 'Jeff', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Maguire', 'Jeff', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Nyswaner', 'Ron', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bennett', 'Alan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Attanasio', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'McGrath', 'Douglas', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Piesiewicz', 'Krzysztof', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Walsh', 'Fran', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Curtis', 'Richard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pavignano', 'Anna', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Scarpelli', 'Giacomo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Broyles Jr.', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Reinert', 'Al', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wallace', 'Randall', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rivele', 'Stephen', 'J.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Wilkinson', 'Christopher', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Whedon', 'Joss', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stanton', 'Andrew', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cohen', 'Joel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sokolow', 'Alec', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hodge', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sardi', 'Jan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Henkin', 'Hilary', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Amini', 'Hossein', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Beaufoy', 'Simon', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Andrus', 'Mark', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Frank', 'Scott', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Condon', 'Bill', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Smith', 'Scott', 'B.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pikser', 'Jeremy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Niccol', 'Andrew', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rodat', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Norman', 'Marc', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cerami', 'Vincenzo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Taylor', 'Jim', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Irving', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ball', 'Alan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ling', 'Wang', 'Hui');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schamus', 'James', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jung', 'Tsai', 'Kuo');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kloves', 'Steve', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jacobs', 'Robert', 'Nelson');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Gaghan', 'Stephen', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lonergan', 'Kenneth', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hall', 'Lee', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Franzoni', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Logan', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Grant', 'Susannah', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Clowes', 'Daniel', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Zwigoff', 'Terry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Festinger', 'Rob', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Field', 'Todd', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Goldsman', 'Akiva', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Elliott', 'Ted', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rossio', 'Terry', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Stillman', 'Joe', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Schulman', 'Roger', 'S.H.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Boyens', 'Philippa', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Laurant', 'Guillaume', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Addica', 'Milo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rokos', 'Will', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Fellowes', 'Julian', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hedges', 'Peter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Weitz', 'Chris', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Weitz', 'Paul', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hare', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Vardalos', 'Nia', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cuaron', 'Carlos', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cuaron', 'Alfonso', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mantovani', 'Braulio', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pulcini', 'Robert', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Berman', 'Shari', 'Springer');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Knight', 'Steven', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Peterson', 'Bob', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Reynolds', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sheridan', 'Naomi', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sheridan', 'Kirsten', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Arcand', 'Denys', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Magee', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Delpy', 'Julie', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Rivera', 'Jose', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bird', 'Brad', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Pearson', 'Keir', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Olson', 'Josh', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kushner', 'Tony', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Futterman', 'Dan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ossana', 'Diana', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Caine', 'Jeffrey', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Heslov', 'Grant', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Moresco', 'Bobby', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Perrotta', 'Tom', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Marber', 'Patrick', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cohen', 'Sacha', 'Baron');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hines', 'Anthony', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Baynham', 'Peter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mazer', 'Dan', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Monahan', 'William', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Sexton', 'Timothy', 'J.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Arata', 'David', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Fergus', 'Mark', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Ostby', 'Hawk', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Arndt', 'Michael', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Morgan', 'Peter', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Arriaga', 'Guillermo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Yamashita', 'Iris', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Polley', 'Sarah', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cody', 'Diablo', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Oliver', 'Nancy', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jenkins', 'Tamara', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hunt', 'Courtney', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'McDonagh', 'Martin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Black', 'Dustin', 'Lance');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Reardon', 'Jim', null);  -- Screenwriter
