INSERT INTO crew_person VALUES (DEFAULT, 'Planer', 'Franz', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Schoenbaum', 'Charles', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Krasker', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Burks', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Mellor', 'William', 'C.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Gilks', 'Alfred', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Harlan', 'Russell', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'Virgil', 'E.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Hoch', 'Winton', 'C.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Stout', 'Archie', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Young', 'Freddie', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Guffey', 'Burnett', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Brun', 'Joseph', 'C.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Alekan', 'Henri', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Griggs', 'Loyal', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Warren', 'John', 'F.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Kaufman', 'Boris', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lipstein', 'Harold', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Strenge', 'Walter', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Fredricks', 'Ellsworth', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Hildyard', 'Jack', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Fapp', 'Daniel', 'L.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Leavitt', 'Sam', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'MacDonald', 'Joseph', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Surtees', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Russell', 'John', 'L.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Francis', 'Freddie', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Laszlo', 'Ernest', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Metty', 'Russell', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Clothier', 'William', 'H.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Harten', 'Charles', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Shufftan', 'Eugen', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Colman', 'Edward', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Bourgoin', 'Jean', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Wottitz', 'Walter', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Ballard', 'Lucien', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lathrop', 'Philip', 'H.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Biroc', 'Joseph', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Figueroa', 'Gabriel', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lassally', 'Walter', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Unsworth', 'Geoffrey', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Higgins', 'Ken', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Grignon', 'Marcel', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Moore', 'Ted', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Kline', 'Richard', 'H.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'De Santis', 'Pasqualino', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Morris', 'Oswald', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Ibbetson', 'Arthur', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Wheeler', 'Charles', 'F.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Furuya', 'Osami', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Himeda', 'Sinsaku', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Satoh', 'Masamichi', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Koenekamp', 'Fred', 'J.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Williams', 'Billy', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Roizman', 'Owen', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Stine', 'Harold', 'E.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Slocombe', 'Douglas', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Stradling Jr.', 'Harry', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Couffer', 'Jack', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Alonzo', 'John', 'A.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Fraker', 'William', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Zsigmond', 'Vilmos', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Phillips', 'Frank', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Rotunno', 'Giuseppe', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Cloquet', 'Ghislain', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Bode', 'Ralf', 'D.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Crabe', 'James', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Chapman', 'Michael', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Ondricek', 'Miroslav', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Thomson', 'Alex', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Vacano', 'Jost', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Daviau', 'Allen', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Taylor', 'Ronnie', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Peterman', 'Don', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Deschanel', 'Caleb', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Menges', 'Chris', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Day', 'Ernest', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Watkin', 'David', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Seale', 'John', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Saito', 'Takao', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Ueda', 'Masaharu', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Nakai', 'Asakazu', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Pierce-Roberts', 'Tony', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Cronenweth', 'Jordan', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Richardson', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Rousselot', 'Philippe', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Ballhaus', 'Michael', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Biziou', 'Peter', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Cundey', 'Dean', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Salomon', 'Mikael', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Semler', 'Dean', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Greenberg', 'Adam', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Goldblatt', 'Stephen', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Biddle', 'Adrian', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Fraisse', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Green', 'Jack', 'N.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Burum', 'Stephen', 'H.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Changwei', 'Gu', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Dryburgh', 'Stuart', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Burgess', 'Don', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Sobocinski', 'Piotr', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lubezki', 'Emmanuel', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Coulter', 'Michael', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Yue', 'Lu', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Khondji', 'Darius', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Spinotti', 'Dante', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Serra', 'Eduardo', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Carpenter', 'Russell', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Greatrex', 'Richard', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Adefarasin', 'Remi', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Pratt', 'Roger', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Koltai', 'Lajos', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Pau', 'Peter', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Mathieson', 'John', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lesnie', 'Andrew', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'McAlpine', 'Donald', 'M.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Delbonnel', 'Bruno', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Idziak', 'Slawomir', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Beebe', 'Dion', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lachman', 'Edward', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Edelman', 'Pawel', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Schwartzman', 'John', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Charlone', 'Cesar', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Boyd', 'Russell', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Xiaoding', 'Zhao', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Prieto', 'Rodrigo', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Pfister', 'Wally', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Pope', 'Dick', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Navarro', 'Guillermo', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'McGarvey', 'Seamus', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Stern', 'Tom', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Miranda', 'Claudio', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Mantle', 'Anthony', 'Dod');  -- Cinematographer
