INSERT INTO crew_person VALUES (DEFAULT, 'Glazer', 'Benjamin', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Coldeway', 'Anthony', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Cohn', 'Alfred', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Biro', 'Lajos', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Hecht', 'Ben', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Meredyth', 'Bess', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Barry', 'Tom', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Clawson', 'Elliott', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Kraly', 'Hans', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lovett', 'Josephine', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Estabrook', 'Howard', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Josephson', 'Julian', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Meehan', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Marion', 'Frances', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Abbott', 'George', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Anderson', 'Maxwell', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Andrews', 'Del', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Jackson', 'Horace', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Faragoh', 'Francis', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Lee', 'Robert', 'N.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'Seton', 'I.');  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Niblo Jr.', 'Fred', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Mintz', 'Sam', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Bright', 'John', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Glasmon', 'Kubec', null);  -- Screenwriter
INSERT INTO crew_person VALUES (DEFAULT, 'Brown', 'Rowland', null);  -- Screenwriter
