INSERT INTO crew_person VALUES (DEFAULT, 'George', 'Chief', 'Dan');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Topol', null, null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Frey', 'Leonard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Johnson', 'Ben', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Jaeckel', 'Richard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Winfield', 'Paul', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Caan', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Grey', 'Joel', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Houseman', 'John', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gilford', 'Jack', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gardenia', 'Vincent', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'Jason', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Quaid', 'Randy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Carney', 'Art', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Astaire', 'Fred', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Strasberg', 'Lee', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gazzo', 'Michael', 'V.');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sarandon', 'Chris', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Meredith', 'Burgess', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dourif', 'Brad', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Burns', 'George', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Warden', 'Jack', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Giannini', 'Giancarlo', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Young', 'Burt', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Robards', 'Jason', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Beatty', 'Ned', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Firth', 'Peter', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Baryshnikov', 'Mikhail', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Busey', 'Gary', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dern', 'Bruce', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Walken', 'Christopher', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Forrest', 'Frederic', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Henry', 'Justin', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'O''Keefe', 'Michael', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hutton', 'Timothy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hirsch', 'Judd', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Moore', 'Dudley', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Holm', 'Ian', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Coco', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Rollins Jr.', 'Howard', 'E.');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Preston', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lithgow', 'John', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Durning', 'Charles', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gossett Jr.', 'Louis', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Conti', 'Tom', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Torn', 'Rip', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Shepard', 'Sam', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Morita', 'Pat', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Caesar', 'Adolph', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ngor', 'Haing', 'S.');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Garner', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Loggia', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Roberts', 'Eric', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ameche', 'Don', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Brandauer', 'Klaus', 'Maria');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hickey', 'William', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Woods', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Elliott', 'Denholm', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dafoe', 'Willem', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Berenger', 'Tom', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Connery', 'Sean', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Brooks', 'Albert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Olmos', 'Edward', 'James');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sydow', 'Max', 'Von');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Landau', 'Martin', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stockwell', 'Dean', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Branagh', 'Kenneth', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Aiello', 'Danny', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Aykroyd', 'Dan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Depardieu', 'Gerard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Greene', 'Graham', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Davison', 'Bruce', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Garcia', 'Andy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lerner', 'Michael', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Davidson', 'Jaye', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Paymer', 'David', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Postlethwaite', 'Pete', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hawthorne', 'Nigel', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sinise', 'Gary', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Palminteri', 'Chazz', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Roth', 'Tim', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cromwell', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Mueller-Stahl', 'Armin', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gooding Jr.', 'Cuba', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Macy', 'William', 'H.');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Reynolds', 'Burt', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Forster', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kinnear', 'Greg', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Coburn', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Osment', 'Haley', 'Joel');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Duncan', 'Michael', 'Clarke');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Broadbent', 'Jim', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hawke', 'Ethan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cooper', 'Chris', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Baldwin', 'Alec', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hounsou', 'Djimon', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Watanabe', 'Ken', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Owen', 'Clive', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Church', 'Thomas', 'Haden');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Alda', 'Alan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Howard', 'Terrence', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gyllenhaal', 'Jake', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Haley', 'Jackie', 'Earle');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Murphy', 'Eddie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Mortensen', 'Viggo', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Affleck', 'Casey', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Holbrook', 'Hal', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Shannon', 'Michael', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dresser', 'Louise', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gaynor', 'Janet', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Swanson', 'Gloria', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Chatterton', 'Ruth', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Pickford', 'Mary', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Eagels', 'Jeanne', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Compson', 'Betty', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Love', 'Bessie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Griffith', 'Corinne', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Carroll', 'Nancy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Shearer', 'Norma', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Garbo', 'Greta', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dressler', 'Marie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dunne', 'Irene', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Harding', 'Ann', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dietrich', 'Marlene', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Fontanne', 'Lynn', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hayes', 'Helen', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wynyard', 'Diana', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Robson', 'May', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Moore', 'Grace', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Colbert', 'Claudette', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bergner', 'Elisabeth', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hopkins', 'Miriam', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Oberon', 'Merle', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lombard', 'Carole', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Rainer', 'Luise', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'George', 'Gladys', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ouspenskaya', 'Maria', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Brady', 'Alice', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Granville', 'Bonita', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bondi', 'Beulah', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sondergaard', 'Gale', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stanwyck', 'Barbara', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Whitty', 'May', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Trevor', 'Claire', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Shirley', 'Anne', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Leeds', 'Andrea', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hiller', 'Wendy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sullavan', 'Margaret', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bainter', 'Fay', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Byington', 'Spring', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Burke', 'Billie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Korjus', 'Miliza', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Garson', 'Greer', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Leigh', 'Vivien', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Fitzgerald', 'Geraldine', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'de Havilland', 'Olivia', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Oliver', 'Edna', 'May');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'McDaniel', 'Hattie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Fontaine', 'Joan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Rogers', 'Ginger', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Scott', 'Martha', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Rambeau', 'Marjorie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hussey', 'Ruth', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'O''Neil', 'Barbara', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Darwell', 'Jane', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Anderson', 'Judith', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Astor', 'Mary', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Collinge', 'Patricia', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wright', 'Teresa', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Allgood', 'Sara', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wycherly', 'Margaret', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Russell', 'Rosalind', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Peters', 'Susan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Moorehead', 'Agnes', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cooper', 'Gladys', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Jones', 'Jennifer', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Arthur', 'Jean', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bergman', 'Ingrid', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Watson', 'Lucile', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Revere', 'Anne', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Goddard', 'Paulette', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Paxinou', 'Katina', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lansbury', 'Angela', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'MacMahon', 'Aline', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Barrymore', 'Ethel', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Tierney', 'Gene', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Crawford', 'Joan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Blyth', 'Ann', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lorring', 'Joan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Arden', 'Eve', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wyman', 'Jane', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Johnson', 'Celia', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Baxter', 'Anne', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gish', 'Lillian', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Robson', 'Flora', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hayward', 'Susan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'McGuire', 'Dorothy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Young', 'Loretta', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Main', 'Marjorie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Holm', 'Celeste', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Grahame', 'Gloria', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Simmons', 'Jean', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Corby', 'Ellen', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Geddes', 'Barbara', 'Bel');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Crain', 'Jeanne', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kerr', 'Deborah', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lanchester', 'Elsa', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'McCambridge', 'Mercedes', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Waters', 'Ethel', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Holliday', 'Judy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Parker', 'Eleanor', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Olson', 'Nancy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hull', 'Josephine', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Emerson', 'Hope', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ritter', 'Thelma', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Winters', 'Shelley', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hunter', 'Kim', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Blondell', 'Joan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Grant', 'Lee', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dunnock', 'Mildred', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Harris', 'Julie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Booth', 'Shirley', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Marchand', 'Colette', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hagen', 'Jean', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Moore', 'Terry', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gardner', 'Ava', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'McNamara', 'Maggie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Caron', 'Leslie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Reed', 'Donna', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Page', 'Geraldine', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kelly', 'Grace', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dandridge', 'Dorothy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Garland', 'Judy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Foch', 'Nina', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Jurado', 'Katy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Saint', 'Eva', 'Marie');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sterling', 'Jan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Magnani', 'Anna', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Pavan', 'Marisa', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Blair', 'Betsy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Fleet', 'Jo', 'Van');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lee', 'Peggy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wood', 'Natalie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Baker', 'Carroll', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kelly', 'Nancy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Heckart', 'Eileen', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'McCormack', 'Patty', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Malone', 'Dorothy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Woodward', 'Joanne', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Taylor', 'Elizabeth', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Turner', 'Lana', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lange', 'Hope', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Umeki', 'Miyoshi', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Jones', 'Carolyn', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Varsi', 'Diane', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'MacLaine', 'Shirley', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stapleton', 'Maureen', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hyer', 'Martha', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Williams', 'Cara', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cass', 'Peggy', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Signoret', 'Simone', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Day', 'Doris', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Baddeley', 'Hermione', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Moore', 'Juanita', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kohner', 'Susan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Mercouri', 'Melina', null);  -- Actor
