INSERT INTO crew_person VALUES (DEFAULT, 'Milestone', 'Lewis', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Wilde', 'Ted', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Brenon', 'Herbert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Borzage', 'Frank', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Vidor', 'King', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Lloyd', 'Frank', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Cummings', 'Irving', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Beaumont', 'Harry', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Lubitsch', 'Ernst', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Leonard', 'Robert', 'Z.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Brown', 'Clarence', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Sternberg', 'Josef', 'Von');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Ruggles', 'Wesley', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Taurog', 'Norman', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Cukor', 'George', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Van Dyke', 'W.', 'S.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Schertzinger', 'Victor', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Curtiz', 'Michael', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Ford', 'John', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hathaway', 'Henry', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'La Cava', 'Gregory', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Wyler', 'William', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Dieterle', 'William', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'McCarey', 'Leo', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Franklin', 'Sidney', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Wellman', 'William', 'A.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Fleming', 'Victor', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Wood', 'Sam', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hawks', 'Howard', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hall', 'Alexander', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Farrow', 'John', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'LeRoy', 'Mervyn', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'King', 'Henry', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Stevens', 'George', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Preminger', 'Otto', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Siodmak', 'Robert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Dmytryk', 'Edward', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Koster', 'Henry', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Zinnemann', 'Fred', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Litvak', 'Anatole', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Negulesco', 'Jean', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Rossen', 'Robert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Reed', 'Carol', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Mankiewicz', 'Joseph', 'L.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Minnelli', 'Vincente', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'DeMille', 'Cecil', 'B.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Walters', 'Charles', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Seaton', 'George', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Logan', 'Joshua', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Mann', 'Delbert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Sturges', 'John', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Lang', 'Walter', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Anderson', 'Michael', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Robson', 'Mark', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Kramer', 'Stanley', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Brooks', 'Richard', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Wise', 'Robert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Clayton', 'Jack', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Cardiff', 'Jack', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Dassin', 'Jules', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Robbins', 'Jerome', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Thompson', 'J.', 'Lee');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Germi', 'Pietro', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Mulligan', 'Robert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Perry', 'Frank', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Richardson', 'Tony', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Ritt', 'Martin', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Cacoyannis', 'Michael', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Glenville', 'Peter', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Stevenson', 'Robert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Teshigahara', 'Hiroshi', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Lelouch', 'Claude', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Pontecorvo', 'Gillo', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Zeffirelli', 'Franco', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Harvey', 'Anthony', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hill', 'George', 'Roy');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Costa-Gavras', null, null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Pollack', 'Sydney', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Schaffner', 'Franklin', 'J.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Russell', 'Ken', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hiller', 'Arthur', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Troell', 'Jan', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Fosse', 'Bob', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Wertmuller', 'Lina', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Avildsen', 'John', 'G.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Ross', 'Herbert', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Cimino', 'Michael', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Henry', 'Buck', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Ashby', 'Hal', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Yates', 'Peter', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Molinaro', 'Edouard', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Rush', 'Richard', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hudson', 'Hugh', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Rydell', 'Mark', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Attenborough', 'Richard', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Beresford', 'Bruce', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Brooks', 'James', 'L.');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Joffe', 'Roland', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Babenco', 'Hector', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Ivory', 'James', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Lyne', 'Adrian', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hallstrom', 'Lasse', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Crichton', 'Charles', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Schroeder', 'Barbet', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Singleton', 'John', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Brest', 'Martin', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Noonan', 'Chris', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Radford', 'Michael', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Minghella', 'Anthony', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hicks', 'Scott', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Cattaneo', 'Peter', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Egoyan', 'Atom', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hanson', 'Curtis', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Madden', 'John', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Lee', 'Ang', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Daldry', 'Stephen', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Almodovar', 'Pedro', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Marshall', 'Rob', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Meirelles', 'Fernando', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Hackford', 'Taylor', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'Bennett', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Inarritu', 'Alejandro', 'Gonzalez');  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Greengrass', 'Paul', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Schnabel', 'Julian', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Reitman', 'Jason', null);  -- Director
INSERT INTO crew_person VALUES (DEFAULT, 'Gilroy', 'Tony', null);  -- Director
