INSERT INTO crew_person VALUES (DEFAULT, 'Jannings', 'Emil', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Barthelmess', 'Richard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Morris', 'Chester', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bancroft', 'George', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Muni', 'Paul', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Baxter', 'Warner', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stone', 'Lewis', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Colman', 'Ronald', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Chevalier', 'Maurice', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Tibbett', 'Lawrence', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Arliss', 'George', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Beery', 'Wallace', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'March', 'Fredric', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dix', 'Richard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Barrymore', 'Lionel', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Menjou', 'Adolphe', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cooper', 'Jackie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lunt', 'Alfred', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Howard', 'Leslie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Morgan', 'Frank', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Powell', 'William', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'McLaglen', 'Victor', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Tone', 'Franchot', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Huston', 'Walter', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Rathbone', 'Basil', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Erwin', 'Stuart', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Auer', 'Mischa', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Brennan', 'Walter', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Tamiroff', 'Akim', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Boyer', 'Charles', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Montgomery', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Schildkraut', 'Joseph', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bellamy', 'Ralph', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Mitchell', 'Thomas', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Warner', 'H.', 'B.');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Young', 'Roland', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Donat', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lockhart', 'Gene', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Garfield', 'John', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Morley', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Rooney', 'Mickey', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Rains', 'Claude', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Donlevy', 'Brian', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Aherne', 'Brian', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Carey', 'Harry', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Massey', 'Raymond', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Oakie', 'Jack', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stephenson', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gargan', 'William', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bassermann', 'Albert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Greenstreet', 'Sydney', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Crisp', 'Donald', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Coburn', 'Charles', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gleason', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Woolley', 'Monty', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Pidgeon', 'Walter', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Travers', 'Henry', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bendix', 'William', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Heflin', 'Van', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Lukas', 'Paul', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Naish', 'J.', 'Carrol');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bickford', 'Charles', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Crosby', 'Bing', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Fitzgerald', 'Barry', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Knox', 'Alexander', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Webb', 'Clifton', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cronyn', 'Hume', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kelly', 'Gene', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Milland', 'Ray', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wilde', 'Cornel', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dall', 'John', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dunn', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Chekhov', 'Michael', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Parks', 'Larry', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Russell', 'Harold', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Demarest', 'William', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Redgrave', 'Michael', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gomez', 'Thomas', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Widmark', 'Richard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ryan', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gwenn', 'Edmund', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ayres', 'Lew', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dailey', 'Dan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Homolka', 'Oscar', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ferrer', 'Jose', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kellaway', 'Cecil', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Todd', 'Richard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Crawford', 'Broderick', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kennedy', 'Arthur', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ireland', 'John', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Richardson', 'Ralph', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Whitmore', 'James', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Jagger', 'Dean', null);  -- Actor
