INSERT INTO crew_person VALUES (DEFAULT, 'Calhern', 'Louis', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Chandler', 'Jeff', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Jaffe', 'Sam', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stroheim', 'Erich', 'von');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sanders', 'George', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ustinov', 'Peter', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Malden', 'Karl', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Genn', 'Leo', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Young', 'Gig', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'McCarthy', 'Kevin', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hunnicutt', 'Arthur', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Quinn', 'Anthony', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Strauss', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Albert', 'Eddie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'De Wilde', 'Brandon', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'O''Herlihy', 'Dan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Tully', 'Tom', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cobb', 'Lee', 'J.');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'O''Brien', 'Edmond', null);  -- Actor
