INSERT INTO crew_person VALUES (DEFAULT, 'Mineo', 'Sal', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Mantell', 'Joe', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'O''Connell', 'Arthur', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Brynner', 'Yul', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Murray', 'Don', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stack', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Perkins', 'Anthony', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Franciosa', 'Anthony', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Hayakawa', 'Sessue', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Tamblyn', 'Russ', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Niven', 'David', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Curtis', 'Tony', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bikel', 'Theodore', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Ives', 'Burl', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Harvey', 'Laurence', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Griffith', 'Hugh', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wynn', 'Ed', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Vaughn', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Howard', 'Trevor', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Falk', 'Peter', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kruschen', 'Jack', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wills', 'Chill', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Whitman', 'Stuart', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Schell', 'Maximilian', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gleason', 'Jackie', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Chakiris', 'George', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Sharif', 'Omar', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Begley', 'Ed', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Stamp', 'Terence', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Savalas', 'Telly', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Buono', 'Victor', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Harris', 'Richard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Darin', 'Bobby', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Douglas', 'Melvyn', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Adams', 'Nick', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Holloway', 'Stanley', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Tracy', 'Lee', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gielgud', 'John', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Werner', 'Oskar', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Marvin', 'Lee', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Dunn', 'Michael', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Finlay', 'Frank', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bannen', 'Ian', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Balsam', 'Martin', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Scofield', 'Paul', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Mako', null, null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Matthau', 'Walter', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Segal', 'George', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Shaw', 'Robert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Pollard', 'Michael', 'J.');  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Kennedy', 'George', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Robertson', 'Cliff', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Moody', 'Ron', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Bates', 'Alan', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Cassel', 'Seymour', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wild', 'Jack', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Albertson', 'Jack', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Wilder', 'Gene', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Massey', 'Daniel', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Gould', 'Elliott', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Quayle', 'Anthony', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Crosse', 'Rupert', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Castellano', 'Richard', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Mills', 'John', null);  -- Actor
INSERT INTO crew_person VALUES (DEFAULT, 'Marley', 'John', null);  -- Actor
