INSERT INTO crew_person VALUES (DEFAULT, 'McGill', 'Barney', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Garmes', 'Lee', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Cronjager', 'Edward', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'June', 'Ray', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lang', 'Charles', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Folsey', 'George', 'J.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Mohr', 'Hal', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Valentine', 'Joseph', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Freund', 'Karl', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Walker', 'Joseph', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Marley', 'Peverell', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Ruttenberg', 'Joseph', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Brodine', 'Norbert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Shamroy', 'Leon', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Haller', 'Ernest', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'Ernest', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Wild', 'Harry', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Howe', 'James', 'Wong');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'de Grasse', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Miller', 'Arthur', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'August', 'Joseph', 'H.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Glennon', 'Bert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Polito', 'Sol', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Greene', 'W.', 'Howard');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Rennahan', 'Ray', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Perinal', 'Georges', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Borradaile', 'Osmond', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Rosson', 'Harold', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Skall', 'William', 'V.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Mate', 'Rudolph', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Wagner', 'Sidney', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Marsh', 'Oliver', 'T.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Davey', 'Allen', 'M.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Tover', 'Leo', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Cline', 'Wilfred', 'M.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Snyder', 'William', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Smith', 'Leonard', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Hallenberger', 'Harry', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Tetzlaff', 'Ted', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Cortez', 'Stanley', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Clarke', 'Charles', 'G.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Mescall', 'John', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Krasner', 'Milton', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Stradling Sr.', 'Harry', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Dyer', 'Elmer', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Marshall', 'Charles', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'LaShelle', 'Joseph', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Surtees', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Lindon', 'Lionel', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'MacWilliams', 'Glen', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Planck', 'Robert', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Boyle', 'Charles', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Arling', 'Arthur', 'E.');  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Green', 'Guy', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Jackson', 'Harry', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Musuraca', 'Nicholas', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'McCord', 'Ted', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Hoch', 'Winton', null);  -- Cinematographer
INSERT INTO crew_person VALUES (DEFAULT, 'Vogel', 'Paul', 'C.');  -- Cinematographer
