INSERT INTO filth.list VALUES (1, 'Greatest Movies #1', 'Roger Ebert');
INSERT INTO filth.list VALUES (2, 'Greatest Movies #2', 'Roger Ebert');
INSERT INTO filth.list VALUES (3, 'Greatest Movies #3', 'Roger Ebert');
INSERT INTO filth.list VALUES (4, 'Greatest Movies #4', 'Roger Ebert');
INSERT INTO filth.list VALUES (5, 'Top Ten Movies of 1997', 'Tyler Hayes');
INSERT INTO filth.list VALUES (6, 'Top Ten Movies of 1998', 'Tyler Hayes');
INSERT INTO filth.list VALUES (7, 'Top Ten Movies of 1999', 'Tyler Hayes');
INSERT INTO filth.list VALUES (8, 'Top Ten Movies of 2000', 'Tyler Hayes');
INSERT INTO filth.list VALUES (9, 'Top Ten Movies of 2001', 'Tyler Hayes');
INSERT INTO filth.list VALUES (10, 'Top Ten Movies of 2002', 'Tyler Hayes');
INSERT INTO filth.list VALUES (11, 'Top Ten Movies of 2003', 'Tyler Hayes');
INSERT INTO filth.list VALUES (12, 'Top Ten Movies of 2004', 'Tyler Hayes');
INSERT INTO filth.list VALUES (13, 'Top Ten Movies of 2005', 'Tyler Hayes');
INSERT INTO filth.list VALUES (14, 'Top Ten Movies of 2006', 'Tyler Hayes');
INSERT INTO filth.list VALUES (15, 'Top Ten Movies of 2007', 'Tyler Hayes');
INSERT INTO filth.list VALUES (16, 'Top Ten Movies of 2008', 'Tyler Hayes');
INSERT INTO filth.list VALUES (17, 'Top Ten Movies of 2009', 'Tyler Hayes');
INSERT INTO filth.list VALUES (18, 'Top Ten Movies of 2010', 'Tyler Hayes');
INSERT INTO filth.list VALUES (19, 'Top Ten Movies of 2011', 'Tyler Hayes');
INSERT INTO filth.list VALUES (20, 'Top Ten Movies of 2012', 'Tyler Hayes');
INSERT INTO filth.list VALUES (21, 'Top Ten Movies of 2013', 'Tyler Hayes');
INSERT INTO filth.list VALUES (22, 'Top Ten Movies of 2014', 'Tyler Hayes');
INSERT INTO filth.list VALUES (23, 'Top Ten Movies of 2015', 'Tyler Hayes');
INSERT INTO filth.list VALUES (24, 'Top Ten Movies of 1967', 'Roger Ebert');
INSERT INTO filth.list VALUES (25, 'Top Ten Movies of 1968', 'Roger Ebert');
INSERT INTO filth.list VALUES (26, 'Top Ten Movies of 1969', 'Roger Ebert');
INSERT INTO filth.list VALUES (27, 'Top Ten Movies of 1970', 'Roger Ebert');
INSERT INTO filth.list VALUES (28, 'Top Ten Movies of 1971', 'Roger Ebert');
INSERT INTO filth.list VALUES (29, 'Top Ten Movies of 1972', 'Roger Ebert');
INSERT INTO filth.list VALUES (30, 'Top Ten Movies of 1973', 'Roger Ebert');
INSERT INTO filth.list VALUES (31, 'Top Ten Movies of 1974', 'Roger Ebert');
INSERT INTO filth.list VALUES (32, 'Top Ten Movies of 1975', 'Roger Ebert');
INSERT INTO filth.list VALUES (33, 'Top Ten Movies of 1976', 'Roger Ebert');
INSERT INTO filth.list VALUES (34, 'Top Ten Movies of 1977', 'Roger Ebert');
INSERT INTO filth.list VALUES (35, 'Top Ten Movies of 1978', 'Roger Ebert');
INSERT INTO filth.list VALUES (36, 'Top Ten Movies of 1979', 'Roger Ebert');
INSERT INTO filth.list VALUES (37, 'Top Ten Movies of 1980', 'Roger Ebert');
INSERT INTO filth.list VALUES (38, 'Top Ten Movies of 1981', 'Roger Ebert');
INSERT INTO filth.list VALUES (39, 'Top Ten Movies of 1982', 'Roger Ebert');
INSERT INTO filth.list VALUES (40, 'Top Ten Movies of 1983', 'Roger Ebert');
INSERT INTO filth.list VALUES (41, 'Top Ten Movies of 1984', 'Roger Ebert');
INSERT INTO filth.list VALUES (42, 'Top Ten Movies of 1985', 'Roger Ebert');
