INSERT INTO filth.list VALUES (1, 'Greatest Movies #1', 'Roger Ebert');
INSERT INTO filth.list VALUES (2, 'Greatest Movies #2', 'Roger Ebert');
INSERT INTO filth.list VALUES (3, 'Greatest Movies #3', 'Roger Ebert');
INSERT INTO filth.list VALUES (4, 'Greatest Movies #4', 'Roger Ebert');
INSERT INTO filth.list VALUES (5, 'Top Ten Movies of 1997', 'Tyler Hayes');
INSERT INTO filth.list VALUES (6, 'Top Ten Movies of 1998', 'Tyler Hayes');
INSERT INTO filth.list VALUES (7, 'Top Ten Movies of 1999', 'Tyler Hayes');
INSERT INTO filth.list VALUES (8, 'Top Ten Movies of 2000', 'Tyler Hayes');
INSERT INTO filth.list VALUES (9, 'Top Ten Movies of 2001', 'Tyler Hayes');
INSERT INTO filth.list VALUES (10, 'Top Ten Movies of 2002', 'Tyler Hayes');
INSERT INTO filth.list VALUES (11, 'Top Ten Movies of 2003', 'Tyler Hayes');
INSERT INTO filth.list VALUES (12, 'Top Ten Movies of 2004', 'Tyler Hayes');
INSERT INTO filth.list VALUES (13, 'Top Ten Movies of 2005', 'Tyler Hayes');
INSERT INTO filth.list VALUES (14, 'Top Ten Movies of 2006', 'Tyler Hayes');
INSERT INTO filth.list VALUES (15, 'Top Ten Movies of 2007', 'Tyler Hayes');
INSERT INTO filth.list VALUES (16, 'Top Ten Movies of 2008', 'Tyler Hayes');
INSERT INTO filth.list VALUES (17, 'Top Ten Movies of 2009', 'Tyler Hayes');
INSERT INTO filth.list VALUES (18, 'Top Ten Movies of 2010', 'Tyler Hayes');
INSERT INTO filth.list VALUES (19, 'Top Ten Movies of 2011', 'Tyler Hayes');
INSERT INTO filth.list VALUES (20, 'Top Ten Movies of 2012', 'Tyler Hayes');
INSERT INTO filth.list VALUES (21, 'Top Ten Movies of 2013', 'Tyler Hayes');
INSERT INTO filth.list VALUES (22, 'Top Ten Movies of 2014', 'Tyler Hayes');
INSERT INTO filth.list VALUES (23, 'Top Ten Movies of 2015', 'Tyler Hayes');
INSERT INTO filth.list VALUES (24, 'Top Ten Movies of 1967', 'Roger Ebert');
INSERT INTO filth.list VALUES (25, 'Top Ten Movies of 1968', 'Roger Ebert');
INSERT INTO filth.list VALUES (26, 'Top Ten Movies of 1969', 'Roger Ebert');
INSERT INTO filth.list VALUES (27, 'Top Ten Movies of 1970', 'Roger Ebert');
INSERT INTO filth.list VALUES (28, 'Top Ten Movies of 1971', 'Roger Ebert');
INSERT INTO filth.list VALUES (29, 'Top Ten Movies of 1972', 'Roger Ebert');
INSERT INTO filth.list VALUES (30, 'Top Ten Movies of 1973', 'Roger Ebert');
INSERT INTO filth.list VALUES (31, 'Top Ten Movies of 1974', 'Roger Ebert');
INSERT INTO filth.list VALUES (32, 'Top Ten Movies of 1975', 'Roger Ebert');
INSERT INTO filth.list VALUES (33, 'Top Ten Movies of 1976', 'Roger Ebert');
INSERT INTO filth.list VALUES (34, 'Top Ten Movies of 1977', 'Roger Ebert');
INSERT INTO filth.list VALUES (35, 'Top Ten Movies of 1978', 'Roger Ebert');
INSERT INTO filth.list VALUES (36, 'Top Ten Movies of 1979', 'Roger Ebert');
INSERT INTO filth.list VALUES (37, 'Top Ten Movies of 1980', 'Roger Ebert');
INSERT INTO filth.list VALUES (38, 'Top Ten Movies of 1981', 'Roger Ebert');
INSERT INTO filth.list VALUES (39, 'Top Ten Movies of 1982', 'Roger Ebert');
INSERT INTO filth.list VALUES (40, 'Top Ten Movies of 1983', 'Roger Ebert');
INSERT INTO filth.list VALUES (41, 'Top Ten Movies of 1984', 'Roger Ebert');
INSERT INTO filth.list VALUES (42, 'Top Ten Movies of 1985', 'Roger Ebert');
INSERT INTO filth.list VALUES (43, 'Top Ten Movies of 1986', 'Roger Ebert');
INSERT INTO filth.list VALUES (44, 'Top Ten Movies of 1987', 'Roger Ebert');
INSERT INTO filth.list VALUES (45, 'Top Ten Movies of 1988', 'Roger Ebert');
INSERT INTO filth.list VALUES (46, 'Top Ten Movies of 1989', 'Roger Ebert');
INSERT INTO filth.list VALUES (47, 'Top Ten Movies of the 1980s', 'Roger Ebert');
INSERT INTO filth.list VALUES (48, 'Top Ten Movies of 1990', 'Roger Ebert');
INSERT INTO filth.list VALUES (49, 'Top Ten Movies of 1991', 'Roger Ebert');
INSERT INTO filth.list VALUES (50, 'Top Ten Movies of 1992', 'Roger Ebert');
INSERT INTO filth.list VALUES (51, 'Top Ten Movies of 1993', 'Roger Ebert');
INSERT INTO filth.list VALUES (52, 'Top Ten Movies of 1994', 'Roger Ebert');
INSERT INTO filth.list VALUES (53, 'Top Ten Movies of 1995', 'Roger Ebert');
INSERT INTO filth.list VALUES (54, 'Top Ten Movies of 1996', 'Roger Ebert');
INSERT INTO filth.list VALUES (55, 'Top Ten Movies of 1997', 'Roger Ebert');
INSERT INTO filth.list VALUES (56, 'Top Ten Movies of 1998', 'Roger Ebert');
INSERT INTO filth.list VALUES (57, 'Top Ten Movies of 1999', 'Roger Ebert');
INSERT INTO filth.list VALUES (58, 'Top Ten Movies of the 1990s', 'Roger Ebert');
INSERT INTO filth.list VALUES (59, 'Top Ten Movies of 2000', 'Roger Ebert');
INSERT INTO filth.list VALUES (60, 'Top Ten Movies of 2001', 'Roger Ebert');
INSERT INTO filth.list VALUES (61, 'Top Ten Movies of 2002', 'Roger Ebert');
INSERT INTO filth.list VALUES (62, 'Top Ten Movies of 2003', 'Roger Ebert');
INSERT INTO filth.list VALUES (63, 'Top Ten Movies of 2004', 'Roger Ebert');
INSERT INTO filth.list VALUES (64, 'Top Ten Movies of 2005', 'Roger Ebert');
INSERT INTO filth.list VALUES (65, 'Best Movies of 2006', 'Roger Ebert');
INSERT INTO filth.list VALUES (66, 'Top Ten Movies of 2007', 'Roger Ebert');
INSERT INTO filth.list VALUES (67, 'Best Movies of 2008', 'Roger Ebert');
INSERT INTO filth.list VALUES (68, 'Best Documentaries of 2008', 'Roger Ebert');
INSERT INTO filth.list VALUES (69, 'Best Mainstream Movies of 2009', 'Roger Ebert');
INSERT INTO filth.list VALUES (70, 'Best Independent Films of 2009', 'Roger Ebert');
INSERT INTO filth.list VALUES (71, 'Best Foreign Films of 2009', 'Roger Ebert');
INSERT INTO filth.list VALUES (72, 'Best Documentaries of 2009', 'Roger Ebert');
INSERT INTO filth.list VALUES (73, 'Best Animated Movies of 2009', 'Roger Ebert');
INSERT INTO filth.list VALUES (74, 'Top Ten Movies of the Decade: 2000-2009', 'Roger Ebert');
INSERT INTO filth.list VALUES (75, 'Top Ten Movies of 2010', 'Roger Ebert');
INSERT INTO filth.list VALUES (76, 'Top 20 Movies of 2011', 'Roger Ebert');
INSERT INTO filth.list VALUES (77, 'Top 20 Documentaries of 2011', 'Roger Ebert');
INSERT INTO filth.list VALUES (78, 'Top Ten Movies of 2012', 'Roger Ebert');
INSERT INTO filth.list VALUES (79, 'Top Ten Movies of 1969', 'Gene Siskel');
INSERT INTO filth.list VALUES (80, 'Top Ten Movies of 1970', 'Gene Siskel');
INSERT INTO filth.list VALUES (81, 'Top Ten Movies of 1971', 'Gene Siskel');
INSERT INTO filth.list VALUES (82, 'Top Ten Movies of 1972', 'Gene Siskel');
INSERT INTO filth.list VALUES (83, 'Top Ten Movies of 1973', 'Gene Siskel');
INSERT INTO filth.list VALUES (84, 'Top Ten Movies of 1974', 'Gene Siskel');
INSERT INTO filth.list VALUES (85, 'Top Ten Movies of 1975', 'Gene Siskel');
INSERT INTO filth.list VALUES (86, 'Top Ten Movies of 1976', 'Gene Siskel');
INSERT INTO filth.list VALUES (87, 'Top Ten Movies of 1977', 'Gene Siskel');
INSERT INTO filth.list VALUES (88, 'Top Ten Movies of 1978', 'Gene Siskel');
INSERT INTO filth.list VALUES (89, 'Top Ten Movies of 1979', 'Gene Siskel');
INSERT INTO filth.list VALUES (90, 'Top Ten Movies of 1980', 'Gene Siskel');
INSERT INTO filth.list VALUES (91, 'Top Ten Movies of 1981', 'Gene Siskel');
INSERT INTO filth.list VALUES (92, 'Top Ten Movies of 1982', 'Gene Siskel');
INSERT INTO filth.list VALUES (93, 'Top Ten Movies of 1983', 'Gene Siskel');
INSERT INTO filth.list VALUES (94, 'Top Ten Movies of 1984', 'Gene Siskel');
INSERT INTO filth.list VALUES (95, 'Top Ten Movies of 1985', 'Gene Siskel');
INSERT INTO filth.list VALUES (96, 'Top Ten Movies of 1986', 'Gene Siskel');
INSERT INTO filth.list VALUES (97, 'Top Ten Movies of 1987', 'Gene Siskel');
INSERT INTO filth.list VALUES (98, 'Top Ten Movies of 1988', 'Gene Siskel');
INSERT INTO filth.list VALUES (99, 'Top Ten Movies of 1989', 'Gene Siskel');
INSERT INTO filth.list VALUES (100, 'Top Ten Movies of the 1980s', 'Gene Siskel');
INSERT INTO filth.list VALUES (101, 'Top Ten Movies of 1990', 'Gene Siskel');
INSERT INTO filth.list VALUES (102, 'Top Ten Movies of 1991', 'Gene Siskel');
INSERT INTO filth.list VALUES (103, 'Top Ten Movies of 1992', 'Gene Siskel');
INSERT INTO filth.list VALUES (104, 'Top Ten Movies of 1993', 'Gene Siskel');
INSERT INTO filth.list VALUES (105, 'Top Ten Movies of 1994', 'Gene Siskel');
INSERT INTO filth.list VALUES (106, 'Top Ten Movies of 1995', 'Gene Siskel');
INSERT INTO filth.list VALUES (107, 'Top Ten Movies of 1996', 'Gene Siskel');
INSERT INTO filth.list VALUES (108, 'Top Ten Movies of 1997', 'Gene Siskel');
INSERT INTO filth.list VALUES (109, 'Top Ten Movies of 1998', 'Gene Siskel');
INSERT INTO filth.list VALUES (110, 'Top Ten Movies of 2000', 'Richard Roeper');
INSERT INTO filth.list VALUES (111, 'Top Ten Movies of 2001', 'Richard Roeper');
INSERT INTO filth.list VALUES (112, 'Top Ten Movies of 2002', 'Richard Roeper');
INSERT INTO filth.list VALUES (113, 'Top Ten Movies of 2003', 'Richard Roeper');
INSERT INTO filth.list VALUES (114, 'Top Ten Movies of 2004', 'Richard Roeper');
INSERT INTO filth.list VALUES (115, 'Top Ten Movies of 2005', 'Richard Roeper');
INSERT INTO filth.list VALUES (116, 'Top Ten Movies of 2006', 'Richard Roeper');
INSERT INTO filth.list VALUES (117, 'Top Ten Movies of 2007', 'Richard Roeper');
INSERT INTO filth.list VALUES (118, 'Top 25 Movies of 2008', 'Richard Roeper');
INSERT INTO filth.list VALUES (119, 'Top Ten Movies of 2009', 'Richard Roeper');
INSERT INTO filth.list VALUES (120, 'Top Ten Movies of 2010', 'Richard Roeper');
INSERT INTO filth.list VALUES (121, 'Top Ten Movies of 2011', 'Richard Roeper');
INSERT INTO filth.list VALUES (122, 'Top Ten Movies of 2012', 'Richard Roeper');
INSERT INTO filth.list VALUES (123, 'Best Movies of 2013', 'Richard Roeper');
INSERT INTO filth.list VALUES (124, 'Top Ten Movies of 2014', 'Richard Roeper');
INSERT INTO filth.list VALUES (125, 'Top Ten Movies of 2015', 'Richard Roeper');
INSERT INTO filth.list VALUES (126, 'AFI''s 100 Years...100 Movies', 'American Film Institute');
INSERT INTO filth.list VALUES (127, 'AFI''s 100 Years...100 Movies -- 10th Anniversary Edition', 'American Film Institute');
