INSERT INTO movie VALUES (DEFAULT, 'Reunion in Vienna', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sign of the Cross', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Operator 13', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Barbary Coast', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Crusades', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wings over Honolulu', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Suez', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mad about Music', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Young in Heart', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Buccaneer', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Army Girl', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Vivacious Lady', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Rains Came', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lady of the Tropics', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great Victor Herbert', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'First Love', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gunga Din', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Only Angels Have Wings', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Intermezzo', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Private Lives of Elizabeth and Essex', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Four Feathers', 1939, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Mikado', 1939, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Arise, My Love', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Waterloo Bridge', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Boom Town', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Spring Parade', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Northwest Passage', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Thief of Bagdad', 1940, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bitter Sweet', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Down Argentine Way', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Blue Bird', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'North West Mounted Police', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sundown', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'That Hamilton Woman', 1941, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Chocolate Soldier', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dr. Jekyll and Mr. Hyde', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sun Valley Serenade', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Aloma of the South Seas', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Billy the Kid', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Blood and Sand', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dive Bomber', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Louisiana Purchase', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'This Above All', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Moontide', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Take a Letter, Darling', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ten Gentlemen from West Point', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Captains of the Clouds', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Black Swan', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Arabian Nights', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'To the Shores of Tripoli', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Reap the Wild Wind', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jungle Book', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The North Star', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Air Force', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Five Graves to Cairo', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Corvette K-225', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hello, Frisco, Hello', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Thousands Cheer', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lassie Come Home', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Phantom of the Opera', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Uninvited', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The White Cliffs of Dover', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Thirty Seconds over Tokyo', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lady in the Dark', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kismet', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Meet Me in St. Louis', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Home in Indiana', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cover Girl', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Spanish Main', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ghost and Mrs. Muir', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Green Dolphin Street', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Black Narcissus', 1947, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mother Wore Tights', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Portrait of Jennie', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Naked City', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Foreign Affair', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Green Grass of Wyoming', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Three Musketeers', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Loves of Carmen', 1948, -2, 0, 'USA', NULL);
