INSERT INTO movie VALUES (DEFAULT, 'This above All', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Prince of Foxes', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jolson Sings Again', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Barkleys of Broadway', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'She Wore a Yellow Ribbon', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Little Women', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Furies', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Flame and the Arrow', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Annie Get Your Gun', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Samson and Delilah', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Frogmen', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'David and Bathsheba', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Show Boat', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'When Worlds Collide', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Navajo', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hans Christian Andersen', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Snows of Kilimanjaro', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Million Dollar Mermaid', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Martin Luther', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Four Poster', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'All the Brothers Were Valiant', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Beneath the 12-Mile Reef', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Rogue Cop', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Egyptian', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Silver Chalice', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Queen Bee', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Blackboard Jungle', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Oklahoma!', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Guys and Dolls', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'To Catch a Thief', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Man Called Peter', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Somebody Up There Likes Me', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Harder They Fall', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Stagecoach to Fury', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Eddy Duchin Story', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'An Affair To Remember', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Desire under the Elms', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Young Lions', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'South Pacific', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Career', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Five Pennies', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Porgy and Bess', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Big Fisherman', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Facts of Life', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pepe', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Absent Minded Professor', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One, Two, Three', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One-Eyed Jacks', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Flower Drum Song', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Majority of One', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Two for the Seesaw', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Wonderful World of the Brothers Grimm', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hatari!', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Balcony', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Caretakers', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'It''s a Mad, Mad, Mad, Mad World', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Americanization of Emily', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fate Is the Hunter', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cheyenne Autumn', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'King Rat', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Morituri', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In Harm''s Way', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great Race', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Agony and the Ecstasy', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Is Paris Burning?', 1966, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Seconds', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fantastic Voyage', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Camelot', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ice Station Zebra', 1968, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Marooned', 1969, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tora! Tora! Tora!', 1970, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Summer of ''42''', 1971, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, '1776', 1972, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jonathan Livingston Seagull', 1973, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Earthquake', 1974, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Hindenburg', 1975, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Funny Lady', 1975, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'King Kong', 1976, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Logan''s Run', 1976, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Star Is Born', 1976, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Islands in the Stream', 1977, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Wiz', 1978, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Black Hole', 1979, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Formula', 1980, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Blue Lagoon', 1980, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Excalibur', 1981, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Flashdance', 1983, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Star Trek IV: The Voyage Home', 1986, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tequila Sunrise', 1988, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Blaze', 1989, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Henry & June', 1990, -2, 6, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A River Runs Through It', 1992, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Lover', 1992, -2, 6, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hoffa', 1992, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Legends of the Fall', 1994, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Batman Forever', 1995, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Shanghai Triad', 1995, -2, 4, 'China', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fly Away Home', 1996, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Evita', 1996, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kundun', 1997, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Snow Falling on Cedars', 1999, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Malena', 2000, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Phantom of the Opera', 2004, -2, 3, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Memoirs of a Geisha', 2005, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Children of Men', 2006, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Black Dahlia', 2006, -2, 4, 'USA', NULL);
