INSERT INTO filth.movie_link VALUES(1, 3869, 1550, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode VII – the Force Awakens (2015) -> Star Wars: Episode VI - Return of the Jedi (1983)
INSERT INTO filth.movie_link VALUES(2, 1550, 1549, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode VI - Return of the Jedi (1983) -> Star Wars: Episode V - The Empire Strikes Back (1980)
INSERT INTO filth.movie_link VALUES(3, 1549, 1550, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode V - The Empire Strikes Back (1980) -> Star Wars: Episode VI - Return of the Jedi (1983)
INSERT INTO filth.movie_link VALUES(4, 1549, 1548, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode V - The Empire Strikes Back (1980) -> Star Wars (1977)
INSERT INTO filth.movie_link VALUES(5, 1548, 1549, 'PREDECESSOR_OF', NULL); -- Star Wars (1977) -> Star Wars: Episode V - The Empire Strikes Back (1980)
INSERT INTO filth.movie_link VALUES(6, 1548, 1547, 'SUCCESSOR_TO', NULL); -- Star Wars (1977) -> Star Wars: Episode III - Revenge of the Sith (2005)
INSERT INTO filth.movie_link VALUES(7, 1547, 1548, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode III - Revenge of the Sith (2005) -> Star Wars (1977)
INSERT INTO filth.movie_link VALUES(8, 1547, 1546, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode III - Revenge of the Sith (2005) -> Star Wars: Episode II - Attack of the Clones (2002)
INSERT INTO filth.movie_link VALUES(9, 1546, 1547, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode II - Attack of the Clones (2002) -> Star Wars: Episode III - Revenge of the Sith (2005)
INSERT INTO filth.movie_link VALUES(10, 1546, 1545, 'SUCCESSOR_TO', NULL); -- Star Wars: Episode II - Attack of the Clones (2002) -> Star Wars: Episode I - The Phantom Menace (1999)
INSERT INTO filth.movie_link VALUES(11, 1545, 1546, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode I - The Phantom Menace (1999) -> Star Wars: Episode II - Attack of the Clones (2002)
INSERT INTO filth.movie_link VALUES(12, 1550, 3869, 'PREDECESSOR_OF', NULL); -- Star Wars: Episode VI - Return of the Jedi (1983) -> Star Wars: Episode VII – the Force Awakens (2015)