INSERT INTO movie VALUES (DEFAULT, 'The Devil Dancer', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Magic Flame', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, '4 Devils', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Our Dancing Daughters', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'White Shadows in the South Seas', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hell''s Angels', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'With Byrd at the South Pole', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tabu: A Story of the South Seas', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Right to Love', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Svengali', 1931, -2, 0, 'USA', NULL);
