INSERT INTO movie VALUES (DEFAULT, 'The Field', 1990, -2, 3, 'Ireland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sunrise at Campobello', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Dark at the Top of the Stairs', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Splendor in the Grass', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Two Women', 1961, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Summer and Smoke', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Roman Spring of Mrs. Stone', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Children''s Hour', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Long Day''s Journey into Night', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The L-Shaped Room', 1963, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Love with the Proper Stranger', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Irma La Douce', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The V.I.P.s', 1963, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Seance on a Wet Afternoon', 1964, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Unsinkable Molly Brown', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Pumpkin Eater', 1964, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Marriage Italian Style', 1964, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hush...Hush, Sweet Charlotte', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Chalk Garden', 1964, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Night of the Iguana', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Patch of Blue', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Collector', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Inside Daisy Clover', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Shop on Main Street', 1966, -2, 0, 'Czechoslovakia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Morgan!', 1966, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Man and a Woman', 1966, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hawaii', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'You''re a Big Boy Now', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Whisperers', 1967, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wait until Dark', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Barefoot in the Park', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Thoroughly Modern Millie', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Isadora', 1968, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sterile Cuckoo', 1969, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Happy Ending', 1969, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Prime of Miss Jean Brodie', 1969, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cactus Flower', 1969, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Last Summer', 1969, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Diary of a Mad Housewife', 1970, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Women in Love', 1970, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Landlord', 1970, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mary, Queen of Scots', 1971, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Klute', 1971, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Who Is Harry Kellerman and Why Is He Saying Those Terrible Things about Me?', 1971, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Carnal Knowledge', 1971, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Go-Between', 1971, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lady Sings the Blues', 1972, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Travels with My Aunt', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fat City', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Poseidon Adventure', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pete ''n'' Tillie', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Butterflies Are Free', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Way We Were', 1973, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cinderella Liberty', 1973, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Summer Wishes, Winter Dreams', 1973, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Claudine', 1974, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Blazing Saddles', 1974, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hester Street', 1975, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hedda', 1975, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tommy', 1975, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Story of Adele H.', 1975, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Once Is Not Enough', 1975, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Farewell, My Lovely', 1975, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Face to Face', 1976, -2, 4, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cousin, Cousine', 1976, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Carrie', 1976, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Voyage of the Damned', 1976, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Looking for Mr. Goodbar', 1977, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Same Time, Next Year', 1978, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'California Suite', 1978, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Chapter Two', 1979, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Starting Over', 1979, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gloria', 1980, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Resurrection', 1980, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Private Benjamin', 1980, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Inside Moves', 1980, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The French Lieutenant''s Woman', 1981, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Frances', 1982, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Testament', 1983, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Year of Living Dangerously', 1983, -2, 2, 'Australia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Yentl', 1983, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Country', 1984, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The River', 1984, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bostonians', 1984, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Pope of Greenwich Village', 1984, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Natural', 1984, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Swing Shift', 1984, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Trip to Bountiful', 1985, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sweet Dreams', 1985, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Agnes of God', 1985, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Twice in a Lifetime', 1985, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Crimes of the Heart', 1986, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Morning After', 1986, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anna', 1987, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gaby: A True Story', 1987, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Throw Momma from the Train', 1987, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Whales of August', 1987, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gorillas in the Mist', 1988, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Music Box', 1989, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Shirley Valentine', 1989, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Fabulous Baker Boys', 1989, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Camille Claudel', 1989, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Steel Magnolias', 1989, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Parenthood', 1989, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mr. & Mrs. Bridge', 1990, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pretty Woman', 1990, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wild at Heart', 1990, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Rambling Rose', 1991, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'For the Boys', 1991, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fried Green Tomatoes', 1991, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Love Field', 1992, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Indochine', 1992, -2, 3, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lorenzo''s Oil', 1992, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Passion Fish', 1992, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Enchanted April', 1992, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Six Degrees of Separation', 1993, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Firm', 1993, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fearless', 1993, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Nell', 1994, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Blue Sky', 1994, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Client', 1994, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tom & Viv', 1994, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bridges of Madison County', 1995, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Georgia', 1995, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Mirror Has Two Faces', 1996, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Afterglow', 1997, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Wings of the Dove', 1997, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One True Thing', 1998, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The End of the Affair', 1999, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tumbleweeds', 1999, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Billy Elliot', 2000, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Unfaithful', 2002, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Frida', 2002, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Being Julia', 2004, -2, 4, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kinsey', 2004, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Transamerica', 2005, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mrs. Henderson Presents', 2005, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Junebug', 2005, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Constant Gardener', 2005, -2, 4, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Notes on a Scandal', 2006, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Volver', 2006, -2, 4, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Savages', 2007, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I''m Not There', 2007, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'American Gangster', 2007, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Vicky Cristina Barcelona', 2008, -2, 3, 'USA', NULL);
