INSERT INTO movie VALUES (DEFAULT, 'The Last Command', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Way of All Flesh', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Noose', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Patent Leather Kid', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Thunderbolt', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Valiant', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bulldog Drummond', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Condemned', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Big Pond', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Rogue Song', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Green Goddess', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Royal Family of Broadway', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Free Soul', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dr. Jekyll and Mr. Hyde', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Guardsman', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Berkeley Square', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Affairs of Cellini', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Black Fury', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Man Godfrey', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pigskin Parade', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Come and Get It', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The General Died at Dawn', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Conquest', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Night Must Fall', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Hurricane', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Topper', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Angels with Dirty Faces', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Algiers', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'If I Were King', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kentucky', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Marie Antoinette', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Babes in Arms', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Beau Geste', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Juarez', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Abe Lincoln in Illinois', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Westerner', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'They Knew What They Wanted', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Devil and Daniel Webster', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Penny Serenade', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Devil and Miss Jones', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tortilla Flat', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Johnny Eager', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sahara', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'None but the Lonely Heart', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mr. Skeffington', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Seventh Cross', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Song to Remember', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Keys of the Kingdom', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Corn Is Green', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Story of G. I. Joe', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Tree Grows in Brooklyn', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Medal for Benny', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Jolson Story', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Green Years', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Life with Father', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Body and Soul', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Double Life', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mourning Becomes Electra', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ride the Pink Horse', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kiss of Death', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Farmer''s Daughter', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sitting Pretty', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Search', 1948, -2, 0, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'When My Baby Smiles at Me', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Remember Mama', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Joan of Arc', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Luck of the Irish', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Hasty Heart', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sands of Iwo Jima', 1949, -2, 0, 'USA', NULL);
