INSERT INTO movie VALUES (DEFAULT, 'The Quiet One', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Secret Land', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kenji Comes Home', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Daybreak in Udi', 1949, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'With These Hands', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Titan: Story of Michelangelo', 1950, -2, 0, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Was a Communist for the F.B.I.', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kon-Tiki', 1950, -2, 0, 'Norway', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Hoaxters', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sea around Us', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Conquest of Everest', 1953, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Living Desert', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Queen Is Crowned', 1953, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Vanishing Prairie', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Stratford Adventure', 1954, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Helen Keller in Her Story', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Heartbreak Ridge', 1955, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Where Mountains Float', 1955, -2, 0, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Naked Eye', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Silent World', 1956, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Albert Schweitzer', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'On the Bowery', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Torero!', 1956, -2, 0, 'Mexico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Psychiatric Nursing', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Antarctic Crossing', 1958, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'White Wilderness', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Hidden World', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Serengeti Shall Not Die', 1959, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Race for Space', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Rebel in Paradise', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Horse with the Flying Tail', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sky Above and Mud Beneath', 1961, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Grand Olympics', 1961, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Black Fox', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Alvorada', 1962, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Yanks Are Coming', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Link and the Chain', 1963, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Robert Frost: A Lover''s Quarrel with the World', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'World Without Sun', 1964, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Finest Hours', 1964, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Over There, 1914-18', 1964, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Human Dutch', 1964, -2, 0, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Four Days in November', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Let My People Go', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Eleanor Roosevelt Story', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'To Die in Madrid', 1963, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Forth Road Bridge', 1965, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Battle of the Bulge...The Brave Rifles', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Really Big Family', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Face of Genius', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Helicopter Canada', 1966, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The War Game', 1965, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Forbidden Valcano', 1966, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Festival', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A King''s Story', 1967, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Harvest', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Time for Burning', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Other Voices', 1968, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Few Notes on Our Food Problem', 1968, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Journey into Self', 1968, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Legendary Champions', 1968, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Arthur Rubinstein - The Love of Life', 1969, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Olympics in Mexico', 1969, -2, 1, 'Mexico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Before the Mountain Was Moved', 1969, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Wolf Men', 1969, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In the Year of the Pig', 1968, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Chariots of the Gods', 1970, -2, 1, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Say Goodbye', 1970, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'King: A Filmed Record...Montgomery to Memphis', 1970, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Woodstock', 1970, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jack Johnson', 1970, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Hellstrom Chronicle', 1971, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sorrow and the Pity', 1969, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Alaska Wilderness Lake', 1971, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'On Any Sunday', 1971, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ra Expeditions', 1971, -2, 1, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Malcolm X', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Marjoe', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ape and Super-Ape', 1972, -2, 1, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Silent Revolution', 1972, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Manson', 1972, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Always a New Beginning', 1973, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Battle of Berlin', 1973, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Walls of Fire', 1971, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Journey to the Outer Limits', 1973, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great American Cowboy', 1973, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Antonia: A Portrait of the Woman', 1974, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Wild and the Brave', 1974, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The 81st Blow', 1974, -2, 0, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Challenge...A Tribute to Modern Art', 1974, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The California Reich', 1975, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Incredible Machine', 1975, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Man Who Skied Down Everest', 1975, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fighting for Our Lives', 1975, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Other Half of the Sky: A China Memoir', 1975, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hollywood On Trial', 1976, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'People of the Wind', 1976, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Volcano: An Inquiry into the Life and Death of Malcolm Lowry', 1976, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Off the Edge', 1976, -2, 2, 'New Zealand', NULL);
INSERT INTO movie VALUES (DEFAULT, 'High Grass Circus', 1977, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Who Are the DeBolts? And Where Did They Get Nineteen Kids?', 1977, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Homage to Chagall--The Colours of Love', 1977, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Children of Theatre Street', 1977, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Union Maids', 1976, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'With Babies and Banners: Story of the Women''s Emergency Brigade', 1978, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Raoni', 1978, -2, 0, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mysterious Castles of Clay', 1978, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Lovers'' Wind', 1978, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Generation on the Wind', 1979, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The War at Home', 1979, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Killing Ground', 1979, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Going the Distance', 1979, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Front Line', 1979, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Yellow Star - The Persecution of the Jews in Europe 1933-45', 1980, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Day After Trinity', 1980, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Agee', 1980, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'From Mao to Mozart: Isaac Stern in China', 1980, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Eight Minutes to Midnight: A Portrait of Dr. Helen Caldicott', 1981, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Brooklyn Bridge', 1981, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Against Wind and Tide: A Cuban Odyssey', 1981, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'El Salvador: Another Vietnam', 1981, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Genocide', 1981, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'After the Axe', 1981, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Portrait of Giselle', 1982, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In Our Water', 1982, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ben''s Mill', 1982, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Just Another Missing Kid', 1982, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Seeing Red', 1983, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'He Makes Me Feel Like Dancin''', 1983, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Children of Darkness', 1983, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Profession of Arms', 1983, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'First Contact', 1982, -2, 0, 'Australia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Times of Harvey Milk', 1984, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Marlene', 1984, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In the Name of the People', 1984, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'High Schools', 1983, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Las Madres--The Mothers of Plaza de Mayo', 1985, -2, 0, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Soldiers in Hiding', 1985, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Unfinished Business', 1985, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Broken Rainbow', 1985, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Statue of Liberty', 1985, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Witness to Apartheid', 1986, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Down and Out in America', 1986, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Isaac in America: A Journey with Isaac Bashevis Singer', 1986, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Chile: Hasta Cuando?', 1986, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Artie Shaw: Time Is All You''ve Got', 1985, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Stitch for Time', 1987, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Radio Bikini', 1987, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Eyes on the Prize: America''s Civil Rights Years/Bridge to Freedom 1965', 1987, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hellfire: A Journey from Hiroshima', 1986, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ten-Year Lunch: The Wit and Legend of the Algonquin Round Table', 1987, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hotel Terminus: The Life and Times of Klaus Barbie', 1988, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Let''s Get Lost', 1988, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Promises to Keep', 1988, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Cry of Reason - Beyers Naude: An Afrikaner Speaks Out', 1988, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Who Killed Vincent Chin?', 1987, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Super Chief: The Life and Legacy of Earl Warren', 1989, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'For All Mankind', 1989, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Adam Clayton Powell', 1989, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Common Threads: Stories from the Quilt', 1989, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Crack USA: County Under Siege', 1989, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Berkeley in the Sixties', 1990, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Building Bombs', 1990, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Waldo Salt: A Screenwriter''s Journey', 1990, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Forever Activists: Stories from the Veterans of the Abraham Lincoln Brigade', 1990, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Restless Conscience', 1991, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Doing Time: Life Inside the Big House', 1991, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Death on the Job', 1991, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wild by Law', 1991, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In the Shadow of the Stars', 1991, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Panama Deception', 1992, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Liberators: Fighting on Two Fronts in World War II', 1992, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Changing Our Minds: The Story of Dr. Evelyn Hooker', 1992, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Music for the Movies: Bernard Herrmann', 1992, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fires of Kuwait', 1992, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Broadcast Tapes of Dr. Peter', 1993, -2, 0, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'For Better or For Worse', 1993, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Am a Promise: The Children of Stanton Elementary School', 1993, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The War Room', 1993, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Children of Fate', 1993, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Freedom on My Mind', 1994, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'D-Day Remembered', 1994, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Complaints of a Dutiful Daughter', 1994, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Great Day in Harlem', 1994, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Maya Lin: A Strong Clear Vision', 1994, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anne Frank Remembered', 1995, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Small Wonders', 1995, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hank Aaron: Chasing the Dream', 1995, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Battle over Citizen Kane', 1995, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Troublesome Creek: A Midwestern', 1995, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Suzanne Farrell: Elusive Muse', 1996, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mandela', 1996, -2, 0, 'South Africa', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Line King: The Al Hirschfeld Story', 1996, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tell the Truth and Run: George Seldes and the American Press', 1996, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Waco: The Rules of Engagement', 1997, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ayn Rand: A Sense of Life', 1997, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Colors Straight Up', 1997, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Long Way Home', 1997, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lenny Bruce: Swear To Tell the Truth', 1998, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Regret to Inform', 1998, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Last Days', 1998, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dancemaker', 1998, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One Day in September', 1999, -2, 4, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Buena Vista Social Club', 1999, -2, 1, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Speaking in Strings', 1999, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Genghis Blues', 1999, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sound and Fury', 2000, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Scottsboro: An American Tragedy', 2000, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Legacy', 2000, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Into the Arms of Strangers: Stories of the Kindertransport', 2000, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Long Night''s Journey into Day', 2000, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'LaLee''s Kin: The Legacy of Cotton', 2001, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Children Underground', 2001, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'War Photographer', 2001, -2, 0, 'Switzerland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Promises', 2001, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Murder on a Sunday Morning', 2001, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Prisoner of Paradise', 2002, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Daughter from Danang', 2002, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Architect', 2003, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Balseros', 2002, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Weather Underground', 2002, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tupac: Resurrection', 2003, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Born into Brothels', 2004, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Twist of Faith', 2004, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Enron: The Smartest Guys in the Room', 2005, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Street Fight', 2005, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Murderball', 2005, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Iraq in Fragments', 2006, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jesus Camp', 2006, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'An Inconvenient Truth', 2006, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Deliver Us from Evil', 2006, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'No End in Sight', 2007, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Operation Homecoming: Writing the Wartime Experience', 2007, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sicko', 2007, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Taxi to the Dark Side', 2007, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'War Dance', 2007, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Betrayal (Nerakhoon)', 2008, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Garden', 2008, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Trouble the Water', 2008, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Country, My Country', 2006, -2, 0, 'USA', NULL);
