INSERT INTO movie VALUES (DEFAULT, 'Two Arabian Knights', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Speedy', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sorrell and Son', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Drag', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Weary River', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hallelujah!', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Southerner', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Killers', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Fallen Idol', 1949, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, '5 Fingers', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'War and Peace', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Inn of the Sixth Happiness', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Woman in the Dunes', 1965, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Professionals', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Alice''s Restaurant', 1969, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'La Cage aux Folles', 1979, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Das Boot', 1982, -2, 4, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Diving Bell and the Butterfly', 2007, -2, 3, 'France', NULL);
