INSERT INTO movie VALUES (DEFAULT, 'And Now My Love', 1975, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Qivitoq', 1956, -2, 0, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Captain from Kopenick', 1956, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gervaise', 1956, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Burmese Harp', 1956, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Nine Lives', 1957, -2, 0, 'Norway', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Devil Strikes at Night', 1957, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mother India', 1957, -2, 0, 'India', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gates of Paris', 1957, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mon Oncle', 1958, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Year Long Road', 1958, -2, 0, 'Yugoslavia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Arms and the Man', 1958, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'La Venganza', 1958, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Big Deal on Madonna Street', 1958, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Black Orpheus', 1959, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great War', 1959, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bridge', 1959, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Paw', 1959, -2, 0, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Village by the River', 1959, -2, 0, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, 'La Verite', 1960, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ninth Circle', 1960, -2, 0, 'Yugoslavia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Macario', 1960, -2, 0, 'Mexico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kapo', 1960, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Important Man', 1961, -2, 0, 'Mexico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Placido', 1961, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Immortal Love', 1961, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Harry and the Butler', 1961, -2, 0, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Four Days of Naples', 1962, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Given Word', 1962, -2, 0, 'Brazil', NULL);
