INSERT INTO movie VALUES (DEFAULT, 'Kotch', 1971, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sometimes a Great Notion', 1971, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ruling Class', 1972, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Heartbreak Kid', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Serpico', 1973, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Save the Tiger', 1973, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Paper Chase', 1973, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Harry and Tonto', 1974, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Murder on the Orient Express', 1974, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Thunderbolt and Lightfoot', 1974, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sunshine Boys', 1975, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Give ''em'' Hell, Harry!', 1975, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Man in the Glass Booth', 1975, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Day of the Locust', 1975, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Shampoo', 1975, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Equus', 1977, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Special Day', 1977, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Buddy Holly Story', 1978, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Boys from Brazil', 1978, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Comes a Horseman', 1978, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, '...And Justice for All', 1979, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Rose', 1979, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Black Stallion', 1979, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Stunt Man', 1980, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great Santini', 1980, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tribute', 1980, -2, 2, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Melvin and Howard', 1980, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Absence of Malice', 1981, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Arthur', 1981, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Only When I Laugh', 1981, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ragtime', 1981, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Favorite Year', 1982, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Victor Victoria', 1982, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Best Little Whorehouse in Texas', 1982, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'An Officer and a Gentleman', 1982, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Educating Rita', 1983, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Reuben, Reuben', 1983, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cross Creek', 1983, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'To Be or Not to Be', 1983, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Under the Volcano', 1984, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Starman', 1984, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Greystoke: The Legend of Tarzan, Lord of the Apes', 1984, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Murphy''s Romance', 1985, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Runaway Train', 1985, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cocoon', 1985, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Salvador', 1986, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Good Morning, Vietnam', 1987, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ironweed', 1987, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dark Eyes', 1987, -2, 0, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Street Smart', 1987, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cry Freedom', 1987, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Stand and Deliver', 1988, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pelle the Conqueror', 1988, -2, 0, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tucker: The Man and His Dream', 1988, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Little Dorrit', 1988, -2, 1, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Married to the Mob', 1988, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Henry V', 1989, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cyrano de Bergerac', 1990, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Longtime Companion', 1990, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mr. Saturday Night', 1992, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Madness of King George', 1994, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Rob Roy', 1995, -2, 4, 'Scotland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ghosts of Mississippi', 1996, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Cooler', 2003, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Closer', 2004, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hustle & Flow', 2005, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Last King of Scotland', 2006, -2, 4, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Venus', 2006, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Little Children', 2006, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dreamgirls', 2006, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In the Valley of Elah', 2007, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Eastern Promises', 2007, -2, 4, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Charlie Wilson''s War', 2007, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Visitor', 2008, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Wrestler', 2008, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Revolutionary Road', 2008, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Ship Comes In', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Street Angel', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sadie Thompson', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Madame X', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Coquette', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Letter', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Barker', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Divine Lady', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Devil''s Holiday', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Their Own Desire', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Trespasser', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sarah and Son', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anna Christie', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Romance', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Min and Bill', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Holiday', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Morocco', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sin of Madelon Claudet', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Emma', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Morning Glory', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Of Human Bondage', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Escape Me Never', 1935, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Becky Sharp', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Dark Angel', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dangerous', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Private Worlds', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Theodora Goes Wild', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Valiant Is the Word for Carrie', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Gorgeous Hussy', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Camille', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Stella Dallas', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Three Comrades', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'White Banners', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Of Human Hearts', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Merrily We Live', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great Waltz', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Drums along the Mohawk', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Primrose Path', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ball of Fire', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great Lie', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Now, Voyager', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Sister Eileen', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Constant Nymph', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'So Proudly We Hail!', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mrs. Parkington', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dragon Seed', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Leave Her to Heaven', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Love Letters', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Valley of Decision', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Picture of Dorian Gray', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'National Velvet', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Duel in the Sun', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'To Each His Own', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sister Kenny', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Brief Encounter', 1946, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anna and the King of Siam', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Saratoga Trunk', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Spiral Staircase', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Smash-Up: The Story of a Woman', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Possessed', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Paradine Case', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Egg and I', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sorry, Wrong Number', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Key Largo', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pinky', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Come to the Stable', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Foolish Heart', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Edward, My Son', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Caged', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Blue Veil', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Detective Story', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Mating Season', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Member of the Wedding', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Star', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Come Back, Little Sheba', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'With a Song in My Heart', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mogambo', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Moon Is Blue', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lili', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pickup on South Street', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Torch Song', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hondo', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Magnificent Obsession', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sabrina', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Carmen Jones', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Executive Suite', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Broken Lance', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The High and the Mighty', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I''ll Cry Tomorrow', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Interrupted Melody', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pete Kelly''s Blues', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Baby Doll', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bad Seed', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Rainmaker', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anastasia', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Three Faces of Eve', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Raintree County', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Heaven Knows, Mr. Allison', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bachelor Party', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Want To Live!', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lonelyhearts', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Suddenly, Last Summer', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pillow Talk', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Imitation of Life', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Butterfield 8', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Never on Sunday', 1960, -2, 0, DEFAULT, NULL);
