UPDATE movie SET year = 1962 WHERE mid = 285;
UPDATE movie SET title = 'The Game Plan' WHERE mid = 614;
UPDATE movie SET title = 'Ghost Dog: Way of the Samurai' WHERE mid = 629;
UPDATE movie SET mpaa = 'X' WHERE mid = 790;
UPDATE movie SET title = 'Lost in La Mancha' WHERE mid = 981;
UPDATE movie SET title = 'Night at the Museum' WHERE mid = 1175;
UPDATE movie SET year = 1993 WHERE mid = 1182;
UPDATE movie SET title = 'The Number 23' WHERE mid = 1196;
UPDATE movie SET title = 'Sherlock Jr.' WHERE mid = 1462;
UPDATE movie SET title = 'The Simpsons Movie' WHERE mid = 1487;
UPDATE movie SET title = 'Thirty Two Short Films About Glenn Gould' WHERE mid = 1626;
UPDATE movie SET title = 'Timecode' WHERE mid = 1637;
UPDATE movie SET title = 'Tron: Legacy' WHERE mid = 1671;
UPDATE movie SET title = 'Lovely & Amazing' WHERE mid = 989;
