INSERT INTO movie VALUES (DEFAULT, 'The Racket', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, '7th Heaven', 1928, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Alibi', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Broadway Melody', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In Old Arizona', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hollywood Revue', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Patriot', 1929, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Love Parade', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Big House', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Disraeli', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Divorcee', 1930, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cimarron', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Front Page', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Skippy', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'East Lynne', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Trader Horn', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Smiling Lieutenant', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Shanghai Express', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Grand Hotel', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Arrowsmith', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One Hour with You', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bad Girl', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Five Star Final', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Champ', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, '42nd Street', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Little Women', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Am a Fugitive from a Chain Gang', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'State Fair', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Smilin'' Through', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Private Life of Henry VIII', 1933, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Farewell to Arms', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'She Done Him Wrong', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lady for a Day', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cavalcade', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Viva Villa!', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Gay Divorcee', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One Night of Love', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Thin Man', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Barretts of Wimpole Street', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Flirtation Walk', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cleopatra', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Here Comes the Navy', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Imitation of Life', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The White Parade', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The House of Rothschild', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Naughty Marietta', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'David Copperfield', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Alice Adams', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Midsummer Night''s Dream', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Lives of a Bengal Lancer', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Top Hat', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Captain Blood', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Les Miserables', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ruggles of Red Gap', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Broadway Melody of 1936', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Informer', 1935, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Three Smart Girls', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mr. Deeds Goes to Town', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Tale of Two Cities', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'San Francisco', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dodsworth', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great Ziegfeld', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Story of Louis Pasteur', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anthony Adverse', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Romeo and Juliet', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Libeled Lady', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Star Is Born', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Awful Truth', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Good Earth', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In Old Chicago', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One Hundred Men and a Girl', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Stage Door', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Life of Emile Zola', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dead End', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lost Horizon', 1937, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Citadel', 1938, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'You Can''t Take It with You', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jezebel', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Boys Town', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pygmalion', 1938, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Four Daughters', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Test Pilot', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Alexander''s Ragtime Band', 1938, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Love Affair', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Of Mice and Men', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dark Victory', 1939, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Goodbye, Mr. Chips', 1939, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Foreign Correspondent', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Long Voyage Home', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kitty Foyle', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'All This, and Heaven Too', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Letter', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Our Town', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One Foot in Heaven', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hold Back the Dawn', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Here Comes Mr. Jordan', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Little Foxes', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Blossoms in the Dust', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Suspicion', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sergeant York', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'How Green Was My Valley', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Pied Piper', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Pride of the Yankees', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Talk of the Town', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, '49th Parallel', 1942, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kings Row', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Random Harvest', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wake Island', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mrs. Miniver', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Heaven Can Wait', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Madame Curie', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ox-Bow Incident', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'For Whom the Bell Tolls', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The More the Merrier', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Song of Bernadette', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'In Which We Serve', 1943, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Human Comedy', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Watch on the Rhine', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gaslight', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wilson', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Since You Went Away', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Going My Way', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Lost Weekend', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anchors Aweigh', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mildred Pierce', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bells of St. Mary''s', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Yearling', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Henry V', 1946, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Razor''s Edge', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Miracle on 34th Street', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Crossfire', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bishop''s Wife', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gentleman''s Agreement', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Johnny Belinda', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Snake Pit', 1948, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Red Shoes', 1948, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hamlet', 1948, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'All the King''s Men', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Twelve O''Clock High', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Battleground', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Heiress', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Letter to Three Wives', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Born Yesterday', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'King Solomon''s Mines', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Father of the Bride', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Quo Vadis', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Decision before Dawn', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Moulin Rouge', 1952, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ivanhoe', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Quiet Man', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Greatest Show on Earth', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Robe', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Julius Caesar', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Country Girl', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Seven Brides for Seven Brothers', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Three Coins in the Fountain', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Caine Mutiny', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Love Is a Many-Splendored Thing', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Picnic', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Rose Tattoo', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mister Roberts', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The King and I', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Around the World in 80 Days', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Friendly Persuasion', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Witness for the Prosecution', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Peyton Place', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Defiant Ones', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Gigi', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Auntie Mame', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Separate Tables', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Room at the Top', 1959, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Diary of Anne Frank', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Nun''s Story', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anatomy of a Murder', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sundowners', 1960, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Alamo', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sons and Lovers', 1960, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fanny', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Judgment at Nuremberg', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Guns of Navarone', 1961, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'How the West Was Won', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'America America', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lilies of the Field', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cleopatra', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tom Jones', 1963, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Becket', 1964, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Zorba the Greek', 1964, -2, 0, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Thousand Clowns', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ship of Fools', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Russians Are Coming The Russians Are Coming', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sand Pebbles', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Man for All Seasons', 1966, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Doctor Dolittle', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Oliver!', 1968, -2, 1, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Funny Girl', 1968, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Lion in Winter', 1968, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Rachel, Rachel', 1968, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Anne of the Thousand Days', 1969, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Z', 1969, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hello, Dolly!', 1969, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Nicholas and Alexandra', 1971, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fiddler on the Roof', 1971, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cabaret', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sounder', 1972, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Emigrants', 1971, -2, 2, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Exorcist', 1973, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bound for Glory', 1976, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'An Unmarried Woman', 1978, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Passage to India', 1984, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Brokeback Mountain', 2005, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Milk', 2008, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Reader', 2008, -2, 4, 'USA', NULL);
