INSERT INTO movie VALUES (DEFAULT, 'Bad Day at Black Rock', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Love Me or Leave Me', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Trial', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lust for Life', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Richard III', 1956, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bus Stop', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bold and the Brave', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wild Is the Wind', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Hatful of Rain', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Farewell to Arms', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Old Man and the Sea', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Some Came Running', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Teacher''s Pet', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Brothers Karamazov', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Big Country', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Last Angry Man', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Young Philadelphians', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Inherit the Wind', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Entertainer', 1960, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Murder, Inc.', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Exodus', 1960, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Mark', 1961, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pocketful of Miracles', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Birdman of Alcatraz', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Divorce--Italian Style', 1962, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sweet Bird of Youth', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Billy Budd', 1962, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'This Sporting Life', 1963, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hud', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Captain Newman, M.D.', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Twilight of Honor', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Cardinal', 1963, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Topkapi', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Best Man', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Seven Days in May', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cat Ballou', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Othello', 1965, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Spy Who Came In from the Cold', 1965, -2, 0, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Flight of the Phoenix', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Fortune Cookie', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Georgy Girl', 1966, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Dirty Dozen', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Heart Is a Lonely Hunter', 1968, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Charly', 1968, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Fixer', 1968, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Subject Was Roses', 1968, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Star!', 1968, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Goodbye, Mr. Chips', 1969, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bob & Carol & Ted & Alice', 1969, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'They Shoot Horses, Don''t They?', 1969, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Reivers', 1969, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great White Hope', 1970, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Never Sang for My Father', 1970, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lovers and Other Strangers', 1970, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ryan''s Daughter', 1970, -2, 4, 'England', NULL);
