INSERT INTO movie VALUES (DEFAULT, 'Electra', 1962, -2, 0, 'Greece', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tlayucan', 1962, -2, 0, 'Mexico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Twin Sisters of Kyoto', 1963, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Red Lanterns', 1963, -2, 0, 'Greece', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Los Tarantos', 1963, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Yesterday, Today and Tomorrow', 1963, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sallah', 1964, -2, 0, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Raven''s End', 1963, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kwaidan', 1964, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dear John', 1964, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Blood on the Land', 1965, -2, 0, 'Greece', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Loves of a Blonde', 1965, -2, 0, 'Czechoslovakia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Three', 1966, -2, 0, 'Yugoslavia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pharaoh', 1966, -2, 0, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Portrait of Chieko', 1967, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Live for Life', 1967, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'El Amor Brujo', 1967, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Even Met Happy Gypsies', 1967, -2, 0, 'Yugoslavia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Closely Watched Trains', 1966, -2, 0, 'Czechoslovakia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Stolen Kisses', 1968, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'War and Peace', 1967, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Girl with a Pistol', 1968, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Boys of Paul Street', 1968, -2, 1, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Battle of Neretva', 1969, -2, 1, 'Yugoslavia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Adalen ''31''', 1969, -2, 5, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Brothers Karamazov', 1969, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hoa-Binh', 1970, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'First Love', 1970, -2, 4, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Paix Sur Les Champs', 1970, -2, 0, 'Belgium', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dodes''ka-Den', 1970, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tchaikovsky', 1970, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Policeman', 1971, -2, 0, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Love You Rosa', 1972, -2, 0, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Dearest Senorita', 1972, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Dawns Here Are Quiet', 1972, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The New Land', 1972, -2, 2, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Turkish Delight', 1973, -2, 4, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The House on Chelouche Street', 1973, -2, 0, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Pedestrian', 1973, -2, 2, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'L''Invitation', 1973, -2, 0, 'Switzerland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lacombe, Lucien', 1974, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Deluge', 1974, -2, 0, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cat''s Play', 1974, -2, 0, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Truce', 1974, -2, 0, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dersu Uzala', 1975, -2, 1, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Promised Land', 1975, -2, 0, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Letters from Marusia', 1975, -2, 0, 'Mexico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sandakan 8', 1974, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Black and White in Color', 1976, -2, 2, 'Ivory Coast', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Nights and Days', 1975, -2, 0, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jacob, the Liar', 1975, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Operation Thunderbolt', 1977, -2, 2, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Iphigenia', 1977, -2, 0, 'Greece', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Madame Rosa', 1977, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'White Bim Black Ear', 1977, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Get Out Your Handkerchiefs', 1978, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hungarians', 1978, -2, 0, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Glass Cell', 1978, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Viva Italia!', 1977, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Simple Story', 1978, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mama Turns 100', 1979, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Maids of Wilko', 1979, -2, 0, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'To Forget Venice', 1979, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Tin Drum', 1979, -2, 4, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kagemusha', 1980, -2, 2, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Nest', 1980, -2, 2, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Confidence', 1980, -2, 0, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Moscow Does Not Believe in Tears', 1980, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Last Metro', 1980, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Three Brothers', 1981, -2, 2, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Man of Iron', 1981, -2, 2, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Muddy River', 1981, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mephisto', 1981, -2, 0, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Boat Is Full', 1981, -2, 0, 'Switzerland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Coup de Torchon', 1981, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Private Life', 1982, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Alsino and the Condor', 1982, -2, 0, 'Nicaragua', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Volver a Empezar', 1982, -2, 2, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Flight of the Eagle', 1982, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Job''s Revolt', 1983, -2, 0, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Entre Nous', 1983, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Le Bal', 1983, -2, 0, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Carmen', 1983, -2, 4, 'Spain', NULL);
