INSERT INTO movie VALUES (DEFAULT, 'The Dawn Patrol', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Smart Money', 1931, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'What Price Hollywood?', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lady and Gent', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Star Witness', 1932, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Prizefighter and the Lady', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One Way Passage', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Rasputin and the Empress', 1933, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hide-Out', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Richest Girl in the World', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Manhattan Melodrama', 1934, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'After the Thin Man', 1936, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dr. Ehrlich''s Magic Bullet', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Angels over Broadway', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Great McGinty', 1940, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tom, Dick and Harry', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tall, Dark and Handsome', 1941, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The War against Mrs. Hadley', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Road to Morocco', 1942, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One of Our Aircraft Is Missing', 1942, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Princess O''Rourke', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Holy Matrimony', 1943, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Wing and a Prayer', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Miracle of Morgan''s Creek', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hail the Conquering Hero', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Two Girls and a Sailor', 1944, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Salty O''Rourke', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'What Next, Corporal Hargrove?', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Marie-Louise', 1945, -2, 0, 'Switzerland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Music for Millions', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dillinger', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pride of the Marines', 1945, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Road to Utopia', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Seventh Veil', 1946, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Blue Dahlia', 1946, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Rome, Open City', 1946, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Bachelor and the Bobby-Soxer', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Shoeshine', 1947, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Boomerang!', 1947, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Passport to Pimlico', 1949, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Paisan', 1949, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Quiet One', 1949, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'No Way Out', 1950, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'La Ronde', 1951, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Go For Broke!', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ace in the Hole', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Well', 1951, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Man in the White Suit', 1952, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pat and Mike', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Atomic City', 1952, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Breaking the Sound Barrier', 1952, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Cruel Sea', 1953, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Take the High Ground', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Naked Spur', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Band Wagon', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Desert Rats', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Titanic', 1953, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Knock on Wood', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Glenn Miller Story', 1954, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Genevieve', 1954, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Seven Little Foys', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Court-Martial of Billy Mitchell', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'It''s Always Fair Weather', 1955, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Red Balloon', 1956, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ladykillers', 1956, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Julie', 1956, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Man of a Thousand Faces', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Vitelloni', 1957, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Designing Woman', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Tin Star', 1957, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Horse''s Mouth', 1958, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Houseboat', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sheepman', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Goddess', 1958, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Operation Petticoat', 1959, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tunes of Glory', 1960, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Angry Silence', 1960, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hiroshima, Mon Amour', 1960, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'General Della Rovere', 1961, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lover Come Back', 1961, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ballad of a Soldier', 1961, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'That Touch of Mink', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Freud', 1962, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Sundays and Cybele', 1962, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Four Days of Naples', 1963, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Father Goose', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Organizer', 1964, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'That Man from Rio', 1964, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'One Potato, Two Potato', 1964, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Umbrellas of Cherbourg', 1965, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Train', 1965, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Casanova ''70''', 1965, -2, 0, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Those Magnificent Men in Their Flying Machines or How I Flew from London to Paris in 25 Hours 11 Minutes', 1965, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Khartoum', 1966, -2, 0, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Naked Prey', 1966, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ulysses', 1967, -2, 0, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Two for the Road', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Divorce American Style', 1967, -2, 0, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The War is Over', 1967, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Odd Couple', 1968, -2, 1, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hot Millions', 1968, -2, 1, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Goodbye, Columbus', 1969, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Damned', 1969, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Joe', 1970, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Night at Maud''s', 1970, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Investigation of a Citizen Above Suspicion', 1971, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Young Winston', 1972, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Murmur of the Heart', 1972, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Candidate', 1972, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Apprenticeship of Duddy Kravitz', 1974, -2, 2, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lies My Father Told Me', 1975, -2, 2, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Scent of a Woman', 1975, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Man Who Would Be King', 1975, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Front', 1976, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fellini''s Casanova', 1976, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Seven-per-cent Solution', 1976, -2, 2, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Late Show', 1977, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'That Obscure Object of Desire', 1977, -2, 4, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Oh, God!', 1977, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'I Never Promised You a Rose Garden', 1977, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bloodbrothers', 1978, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Little Romance', 1979, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Breaker Morant', 1980, -2, 2, 'Australia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mon Oncle D''Amerique', 1980, -2, 2, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Fame', 1980, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Brubaker', 1980, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Prince of the City', 1981, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pennies from Heaven', 1981, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Betrayal', 1983, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Splash', 1984, -2, 2, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'El Norte', 1984, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Official Story', 1985, -2, 4, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Beautiful Laundrette', 1986, -2, 4, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Crocodile Dundee', 1986, -2, 3, 'Australia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Dead', 1987, -2, 2, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'sex, lies, and videotape', 1989, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Green Card', 1990, -2, 3, DEFAULT, NULL);
INSERT INTO movie VALUES (DEFAULT, 'Metropolitan', 1990, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Europa Europa', 1991, -2, 4, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Heavenly Creatures', 1994, -2, 4, 'New Zealand', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hamlet', 1996, -2, 3, 'England', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Bulworth', 1998, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Squid and the Whale', 2005, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan', 2006, -2, 4, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lars and the Real Girl', 2007, -2, 3, 'USA', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Happy-Go-Lucky', 2008, -2, 4, 'England', NULL);
