INSERT INTO movie VALUES (DEFAULT, 'Wartime Romance', 1984, -2, 0, 'USSR', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Beyond the Walls', 1984, -2, 4, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dangerous Moves', 1984, -2, 0, 'Switzerland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Camila', 1984, -2, 4, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Double Feature', 1984, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'When Father Was Away on Business', 1985, -2, 4, 'Yugoslavia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Colonel Redl', 1985, -2, 4, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Angry Harvest', 1985, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Three Men and a Cradle', 1985, -2, 3, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'My Sweet Little Village', 1985, -2, 0, 'Czechoslovakia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Betty Blue', 1986, -2, 0, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Assault', 1986, -2, 2, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, '''38', 1986, -2, 0, 'Austria', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Decline of the American Empire', 1986, -2, 4, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Family', 1987, -2, 2, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Pathfinder', 1987, -2, 0, 'Norway', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Course Completed', 1987, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Babette''s Feast', 1987, -2, 1, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hanussen', 1988, -2, 4, 'Hungary', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Music Teacher', 1988, -2, 2, 'Belgium', NULL);
INSERT INTO movie VALUES (DEFAULT, 'What Happened to Santiago', 1989, -2, 0, 'Puerto Rico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Waltzing Regitze', 1989, -2, 0, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Jesus of Montreal', 1989, -2, 4, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Cinema Paradiso', 1988, -2, 2, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Open Doors', 1990, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Nasty Girl', 1990, -2, 3, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Journey of Hope', 1990, -2, 2, 'Switzerland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ju Dou', 1990, -2, 3, 'China', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Children of Nature', 1991, -2, 0, 'Iceland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mediterraneo', 1991, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Ox', 1991, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Raise the Red Lantern', 1991, -2, 2, 'China', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Elementary School', 1991, -2, 0, 'Czechoslovakia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Close to Eden', 1991, -2, 2, 'Russia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Daens', 1992, -2, 0, 'Belgium', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Schtonk!', 1992, -2, 0, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Place in the World', 1992, -2, 2, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Scent of Green Papaya', 1993, -2, 0, 'Vietnam', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Hedd Wyn', 1992, -2, 0, 'Wales', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Wedding Banquet', 1993, -2, 4, 'Taiwan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Belle Epoque', 1992, -2, 4, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Burnt by the Sun', 1994, -2, 4, 'Russia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Eat Drink Man Woman', 1994, -2, 0, 'Taiwan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Farinelli', 1994, -2, 4, 'Belgium', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Strawberry and Chocolate', 1994, -2, 4, 'Cuba', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Before the Rain', 1994, -2, 0, 'Macedonia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Antonia''s Line', 1995, -2, 4, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, 'All Things Fair', 1995, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'O Quatrilho', 1995, -2, 0, 'Brazil', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Star Maker', 1995, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Dust of Life', 1995, -2, 0, 'Algeria', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Other Side of Sunday', 1996, -2, 3, 'Norway', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Kolya', 1996, -2, 3, 'Czech Republic', NULL);
INSERT INTO movie VALUES (DEFAULT, 'A Chef in Love', 1996, -2, 3, 'Georgia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Prisoner of the Mountains', 1996, -2, 4, 'Russia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Ridicule', 1996, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Thief', 1997, -2, 4, 'Russia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Beyond Silence', 1996, -2, 3, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Four Days in September', 1997, -2, 4, 'Brazil', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Secrets of the Heart', 1997, -2, 0, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tango', 1998, -2, 3, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Grandfather', 1998, -2, 2, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'East-West', 1999, -2, 3, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Under the Sun', 1998, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Solomon and Gaenor', 1999, -2, 4, 'Wales', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Himalaya', 1999, -2, 0, 'Nepal', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Everybody Famous!', 2000, -2, 4, 'Belgium', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Taste of Others', 2000, -2, 4, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Divided We Fall', 2000, -2, 3, 'Czech Republic', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Son of the Bride', 2001, -2, 4, 'Argentina', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Elling', 2001, -2, 4, 'Norway', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Lagaan: Once Upon a Time in India', 2001, -2, 2, 'India', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Zus & Zo', 2001, -2, 0, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Crime of Father Amaro', 2002, -2, 4, 'Mexico', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Nowhere in Africa', 2001, -2, 4, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Man without a Past', 2002, -2, 3, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Twin Sisters', 2002, -2, 4, 'The Netherlands', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Evil', 2003, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Twilight Samurai', 2002, -2, 0, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Zelary', 2003, -2, 4, 'Czech Republic', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Sea Inside', 2004, -2, 3, 'Spain', NULL);
INSERT INTO movie VALUES (DEFAULT, 'As It Is in Heaven', 2004, -2, 0, 'Sweden', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Yesterday', 2004, -2, 4, 'South Africa', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Don''''t Tell', 2005, -2, 4, 'Italy', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Joyeux Noel', 2005, -2, 3, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Paradise Now', 2005, -2, 3, 'Palestine', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Tsotsi', 2005, -2, 4, 'South Africa', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Water', 2005, -2, 3, 'Canada', NULL);
INSERT INTO movie VALUES (DEFAULT, 'After the Wedding', 2006, -2, 4, 'Denmark', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Lives of Others', 2006, -2, 4, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Days of Glory', 2006, -2, 4, 'Algeria', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Beaufort', 2007, -2, 0, 'Israel', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Katyn', 2007, -2, 0, 'Poland', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Mongol', 2007, -2, 4, 'Kazakhstan', NULL);
INSERT INTO movie VALUES (DEFAULT, '12', 2007, -2, 3, 'Russia', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Baader Meinhof Complex', 2008, -2, 4, 'Germany', NULL);
INSERT INTO movie VALUES (DEFAULT, 'The Class', 2008, -2, 3, 'France', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Departures', 2008, -2, 3, 'Japan', NULL);
INSERT INTO movie VALUES (DEFAULT, 'Revanche', 2008, -2, 0, 'Austria', NULL);
