INSERT INTO mpaa VALUES('NR');
INSERT INTO mpaa VALUES('G');
INSERT INTO mpaa VALUES('PG');
INSERT INTO mpaa VALUES('PG-13');
INSERT INTO mpaa VALUES('R');
INSERT INTO mpaa VALUES('X');
INSERT INTO mpaa VALUES('NC-17');
