INSERT INTO oscar VALUES (1, 'Best Picture');
INSERT INTO oscar VALUES (2, 'Best Actor');
INSERT INTO oscar VALUES (3, 'Best Actress');
INSERT INTO oscar VALUES (4, 'Best Supporting Actor');
INSERT INTO oscar VALUES (5, 'Best Supporting Actress');
INSERT INTO oscar VALUES (6, 'Best Director');
INSERT INTO oscar VALUES (7, 'Best Cinematography (black and white)');
INSERT INTO oscar VALUES (8, 'Best Cinematography (color)');
INSERT INTO oscar VALUES (9, 'Best Cinematography');
INSERT INTO oscar VALUES (10, 'Best Adapted Screenplay');
INSERT INTO oscar VALUES (11, 'Best Original Screenplay');
INSERT INTO oscar VALUES (12, 'Best Foreign Language Film');
INSERT INTO oscar VALUES (13, 'Best Documentary');
INSERT INTO oscar VALUES (14, 'Best Screenplay');
