INSERT INTO oscar_given_to VALUES(1813, 1, DEFAULT, 0, DEFAULT);  -- 1928 Best Picture: "The Racket"
INSERT INTO oscar_given_to VALUES(1751, 1, DEFAULT, 1, DEFAULT);  -- 1928 Best Picture: "Wings"
INSERT INTO oscar_given_to VALUES(1814, 1, DEFAULT, 0, DEFAULT);  -- 1928 Best Picture: "7th Heaven"
INSERT INTO oscar_given_to VALUES(1815, 1, DEFAULT, 0, DEFAULT);  -- 1929 Best Picture: "Alibi"
INSERT INTO oscar_given_to VALUES(1816, 1, DEFAULT, 1, DEFAULT);  -- 1929 Best Picture: "The Broadway Melody"
INSERT INTO oscar_given_to VALUES(1817, 1, DEFAULT, 0, DEFAULT);  -- 1929 Best Picture: "In Old Arizona"
INSERT INTO oscar_given_to VALUES(1818, 1, DEFAULT, 0, DEFAULT);  -- 1929 Best Picture: "Hollywood Revue"
INSERT INTO oscar_given_to VALUES(1819, 1, DEFAULT, 0, DEFAULT);  -- 1929 Best Picture: "The Patriot"
INSERT INTO oscar_given_to VALUES(1820, 1, DEFAULT, 0, DEFAULT);  -- 1930 Best Picture: "The Love Parade"
INSERT INTO oscar_given_to VALUES(1821, 1, DEFAULT, 0, DEFAULT);  -- 1930 Best Picture: "The Big House"
INSERT INTO oscar_given_to VALUES(1822, 1, DEFAULT, 0, DEFAULT);  -- 1930 Best Picture: "Disraeli"
INSERT INTO oscar_given_to VALUES(1823, 1, DEFAULT, 0, DEFAULT);  -- 1930 Best Picture: "The Divorcee"
INSERT INTO oscar_given_to VALUES(68, 1, DEFAULT, 1, DEFAULT);  -- 1930 Best Picture: "All Quiet on the Western Front"
INSERT INTO oscar_given_to VALUES(1824, 1, DEFAULT, 1, DEFAULT);  -- 1931 Best Picture: "Cimarron"
INSERT INTO oscar_given_to VALUES(1825, 1, DEFAULT, 0, DEFAULT);  -- 1931 Best Picture: "The Front Page"
INSERT INTO oscar_given_to VALUES(1826, 1, DEFAULT, 0, DEFAULT);  -- 1931 Best Picture: "Skippy"
INSERT INTO oscar_given_to VALUES(1827, 1, DEFAULT, 0, DEFAULT);  -- 1931 Best Picture: "East Lynne"
INSERT INTO oscar_given_to VALUES(1828, 1, DEFAULT, 0, DEFAULT);  -- 1931 Best Picture: "Trader Horn"
INSERT INTO oscar_given_to VALUES(1829, 1, DEFAULT, 0, DEFAULT);  -- 1932 Best Picture: "The Smiling Lieutenant"
INSERT INTO oscar_given_to VALUES(1830, 1, DEFAULT, 0, DEFAULT);  -- 1932 Best Picture: "Shanghai Express"
INSERT INTO oscar_given_to VALUES(1831, 1, DEFAULT, 1, DEFAULT);  -- 1932 Best Picture: "Grand Hotel"
INSERT INTO oscar_given_to VALUES(1832, 1, DEFAULT, 0, DEFAULT);  -- 1932 Best Picture: "Arrowsmith"
INSERT INTO oscar_given_to VALUES(1833, 1, DEFAULT, 0, DEFAULT);  -- 1932 Best Picture: "One Hour with You"
INSERT INTO oscar_given_to VALUES(1834, 1, DEFAULT, 0, DEFAULT);  -- 1932 Best Picture: "Bad Girl"
INSERT INTO oscar_given_to VALUES(1835, 1, DEFAULT, 0, DEFAULT);  -- 1932 Best Picture: "Five Star Final"
INSERT INTO oscar_given_to VALUES(1836, 1, DEFAULT, 0, DEFAULT);  -- 1932 Best Picture: "The Champ"
INSERT INTO oscar_given_to VALUES(1837, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "42nd Street"
INSERT INTO oscar_given_to VALUES(1838, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "Little Women"
INSERT INTO oscar_given_to VALUES(1839, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "I Am a Fugitive from a Chain Gang"
INSERT INTO oscar_given_to VALUES(1840, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "State Fair"
INSERT INTO oscar_given_to VALUES(1841, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "Smilin' Through"
INSERT INTO oscar_given_to VALUES(1842, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "The Private Life of Henry VIII"
INSERT INTO oscar_given_to VALUES(1843, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "A Farewell to Arms"
INSERT INTO oscar_given_to VALUES(1844, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "She Done Him Wrong"
INSERT INTO oscar_given_to VALUES(1845, 1, DEFAULT, 0, DEFAULT);  -- 1933 Best Picture: "Lady for a Day"
INSERT INTO oscar_given_to VALUES(1846, 1, DEFAULT, 1, DEFAULT);  -- 1933 Best Picture: "Cavalcade"
INSERT INTO oscar_given_to VALUES(1847, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "Viva Villa!"
INSERT INTO oscar_given_to VALUES(1848, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "The Gay Divorcee"
INSERT INTO oscar_given_to VALUES(1849, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "One Night of Love"
INSERT INTO oscar_given_to VALUES(1850, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "The Thin Man"
INSERT INTO oscar_given_to VALUES(1851, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "The Barretts of Wimpole Street"
INSERT INTO oscar_given_to VALUES(826, 1, DEFAULT, 1, DEFAULT);  -- 1934 Best Picture: "It Happened One Night"
INSERT INTO oscar_given_to VALUES(1852, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "Flirtation Walk"
INSERT INTO oscar_given_to VALUES(1853, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "Cleopatra"
INSERT INTO oscar_given_to VALUES(1854, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "Here Comes the Navy"
INSERT INTO oscar_given_to VALUES(1855, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "Imitation of Life"
INSERT INTO oscar_given_to VALUES(1856, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "The White Parade"
INSERT INTO oscar_given_to VALUES(1857, 1, DEFAULT, 0, DEFAULT);  -- 1934 Best Picture: "The House of Rothschild"
INSERT INTO oscar_given_to VALUES(1858, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "Naughty Marietta"
INSERT INTO oscar_given_to VALUES(1859, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "David Copperfield"
INSERT INTO oscar_given_to VALUES(1860, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "Alice Adams"
INSERT INTO oscar_given_to VALUES(1861, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "A Midsummer Night's Dream"
INSERT INTO oscar_given_to VALUES(1862, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "The Lives of a Bengal Lancer"
INSERT INTO oscar_given_to VALUES(1863, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "Top Hat"
INSERT INTO oscar_given_to VALUES(1864, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "Captain Blood"
INSERT INTO oscar_given_to VALUES(1865, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "Les Miserables"
INSERT INTO oscar_given_to VALUES(1866, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "Ruggles of Red Gap"
INSERT INTO oscar_given_to VALUES(1867, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "Broadway Melody of 1936"
INSERT INTO oscar_given_to VALUES(1111, 1, DEFAULT, 1, DEFAULT);  -- 1935 Best Picture: "Mutiny on the Bounty"
INSERT INTO oscar_given_to VALUES(1868, 1, DEFAULT, 0, DEFAULT);  -- 1935 Best Picture: "The Informer"
INSERT INTO oscar_given_to VALUES(1869, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "Three Smart Girls"
INSERT INTO oscar_given_to VALUES(1870, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "Mr. Deeds Goes to Town"
INSERT INTO oscar_given_to VALUES(1871, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "A Tale of Two Cities"
INSERT INTO oscar_given_to VALUES(1872, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "San Francisco"
INSERT INTO oscar_given_to VALUES(1873, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "Dodsworth"
INSERT INTO oscar_given_to VALUES(1874, 1, DEFAULT, 1, DEFAULT);  -- 1936 Best Picture: "The Great Ziegfeld"
INSERT INTO oscar_given_to VALUES(1875, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "The Story of Louis Pasteur"
INSERT INTO oscar_given_to VALUES(1876, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "Anthony Adverse"
INSERT INTO oscar_given_to VALUES(1877, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "Romeo and Juliet"
INSERT INTO oscar_given_to VALUES(1878, 1, DEFAULT, 0, DEFAULT);  -- 1936 Best Picture: "Libeled Lady"
INSERT INTO oscar_given_to VALUES(1879, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "A Star Is Born"
INSERT INTO oscar_given_to VALUES(1880, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "The Awful Truth"
INSERT INTO oscar_given_to VALUES(1881, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "The Good Earth"
INSERT INTO oscar_given_to VALUES(285, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "Captains Courageous"
INSERT INTO oscar_given_to VALUES(1882, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "In Old Chicago"
INSERT INTO oscar_given_to VALUES(1883, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "One Hundred Men and a Girl"
INSERT INTO oscar_given_to VALUES(1884, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "Stage Door"
INSERT INTO oscar_given_to VALUES(1885, 1, DEFAULT, 1, DEFAULT);  -- 1937 Best Picture: "The Life of Emile Zola"
INSERT INTO oscar_given_to VALUES(1886, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "Dead End"
INSERT INTO oscar_given_to VALUES(1887, 1, DEFAULT, 0, DEFAULT);  -- 1937 Best Picture: "Lost Horizon"
INSERT INTO oscar_given_to VALUES(1888, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "The Citadel"
INSERT INTO oscar_given_to VALUES(1889, 1, DEFAULT, 1, DEFAULT);  -- 1938 Best Picture: "You Can't Take It with You"
INSERT INTO oscar_given_to VALUES(1890, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "Jezebel"
INSERT INTO oscar_given_to VALUES(1891, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "Boys Town"
INSERT INTO oscar_given_to VALUES(1892, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "Pygmalion"
INSERT INTO oscar_given_to VALUES(1893, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "Four Daughters"
INSERT INTO oscar_given_to VALUES(40, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "The Adventures of Robin Hood"
INSERT INTO oscar_given_to VALUES(1894, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "Test Pilot"
INSERT INTO oscar_given_to VALUES(1895, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "Alexander's Ragtime Band"
INSERT INTO oscar_given_to VALUES(662, 1, DEFAULT, 0, DEFAULT);  -- 1938 Best Picture: "Grand Illusion"
INSERT INTO oscar_given_to VALUES(1896, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Love Affair"
INSERT INTO oscar_given_to VALUES(1099, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Mr. Smith Goes to Washington"
INSERT INTO oscar_given_to VALUES(1758, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "The Wizard of Oz"
INSERT INTO oscar_given_to VALUES(1511, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Stagecoach"
INSERT INTO oscar_given_to VALUES(1771, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Wuthering Heights"
INSERT INTO oscar_given_to VALUES(644, 1, DEFAULT, 1, DEFAULT);  -- 1939 Best Picture: "Gone with the Wind"
INSERT INTO oscar_given_to VALUES(1897, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Of Mice and Men"
INSERT INTO oscar_given_to VALUES(1898, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Dark Victory"
INSERT INTO oscar_given_to VALUES(1163, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Ninotchka"
INSERT INTO oscar_given_to VALUES(1899, 1, DEFAULT, 0, DEFAULT);  -- 1939 Best Picture: "Goodbye, Mr. Chips"
INSERT INTO oscar_given_to VALUES(1900, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "Foreign Correspondent"
INSERT INTO oscar_given_to VALUES(1901, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "The Long Voyage Home"
INSERT INTO oscar_given_to VALUES(1902, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "Kitty Foyle"
INSERT INTO oscar_given_to VALUES(1903, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "All This, and Heaven Too"
INSERT INTO oscar_given_to VALUES(1320, 1, DEFAULT, 1, DEFAULT);  -- 1940 Best Picture: "Rebecca"
INSERT INTO oscar_given_to VALUES(1904, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "The Letter"
INSERT INTO oscar_given_to VALUES(1238, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "The Philadelphia Story"
INSERT INTO oscar_given_to VALUES(667, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "The Great Dictator"
INSERT INTO oscar_given_to VALUES(1905, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "Our Town"
INSERT INTO oscar_given_to VALUES(663, 1, DEFAULT, 0, DEFAULT);  -- 1940 Best Picture: "The Grapes of Wrath"
INSERT INTO oscar_given_to VALUES(1906, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "One Foot in Heaven"
INSERT INTO oscar_given_to VALUES(1907, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "Hold Back the Dawn"
INSERT INTO oscar_given_to VALUES(1908, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "Here Comes Mr. Jordan"
INSERT INTO oscar_given_to VALUES(1909, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "The Little Foxes"
INSERT INTO oscar_given_to VALUES(988, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "The Maltese Falcon"
INSERT INTO oscar_given_to VALUES(1910, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "Blossoms in the Dust"
INSERT INTO oscar_given_to VALUES(1911, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "Suspicion"
INSERT INTO oscar_given_to VALUES(333, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "Citizen Kane"
INSERT INTO oscar_given_to VALUES(1912, 1, DEFAULT, 0, DEFAULT);  -- 1941 Best Picture: "Sergeant York"
INSERT INTO oscar_given_to VALUES(1913, 1, DEFAULT, 1, DEFAULT);  -- 1941 Best Picture: "How Green Was My Valley"
INSERT INTO oscar_given_to VALUES(1914, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "The Pied Piper"
INSERT INTO oscar_given_to VALUES(1915, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "The Pride of the Yankees"
INSERT INTO oscar_given_to VALUES(1916, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "The Talk of the Town"
INSERT INTO oscar_given_to VALUES(1917, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "49th Parallel"
INSERT INTO oscar_given_to VALUES(1779, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "Yankee Doodle Dandy"
INSERT INTO oscar_given_to VALUES(1918, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "Kings Row"
INSERT INTO oscar_given_to VALUES(1919, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "Random Harvest"
INSERT INTO oscar_given_to VALUES(1920, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "Wake Island"
INSERT INTO oscar_given_to VALUES(982, 1, DEFAULT, 0, DEFAULT);  -- 1942 Best Picture: "The Magnificent Ambersons"
INSERT INTO oscar_given_to VALUES(1921, 1, DEFAULT, 1, DEFAULT);  -- 1942 Best Picture: "Mrs. Miniver"
INSERT INTO oscar_given_to VALUES(1922, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "Heaven Can Wait"
INSERT INTO oscar_given_to VALUES(1923, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "Madame Curie"
INSERT INTO oscar_given_to VALUES(1924, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "The Ox-Bow Incident"
INSERT INTO oscar_given_to VALUES(1925, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "For Whom the Bell Tolls"
INSERT INTO oscar_given_to VALUES(289, 1, DEFAULT, 1, DEFAULT);  -- 1943 Best Picture: "Casablanca"
INSERT INTO oscar_given_to VALUES(1926, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "The More the Merrier"
INSERT INTO oscar_given_to VALUES(1927, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "The Song of Bernadette"
INSERT INTO oscar_given_to VALUES(1928, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "In Which We Serve"
INSERT INTO oscar_given_to VALUES(1929, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "The Human Comedy"
INSERT INTO oscar_given_to VALUES(1930, 1, DEFAULT, 0, DEFAULT);  -- 1943 Best Picture: "Watch on the Rhine"
INSERT INTO oscar_given_to VALUES(1931, 1, DEFAULT, 0, DEFAULT);  -- 1944 Best Picture: "Gaslight"
INSERT INTO oscar_given_to VALUES(1932, 1, DEFAULT, 0, DEFAULT);  -- 1944 Best Picture: "Wilson"
INSERT INTO oscar_given_to VALUES(464, 1, DEFAULT, 0, DEFAULT);  -- 1944 Best Picture: "Double Indemnity"
INSERT INTO oscar_given_to VALUES(1933, 1, DEFAULT, 0, DEFAULT);  -- 1944 Best Picture: "Since You Went Away"
INSERT INTO oscar_given_to VALUES(1934, 1, DEFAULT, 1, DEFAULT);  -- 1944 Best Picture: "Going My Way"
INSERT INTO oscar_given_to VALUES(1935, 1, DEFAULT, 1, DEFAULT);  -- 1945 Best Picture: "The Lost Weekend"
INSERT INTO oscar_given_to VALUES(1936, 1, DEFAULT, 0, DEFAULT);  -- 1945 Best Picture: "Anchors Aweigh"
INSERT INTO oscar_given_to VALUES(1503, 1, DEFAULT, 0, DEFAULT);  -- 1945 Best Picture: "Spellbound"
INSERT INTO oscar_given_to VALUES(1937, 1, DEFAULT, 0, DEFAULT);  -- 1945 Best Picture: "Mildred Pierce"
INSERT INTO oscar_given_to VALUES(1938, 1, DEFAULT, 0, DEFAULT);  -- 1945 Best Picture: "The Bells of St. Mary's"
INSERT INTO oscar_given_to VALUES(1939, 1, DEFAULT, 0, DEFAULT);  -- 1946 Best Picture: "The Yearling"
INSERT INTO oscar_given_to VALUES(828, 1, DEFAULT, 0, DEFAULT);  -- 1946 Best Picture: "It's a Wonderful Life"
INSERT INTO oscar_given_to VALUES(186, 1, DEFAULT, 1, DEFAULT);  -- 1946 Best Picture: "The Best Years of Our Lives"
INSERT INTO oscar_given_to VALUES(1940, 1, DEFAULT, 0, DEFAULT);  -- 1946 Best Picture: "Henry V"
INSERT INTO oscar_given_to VALUES(1941, 1, DEFAULT, 0, DEFAULT);  -- 1946 Best Picture: "The Razor's Edge"
INSERT INTO oscar_given_to VALUES(1942, 1, DEFAULT, 0, DEFAULT);  -- 1947 Best Picture: "Miracle on 34th Street"
INSERT INTO oscar_given_to VALUES(1943, 1, DEFAULT, 0, DEFAULT);  -- 1947 Best Picture: "Crossfire"
INSERT INTO oscar_given_to VALUES(669, 1, DEFAULT, 0, DEFAULT);  -- 1947 Best Picture: "Great Expectations"
INSERT INTO oscar_given_to VALUES(1944, 1, DEFAULT, 0, DEFAULT);  -- 1947 Best Picture: "The Bishop's Wife"
INSERT INTO oscar_given_to VALUES(1945, 1, DEFAULT, 1, DEFAULT);  -- 1947 Best Picture: "Gentleman's Agreement"
INSERT INTO oscar_given_to VALUES(1946, 1, DEFAULT, 0, DEFAULT);  -- 1948 Best Picture: "Johnny Belinda"
INSERT INTO oscar_given_to VALUES(1947, 1, DEFAULT, 0, DEFAULT);  -- 1948 Best Picture: "The Snake Pit"
INSERT INTO oscar_given_to VALUES(1948, 1, DEFAULT, 0, DEFAULT);  -- 1948 Best Picture: "The Red Shoes"
INSERT INTO oscar_given_to VALUES(1949, 1, DEFAULT, 1, DEFAULT);  -- 1948 Best Picture: "Hamlet"
INSERT INTO oscar_given_to VALUES(1634, 1, DEFAULT, 0, DEFAULT);  -- 1948 Best Picture: "The Treasure of the Sierra Madre"
INSERT INTO oscar_given_to VALUES(1950, 1, DEFAULT, 1, DEFAULT);  -- 1949 Best Picture: "All the King's Men"
INSERT INTO oscar_given_to VALUES(1951, 1, DEFAULT, 0, DEFAULT);  -- 1949 Best Picture: "Twelve O'Clock High"
INSERT INTO oscar_given_to VALUES(1952, 1, DEFAULT, 0, DEFAULT);  -- 1949 Best Picture: "Battleground"
INSERT INTO oscar_given_to VALUES(1953, 1, DEFAULT, 0, DEFAULT);  -- 1949 Best Picture: "The Heiress"
INSERT INTO oscar_given_to VALUES(1954, 1, DEFAULT, 0, DEFAULT);  -- 1949 Best Picture: "A Letter to Three Wives"
INSERT INTO oscar_given_to VALUES(1955, 1, DEFAULT, 0, DEFAULT);  -- 1950 Best Picture: "Born Yesterday"
INSERT INTO oscar_given_to VALUES(1956, 1, DEFAULT, 0, DEFAULT);  -- 1950 Best Picture: "King Solomon's Mines"
INSERT INTO oscar_given_to VALUES(65, 1, DEFAULT, 1, DEFAULT);  -- 1950 Best Picture: "All about Eve"
INSERT INTO oscar_given_to VALUES(1957, 1, DEFAULT, 0, DEFAULT);  -- 1950 Best Picture: "Father of the Bride"
INSERT INTO oscar_given_to VALUES(1546, 1, DEFAULT, 0, DEFAULT);  -- 1950 Best Picture: "Sunset Boulevard"
INSERT INTO oscar_given_to VALUES(1252, 1, DEFAULT, 0, DEFAULT);  -- 1951 Best Picture: "A Place in the Sun"
INSERT INTO oscar_given_to VALUES(1958, 1, DEFAULT, 0, DEFAULT);  -- 1951 Best Picture: "Quo Vadis"
INSERT INTO oscar_given_to VALUES(83, 1, DEFAULT, 1, DEFAULT);  -- 1951 Best Picture: "An American in Paris"
INSERT INTO oscar_given_to VALUES(1959, 1, DEFAULT, 0, DEFAULT);  -- 1951 Best Picture: "Decision before Dawn"
INSERT INTO oscar_given_to VALUES(1537, 1, DEFAULT, 0, DEFAULT);  -- 1951 Best Picture: "A Streetcar Named Desire"
INSERT INTO oscar_given_to VALUES(1960, 1, DEFAULT, 0, DEFAULT);  -- 1952 Best Picture: "Moulin Rouge"
INSERT INTO oscar_given_to VALUES(729, 1, DEFAULT, 0, DEFAULT);  -- 1952 Best Picture: "High Noon"
INSERT INTO oscar_given_to VALUES(1961, 1, DEFAULT, 0, DEFAULT);  -- 1952 Best Picture: "Ivanhoe"
INSERT INTO oscar_given_to VALUES(1962, 1, DEFAULT, 0, DEFAULT);  -- 1952 Best Picture: "The Quiet Man"
INSERT INTO oscar_given_to VALUES(1963, 1, DEFAULT, 1, DEFAULT);  -- 1952 Best Picture: "The Greatest Show on Earth"
INSERT INTO oscar_given_to VALUES(1429, 1, DEFAULT, 0, DEFAULT);  -- 1953 Best Picture: "Shane"
INSERT INTO oscar_given_to VALUES(1964, 1, DEFAULT, 0, DEFAULT);  -- 1953 Best Picture: "The Robe"
INSERT INTO oscar_given_to VALUES(1965, 1, DEFAULT, 0, DEFAULT);  -- 1953 Best Picture: "Julius Caesar"
INSERT INTO oscar_given_to VALUES(1810, 1, DEFAULT, 0, DEFAULT);  -- 1953 Best Picture: "Roman Holiday"
INSERT INTO oscar_given_to VALUES(591, 1, DEFAULT, 1, DEFAULT);  -- 1953 Best Picture: "From Here to Eternity"
INSERT INTO oscar_given_to VALUES(1966, 1, DEFAULT, 0, DEFAULT);  -- 1954 Best Picture: "The Country Girl"
INSERT INTO oscar_given_to VALUES(1967, 1, DEFAULT, 0, DEFAULT);  -- 1954 Best Picture: "Seven Brides for Seven Brothers"
INSERT INTO oscar_given_to VALUES(1186, 1, DEFAULT, 1, DEFAULT);  -- 1954 Best Picture: "On the Waterfront"
INSERT INTO oscar_given_to VALUES(1968, 1, DEFAULT, 0, DEFAULT);  -- 1954 Best Picture: "Three Coins in the Fountain"
INSERT INTO oscar_given_to VALUES(1969, 1, DEFAULT, 0, DEFAULT);  -- 1954 Best Picture: "The Caine Mutiny"
INSERT INTO oscar_given_to VALUES(1970, 1, DEFAULT, 0, DEFAULT);  -- 1955 Best Picture: "Love Is a Many-Splendored Thing"
INSERT INTO oscar_given_to VALUES(1971, 1, DEFAULT, 0, DEFAULT);  -- 1955 Best Picture: "Picnic"
INSERT INTO oscar_given_to VALUES(1972, 1, DEFAULT, 0, DEFAULT);  -- 1955 Best Picture: "The Rose Tattoo"
INSERT INTO oscar_given_to VALUES(1973, 1, DEFAULT, 0, DEFAULT);  -- 1955 Best Picture: "Mister Roberts"
INSERT INTO oscar_given_to VALUES(1009, 1, DEFAULT, 1, DEFAULT);  -- 1955 Best Picture: "Marty"
INSERT INTO oscar_given_to VALUES(1974, 1, DEFAULT, 0, DEFAULT);  -- 1956 Best Picture: "The King and I"
INSERT INTO oscar_given_to VALUES(1577, 1, DEFAULT, 0, DEFAULT);  -- 1956 Best Picture: "The Ten Commandments"
INSERT INTO oscar_given_to VALUES(1975, 1, DEFAULT, 1, DEFAULT);  -- 1956 Best Picture: "Around the World in 80 Days"
INSERT INTO oscar_given_to VALUES(620, 1, DEFAULT, 0, DEFAULT);  -- 1956 Best Picture: "Giant"
INSERT INTO oscar_given_to VALUES(1976, 1, DEFAULT, 0, DEFAULT);  -- 1956 Best Picture: "Friendly Persuasion"
INSERT INTO oscar_given_to VALUES(254, 1, DEFAULT, 1, DEFAULT);  -- 1957 Best Picture: "The Bridge on the River Kwai"
INSERT INTO oscar_given_to VALUES(1977, 1, DEFAULT, 0, DEFAULT);  -- 1957 Best Picture: "Witness for the Prosecution"
INSERT INTO oscar_given_to VALUES(1387, 1, DEFAULT, 0, DEFAULT);  -- 1957 Best Picture: "Sayonara"
INSERT INTO oscar_given_to VALUES(6, 1, DEFAULT, 0, DEFAULT);  -- 1957 Best Picture: "12 Angry Men"
INSERT INTO oscar_given_to VALUES(1978, 1, DEFAULT, 0, DEFAULT);  -- 1957 Best Picture: "Peyton Place"
INSERT INTO oscar_given_to VALUES(1979, 1, DEFAULT, 0, DEFAULT);  -- 1958 Best Picture: "The Defiant Ones"
INSERT INTO oscar_given_to VALUES(1980, 1, DEFAULT, 1, DEFAULT);  -- 1958 Best Picture: "Gigi"
INSERT INTO oscar_given_to VALUES(1981, 1, DEFAULT, 0, DEFAULT);  -- 1958 Best Picture: "Auntie Mame"
INSERT INTO oscar_given_to VALUES(295, 1, DEFAULT, 0, DEFAULT);  -- 1958 Best Picture: "Cat on a Hot Tin Roof"
INSERT INTO oscar_given_to VALUES(1982, 1, DEFAULT, 0, DEFAULT);  -- 1958 Best Picture: "Separate Tables"
INSERT INTO oscar_given_to VALUES(1983, 1, DEFAULT, 0, DEFAULT);  -- 1959 Best Picture: "Room at the Top"
INSERT INTO oscar_given_to VALUES(1984, 1, DEFAULT, 0, DEFAULT);  -- 1959 Best Picture: "The Diary of Anne Frank"
INSERT INTO oscar_given_to VALUES(180, 1, DEFAULT, 1, DEFAULT);  -- 1959 Best Picture: "Ben-Hur"
INSERT INTO oscar_given_to VALUES(1985, 1, DEFAULT, 0, DEFAULT);  -- 1959 Best Picture: "The Nun's Story"
INSERT INTO oscar_given_to VALUES(1986, 1, DEFAULT, 0, DEFAULT);  -- 1959 Best Picture: "Anatomy of a Murder"
INSERT INTO oscar_given_to VALUES(1987, 1, DEFAULT, 0, DEFAULT);  -- 1960 Best Picture: "The Sundowners"
INSERT INTO oscar_given_to VALUES(106, 1, DEFAULT, 1, DEFAULT);  -- 1960 Best Picture: "The Apartment"
INSERT INTO oscar_given_to VALUES(1988, 1, DEFAULT, 0, DEFAULT);  -- 1960 Best Picture: "The Alamo"
INSERT INTO oscar_given_to VALUES(499, 1, DEFAULT, 0, DEFAULT);  -- 1960 Best Picture: "Elmer Gantry"
INSERT INTO oscar_given_to VALUES(1989, 1, DEFAULT, 0, DEFAULT);  -- 1960 Best Picture: "Sons and Lovers"
INSERT INTO oscar_given_to VALUES(1990, 1, DEFAULT, 0, DEFAULT);  -- 1961 Best Picture: "Fanny"
INSERT INTO oscar_given_to VALUES(1991, 1, DEFAULT, 0, DEFAULT);  -- 1961 Best Picture: "Judgment at Nuremberg"
INSERT INTO oscar_given_to VALUES(763, 1, DEFAULT, 0, DEFAULT);  -- 1961 Best Picture: "The Hustler"
INSERT INTO oscar_given_to VALUES(1992, 1, DEFAULT, 0, DEFAULT);  -- 1961 Best Picture: "The Guns of Navarone"
INSERT INTO oscar_given_to VALUES(1719, 1, DEFAULT, 1, DEFAULT);  -- 1961 Best Picture: "West Side Story"
INSERT INTO oscar_given_to VALUES(1612, 1, DEFAULT, 0, DEFAULT);  -- 1962 Best Picture: "To Kill a Mockingbird"
INSERT INTO oscar_given_to VALUES(959, 1, DEFAULT, 0, DEFAULT);  -- 1962 Best Picture: "The Longest Day"
INSERT INTO oscar_given_to VALUES(919, 1, DEFAULT, 1, DEFAULT);  -- 1962 Best Picture: "Lawrence of Arabia"
INSERT INTO oscar_given_to VALUES(1109, 1, DEFAULT, 0, DEFAULT);  -- 1962 Best Picture: "The Music Man"
INSERT INTO oscar_given_to VALUES(1112, 1, DEFAULT, 0, DEFAULT);  -- 1962 Best Picture: "Mutiny on the Bounty"
INSERT INTO oscar_given_to VALUES(1993, 1, DEFAULT, 0, DEFAULT);  -- 1963 Best Picture: "How the West Was Won"
INSERT INTO oscar_given_to VALUES(1994, 1, DEFAULT, 0, DEFAULT);  -- 1963 Best Picture: "America America"
INSERT INTO oscar_given_to VALUES(1995, 1, DEFAULT, 0, DEFAULT);  -- 1963 Best Picture: "Lilies of the Field"
INSERT INTO oscar_given_to VALUES(1996, 1, DEFAULT, 0, DEFAULT);  -- 1963 Best Picture: "Cleopatra"
INSERT INTO oscar_given_to VALUES(1997, 1, DEFAULT, 1, DEFAULT);  -- 1963 Best Picture: "Tom Jones"
INSERT INTO oscar_given_to VALUES(1118, 1, DEFAULT, 1, DEFAULT);  -- 1964 Best Picture: "My Fair Lady"
INSERT INTO oscar_given_to VALUES(1998, 1, DEFAULT, 0, DEFAULT);  -- 1964 Best Picture: "Becket"
INSERT INTO oscar_given_to VALUES(1011, 1, DEFAULT, 0, DEFAULT);  -- 1964 Best Picture: "Mary Poppins"
INSERT INTO oscar_given_to VALUES(1999, 1, DEFAULT, 0, DEFAULT);  -- 1964 Best Picture: "Zorba the Greek"
INSERT INTO oscar_given_to VALUES(472, 1, DEFAULT, 0, DEFAULT);  -- 1964 Best Picture: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb"
INSERT INTO oscar_given_to VALUES(399, 1, DEFAULT, 0, DEFAULT);  -- 1965 Best Picture: "Darling"
INSERT INTO oscar_given_to VALUES(1494, 1, DEFAULT, 1, DEFAULT);  -- 1965 Best Picture: "The Sound of Music"
INSERT INTO oscar_given_to VALUES(451, 1, DEFAULT, 0, DEFAULT);  -- 1965 Best Picture: "Doctor Zhivago"
INSERT INTO oscar_given_to VALUES(2000, 1, DEFAULT, 0, DEFAULT);  -- 1965 Best Picture: "A Thousand Clowns"
INSERT INTO oscar_given_to VALUES(2001, 1, DEFAULT, 0, DEFAULT);  -- 1965 Best Picture: "Ship of Fools"
INSERT INTO oscar_given_to VALUES(2002, 1, DEFAULT, 0, DEFAULT);  -- 1966 Best Picture: "The Russians Are Coming The Russians Are Coming"
INSERT INTO oscar_given_to VALUES(1741, 1, DEFAULT, 0, DEFAULT);  -- 1966 Best Picture: "Who's Afraid of Virginia Woolf?"
INSERT INTO oscar_given_to VALUES(2003, 1, DEFAULT, 0, DEFAULT);  -- 1966 Best Picture: "The Sand Pebbles"
INSERT INTO oscar_given_to VALUES(2004, 1, DEFAULT, 1, DEFAULT);  -- 1966 Best Picture: "A Man for All Seasons"
INSERT INTO oscar_given_to VALUES(52, 1, DEFAULT, 0, DEFAULT);  -- 1966 Best Picture: "Alfie"
INSERT INTO oscar_given_to VALUES(659, 1, DEFAULT, 0, DEFAULT);  -- 1967 Best Picture: "The Graduate"
INSERT INTO oscar_given_to VALUES(791, 1, DEFAULT, 1, DEFAULT);  -- 1967 Best Picture: "In the Heat of the Night"
INSERT INTO oscar_given_to VALUES(232, 1, DEFAULT, 0, DEFAULT);  -- 1967 Best Picture: "Bonnie and Clyde"
INSERT INTO oscar_given_to VALUES(683, 1, DEFAULT, 0, DEFAULT);  -- 1967 Best Picture: "Guess Who's Coming to Dinner"
INSERT INTO oscar_given_to VALUES(2005, 1, DEFAULT, 0, DEFAULT);  -- 1967 Best Picture: "Doctor Dolittle"
INSERT INTO oscar_given_to VALUES(2006, 1, DEFAULT, 1, DEFAULT);  -- 1968 Best Picture: "Oliver!"
INSERT INTO oscar_given_to VALUES(2007, 1, DEFAULT, 0, DEFAULT);  -- 1968 Best Picture: "Funny Girl"
INSERT INTO oscar_given_to VALUES(2008, 1, DEFAULT, 0, DEFAULT);  -- 1968 Best Picture: "The Lion in Winter"
INSERT INTO oscar_given_to VALUES(2009, 1, DEFAULT, 0, DEFAULT);  -- 1968 Best Picture: "Rachel, Rachel"
INSERT INTO oscar_given_to VALUES(1360, 1, DEFAULT, 0, DEFAULT);  -- 1968 Best Picture: "Romeo and Juliet"
INSERT INTO oscar_given_to VALUES(1048, 1, DEFAULT, 1, DEFAULT);  -- 1969 Best Picture: "Midnight Cowboy"
INSERT INTO oscar_given_to VALUES(2010, 1, DEFAULT, 0, DEFAULT);  -- 1969 Best Picture: "Anne of the Thousand Days"
INSERT INTO oscar_given_to VALUES(277, 1, DEFAULT, 0, DEFAULT);  -- 1969 Best Picture: "Butch Cassidy and the Sundance Kid"
INSERT INTO oscar_given_to VALUES(2011, 1, DEFAULT, 0, DEFAULT);  -- 1969 Best Picture: "Z"
INSERT INTO oscar_given_to VALUES(2012, 1, DEFAULT, 0, DEFAULT);  -- 1969 Best Picture: "Hello, Dolly!"
INSERT INTO oscar_given_to VALUES(1013, 1, DEFAULT, 0, DEFAULT);  -- 1970 Best Picture: "M*A*S*H"
INSERT INTO oscar_given_to VALUES(971, 1, DEFAULT, 0, DEFAULT);  -- 1970 Best Picture: "Love Story"
INSERT INTO oscar_given_to VALUES(564, 1, DEFAULT, 0, DEFAULT);  -- 1970 Best Picture: "Five Easy Pieces"
INSERT INTO oscar_given_to VALUES(49, 1, DEFAULT, 0, DEFAULT);  -- 1970 Best Picture: "Airport"
INSERT INTO oscar_given_to VALUES(1226, 1, DEFAULT, 1, DEFAULT);  -- 1970 Best Picture: "Patton"
INSERT INTO oscar_given_to VALUES(2013, 1, DEFAULT, 0, DEFAULT);  -- 1971 Best Picture: "Nicholas and Alexandra"
INSERT INTO oscar_given_to VALUES(906, 1, DEFAULT, 0, DEFAULT);  -- 1971 Best Picture: "The Last Picture Show"
INSERT INTO oscar_given_to VALUES(342, 1, DEFAULT, 0, DEFAULT);  -- 1971 Best Picture: "A Clockwork Orange"
INSERT INTO oscar_given_to VALUES(585, 1, DEFAULT, 1, DEFAULT);  -- 1971 Best Picture: "The French Connection"
INSERT INTO oscar_given_to VALUES(2014, 1, DEFAULT, 0, DEFAULT);  -- 1971 Best Picture: "Fiddler on the Roof"
INSERT INTO oscar_given_to VALUES(432, 1, DEFAULT, 0, DEFAULT);  -- 1972 Best Picture: "Deliverance"
INSERT INTO oscar_given_to VALUES(2015, 1, DEFAULT, 0, DEFAULT);  -- 1972 Best Picture: "Cabaret"
INSERT INTO oscar_given_to VALUES(2016, 1, DEFAULT, 0, DEFAULT);  -- 1972 Best Picture: "Sounder"
INSERT INTO oscar_given_to VALUES(2017, 1, DEFAULT, 0, DEFAULT);  -- 1972 Best Picture: "The Emigrants"
INSERT INTO oscar_given_to VALUES(634, 1, DEFAULT, 1, DEFAULT);  -- 1972 Best Picture: "The Godfather"
INSERT INTO oscar_given_to VALUES(1618, 1, DEFAULT, 0, DEFAULT);  -- 1973 Best Picture: "A Touch of Class"
INSERT INTO oscar_given_to VALUES(1530, 1, DEFAULT, 1, DEFAULT);  -- 1973 Best Picture: "The Sting"
INSERT INTO oscar_given_to VALUES(2018, 1, DEFAULT, 0, DEFAULT);  -- 1973 Best Picture: "The Exorcist"
INSERT INTO oscar_given_to VALUES(81, 1, DEFAULT, 0, DEFAULT);  -- 1973 Best Picture: "American Graffiti"
INSERT INTO oscar_given_to VALUES(378, 1, DEFAULT, 0, DEFAULT);  -- 1973 Best Picture: "Cries and Whispers"
INSERT INTO oscar_given_to VALUES(320, 1, DEFAULT, 0, DEFAULT);  -- 1974 Best Picture: "Chinatown"
INSERT INTO oscar_given_to VALUES(1622, 1, DEFAULT, 0, DEFAULT);  -- 1974 Best Picture: "The Towering Inferno"
INSERT INTO oscar_given_to VALUES(928, 1, DEFAULT, 0, DEFAULT);  -- 1974 Best Picture: "Lenny"
INSERT INTO oscar_given_to VALUES(364, 1, DEFAULT, 0, DEFAULT);  -- 1974 Best Picture: "The Conversation"
INSERT INTO oscar_given_to VALUES(635, 1, DEFAULT, 1, DEFAULT);  -- 1974 Best Picture: "The Godfather Part II"
INSERT INTO oscar_given_to VALUES(453, 1, DEFAULT, 0, DEFAULT);  -- 1975 Best Picture: "Dog Day Afternoon"
INSERT INTO oscar_given_to VALUES(1189, 1, DEFAULT, 1, DEFAULT);  -- 1975 Best Picture: "One Flew over the Cuckoo's Nest"
INSERT INTO oscar_given_to VALUES(159, 1, DEFAULT, 0, DEFAULT);  -- 1975 Best Picture: "Barry Lyndon"
INSERT INTO oscar_given_to VALUES(835, 1, DEFAULT, 0, DEFAULT);  -- 1975 Best Picture: "Jaws"
INSERT INTO oscar_given_to VALUES(1139, 1, DEFAULT, 0, DEFAULT);  -- 1975 Best Picture: "Nashville"
INSERT INTO oscar_given_to VALUES(1146, 1, DEFAULT, 0, DEFAULT);  -- 1976 Best Picture: "Network"
INSERT INTO oscar_given_to VALUES(70, 1, DEFAULT, 0, DEFAULT);  -- 1976 Best Picture: "All the President's Men"
INSERT INTO oscar_given_to VALUES(1573, 1, DEFAULT, 0, DEFAULT);  -- 1976 Best Picture: "Taxi Driver"
INSERT INTO oscar_given_to VALUES(1356, 1, DEFAULT, 1, DEFAULT);  -- 1976 Best Picture: "Rocky"
INSERT INTO oscar_given_to VALUES(2019, 1, DEFAULT, 0, DEFAULT);  -- 1976 Best Picture: "Bound for Glory"
INSERT INTO oscar_given_to VALUES(852, 1, DEFAULT, 0, DEFAULT);  -- 1977 Best Picture: "Julia"
INSERT INTO oscar_given_to VALUES(650, 1, DEFAULT, 0, DEFAULT);  -- 1977 Best Picture: "The Goodbye Girl"
INSERT INTO oscar_given_to VALUES(101, 1, DEFAULT, 1, DEFAULT);  -- 1977 Best Picture: "Annie Hall"
INSERT INTO oscar_given_to VALUES(1520, 1, DEFAULT, 0, DEFAULT);  -- 1977 Best Picture: "Star Wars"
INSERT INTO oscar_given_to VALUES(1649, 1, DEFAULT, 0, DEFAULT);  -- 1977 Best Picture: "The Turning Point"
INSERT INTO oscar_given_to VALUES(717, 1, DEFAULT, 0, DEFAULT);  -- 1978 Best Picture: "Heaven Can Wait"
INSERT INTO oscar_given_to VALUES(354, 1, DEFAULT, 0, DEFAULT);  -- 1978 Best Picture: "Coming Home"
INSERT INTO oscar_given_to VALUES(430, 1, DEFAULT, 1, DEFAULT);  -- 1978 Best Picture: "The Deer Hunter"
INSERT INTO oscar_given_to VALUES(1049, 1, DEFAULT, 0, DEFAULT);  -- 1978 Best Picture: "Midnight Express"
INSERT INTO oscar_given_to VALUES(2020, 1, DEFAULT, 0, DEFAULT);  -- 1978 Best Picture: "An Unmarried Woman"
INSERT INTO oscar_given_to VALUES(888, 1, DEFAULT, 1, DEFAULT);  -- 1979 Best Picture: "Kramer vs. Kramer"
INSERT INTO oscar_given_to VALUES(69, 1, DEFAULT, 0, DEFAULT);  -- 1979 Best Picture: "All That Jazz"
INSERT INTO oscar_given_to VALUES(108, 1, DEFAULT, 0, DEFAULT);  -- 1979 Best Picture: "Apocalypse Now"
INSERT INTO oscar_given_to VALUES(250, 1, DEFAULT, 0, DEFAULT);  -- 1979 Best Picture: "Breaking Away"
INSERT INTO oscar_given_to VALUES(1169, 1, DEFAULT, 0, DEFAULT);  -- 1979 Best Picture: "Norma Rae"
INSERT INTO oscar_given_to VALUES(1194, 1, DEFAULT, 1, DEFAULT);  -- 1980 Best Picture: "Ordinary People"
INSERT INTO oscar_given_to VALUES(346, 1, DEFAULT, 0, DEFAULT);  -- 1980 Best Picture: "Coal Miner's Daughter"
INSERT INTO oscar_given_to VALUES(1586, 1, DEFAULT, 0, DEFAULT);  -- 1980 Best Picture: "Tess"
INSERT INTO oscar_given_to VALUES(1307, 1, DEFAULT, 0, DEFAULT);  -- 1980 Best Picture: "Raging Bull"
INSERT INTO oscar_given_to VALUES(495, 1, DEFAULT, 0, DEFAULT);  -- 1980 Best Picture: "The Elephant Man"
INSERT INTO oscar_given_to VALUES(1328, 1, DEFAULT, 0, DEFAULT);  -- 1981 Best Picture: "Reds"
INSERT INTO oscar_given_to VALUES(1308, 1, DEFAULT, 0, DEFAULT);  -- 1981 Best Picture: "Raiders of the Lost Ark"
INSERT INTO oscar_given_to VALUES(310, 1, DEFAULT, 1, DEFAULT);  -- 1981 Best Picture: "Chariots of Fire"
INSERT INTO oscar_given_to VALUES(1184, 1, DEFAULT, 0, DEFAULT);  -- 1981 Best Picture: "On Golden Pond"
INSERT INTO oscar_given_to VALUES(122, 1, DEFAULT, 0, DEFAULT);  -- 1981 Best Picture: "Atlantic City"
INSERT INTO oscar_given_to VALUES(602, 1, DEFAULT, 1, DEFAULT);  -- 1982 Best Picture: "Gandhi"
INSERT INTO oscar_given_to VALUES(1066, 1, DEFAULT, 0, DEFAULT);  -- 1982 Best Picture: "Missing"
INSERT INTO oscar_given_to VALUES(1614, 1, DEFAULT, 0, DEFAULT);  -- 1982 Best Picture: "Tootsie"
INSERT INTO oscar_given_to VALUES(1683, 1, DEFAULT, 0, DEFAULT);  -- 1982 Best Picture: "The Verdict"
INSERT INTO oscar_given_to VALUES(484, 1, DEFAULT, 0, DEFAULT);  -- 1982 Best Picture: "E.T. The Extra-Terrestrial"
INSERT INTO oscar_given_to VALUES(1578, 1, DEFAULT, 0, DEFAULT);  -- 1983 Best Picture: "Tender Mercies"
INSERT INTO oscar_given_to VALUES(1584, 1, DEFAULT, 1, DEFAULT);  -- 1983 Best Picture: "Terms of Endearment"
INSERT INTO oscar_given_to VALUES(193, 1, DEFAULT, 0, DEFAULT);  -- 1983 Best Picture: "The Big Chill"
INSERT INTO oscar_given_to VALUES(477, 1, DEFAULT, 0, DEFAULT);  -- 1983 Best Picture: "The Dresser"
INSERT INTO oscar_given_to VALUES(1345, 1, DEFAULT, 0, DEFAULT);  -- 1983 Best Picture: "The Right Stuff"
INSERT INTO oscar_given_to VALUES(2021, 1, DEFAULT, 0, DEFAULT);  -- 1984 Best Picture: "A Passage to India"
INSERT INTO oscar_given_to VALUES(1253, 1, DEFAULT, 0, DEFAULT);  -- 1984 Best Picture: "Places in the Heart"
INSERT INTO oscar_given_to VALUES(74, 1, DEFAULT, 1, DEFAULT);  -- 1984 Best Picture: "Amadeus"
INSERT INTO oscar_given_to VALUES(874, 1, DEFAULT, 0, DEFAULT);  -- 1984 Best Picture: "The Killing Fields"
INSERT INTO oscar_given_to VALUES(1486, 1, DEFAULT, 0, DEFAULT);  -- 1984 Best Picture: "A Soldier's Story"
INSERT INTO oscar_given_to VALUES(884, 1, DEFAULT, 0, DEFAULT);  -- 1985 Best Picture: "Kiss of the Spider Woman"
INSERT INTO oscar_given_to VALUES(1286, 1, DEFAULT, 0, DEFAULT);  -- 1985 Best Picture: "Prizzi's Honor"
INSERT INTO oscar_given_to VALUES(1201, 1, DEFAULT, 1, DEFAULT);  -- 1985 Best Picture: "Out of Africa"
INSERT INTO oscar_given_to VALUES(352, 1, DEFAULT, 0, DEFAULT);  -- 1985 Best Picture: "The Color Purple"
INSERT INTO oscar_given_to VALUES(1757, 1, DEFAULT, 0, DEFAULT);  -- 1985 Best Picture: "Witness"
INSERT INTO oscar_given_to VALUES(691, 1, DEFAULT, 0, DEFAULT);  -- 1986 Best Picture: "Hannah and Her Sisters"
INSERT INTO oscar_given_to VALUES(1364, 1, DEFAULT, 0, DEFAULT);  -- 1986 Best Picture: "A Room with a View"
INSERT INTO oscar_given_to VALUES(316, 1, DEFAULT, 0, DEFAULT);  -- 1986 Best Picture: "Children of a Lesser God"
INSERT INTO oscar_given_to VALUES(1067, 1, DEFAULT, 0, DEFAULT);  -- 1986 Best Picture: "The Mission"
INSERT INTO oscar_given_to VALUES(1257, 1, DEFAULT, 1, DEFAULT);  -- 1986 Best Picture: "Platoon"
INSERT INTO oscar_given_to VALUES(903, 1, DEFAULT, 1, DEFAULT);  -- 1987 Best Picture: "The Last Emperor"
INSERT INTO oscar_given_to VALUES(743, 1, DEFAULT, 0, DEFAULT);  -- 1987 Best Picture: "Hope and Glory"
INSERT INTO oscar_given_to VALUES(1086, 1, DEFAULT, 0, DEFAULT);  -- 1987 Best Picture: "Moonstruck"
INSERT INTO oscar_given_to VALUES(545, 1, DEFAULT, 0, DEFAULT);  -- 1987 Best Picture: "Fatal Attraction"
INSERT INTO oscar_given_to VALUES(261, 1, DEFAULT, 0, DEFAULT);  -- 1987 Best Picture: "Broadcast News"
INSERT INTO oscar_given_to VALUES(1070, 1, DEFAULT, 0, DEFAULT);  -- 1988 Best Picture: "Mississippi Burning"
INSERT INTO oscar_given_to VALUES(1766, 1, DEFAULT, 0, DEFAULT);  -- 1988 Best Picture: "Working Girl"
INSERT INTO oscar_given_to VALUES(394, 1, DEFAULT, 0, DEFAULT);  -- 1988 Best Picture: "Dangerous Liaisons"
INSERT INTO oscar_given_to VALUES(32, 1, DEFAULT, 0, DEFAULT);  -- 1988 Best Picture: "The Accidental Tourist"
INSERT INTO oscar_given_to VALUES(1309, 1, DEFAULT, 1, DEFAULT);  -- 1988 Best Picture: "Rain Man"
INSERT INTO oscar_given_to VALUES(1122, 1, DEFAULT, 0, DEFAULT);  -- 1989 Best Picture: "My Left Foot"
INSERT INTO oscar_given_to VALUES(552, 1, DEFAULT, 0, DEFAULT);  -- 1989 Best Picture: "Field of Dreams"
INSERT INTO oscar_given_to VALUES(478, 1, DEFAULT, 1, DEFAULT);  -- 1989 Best Picture: "Driving Miss Daisy"
INSERT INTO oscar_given_to VALUES(411, 1, DEFAULT, 0, DEFAULT);  -- 1989 Best Picture: "Dead Poets Society"
INSERT INTO oscar_given_to VALUES(235, 1, DEFAULT, 0, DEFAULT);  -- 1989 Best Picture: "Born on the Fourth of July"
INSERT INTO oscar_given_to VALUES(653, 1, DEFAULT, 0, DEFAULT);  -- 1990 Best Picture: "Goodfellas"
INSERT INTO oscar_given_to VALUES(133, 1, DEFAULT, 0, DEFAULT);  -- 1990 Best Picture: "Awakenings"
INSERT INTO oscar_given_to VALUES(636, 1, DEFAULT, 0, DEFAULT);  -- 1990 Best Picture: "The Godfather, Part III"
INSERT INTO oscar_given_to VALUES(393, 1, DEFAULT, 1, DEFAULT);  -- 1990 Best Picture: "Dances With Wolves"
INSERT INTO oscar_given_to VALUES(615, 1, DEFAULT, 0, DEFAULT);  -- 1990 Best Picture: "Ghost"
INSERT INTO oscar_given_to VALUES(846, 1, DEFAULT, 0, DEFAULT);  -- 1991 Best Picture: "JFK"
INSERT INTO oscar_given_to VALUES(169, 1, DEFAULT, 0, DEFAULT);  -- 1991 Best Picture: "Beauty and the Beast"
INSERT INTO oscar_given_to VALUES(1452, 1, DEFAULT, 1, DEFAULT);  -- 1991 Best Picture: "The Silence of the Lambs"
INSERT INTO oscar_given_to VALUES(272, 1, DEFAULT, 0, DEFAULT);  -- 1991 Best Picture: "Bugsy"
INSERT INTO oscar_given_to VALUES(1280, 1, DEFAULT, 0, DEFAULT);  -- 1991 Best Picture: "The Prince of Tides"
INSERT INTO oscar_given_to VALUES(754, 1, DEFAULT, 0, DEFAULT);  -- 1992 Best Picture: "Howards End"
INSERT INTO oscar_given_to VALUES(388, 1, DEFAULT, 0, DEFAULT);  -- 1992 Best Picture: "The Crying Game"
INSERT INTO oscar_given_to VALUES(1393, 1, DEFAULT, 0, DEFAULT);  -- 1992 Best Picture: "Scent of a Woman"
INSERT INTO oscar_given_to VALUES(1666, 1, DEFAULT, 1, DEFAULT);  -- 1992 Best Picture: "Unforgiven"
INSERT INTO oscar_given_to VALUES(551, 1, DEFAULT, 0, DEFAULT);  -- 1992 Best Picture: "A Few Good Men"
INSERT INTO oscar_given_to VALUES(594, 1, DEFAULT, 0, DEFAULT);  -- 1993 Best Picture: "The Fugitive"
INSERT INTO oscar_given_to VALUES(1394, 1, DEFAULT, 1, DEFAULT);  -- 1993 Best Picture: "Schindler's List"
INSERT INTO oscar_given_to VALUES(793, 1, DEFAULT, 0, DEFAULT);  -- 1993 Best Picture: "In the Name of the Father"
INSERT INTO oscar_given_to VALUES(1242, 1, DEFAULT, 0, DEFAULT);  -- 1993 Best Picture: "The Piano"
INSERT INTO oscar_given_to VALUES(1332, 1, DEFAULT, 0, DEFAULT);  -- 1993 Best Picture: "The Remains of the Day"
INSERT INTO oscar_given_to VALUES(1432, 1, DEFAULT, 0, DEFAULT);  -- 1994 Best Picture: "The Shawshank Redemption"
INSERT INTO oscar_given_to VALUES(1293, 1, DEFAULT, 0, DEFAULT);  -- 1994 Best Picture: "Pulp Fiction"
INSERT INTO oscar_given_to VALUES(1301, 1, DEFAULT, 0, DEFAULT);  -- 1994 Best Picture: "Quiz Show"
INSERT INTO oscar_given_to VALUES(579, 1, DEFAULT, 0, DEFAULT);  -- 1994 Best Picture: "Four Weddings and a Funeral"
INSERT INTO oscar_given_to VALUES(574, 1, DEFAULT, 1, DEFAULT);  -- 1994 Best Picture: "Forrest Gump"
INSERT INTO oscar_given_to VALUES(1412, 1, DEFAULT, 0, DEFAULT);  -- 1995 Best Picture: "Sense and Sensibility"
INSERT INTO oscar_given_to VALUES(246, 1, DEFAULT, 1, DEFAULT);  -- 1995 Best Picture: "Braveheart"
INSERT INTO oscar_given_to VALUES(111, 1, DEFAULT, 0, DEFAULT);  -- 1995 Best Picture: "Apollo 13"
INSERT INTO oscar_given_to VALUES(136, 1, DEFAULT, 0, DEFAULT);  -- 1995 Best Picture: "Babe"
INSERT INTO oscar_given_to VALUES(777, 1, DEFAULT, 0, DEFAULT);  -- 1995 Best Picture: "Il Postino"
INSERT INTO oscar_given_to VALUES(1411, 1, DEFAULT, 0, DEFAULT);  -- 1996 Best Picture: "Secrets & Lies"
INSERT INTO oscar_given_to VALUES(509, 1, DEFAULT, 1, DEFAULT);  -- 1996 Best Picture: "The English Patient"
INSERT INTO oscar_given_to VALUES(541, 1, DEFAULT, 0, DEFAULT);  -- 1996 Best Picture: "Fargo"
INSERT INTO oscar_given_to VALUES(841, 1, DEFAULT, 0, DEFAULT);  -- 1996 Best Picture: "Jerry Maguire"
INSERT INTO oscar_given_to VALUES(1437, 1, DEFAULT, 0, DEFAULT);  -- 1996 Best Picture: "Shine"
INSERT INTO oscar_given_to VALUES(596, 1, DEFAULT, 0, DEFAULT);  -- 1997 Best Picture: "The Full Monty"
INSERT INTO oscar_given_to VALUES(118, 1, DEFAULT, 0, DEFAULT);  -- 1997 Best Picture: "As Good As It Gets"
INSERT INTO oscar_given_to VALUES(890, 1, DEFAULT, 0, DEFAULT);  -- 1997 Best Picture: "L.A. Confidential"
INSERT INTO oscar_given_to VALUES(1610, 1, DEFAULT, 1, DEFAULT);  -- 1997 Best Picture: "Titanic"
INSERT INTO oscar_given_to VALUES(649, 1, DEFAULT, 0, DEFAULT);  -- 1997 Best Picture: "Good Will Hunting"
INSERT INTO oscar_given_to VALUES(497, 1, DEFAULT, 0, DEFAULT);  -- 1998 Best Picture: "Elizabeth"
INSERT INTO oscar_given_to VALUES(1427, 1, DEFAULT, 1, DEFAULT);  -- 1998 Best Picture: "Shakespeare in Love"
INSERT INTO oscar_given_to VALUES(936, 1, DEFAULT, 0, DEFAULT);  -- 1998 Best Picture: "Life Is Beautiful"
INSERT INTO oscar_given_to VALUES(1593, 1, DEFAULT, 0, DEFAULT);  -- 1998 Best Picture: "The Thin Red Line"
INSERT INTO oscar_given_to VALUES(1388, 1, DEFAULT, 0, DEFAULT);  -- 1998 Best Picture: "Saving Private Ryan"
INSERT INTO oscar_given_to VALUES(77, 1, DEFAULT, 1, DEFAULT);  -- 1999 Best Picture: "American Beauty"
INSERT INTO oscar_given_to VALUES(1462, 1, DEFAULT, 0, DEFAULT);  -- 1999 Best Picture: "The Sixth Sense"
INSERT INTO oscar_given_to VALUES(673, 1, DEFAULT, 0, DEFAULT);  -- 1999 Best Picture: "The Green Mile"
INSERT INTO oscar_given_to VALUES(808, 1, DEFAULT, 0, DEFAULT);  -- 1999 Best Picture: "The Insider"
INSERT INTO oscar_given_to VALUES(329, 1, DEFAULT, 0, DEFAULT);  -- 1999 Best Picture: "The Cider House Rules"
INSERT INTO oscar_given_to VALUES(512, 1, DEFAULT, 0, DEFAULT);  -- 2000 Best Picture: "Erin Brockovich"
INSERT INTO oscar_given_to VALUES(382, 1, DEFAULT, 0, DEFAULT);  -- 2000 Best Picture: "Crouching Tiger, Hidden Dragon"
INSERT INTO oscar_given_to VALUES(321, 1, DEFAULT, 0, DEFAULT);  -- 2000 Best Picture: "Chocolat"
INSERT INTO oscar_given_to VALUES(1629, 1, DEFAULT, 0, DEFAULT);  -- 2000 Best Picture: "Traffic"
INSERT INTO oscar_given_to VALUES(627, 1, DEFAULT, 1, DEFAULT);  -- 2000 Best Picture: "Gladiator"
INSERT INTO oscar_given_to VALUES(655, 1, DEFAULT, 0, DEFAULT);  -- 2001 Best Picture: "Gosford Park"
INSERT INTO oscar_given_to VALUES(167, 1, DEFAULT, 1, DEFAULT);  -- 2001 Best Picture: "A Beautiful Mind"
INSERT INTO oscar_given_to VALUES(789, 1, DEFAULT, 0, DEFAULT);  -- 2001 Best Picture: "In the Bedroom"
INSERT INTO oscar_given_to VALUES(1090, 1, DEFAULT, 0, DEFAULT);  -- 2001 Best Picture: "Moulin Rouge"
INSERT INTO oscar_given_to VALUES(961, 1, DEFAULT, 0, DEFAULT);  -- 2001 Best Picture: "The Lord of the Rings: The Fellowship of the Ring"
INSERT INTO oscar_given_to VALUES(603, 1, DEFAULT, 0, DEFAULT);  -- 2002 Best Picture: "Gangs of New York"
INSERT INTO oscar_given_to VALUES(313, 1, DEFAULT, 1, DEFAULT);  -- 2002 Best Picture: "Chicago"
INSERT INTO oscar_given_to VALUES(1241, 1, DEFAULT, 0, DEFAULT);  -- 2002 Best Picture: "The Pianist"
INSERT INTO oscar_given_to VALUES(746, 1, DEFAULT, 0, DEFAULT);  -- 2002 Best Picture: "The Hours"
INSERT INTO oscar_given_to VALUES(962, 1, DEFAULT, 0, DEFAULT);  -- 2002 Best Picture: "The Lord of the Rings: The Two Towers"
INSERT INTO oscar_given_to VALUES(1399, 1, DEFAULT, 0, DEFAULT);  -- 2003 Best Picture: "Seabiscuit"
INSERT INTO oscar_given_to VALUES(1016, 1, DEFAULT, 0, DEFAULT);  -- 2003 Best Picture: "Master and Commander: The Far Side of the World"
INSERT INTO oscar_given_to VALUES(963, 1, DEFAULT, 1, DEFAULT);  -- 2003 Best Picture: "The Lord of the Rings: The Return of the King"
INSERT INTO oscar_given_to VALUES(1134, 1, DEFAULT, 0, DEFAULT);  -- 2003 Best Picture: "Mystic River"
INSERT INTO oscar_given_to VALUES(966, 1, DEFAULT, 0, DEFAULT);  -- 2003 Best Picture: "Lost in Translation"
INSERT INTO oscar_given_to VALUES(2022, 1, DEFAULT, 0, DEFAULT);  -- 2004 Best Picture: "Ray"
INSERT INTO oscar_given_to VALUES(1449, 1, DEFAULT, 0, DEFAULT);  -- 2004 Best Picture: "Sideways"
INSERT INTO oscar_given_to VALUES(132, 1, DEFAULT, 0, DEFAULT);  -- 2004 Best Picture: "The Aviator"
INSERT INTO oscar_given_to VALUES(559, 1, DEFAULT, 0, DEFAULT);  -- 2004 Best Picture: "Finding Neverland"
INSERT INTO oscar_given_to VALUES(1059, 1, DEFAULT, 1, DEFAULT);  -- 2004 Best Picture: "Million Dollar Baby"
INSERT INTO oscar_given_to VALUES(646, 1, DEFAULT, 0, DEFAULT);  -- 2005 Best Picture: "Good Night, and Good Luck."
INSERT INTO oscar_given_to VALUES(2023, 1, DEFAULT, 0, DEFAULT);  -- 2005 Best Picture: "Brokeback Mountain"
INSERT INTO oscar_given_to VALUES(284, 1, DEFAULT, 0, DEFAULT);  -- 2005 Best Picture: "Capote"
INSERT INTO oscar_given_to VALUES(1106, 1, DEFAULT, 0, DEFAULT);  -- 2005 Best Picture: "Munich"
INSERT INTO oscar_given_to VALUES(376, 1, DEFAULT, 1, DEFAULT);  -- 2005 Best Picture: "Crash"
INSERT INTO oscar_given_to VALUES(931, 1, DEFAULT, 0, DEFAULT);  -- 2006 Best Picture: "Letters from Iwo Jima"
INSERT INTO oscar_given_to VALUES(138, 1, DEFAULT, 0, DEFAULT);  -- 2006 Best Picture: "Babel"
INSERT INTO oscar_given_to VALUES(948, 1, DEFAULT, 0, DEFAULT);  -- 2006 Best Picture: "Little Miss Sunshine"
INSERT INTO oscar_given_to VALUES(433, 1, DEFAULT, 1, DEFAULT);  -- 2006 Best Picture: "The Departed"
INSERT INTO oscar_given_to VALUES(1297, 1, DEFAULT, 0, DEFAULT);  -- 2006 Best Picture: "The Queen"
INSERT INTO oscar_given_to VALUES(124, 1, DEFAULT, 0, DEFAULT);  -- 2007 Best Picture: "Atonement"
INSERT INTO oscar_given_to VALUES(857, 1, DEFAULT, 0, DEFAULT);  -- 2007 Best Picture: "Juno"
INSERT INTO oscar_given_to VALUES(1045, 1, DEFAULT, 0, DEFAULT);  -- 2007 Best Picture: "Michael Clayton"
INSERT INTO oscar_given_to VALUES(1165, 1, DEFAULT, 1, DEFAULT);  -- 2007 Best Picture: "No Country for Old Men"
INSERT INTO oscar_given_to VALUES(1590, 1, DEFAULT, 0, DEFAULT);  -- 2007 Best Picture: "There Will Be Blood"
INSERT INTO oscar_given_to VALUES(389, 1, DEFAULT, 0, DEFAULT);  -- 2008 Best Picture: "The Curious Case of Benjamin Button"
INSERT INTO oscar_given_to VALUES(592, 1, DEFAULT, 0, DEFAULT);  -- 2008 Best Picture: "Frost/Nixon"
INSERT INTO oscar_given_to VALUES(2024, 1, DEFAULT, 0, DEFAULT);  -- 2008 Best Picture: "Milk"
INSERT INTO oscar_given_to VALUES(2025, 1, DEFAULT, 0, DEFAULT);  -- 2008 Best Picture: "The Reader"
INSERT INTO oscar_given_to VALUES(1473, 1, DEFAULT, 1, DEFAULT);  -- 2008 Best Picture: "Slumdog Millionaire"
INSERT INTO oscar_given_to VALUES(2026, 2, 385, 1, 0);  -- 1928 Best Actor: Emil Jannings for "The Last Command"
INSERT INTO oscar_given_to VALUES(2027, 2, 385, 1, 0);  -- 1928 Best Actor: Emil Jannings for "The Way of All Flesh"
INSERT INTO oscar_given_to VALUES(2028, 2, 386, 0, 0);  -- 1928 Best Actor: Richard Barthelmess for "The Noose"
INSERT INTO oscar_given_to VALUES(2029, 2, 386, 0, 0);  -- 1928 Best Actor: Richard Barthelmess for "The Patent Leather Kid"
INSERT INTO oscar_given_to VALUES(1815, 2, 387, 0, 0);  -- 1929 Best Actor: Chester Morris for "Alibi"
INSERT INTO oscar_given_to VALUES(2030, 2, 388, 0, 0);  -- 1929 Best Actor: George Bancroft for "Thunderbolt"
INSERT INTO oscar_given_to VALUES(2031, 2, 389, 0, 0);  -- 1929 Best Actor: Paul Muni for "The Valiant"
INSERT INTO oscar_given_to VALUES(1817, 2, 390, 1, 0);  -- 1929 Best Actor: Warner Baxter for "In Old Arizona"
INSERT INTO oscar_given_to VALUES(1819, 2, 391, 0, 0);  -- 1929 Best Actor: Lewis Stone for "The Patriot"
INSERT INTO oscar_given_to VALUES(2032, 2, 392, 0, 0);  -- 1930 Best Actor: Ronald Colman for "Bulldog Drummond"
INSERT INTO oscar_given_to VALUES(2033, 2, 392, 0, 0);  -- 1930 Best Actor: Ronald Colman for "Condemned"
INSERT INTO oscar_given_to VALUES(2034, 2, 393, 0, 0);  -- 1930 Best Actor: Maurice Chevalier for "The Big Pond"
INSERT INTO oscar_given_to VALUES(1820, 2, 393, 0, 0);  -- 1930 Best Actor: Maurice Chevalier for "The Love Parade"
INSERT INTO oscar_given_to VALUES(2035, 2, 394, 0, 0);  -- 1930 Best Actor: Lawrence Tibbett for "The Rogue Song"
INSERT INTO oscar_given_to VALUES(1822, 2, 395, 1, 0);  -- 1930 Best Actor: George Arliss for "Disraeli"
INSERT INTO oscar_given_to VALUES(2036, 2, 395, 0, 0);  -- 1930 Best Actor: George Arliss for "The Green Goddess"
INSERT INTO oscar_given_to VALUES(1821, 2, 396, 0, 0);  -- 1930 Best Actor: Wallace Beery for "The Big House"
INSERT INTO oscar_given_to VALUES(2037, 2, 397, 0, 0);  -- 1931 Best Actor: Fredric March for "The Royal Family of Broadway"
INSERT INTO oscar_given_to VALUES(1824, 2, 398, 0, 0);  -- 1931 Best Actor: Richard Dix for "Cimarron"
INSERT INTO oscar_given_to VALUES(2038, 2, 399, 1, 0);  -- 1931 Best Actor: Lionel Barrymore for "A Free Soul"
INSERT INTO oscar_given_to VALUES(1825, 2, 400, 0, 0);  -- 1931 Best Actor: Adolphe Menjou for "The Front Page"
INSERT INTO oscar_given_to VALUES(1826, 2, 401, 0, 0);  -- 1931 Best Actor: Jackie Cooper for "Skippy"
INSERT INTO oscar_given_to VALUES(2039, 2, 397, 2, 0);  -- 1932 Best Actor: Fredric March for "Dr. Jekyll and Mr. Hyde"
INSERT INTO oscar_given_to VALUES(1836, 2, 396, 2, 0);  -- 1932 Best Actor: Wallace Beery for "The Champ"
INSERT INTO oscar_given_to VALUES(2040, 2, 402, 0, 0);  -- 1932 Best Actor: Alfred Lunt for "The Guardsman"
INSERT INTO oscar_given_to VALUES(1842, 2, 179, 1, 0);  -- 1933 Best Actor: Charles Laughton for "The Private Life of Henry VIII"
INSERT INTO oscar_given_to VALUES(1839, 2, 389, 0, 0);  -- 1933 Best Actor: Paul Muni for "I Am a Fugitive from a Chain Gang"
INSERT INTO oscar_given_to VALUES(2041, 2, 403, 0, 0);  -- 1933 Best Actor: Leslie Howard for "Berkeley Square"
INSERT INTO oscar_given_to VALUES(2042, 2, 404, 0, 0);  -- 1934 Best Actor: Frank Morgan for "The Affairs of Cellini"
INSERT INTO oscar_given_to VALUES(826, 2, 177, 1, 0);  -- 1934 Best Actor: Clark Gable for "It Happened One Night"
INSERT INTO oscar_given_to VALUES(1850, 2, 405, 0, 0);  -- 1934 Best Actor: William Powell for "The Thin Man"
INSERT INTO oscar_given_to VALUES(1868, 2, 406, 1, 0);  -- 1935 Best Actor: Victor McLaglen for "The Informer"
INSERT INTO oscar_given_to VALUES(1111, 2, 407, 0, 0);  -- 1935 Best Actor: Franchot Tone for "Mutiny on the Bounty"
INSERT INTO oscar_given_to VALUES(2043, 2, 389, 0, 0);  -- 1935 Best Actor: Paul Muni for "Black Fury"
INSERT INTO oscar_given_to VALUES(1111, 2, 179, 0, 0);  -- 1935 Best Actor: Charles Laughton for "Mutiny on the Bounty"
INSERT INTO oscar_given_to VALUES(1111, 2, 177, 0, 0);  -- 1935 Best Actor: Clark Gable for "Mutiny on the Bounty"
INSERT INTO oscar_given_to VALUES(1870, 2, 178, 0, 0);  -- 1936 Best Actor: Gary Cooper for "Mr. Deeds Goes to Town"
INSERT INTO oscar_given_to VALUES(1873, 2, 408, 0, 0);  -- 1936 Best Actor: Walter Huston for "Dodsworth"
INSERT INTO oscar_given_to VALUES(1872, 2, 118, 0, 0);  -- 1936 Best Actor: Spencer Tracy for "San Francisco"
INSERT INTO oscar_given_to VALUES(2044, 2, 405, 0, 0);  -- 1936 Best Actor: William Powell for "My Man Godfrey"
INSERT INTO oscar_given_to VALUES(1875, 2, 389, 1, 0);  -- 1936 Best Actor: Paul Muni for "The Story of Louis Pasteur"
INSERT INTO oscar_given_to VALUES(1877, 4, 409, 0, 0);  -- 1936 Best Supporting Actor: Basil Rathbone for "Romeo and Juliet"
INSERT INTO oscar_given_to VALUES(2045, 4, 410, 0, 0);  -- 1936 Best Supporting Actor: Stuart Erwin for "Pigskin Parade"
INSERT INTO oscar_given_to VALUES(2044, 4, 411, 0, 0);  -- 1936 Best Supporting Actor: Mischa Auer for "My Man Godfrey"
INSERT INTO oscar_given_to VALUES(2046, 4, 412, 1, 0);  -- 1936 Best Supporting Actor: Walter Brennan for "Come and Get It"
INSERT INTO oscar_given_to VALUES(2047, 4, 413, 0, 0);  -- 1936 Best Supporting Actor: Akim Tamiroff for "The General Died at Dawn"
INSERT INTO oscar_given_to VALUES(1879, 2, 397, 0, 0);  -- 1937 Best Actor: Fredric March for "A Star Is Born"
INSERT INTO oscar_given_to VALUES(2048, 2, 414, 0, 0);  -- 1937 Best Actor: Charles Boyer for "Conquest"
INSERT INTO oscar_given_to VALUES(2049, 2, 415, 0, 0);  -- 1937 Best Actor: Robert Montgomery for "Night Must Fall"
INSERT INTO oscar_given_to VALUES(285, 2, 118, 1, 0);  -- 1937 Best Actor: Spencer Tracy for "Captains Courageous"
INSERT INTO oscar_given_to VALUES(1885, 2, 389, 0, 0);  -- 1937 Best Actor: Paul Muni for "The Life of Emile Zola"
INSERT INTO oscar_given_to VALUES(1885, 4, 416, 1, 0);  -- 1937 Best Supporting Actor: Joseph Schildkraut for "The Life of Emile Zola"
INSERT INTO oscar_given_to VALUES(1880, 4, 417, 0, 0);  -- 1937 Best Supporting Actor: Ralph Bellamy for "The Awful Truth"
INSERT INTO oscar_given_to VALUES(2050, 4, 418, 0, 0);  -- 1937 Best Supporting Actor: Thomas Mitchell for "The Hurricane"
INSERT INTO oscar_given_to VALUES(1887, 4, 419, 0, 0);  -- 1937 Best Supporting Actor: H. B. Warner for "Lost Horizon"
INSERT INTO oscar_given_to VALUES(2051, 4, 420, 0, 0);  -- 1937 Best Supporting Actor: Roland Young for "Topper"
INSERT INTO oscar_given_to VALUES(1892, 2, 403, 0, 0);  -- 1938 Best Actor: Leslie Howard for "Pygmalion"
INSERT INTO oscar_given_to VALUES(1891, 2, 118, 1, 0);  -- 1938 Best Actor: Spencer Tracy for "Boys Town"
INSERT INTO oscar_given_to VALUES(1888, 2, 421, 0, 0);  -- 1938 Best Actor: Robert Donat for "The Citadel"
INSERT INTO oscar_given_to VALUES(2052, 2, 176, 0, 0);  -- 1938 Best Actor: James Cagney for "Angels with Dirty Faces"
INSERT INTO oscar_given_to VALUES(2053, 2, 414, 0, 0);  -- 1938 Best Actor: Charles Boyer for "Algiers"
INSERT INTO oscar_given_to VALUES(2054, 4, 409, 0, 0);  -- 1938 Best Supporting Actor: Basil Rathbone for "If I Were King"
INSERT INTO oscar_given_to VALUES(2053, 4, 422, 0, 0);  -- 1938 Best Supporting Actor: Gene Lockhart for "Algiers"
INSERT INTO oscar_given_to VALUES(1893, 4, 423, 0, 0);  -- 1938 Best Supporting Actor: John Garfield for "Four Daughters"
INSERT INTO oscar_given_to VALUES(2055, 4, 412, 1, 0);  -- 1938 Best Supporting Actor: Walter Brennan for "Kentucky"
INSERT INTO oscar_given_to VALUES(2056, 4, 424, 0, 0);  -- 1938 Best Supporting Actor: Robert Morley for "Marie Antoinette"
INSERT INTO oscar_given_to VALUES(644, 2, 177, 0, 0);  -- 1939 Best Actor: Clark Gable for "Gone with the Wind"
INSERT INTO oscar_given_to VALUES(1099, 2, 23, 0, 0);  -- 1939 Best Actor: Jimmy Stewart for "Mr. Smith Goes to Washington"
INSERT INTO oscar_given_to VALUES(1771, 2, 119, 0, 0);  -- 1939 Best Actor: Laurence Olivier for "Wuthering Heights"
INSERT INTO oscar_given_to VALUES(1899, 2, 421, 1, 0);  -- 1939 Best Actor: Robert Donat for "Goodbye, Mr. Chips"
INSERT INTO oscar_given_to VALUES(2057, 2, 425, 0, 0);  -- 1939 Best Actor: Mickey Rooney for "Babes in Arms"
INSERT INTO oscar_given_to VALUES(1099, 4, 426, 0, 0);  -- 1939 Best Supporting Actor: Claude Rains for "Mr. Smith Goes to Washington"
INSERT INTO oscar_given_to VALUES(2058, 4, 427, 0, 0);  -- 1939 Best Supporting Actor: Brian Donlevy for "Beau Geste"
INSERT INTO oscar_given_to VALUES(1511, 4, 418, 1, 0);  -- 1939 Best Supporting Actor: Thomas Mitchell for "Stagecoach"
INSERT INTO oscar_given_to VALUES(2059, 4, 428, 0, 0);  -- 1939 Best Supporting Actor: Brian Aherne for "Juarez"
INSERT INTO oscar_given_to VALUES(1099, 4, 429, 0, 0);  -- 1939 Best Supporting Actor: Harry Carey for "Mr. Smith Goes to Washington"
INSERT INTO oscar_given_to VALUES(1320, 2, 119, 0, 0);  -- 1940 Best Actor: Laurence Olivier for "Rebecca"
INSERT INTO oscar_given_to VALUES(2060, 2, 430, 0, 0);  -- 1940 Best Actor: Raymond Massey for "Abe Lincoln in Illinois"
INSERT INTO oscar_given_to VALUES(667, 2, 266, 0, 0);  -- 1940 Best Actor: Charlie Chaplin for "The Great Dictator"
INSERT INTO oscar_given_to VALUES(1238, 2, 23, 1, 0);  -- 1940 Best Actor: Jimmy Stewart for "The Philadelphia Story"
INSERT INTO oscar_given_to VALUES(663, 2, 66, 0, 0);  -- 1940 Best Actor: Henry Fonda for "The Grapes of Wrath"
INSERT INTO oscar_given_to VALUES(667, 4, 431, 0, 0);  -- 1940 Best Supporting Actor: Jack Oakie for "The Great Dictator"
INSERT INTO oscar_given_to VALUES(1904, 4, 432, 0, 0);  -- 1940 Best Supporting Actor: James Stephenson for "The Letter"
INSERT INTO oscar_given_to VALUES(2061, 4, 412, 1, 0);  -- 1940 Best Supporting Actor: Walter Brennan for "The Westerner"
INSERT INTO oscar_given_to VALUES(2062, 4, 433, 0, 0);  -- 1940 Best Supporting Actor: William Gargan for "They Knew What They Wanted"
INSERT INTO oscar_given_to VALUES(1900, 4, 434, 0, 0);  -- 1940 Best Supporting Actor: Albert Bassermann for "Foreign Correspondent"
INSERT INTO oscar_given_to VALUES(2063, 2, 408, 0, 0);  -- 1941 Best Actor: Walter Huston for "The Devil and Daniel Webster"
INSERT INTO oscar_given_to VALUES(333, 2, 19, 0, 0);  -- 1941 Best Actor: Orson Welles for "Citizen Kane"
INSERT INTO oscar_given_to VALUES(1908, 2, 415, 0, 0);  -- 1941 Best Actor: Robert Montgomery for "Here Comes Mr. Jordan"
INSERT INTO oscar_given_to VALUES(1912, 2, 178, 1, 0);  -- 1941 Best Actor: Gary Cooper for "Sergeant York"
INSERT INTO oscar_given_to VALUES(2064, 2, 24, 0, 0);  -- 1941 Best Actor: Cary Grant for "Penny Serenade"
INSERT INTO oscar_given_to VALUES(988, 4, 435, 0, 0);  -- 1941 Best Supporting Actor: Sydney Greenstreet for "The Maltese Falcon"
INSERT INTO oscar_given_to VALUES(1913, 4, 436, 1, 0);  -- 1941 Best Supporting Actor: Donald Crisp for "How Green Was My Valley"
INSERT INTO oscar_given_to VALUES(2065, 4, 437, 0, 0);  -- 1941 Best Supporting Actor: Charles Coburn for "The Devil and Miss Jones"
INSERT INTO oscar_given_to VALUES(1912, 4, 412, 0, 0);  -- 1941 Best Supporting Actor: Walter Brennan for "Sergeant York"
INSERT INTO oscar_given_to VALUES(1908, 4, 438, 0, 0);  -- 1941 Best Supporting Actor: James Gleason for "Here Comes Mr. Jordan"
INSERT INTO oscar_given_to VALUES(1779, 2, 176, 1, 0);  -- 1942 Best Actor: James Cagney for "Yankee Doodle Dandy"
INSERT INTO oscar_given_to VALUES(1914, 2, 439, 0, 0);  -- 1942 Best Actor: Monty Woolley for "The Pied Piper"
INSERT INTO oscar_given_to VALUES(1919, 2, 392, 0, 0);  -- 1942 Best Actor: Ronald Colman for "Random Harvest"
INSERT INTO oscar_given_to VALUES(1915, 2, 178, 0, 0);  -- 1942 Best Actor: Gary Cooper for "The Pride of the Yankees"
INSERT INTO oscar_given_to VALUES(1921, 2, 440, 0, 0);  -- 1942 Best Actor: Walter Pidgeon for "Mrs. Miniver"
INSERT INTO oscar_given_to VALUES(1921, 4, 441, 0, 0);  -- 1942 Best Supporting Actor: Henry Travers for "Mrs. Miniver"
INSERT INTO oscar_given_to VALUES(2066, 4, 404, 0, 0);  -- 1942 Best Supporting Actor: Frank Morgan for "Tortilla Flat"
INSERT INTO oscar_given_to VALUES(1920, 4, 442, 0, 0);  -- 1942 Best Supporting Actor: William Bendix for "Wake Island"
INSERT INTO oscar_given_to VALUES(2067, 4, 443, 1, 0);  -- 1942 Best Supporting Actor: Van Heflin for "Johnny Eager"
INSERT INTO oscar_given_to VALUES(1779, 4, 408, 0, 0);  -- 1942 Best Supporting Actor: Walter Huston for "Yankee Doodle Dandy"
INSERT INTO oscar_given_to VALUES(1923, 2, 440, 0, 0);  -- 1943 Best Actor: Walter Pidgeon for "Madame Curie"
INSERT INTO oscar_given_to VALUES(289, 2, 22, 0, 0);  -- 1943 Best Actor: Humphrey Bogart for "Casablanca"
INSERT INTO oscar_given_to VALUES(1930, 2, 444, 1, 0);  -- 1943 Best Actor: Paul Lukas for "Watch on the Rhine"
INSERT INTO oscar_given_to VALUES(1925, 2, 178, 0, 0);  -- 1943 Best Actor: Gary Cooper for "For Whom the Bell Tolls"
INSERT INTO oscar_given_to VALUES(1929, 2, 425, 0, 0);  -- 1943 Best Actor: Mickey Rooney for "The Human Comedy"
INSERT INTO oscar_given_to VALUES(2068, 4, 445, 0, 0);  -- 1943 Best Supporting Actor: J. Carrol Naish for "Sahara"
INSERT INTO oscar_given_to VALUES(289, 4, 426, 0, 0);  -- 1943 Best Supporting Actor: Claude Rains for "Casablanca"
INSERT INTO oscar_given_to VALUES(1925, 4, 413, 0, 0);  -- 1943 Best Supporting Actor: Akim Tamiroff for "For Whom the Bell Tolls"
INSERT INTO oscar_given_to VALUES(1926, 4, 437, 1, 0);  -- 1943 Best Supporting Actor: Charles Coburn for "The More the Merrier"
INSERT INTO oscar_given_to VALUES(1927, 4, 446, 0, 0);  -- 1943 Best Supporting Actor: Charles Bickford for "The Song of Bernadette"
INSERT INTO oscar_given_to VALUES(2069, 2, 24, 0, 0);  -- 1944 Best Actor: Cary Grant for "None but the Lonely Heart"
INSERT INTO oscar_given_to VALUES(1934, 2, 447, 1, 0);  -- 1944 Best Actor: Bing Crosby for "Going My Way"
INSERT INTO oscar_given_to VALUES(1934, 2, 448, 0, 0);  -- 1944 Best Actor: Barry Fitzgerald for "Going My Way"
INSERT INTO oscar_given_to VALUES(1932, 2, 449, 0, 0);  -- 1944 Best Actor: Alexander Knox for "Wilson"
INSERT INTO oscar_given_to VALUES(1931, 2, 414, 0, 0);  -- 1944 Best Actor: Charles Boyer for "Gaslight"
INSERT INTO oscar_given_to VALUES(916, 4, 450, 0, 0);  -- 1944 Best Supporting Actor: Clifton Webb for "Laura"
INSERT INTO oscar_given_to VALUES(2070, 4, 426, 0, 0);  -- 1944 Best Supporting Actor: Claude Rains for "Mr. Skeffington"
INSERT INTO oscar_given_to VALUES(2071, 4, 451, 0, 0);  -- 1944 Best Supporting Actor: Hume Cronyn for "The Seventh Cross"
INSERT INTO oscar_given_to VALUES(1934, 4, 448, 1, 0);  -- 1944 Best Supporting Actor: Barry Fitzgerald for "Going My Way"
INSERT INTO oscar_given_to VALUES(1933, 4, 439, 0, 0);  -- 1944 Best Supporting Actor: Monty Woolley for "Since You Went Away"
INSERT INTO oscar_given_to VALUES(1936, 2, 452, 0, 0);  -- 1945 Best Actor: Gene Kelly for "Anchors Aweigh"
INSERT INTO oscar_given_to VALUES(1935, 2, 453, 1, 0);  -- 1945 Best Actor: Ray Milland for "The Lost Weekend"
INSERT INTO oscar_given_to VALUES(1938, 2, 447, 0, 0);  -- 1945 Best Actor: Bing Crosby for "The Bells of St. Mary's"
INSERT INTO oscar_given_to VALUES(2072, 2, 454, 0, 0);  -- 1945 Best Actor: Cornel Wilde for "A Song to Remember"
INSERT INTO oscar_given_to VALUES(2073, 2, 180, 0, 0);  -- 1945 Best Actor: Gregory Peck for "The Keys of the Kingdom"
INSERT INTO oscar_given_to VALUES(2074, 4, 455, 0, 0);  -- 1945 Best Supporting Actor: John Dall for "The Corn Is Green"
INSERT INTO oscar_given_to VALUES(2075, 4, 25, 0, 0);  -- 1945 Best Supporting Actor: Robert Mitchum for "The Story of G. I. Joe"
INSERT INTO oscar_given_to VALUES(2076, 4, 456, 1, 0);  -- 1945 Best Supporting Actor: James Dunn for "A Tree Grows in Brooklyn"
INSERT INTO oscar_given_to VALUES(1503, 4, 457, 0, 0);  -- 1945 Best Supporting Actor: Michael Chekhov for "Spellbound"
INSERT INTO oscar_given_to VALUES(2077, 4, 445, 0, 0);  -- 1945 Best Supporting Actor: J. Carrol Naish for "A Medal for Benny"
INSERT INTO oscar_given_to VALUES(1939, 2, 180, 0, 0);  -- 1946 Best Actor: Gregory Peck for "The Yearling"
INSERT INTO oscar_given_to VALUES(1940, 2, 119, 0, 0);  -- 1946 Best Actor: Laurence Olivier for "Henry V"
INSERT INTO oscar_given_to VALUES(828, 2, 23, 0, 0);  -- 1946 Best Actor: Jimmy Stewart for "It's a Wonderful Life"
INSERT INTO oscar_given_to VALUES(2078, 2, 458, 0, 0);  -- 1946 Best Actor: Larry Parks for "The Jolson Story"
INSERT INTO oscar_given_to VALUES(186, 2, 397, 1, 0);  -- 1946 Best Actor: Fredric March for "The Best Years of Our Lives"
INSERT INTO oscar_given_to VALUES(186, 4, 459, 1, 0);  -- 1946 Best Supporting Actor: Harold Russell for "The Best Years of Our Lives"
INSERT INTO oscar_given_to VALUES(1174, 4, 426, 0, 0);  -- 1946 Best Supporting Actor: Claude Rains for "Notorious"
INSERT INTO oscar_given_to VALUES(1941, 4, 450, 0, 0);  -- 1946 Best Supporting Actor: Clifton Webb for "The Razor's Edge"
INSERT INTO oscar_given_to VALUES(2078, 4, 460, 0, 0);  -- 1946 Best Supporting Actor: William Demarest for "The Jolson Story"
INSERT INTO oscar_given_to VALUES(2079, 4, 437, 0, 0);  -- 1946 Best Supporting Actor: Charles Coburn for "The Green Years"
INSERT INTO oscar_given_to VALUES(2080, 2, 405, 0, 0);  -- 1947 Best Actor: William Powell for "Life with Father"
INSERT INTO oscar_given_to VALUES(2081, 2, 423, 0, 0);  -- 1947 Best Actor: John Garfield for "Body and Soul"
INSERT INTO oscar_given_to VALUES(1945, 2, 180, 0, 0);  -- 1947 Best Actor: Gregory Peck for "Gentleman's Agreement"
INSERT INTO oscar_given_to VALUES(2082, 2, 392, 1, 0);  -- 1947 Best Actor: Ronald Colman for "A Double Life"
INSERT INTO oscar_given_to VALUES(2083, 2, 461, 0, 0);  -- 1947 Best Actor: Michael Redgrave for "Mourning Becomes Electra"
INSERT INTO oscar_given_to VALUES(2084, 4, 462, 0, 0);  -- 1947 Best Supporting Actor: Thomas Gomez for "Ride the Pink Horse"
INSERT INTO oscar_given_to VALUES(2085, 4, 463, 0, 0);  -- 1947 Best Supporting Actor: Richard Widmark for "Kiss of Death"
INSERT INTO oscar_given_to VALUES(1943, 4, 464, 0, 0);  -- 1947 Best Supporting Actor: Robert Ryan for "Crossfire"
INSERT INTO oscar_given_to VALUES(2086, 4, 446, 0, 0);  -- 1947 Best Supporting Actor: Charles Bickford for "The Farmer's Daughter"
INSERT INTO oscar_given_to VALUES(1942, 4, 465, 1, 0);  -- 1947 Best Supporting Actor: Edmund Gwenn for "Miracle on 34th Street"
INSERT INTO oscar_given_to VALUES(1949, 2, 119, 1, 0);  -- 1948 Best Actor: Laurence Olivier for "Hamlet"
INSERT INTO oscar_given_to VALUES(2087, 2, 450, 0, 0);  -- 1948 Best Actor: Clifton Webb for "Sitting Pretty"
INSERT INTO oscar_given_to VALUES(1946, 2, 466, 0, 0);  -- 1948 Best Actor: Lew Ayres for "Johnny Belinda"
INSERT INTO oscar_given_to VALUES(2088, 2, 181, 0, 0);  -- 1948 Best Actor: Montgomery Clift for "The Search"
INSERT INTO oscar_given_to VALUES(2089, 2, 467, 0, 0);  -- 1948 Best Actor: Dan Dailey for "When My Baby Smiles at Me"
INSERT INTO oscar_given_to VALUES(2090, 4, 468, 0, 0);  -- 1948 Best Supporting Actor: Oscar Homolka for "I Remember Mama"
INSERT INTO oscar_given_to VALUES(2091, 4, 469, 0, 0);  -- 1948 Best Supporting Actor: Jose Ferrer for "Joan of Arc"
INSERT INTO oscar_given_to VALUES(1634, 4, 408, 1, 0);  -- 1948 Best Supporting Actor: Walter Huston for "The Treasure of the Sierra Madre"
INSERT INTO oscar_given_to VALUES(1946, 4, 446, 0, 0);  -- 1948 Best Supporting Actor: Charles Bickford for "Johnny Belinda"
INSERT INTO oscar_given_to VALUES(2092, 4, 470, 0, 0);  -- 1948 Best Supporting Actor: Cecil Kellaway for "The Luck of the Irish"
INSERT INTO oscar_given_to VALUES(305, 2, 78, 0, 0);  -- 1949 Best Actor: Kirk Douglas for "Champion"
INSERT INTO oscar_given_to VALUES(2093, 2, 471, 0, 0);  -- 1949 Best Actor: Richard Todd for "The Hasty Heart"
INSERT INTO oscar_given_to VALUES(1950, 2, 472, 1, 0);  -- 1949 Best Actor: Broderick Crawford for "All the King's Men"
INSERT INTO oscar_given_to VALUES(1951, 2, 180, 0, 0);  -- 1949 Best Actor: Gregory Peck for "Twelve O'Clock High"
INSERT INTO oscar_given_to VALUES(2094, 2, 65, 0, 0);  -- 1949 Best Actor: John Wayne for "Sands of Iwo Jima"
INSERT INTO oscar_given_to VALUES(305, 4, 473, 0, 0);  -- 1949 Best Supporting Actor: Arthur Kennedy for "Champion"
INSERT INTO oscar_given_to VALUES(1950, 4, 474, 0, 0);  -- 1949 Best Supporting Actor: John Ireland for "All the King's Men"
INSERT INTO oscar_given_to VALUES(1953, 4, 475, 0, 0);  -- 1949 Best Supporting Actor: Ralph Richardson for "The Heiress"
INSERT INTO oscar_given_to VALUES(1952, 4, 476, 0, 0);  -- 1949 Best Supporting Actor: James Whitmore for "Battleground"
INSERT INTO oscar_given_to VALUES(1951, 4, 477, 1, 0);  -- 1949 Best Supporting Actor: Dean Jagger for "Twelve O'Clock High"
INSERT INTO oscar_given_to VALUES(1957, 2, 118, 0, 0);  -- 1950 Best Actor: Spencer Tracy for "Father of the Bride"
INSERT INTO oscar_given_to VALUES(711, 2, 23, 0, 0);  -- 1950 Best Actor: Jimmy Stewart for "Harvey"
INSERT INTO oscar_given_to VALUES(1546, 2, 182, 0, 0);  -- 1950 Best Actor: William Holden for "Sunset Boulevard"
INSERT INTO oscar_given_to VALUES(1252, 2, 181, 0, 0);  -- 1951 Best Actor: Montgomery Clift for "A Place in the Sun"
INSERT INTO oscar_given_to VALUES(1537, 2, 2, 0, 0);  -- 1951 Best Actor: Marlon Brando for "A Streetcar Named Desire"
INSERT INTO oscar_given_to VALUES(42, 2, 22, 1, 0);  -- 1951 Best Actor: Humphrey Bogart for "The African Queen"
INSERT INTO oscar_given_to VALUES(144, 2, 78, 0, 0);  -- 1952 Best Actor: Kirk Douglas for "The Bad and the Beautiful"
INSERT INTO oscar_given_to VALUES(1960, 2, 469, 0, 0);  -- 1952 Best Actor: Jose Ferrer for "Moulin Rouge"
INSERT INTO oscar_given_to VALUES(1692, 2, 2, 0, 0);  -- 1952 Best Actor: Marlon Brando for "Viva Zapata!"
INSERT INTO oscar_given_to VALUES(729, 2, 178, 1, 0);  -- 1952 Best Actor: Gary Cooper for "High Noon"
INSERT INTO oscar_given_to VALUES(1962, 4, 406, 0, 0);  -- 1952 Best Supporting Actor: Victor McLaglen for "The Quiet Man"
INSERT INTO oscar_given_to VALUES(591, 2, 181, 0, 0);  -- 1953 Best Actor: Montgomery Clift for "From Here to Eternity"
INSERT INTO oscar_given_to VALUES(1965, 2, 2, 0, 0);  -- 1953 Best Actor: Marlon Brando for "Julius Caesar"
INSERT INTO oscar_given_to VALUES(1964, 2, 192, 0, 0);  -- 1953 Best Actor: Richard Burton for "The Robe"
INSERT INTO oscar_given_to VALUES(591, 2, 183, 0, 0);  -- 1953 Best Actor: Burt Lancaster for "From Here to Eternity"
INSERT INTO oscar_given_to VALUES(1429, 4, 185, 0, 0);  -- 1953 Best Supporting Actor: Jack Palance for "Shane"
INSERT INTO oscar_given_to VALUES(591, 4, 186, 1, 0);  -- 1953 Best Supporting Actor: Frank Sinatra for "From Here to Eternity"
INSERT INTO oscar_given_to VALUES(1186, 2, 2, 1, 0);  -- 1954 Best Actor: Marlon Brando for "On the Waterfront"
INSERT INTO oscar_given_to VALUES(1969, 2, 22, 0, 0);  -- 1954 Best Actor: Humphrey Bogart for "The Caine Mutiny"
INSERT INTO oscar_given_to VALUES(1966, 2, 447, 0, 0);  -- 1954 Best Actor: Bing Crosby for "The Country Girl"
INSERT INTO oscar_given_to VALUES(1186, 4, 191, 0, 0);  -- 1954 Best Supporting Actor: Rod Steiger for "On the Waterfront"
