INSERT INTO oscar VALUES (DEFAULT, 'Best Picture');
INSERT INTO oscar VALUES (DEFAULT, 'Best Actor');
INSERT INTO oscar VALUES (DEFAULT, 'Best Actress');
INSERT INTO oscar VALUES (DEFAULT, 'Best Supporting Actor');
INSERT INTO oscar VALUES (DEFAULT, 'Best Supporting Actress');
INSERT INTO oscar VALUES (DEFAULT, 'Best Director');
INSERT INTO oscar VALUES (DEFAULT, 'Best Cinematography (black and white)');
INSERT INTO oscar VALUES (DEFAULT, 'Best Cinematography (color)');
INSERT INTO oscar VALUES (DEFAULT, 'Best Cinematography');
INSERT INTO oscar VALUES (DEFAULT, 'Best Adapted Screenplay');
INSERT INTO oscar VALUES (DEFAULT, 'Best Original Screenplay');
INSERT INTO oscar VALUES (DEFAULT, 'Best Foreign Language Film');
INSERT INTO oscar VALUES (DEFAULT, 'Best Documentary');
