INSERT INTO position VALUES('Actor');
INSERT INTO position VALUES('Actress');
INSERT INTO position VALUES('Cinematographer');
INSERT INTO position VALUES('Director');
INSERT INTO position VALUES('Screenwriter');
INSERT INTO position VALUES('Producer');
INSERT INTO position VALUES('Character Voice');
INSERT INTO position VALUES('Narrator');
INSERT INTO position VALUES('Lead Actor');
INSERT INTO position VALUES('Supporting Actor');
INSERT INTO position VALUES('Lead Actress');
INSERT INTO position VALUES('Supporting Actress');
INSERT INTO position VALUES('Small Part');
INSERT INTO position VALUES('Cameo');
INSERT INTO position VALUES('Editor');
