INSERT INTO filth.position VALUES('Actor');
INSERT INTO filth.position VALUES('Actress');
INSERT INTO filth.position VALUES('Cinematographer');
INSERT INTO filth.position VALUES('Director');
INSERT INTO filth.position VALUES('Screenwriter');
INSERT INTO filth.position VALUES('Producer');
INSERT INTO filth.position VALUES('Character Voice');
INSERT INTO filth.position VALUES('Narrator');
INSERT INTO filth.position VALUES('Lead Actor');
INSERT INTO filth.position VALUES('Supporting Actor');
INSERT INTO filth.position VALUES('Lead Actress');
INSERT INTO filth.position VALUES('Supporting Actress');
INSERT INTO filth.position VALUES('Small Part');
INSERT INTO filth.position VALUES('Cameo');
INSERT INTO filth.position VALUES('Editor');
