INSERT INTO star_rating VALUES('not seen');
INSERT INTO star_rating VALUES('N/A');
INSERT INTO star_rating VALUES('NO STARS');
INSERT INTO star_rating VALUES('½*');
INSERT INTO star_rating VALUES('*');
INSERT INTO star_rating VALUES('*½');
INSERT INTO star_rating VALUES('**');
INSERT INTO star_rating VALUES('**½');
INSERT INTO star_rating VALUES('***');
INSERT INTO star_rating VALUES('***½');
INSERT INTO star_rating VALUES('****');
