INSERT INTO filth.star_rating VALUES(1, 'not seen');
INSERT INTO filth.star_rating VALUES(2, 'N/A');
INSERT INTO filth.star_rating VALUES(3, 'NO STARS');
INSERT INTO filth.star_rating VALUES(4, '½*');
INSERT INTO filth.star_rating VALUES(5, '*');
INSERT INTO filth.star_rating VALUES(6, '*½');
INSERT INTO filth.star_rating VALUES(7, '**');
INSERT INTO filth.star_rating VALUES(8, '**½');
INSERT INTO filth.star_rating VALUES(9, '***');
INSERT INTO filth.star_rating VALUES(10, '***½');
INSERT INTO filth.star_rating VALUES(11, '****');
