INSERT INTO tag_given_to VALUES(285, 59);  -- Cape Fear (1962) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(285, 58);  -- Cape Fear (1962) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(1175, 59);  -- Night at the Museum (2007) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(1175, 58);  -- Night at the Museum (2007) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(1626, 61);  -- Thirty Two Short Films About Glenn Gould (1994) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(1112, 2);  -- Mr. & Mrs. Smith (2005) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(1226, 59);  -- Owning Mahowny (2003) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(1226, 58);  -- Owning Mahowny (2003) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3508, 59);  -- The Hunger Games: Catching Fire (2013) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3508, 58);  -- The Hunger Games: Catching Fire (2013) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(38, 57);  -- The Adventures of Baron Munchausen (1989) tagged with 'remake'
INSERT INTO tag_given_to VALUES(48, 307);  -- Airplane! (1980) tagged with 'spoof'
INSERT INTO tag_given_to VALUES(49, 60);  -- Airport (1970) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(49, 59);  -- Airport (1970) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(49, 58);  -- Airport (1970) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(51, 57);  -- The Alamo (2004) tagged with 'remake'
INSERT INTO tag_given_to VALUES(52, 59);  -- Alfie (1966) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(52, 58);  -- Alfie (1966) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(51, 117);  -- The Alamo (2004) tagged with '19th-century'
INSERT INTO tag_given_to VALUES(51, 21);  -- The Alamo (2004) tagged with 'period'
INSERT INTO tag_given_to VALUES(53, 105);  -- Ali (2001) tagged with 'boxing'
INSERT INTO tag_given_to VALUES(55, 2);  -- Alice (1990) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(57, 59);  -- Alice in Wonderland (1951) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(57, 58);  -- Alice in Wonderland (1951) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(58, 59);  -- Alice in Wonderland (2010) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(58, 58);  -- Alice in Wonderland (2010) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(59, 299);  -- Alien (1979) tagged with 'future'
INSERT INTO tag_given_to VALUES(59, 302);  -- Alien (1979) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(59, 284);  -- Alien (1979) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(60, 299);  -- Alien: The Director's Cut (2003) tagged with 'future'
INSERT INTO tag_given_to VALUES(60, 302);  -- Alien: The Director's Cut (2003) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(60, 284);  -- Alien: The Director's Cut (2003) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(61, 299);  -- Alien Resurrection (1998) tagged with 'future'
INSERT INTO tag_given_to VALUES(61, 302);  -- Alien Resurrection (1998) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(61, 284);  -- Alien Resurrection (1998) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(62, 302);  -- Alien vs. Predator (2004) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(63, 299);  -- Aliens (1986) tagged with 'future'
INSERT INTO tag_given_to VALUES(63, 302);  -- Aliens (1986) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(63, 284);  -- Aliens (1986) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(63, 29);  -- Aliens (1986) tagged with 'dark'
INSERT INTO tag_given_to VALUES(64, 266);  -- Aliens of the Deep (2005) tagged with 'at-sea'
INSERT INTO tag_given_to VALUES(1168, 59);  -- The Twilight Saga: New Moon (2009) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(1168, 58);  -- The Twilight Saga: New Moon (2009) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(499, 59);  -- The Twilight Saga: Eclipse (2010) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(499, 58);  -- The Twilight Saga: Eclipse (2010) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3392, 59);  -- The Twilight Saga: Breaking Dawn Part 1 (2011) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3392, 58);  -- The Twilight Saga: Breaking Dawn Part 1 (2011) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3453, 59);  -- The Twilight Saga: Breaking Dawn Part 2 (2012) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3453, 58);  -- The Twilight Saga: Breaking Dawn Part 2 (2012) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3582, 34);  -- Saving Mr. Banks (2013) tagged with 'drama-comedy'
INSERT INTO tag_given_to VALUES(3582, 125);  -- Saving Mr. Banks (2013) tagged with '1960''s'
INSERT INTO tag_given_to VALUES(3582, 119);  -- Saving Mr. Banks (2013) tagged with '1900''s'
INSERT INTO tag_given_to VALUES(3582, 209);  -- Saving Mr. Banks (2013) tagged with 'filmmaking'
INSERT INTO tag_given_to VALUES(3582, 207);  -- Saving Mr. Banks (2013) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(3582, 118);  -- Saving Mr. Banks (2013) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(3582, 21);  -- Saving Mr. Banks (2013) tagged with 'period'
INSERT INTO tag_given_to VALUES(3582, 61);  -- Saving Mr. Banks (2013) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(3582, 58);  -- Saving Mr. Banks (2013) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(2185, 1);  -- Serpico (1973) tagged with 'drama'
INSERT INTO tag_given_to VALUES(2185, 271);  -- Serpico (1973) tagged with 'corruption'
INSERT INTO tag_given_to VALUES(2185, 134);  -- Serpico (1973) tagged with 'cops'
INSERT INTO tag_given_to VALUES(2185, 227);  -- Serpico (1973) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(2185, 38);  -- Serpico (1973) tagged with 'new-york-city'
INSERT INTO tag_given_to VALUES(2185, 22);  -- Serpico (1973) tagged with 'biography'
INSERT INTO tag_given_to VALUES(2185, 207);  -- Serpico (1973) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(2185, 25);  -- Serpico (1973) tagged with 'crime'
INSERT INTO tag_given_to VALUES(2185, 60);  -- Serpico (1973) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(2185, 133);  -- Serpico (1973) tagged with 'law-enforcement'
INSERT INTO tag_given_to VALUES(2185, 226);  -- Serpico (1973) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(2185, 225);  -- Serpico (1973) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(2185, 58);  -- Serpico (1973) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(2185, 59);  -- Serpico (1973) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(65, 207);  -- Alive (1993) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(65, 223);  -- Alive (1993) tagged with 'survival'
INSERT INTO tag_given_to VALUES(65, 58);  -- Alive (1993) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(65, 59);  -- Alive (1993) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(66, 214);  -- All About Eve (1950) tagged with 'theatre'
INSERT INTO tag_given_to VALUES(66, 61);  -- All About Eve (1950) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(66, 59);  -- All About Eve (1950) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(66, 58);  -- All About Eve (1950) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(67, 227);  -- All About My Mother (1999) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(67, 226);  -- All About My Mother (1999) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(67, 225);  -- All About My Mother (1999) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(68, 263);  -- All or Nothing (2002) tagged with 'family'
INSERT INTO tag_given_to VALUES(68, 262);  -- All or Nothing (2002) tagged with 'marriage'
INSERT INTO tag_given_to VALUES(69, 120);  -- All Quiet on the Western Front (1930) tagged with '1910''s'
INSERT INTO tag_given_to VALUES(69, 118);  -- All Quiet on the Western Front (1930) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(69, 21);  -- All Quiet on the Western Front (1930) tagged with 'period'
INSERT INTO tag_given_to VALUES(69, 17);  -- All Quiet on the Western Front (1930) tagged with 'war'
INSERT INTO tag_given_to VALUES(69, 59);  -- All Quiet on the Western Front (1930) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(69, 58);  -- All Quiet on the Western Front (1930) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(70, 214);  -- All That Jazz (1979) tagged with 'theatre'
INSERT INTO tag_given_to VALUES(70, 207);  -- All That Jazz (1979) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(70, 61);  -- All That Jazz (1979) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(70, 58);  -- All That Jazz (1979) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(71, 207);  -- All the President's Men (1976) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(71, 26);  -- All the President's Men (1976) tagged with 'history'
INSERT INTO tag_given_to VALUES(71, 271);  -- All the President's Men (1976) tagged with 'corruption'
INSERT INTO tag_given_to VALUES(71, 184);  -- All the President's Men (1976) tagged with 'white-collar-crime'
INSERT INTO tag_given_to VALUES(71, 58);  -- All the President's Men (1976) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(71, 25);  -- All the President's Men (1976) tagged with 'crime'
INSERT INTO tag_given_to VALUES(71, 59);  -- All the President's Men (1976) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(73, 126);  -- Almost Famous (2000) tagged with '1970''s'
INSERT INTO tag_given_to VALUES(73, 118);  -- Almost Famous (2000) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(73, 21);  -- Almost Famous (2000) tagged with 'period'
INSERT INTO tag_given_to VALUES(73, 61);  -- Almost Famous (2000) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(74, 227);  -- Altered States (1980) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(74, 226);  -- Altered States (1980) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(74, 225);  -- Altered States (1980) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(74, 59);  -- Altered States (1980) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(74, 58);  -- Altered States (1980) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(75, 116);  -- Amadeus (1984) tagged with '18th-century'
INSERT INTO tag_given_to VALUES(75, 233);  -- Amadeus (1984) tagged with 'non-sexual-male-nudity'
INSERT INTO tag_given_to VALUES(75, 230);  -- Amadeus (1984) tagged with 'non-sexual-nudity'
INSERT INTO tag_given_to VALUES(75, 225);  -- Amadeus (1984) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(75, 59);  -- Amadeus (1984) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(75, 58);  -- Amadeus (1984) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(75, 61);  -- Amadeus (1984) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(76, 122);  -- Amarcord (1974) tagged with '1930''s'
INSERT INTO tag_given_to VALUES(76, 227);  -- Amarcord (1974) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(76, 118);  -- Amarcord (1974) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(76, 21);  -- Amarcord (1974) tagged with 'period'
INSERT INTO tag_given_to VALUES(76, 226);  -- Amarcord (1974) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(76, 225);  -- Amarcord (1974) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(77, 227);  -- Amelie (2001) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(77, 226);  -- Amelie (2001) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(77, 225);  -- Amelie (2001) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(77, 2);  -- Amelie (2001) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(78, 227);  -- American Beauty (1999) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(78, 296);  -- American Beauty (1999) tagged with 'family-disfunction'
INSERT INTO tag_given_to VALUES(78, 226);  -- American Beauty (1999) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(78, 225);  -- American Beauty (1999) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(78, 263);  -- American Beauty (1999) tagged with 'family'
INSERT INTO tag_given_to VALUES(79, 171);  -- American Buffalo (1996) tagged with 'robbery'
INSERT INTO tag_given_to VALUES(79, 169);  -- American Buffalo (1996) tagged with 'stealing'
INSERT INTO tag_given_to VALUES(79, 25);  -- American Buffalo (1996) tagged with 'crime'
INSERT INTO tag_given_to VALUES(79, 59);  -- American Buffalo (1996) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(79, 58);  -- American Buffalo (1996) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(80, 288);  -- An American Crime (2007) tagged with 'upsetting'
INSERT INTO tag_given_to VALUES(80, 207);  -- An American Crime (2007) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(80, 125);  -- An American Crime (2007) tagged with '1960''s'
INSERT INTO tag_given_to VALUES(80, 185);  -- An American Crime (2007) tagged with 'domestic-violence'
INSERT INTO tag_given_to VALUES(80, 58);  -- An American Crime (2007) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(80, 118);  -- An American Crime (2007) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(80, 21);  -- An American Crime (2007) tagged with 'period'
INSERT INTO tag_given_to VALUES(82, 124);  -- American Graffiti (1973) tagged with '1950''s'
INSERT INTO tag_given_to VALUES(82, 249);  -- American Graffiti (1973) tagged with 'coming-of-age/childhood'
INSERT INTO tag_given_to VALUES(82, 118);  -- American Graffiti (1973) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(82, 21);  -- American Graffiti (1973) tagged with 'period'
INSERT INTO tag_given_to VALUES(83, 282);  -- American History X (1998) tagged with 'racism'
INSERT INTO tag_given_to VALUES(83, 167);  -- American History X (1998) tagged with 'murder'
INSERT INTO tag_given_to VALUES(83, 176);  -- American History X (1998) tagged with 'gangs'
INSERT INTO tag_given_to VALUES(83, 79);  -- American History X (1998) tagged with 'prison'
INSERT INTO tag_given_to VALUES(83, 31);  -- American History X (1998) tagged with 'sad'
INSERT INTO tag_given_to VALUES(85, 209);  -- American Movie (1999) tagged with 'filmmaking'
INSERT INTO tag_given_to VALUES(85, 61);  -- American Movie (1999) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(86, 24);  -- The American President (1995) tagged with 'political'
INSERT INTO tag_given_to VALUES(87, 308);  -- American Psycho (2000) tagged with 'graphic-sexual-content'
INSERT INTO tag_given_to VALUES(87, 309);  -- American Psycho (2000) tagged with 'graphic-violence'
INSERT INTO tag_given_to VALUES(87, 168);  -- American Psycho (2000) tagged with 'serial-killer'
INSERT INTO tag_given_to VALUES(87, 227);  -- American Psycho (2000) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(87, 167);  -- American Psycho (2000) tagged with 'murder'
INSERT INTO tag_given_to VALUES(87, 226);  -- American Psycho (2000) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(87, 225);  -- American Psycho (2000) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(87, 59);  -- American Psycho (2000) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(87, 58);  -- American Psycho (2000) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(87, 2);  -- American Psycho (2000) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(3583, 1);  -- Interstellar (2014) tagged with 'drama'
INSERT INTO tag_given_to VALUES(3583, 11);  -- Interstellar (2014) tagged with 'adventure'
INSERT INTO tag_given_to VALUES(3583, 299);  -- Interstellar (2014) tagged with 'future'
INSERT INTO tag_given_to VALUES(3583, 284);  -- Interstellar (2014) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(3583, 6);  -- Interstellar (2014) tagged with 'science-fiction'
INSERT INTO tag_given_to VALUES(88, 59);  -- American Splendor (2003) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(88, 58);  -- American Splendor (2003) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(89, 2);  -- America's Sweethearts (2001) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(90, 117);  -- Amistad (1997) tagged with '19th-century'
INSERT INTO tag_given_to VALUES(90, 273);  -- Amistad (1997) tagged with 'slavery'
INSERT INTO tag_given_to VALUES(90, 282);  -- Amistad (1997) tagged with 'racism'
INSERT INTO tag_given_to VALUES(90, 287);  -- Amistad (1997) tagged with 'social-injustice'
INSERT INTO tag_given_to VALUES(90, 230);  -- Amistad (1997) tagged with 'non-sexual-nudity'
INSERT INTO tag_given_to VALUES(90, 225);  -- Amistad (1997) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(2479, 1);  -- The Firm (1993) tagged with 'drama'
INSERT INTO tag_given_to VALUES(2479, 3);  -- The Firm (1993) tagged with 'thriller'
INSERT INTO tag_given_to VALUES(2479, 60);  -- The Firm (1993) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(2479, 184);  -- The Firm (1993) tagged with 'white-collar-crime'
INSERT INTO tag_given_to VALUES(2479, 271);  -- The Firm (1993) tagged with 'corruption'
INSERT INTO tag_given_to VALUES(2479, 59);  -- The Firm (1993) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(2479, 58);  -- The Firm (1993) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(2479, 25);  -- The Firm (1993) tagged with 'crime'
INSERT INTO tag_given_to VALUES(3584, 10);  -- Lone Survivor (2013) tagged with 'action'
INSERT INTO tag_given_to VALUES(3584, 297);  -- Lone Survivor (2013) tagged with 'war-on-terror'
INSERT INTO tag_given_to VALUES(3584, 217);  -- Lone Survivor (2013) tagged with 'military'
INSERT INTO tag_given_to VALUES(3584, 207);  -- Lone Survivor (2013) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(3584, 60);  -- Lone Survivor (2013) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(3584, 261);  -- Lone Survivor (2013) tagged with 'excessive-swearing'
INSERT INTO tag_given_to VALUES(3584, 309);  -- Lone Survivor (2013) tagged with 'graphic-violence'
INSERT INTO tag_given_to VALUES(3584, 17);  -- Lone Survivor (2013) tagged with 'war'
INSERT INTO tag_given_to VALUES(3584, 58);  -- Lone Survivor (2013) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3584, 59);  -- Lone Survivor (2013) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3584, 63);  -- Lone Survivor (2013) tagged with 'graphic'
INSERT INTO tag_given_to VALUES(94, 120);  -- Anastasia (1997) tagged with '1910''s'
INSERT INTO tag_given_to VALUES(94, 118);  -- Anastasia (1997) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(96, 32);  -- The Anderson Platoon (1967) tagged with 'black-and-white'
INSERT INTO tag_given_to VALUES(96, 17);  -- The Anderson Platoon (1967) tagged with 'war'
INSERT INTO tag_given_to VALUES(97, 121);  -- An Angel at My Table (1991) tagged with '1920''s'
INSERT INTO tag_given_to VALUES(97, 122);  -- An Angel at My Table (1991) tagged with '1930''s'
INSERT INTO tag_given_to VALUES(97, 207);  -- An Angel at My Table (1991) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(97, 147);  -- An Angel at My Table (1991) tagged with 'insanity'
INSERT INTO tag_given_to VALUES(97, 118);  -- An Angel at My Table (1991) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(97, 21);  -- An Angel at My Table (1991) tagged with 'period'
INSERT INTO tag_given_to VALUES(97, 58);  -- An Angel at My Table (1991) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(97, 143);  -- An Angel at My Table (1991) tagged with 'mental-illness/condition'
INSERT INTO tag_given_to VALUES(97, 142);  -- An Angel at My Table (1991) tagged with 'illness/condition'
INSERT INTO tag_given_to VALUES(97, 59);  -- An Angel at My Table (1991) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(98, 134);  -- Angel Eyes (2001) tagged with 'cops'
INSERT INTO tag_given_to VALUES(98, 133);  -- Angel Eyes (2001) tagged with 'law-enforcement'
INSERT INTO tag_given_to VALUES(99, 207);  -- Angela's Ashes (2000) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(99, 122);  -- Angela's Ashes (2000) tagged with '1930''s'
INSERT INTO tag_given_to VALUES(99, 123);  -- Angela's Ashes (2000) tagged with '1940''s'
INSERT INTO tag_given_to VALUES(99, 238);  -- Angela's Ashes (2000) tagged with 'lower-class'
INSERT INTO tag_given_to VALUES(99, 58);  -- Angela's Ashes (2000) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(99, 118);  -- Angela's Ashes (2000) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(99, 21);  -- Angela's Ashes (2000) tagged with 'period'
INSERT INTO tag_given_to VALUES(99, 236);  -- Angela's Ashes (2000) tagged with 'social-classes'
INSERT INTO tag_given_to VALUES(99, 59);  -- Angela's Ashes (2000) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(101, 263);  -- Animal Kingdom (2010) tagged with 'family'
INSERT INTO tag_given_to VALUES(101, 254);  -- Animal Kingdom (2010) tagged with 'detective'
INSERT INTO tag_given_to VALUES(101, 167);  -- Animal Kingdom (2010) tagged with 'murder'
INSERT INTO tag_given_to VALUES(101, 171);  -- Animal Kingdom (2010) tagged with 'robbery'
INSERT INTO tag_given_to VALUES(101, 175);  -- Animal Kingdom (2010) tagged with 'drug-dealing'
INSERT INTO tag_given_to VALUES(101, 31);  -- Animal Kingdom (2010) tagged with 'sad'
INSERT INTO tag_given_to VALUES(101, 169);  -- Animal Kingdom (2010) tagged with 'stealing'
INSERT INTO tag_given_to VALUES(102, 2);  -- Annie Hall (1977) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(104, 7);  -- Antz (1998) tagged with 'animation'
INSERT INTO tag_given_to VALUES(105, 2);  -- Anything Else (2003) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(3585, 2);  -- Alan Partridge (2013) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(3585, 215);  -- Alan Partridge (2013) tagged with 'radio'
INSERT INTO tag_given_to VALUES(3585, 233);  -- Alan Partridge (2013) tagged with 'non-sexual-male-nudity'
INSERT INTO tag_given_to VALUES(3585, 305);  -- Alan Partridge (2013) tagged with 'hostage-situation'
INSERT INTO tag_given_to VALUES(3585, 205);  -- Alan Partridge (2013) tagged with 'based-on-tv-show'
INSERT INTO tag_given_to VALUES(3585, 61);  -- Alan Partridge (2013) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(3585, 230);  -- Alan Partridge (2013) tagged with 'non-sexual-nudity'
INSERT INTO tag_given_to VALUES(3585, 225);  -- Alan Partridge (2013) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(3585, 25);  -- Alan Partridge (2013) tagged with 'crime'
INSERT INTO tag_given_to VALUES(3585, 59);  -- Alan Partridge (2013) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3585, 58);  -- Alan Partridge (2013) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(2015, 1);  -- Becket (1964) tagged with 'drama'
INSERT INTO tag_given_to VALUES(2015, 112);  -- Becket (1964) tagged with 'medieval'
INSERT INTO tag_given_to VALUES(2015, 26);  -- Becket (1964) tagged with 'history'
INSERT INTO tag_given_to VALUES(2015, 22);  -- Becket (1964) tagged with 'biography'
INSERT INTO tag_given_to VALUES(2015, 81);  -- Becket (1964) tagged with 'based-on-play'
INSERT INTO tag_given_to VALUES(2015, 207);  -- Becket (1964) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(2015, 186);  -- Becket (1964) tagged with 'christian/christianity'
INSERT INTO tag_given_to VALUES(2015, 21);  -- Becket (1964) tagged with 'period'
INSERT INTO tag_given_to VALUES(2015, 59);  -- Becket (1964) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(2015, 58);  -- Becket (1964) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(2015, 50);  -- Becket (1964) tagged with 'spiritual/religion'
INSERT INTO tag_given_to VALUES(3586, 1);  -- Dream House (2011) tagged with 'drama'
INSERT INTO tag_given_to VALUES(3586, 8);  -- Dream House (2011) tagged with 'mystery'
INSERT INTO tag_given_to VALUES(3586, 3);  -- Dream House (2011) tagged with 'thriller'
INSERT INTO tag_given_to VALUES(3586, 46);  -- Dream House (2011) tagged with 'psychological'
INSERT INTO tag_given_to VALUES(3586, 38);  -- Dream House (2011) tagged with 'new-york-city'
INSERT INTO tag_given_to VALUES(3586, 143);  -- Dream House (2011) tagged with 'mental-illness/condition'
INSERT INTO tag_given_to VALUES(3586, 142);  -- Dream House (2011) tagged with 'illness/condition'
INSERT INTO tag_given_to VALUES(1962, 1);  -- Gentleman''s Agreement (1947) tagged with 'drama'
INSERT INTO tag_given_to VALUES(1962, 32);  -- Gentleman''s Agreement (1947) tagged with 'black-and-white'
INSERT INTO tag_given_to VALUES(1962, 38);  -- Gentleman''s Agreement (1947) tagged with 'new-york-city'
INSERT INTO tag_given_to VALUES(1962, 282);  -- Gentleman''s Agreement (1947) tagged with 'racism'
INSERT INTO tag_given_to VALUES(1962, 60);  -- Gentleman''s Agreement (1947) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(1962, 59);  -- Gentleman''s Agreement (1947) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(1962, 58);  -- Gentleman''s Agreement (1947) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3587, 1);  -- The Imitation Game (2014) tagged with 'drama'
INSERT INTO tag_given_to VALUES(3587, 26);  -- The Imitation Game (2014) tagged with 'history'
INSERT INTO tag_given_to VALUES(3587, 22);  -- The Imitation Game (2014) tagged with 'biography'
INSERT INTO tag_given_to VALUES(3587, 207);  -- The Imitation Game (2014) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(3587, 37);  -- The Imitation Game (2014) tagged with 'world-war-ii'
INSERT INTO tag_given_to VALUES(3587, 259);  -- The Imitation Game (2014) tagged with 'homosexuality'
INSERT INTO tag_given_to VALUES(3587, 141);  -- The Imitation Game (2014) tagged with 'mi6'
INSERT INTO tag_given_to VALUES(3587, 60);  -- The Imitation Game (2014) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(3587, 58);  -- The Imitation Game (2014) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3587, 17);  -- The Imitation Game (2014) tagged with 'war'
INSERT INTO tag_given_to VALUES(3587, 136);  -- The Imitation Game (2014) tagged with 'government-agency'
INSERT INTO tag_given_to VALUES(3587, 59);  -- The Imitation Game (2014) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3588, 1);  -- Tell No One (2006) tagged with 'drama'
INSERT INTO tag_given_to VALUES(3588, 8);  -- Tell No One (2006) tagged with 'mystery'
INSERT INTO tag_given_to VALUES(3588, 167);  -- Tell No One (2006) tagged with 'murder'
INSERT INTO tag_given_to VALUES(3588, 271);  -- Tell No One (2006) tagged with 'corruption'
INSERT INTO tag_given_to VALUES(3588, 60);  -- Tell No One (2006) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(3588, 233);  -- Tell No One (2006) tagged with 'non-sexual-male-nudity'
INSERT INTO tag_given_to VALUES(3588, 227);  -- Tell No One (2006) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(3588, 25);  -- Tell No One (2006) tagged with 'crime'
INSERT INTO tag_given_to VALUES(3588, 59);  -- Tell No One (2006) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3588, 58);  -- Tell No One (2006) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3588, 230);  -- Tell No One (2006) tagged with 'non-sexual-nudity'
INSERT INTO tag_given_to VALUES(3588, 225);  -- Tell No One (2006) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(3588, 226);  -- Tell No One (2006) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(2023, 34);  -- Oliver! (1968) tagged with 'drama-comedy'
INSERT INTO tag_given_to VALUES(2023, 23);  -- Oliver! (1968) tagged with 'musical'
INSERT INTO tag_given_to VALUES(2023, 169);  -- Oliver! (1968) tagged with 'stealing'
INSERT INTO tag_given_to VALUES(2023, 117);  -- Oliver! (1968) tagged with '19th-century'
INSERT INTO tag_given_to VALUES(2023, 238);  -- Oliver! (1968) tagged with 'lower-class'
INSERT INTO tag_given_to VALUES(2023, 60);  -- Oliver! (1968) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(2023, 199);  -- Oliver! (1968) tagged with 'based-on-musical'
INSERT INTO tag_given_to VALUES(2023, 249);  -- Oliver! (1968) tagged with 'coming-of-age/childhood'
INSERT INTO tag_given_to VALUES(2023, 25);  -- Oliver! (1968) tagged with 'crime'
INSERT INTO tag_given_to VALUES(2023, 21);  -- Oliver! (1968) tagged with 'period'
INSERT INTO tag_given_to VALUES(2023, 236);  -- Oliver! (1968) tagged with 'social-classes'
INSERT INTO tag_given_to VALUES(2023, 59);  -- Oliver! (1968) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(2023, 58);  -- Oliver! (1968) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(106, 249);  -- Aparajito (1957) tagged with 'coming-of-age/childhood'
INSERT INTO tag_given_to VALUES(106, 263);  -- Aparajito (1957) tagged with 'family'
INSERT INTO tag_given_to VALUES(106, 59);  -- Aparajito (1957) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(106, 58);  -- Aparajito (1957) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(107, 2);  -- The Apartment (1960) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(108, 46);  -- Apartment Zero (1988) tagged with 'psychological'
INSERT INTO tag_given_to VALUES(109, 147);  -- Apocalypse Now (1979) tagged with 'insanity'
INSERT INTO tag_given_to VALUES(109, 217);  -- Apocalypse Now (1979) tagged with 'military'
INSERT INTO tag_given_to VALUES(109, 143);  -- Apocalypse Now (1979) tagged with 'mental-illness/condition'
INSERT INTO tag_given_to VALUES(109, 142);  -- Apocalypse Now (1979) tagged with 'illness/condition'
INSERT INTO tag_given_to VALUES(109, 17);  -- Apocalypse Now (1979) tagged with 'war'
INSERT INTO tag_given_to VALUES(109, 59);  -- Apocalypse Now (1979) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(109, 58);  -- Apocalypse Now (1979) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(110, 147);  -- Apocalypse Now Redux (2001) tagged with 'insanity'
INSERT INTO tag_given_to VALUES(110, 217);  -- Apocalypse Now Redux (2001) tagged with 'military'
INSERT INTO tag_given_to VALUES(110, 227);  -- Apocalypse Now Redux (2001) tagged with 'sexual-female-nudity'
INSERT INTO tag_given_to VALUES(110, 71);  -- Apocalypse Now Redux (2001) tagged with 'epic'
INSERT INTO tag_given_to VALUES(110, 143);  -- Apocalypse Now Redux (2001) tagged with 'mental-illness/condition'
INSERT INTO tag_given_to VALUES(110, 142);  -- Apocalypse Now Redux (2001) tagged with 'illness/condition'
INSERT INTO tag_given_to VALUES(110, 226);  -- Apocalypse Now Redux (2001) tagged with 'sexual-nudity'
INSERT INTO tag_given_to VALUES(110, 225);  -- Apocalypse Now Redux (2001) tagged with 'nudity'
INSERT INTO tag_given_to VALUES(110, 17);  -- Apocalypse Now Redux (2001) tagged with 'war'
INSERT INTO tag_given_to VALUES(110, 59);  -- Apocalypse Now Redux (2001) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(110, 58);  -- Apocalypse Now Redux (2001) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(111, 114);  -- Apocalypto (2006) tagged with '16th-century'
INSERT INTO tag_given_to VALUES(111, 309);  -- Apocalypto (2006) tagged with 'graphic-violence'
INSERT INTO tag_given_to VALUES(112, 207);  -- Apollo 13 (1995) tagged with 'based-on-a-true-story'
INSERT INTO tag_given_to VALUES(112, 284);  -- Apollo 13 (1995) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(112, 126);  -- Apollo 13 (1995) tagged with '1970''s'
INSERT INTO tag_given_to VALUES(112, 58);  -- Apollo 13 (1995) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(112, 118);  -- Apollo 13 (1995) tagged with '20th-century'
INSERT INTO tag_given_to VALUES(112, 21);  -- Apollo 13 (1995) tagged with 'period'
INSERT INTO tag_given_to VALUES(112, 59);  -- Apollo 13 (1995) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(113, 50);  -- The Apostle (1997) tagged with 'spiritual/religion'
INSERT INTO tag_given_to VALUES(114, 117);  -- Appaloosa (2008) tagged with '19th-century'
INSERT INTO tag_given_to VALUES(114, 133);  -- Appaloosa (2008) tagged with 'law-enforcement'
INSERT INTO tag_given_to VALUES(114, 21);  -- Appaloosa (2008) tagged with 'period'
INSERT INTO tag_given_to VALUES(114, 59);  -- Appaloosa (2008) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(114, 58);  -- Appaloosa (2008) tagged with 'based-on-something'
