INSERT INTO tag_given_to VALUES(285, 59);  -- Cape Fear (1962) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(285, 58);  -- Cape Fear (1962) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(1175, 59);  -- Night at the Museum (2007) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(1175, 58);  -- Night at the Museum (2007) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(1626, 61);  -- Thirty Two Short Films About Glenn Gould (1994) tagged with 'arts/entertainment'
INSERT INTO tag_given_to VALUES(1112, 2);  -- Mr. & Mrs. Smith (2005) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(1226, 59);  -- Owning Mahowny (2003) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(1226, 58);  -- Owning Mahowny (2003) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3508, 59);  -- The Hunger Games: Catching Fire (2013) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3508, 58);  -- The Hunger Games: Catching Fire (2013) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(38, 57);  -- The Adventures of Baron Munchausen (1989) tagged with 'remake'
INSERT INTO tag_given_to VALUES(48, 307);  -- Airplane! (1980) tagged with 'spoof'
INSERT INTO tag_given_to VALUES(49, 60);  -- Airport (1970) tagged with 'based-on-book'
INSERT INTO tag_given_to VALUES(49, 59);  -- Airport (1970) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(49, 58);  -- Airport (1970) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(51, 57);  -- The Alamo (2004) tagged with 'remake'
INSERT INTO tag_given_to VALUES(52, 59);  -- Alfie (1966) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(52, 58);  -- Alfie (1966) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(51, 117);  -- The Alamo (2004) tagged with '19th-century'
INSERT INTO tag_given_to VALUES(51, 21);  -- The Alamo (2004) tagged with 'period'
INSERT INTO tag_given_to VALUES(53, 105);  -- Ali (2001) tagged with 'boxing'
INSERT INTO tag_given_to VALUES(55, 2);  -- Alice (1990) tagged with 'comedy'
INSERT INTO tag_given_to VALUES(57, 59);  -- Alice in Wonderland (1951) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(57, 58);  -- Alice in Wonderland (1951) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(58, 59);  -- Alice in Wonderland (2010) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(58, 58);  -- Alice in Wonderland (2010) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(59, 299);  -- Alien (1979) tagged with 'future'
INSERT INTO tag_given_to VALUES(59, 302);  -- Alien (1979) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(59, 284);  -- Alien (1979) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(60, 299);  -- Alien: The Director's Cut (2003) tagged with 'future'
INSERT INTO tag_given_to VALUES(60, 302);  -- Alien: The Director's Cut (2003) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(60, 284);  -- Alien: The Director's Cut (2003) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(61, 299);  -- Alien Resurrection (1998) tagged with 'future'
INSERT INTO tag_given_to VALUES(61, 302);  -- Alien Resurrection (1998) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(61, 284);  -- Alien Resurrection (1998) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(62, 302);  -- Alien vs. Predator (2004) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(63, 299);  -- Aliens (1986) tagged with 'future'
INSERT INTO tag_given_to VALUES(63, 302);  -- Aliens (1986) tagged with 'alien(s)'
INSERT INTO tag_given_to VALUES(63, 284);  -- Aliens (1986) tagged with 'outer-space'
INSERT INTO tag_given_to VALUES(63, 29);  -- Aliens (1986) tagged with 'dark'
INSERT INTO tag_given_to VALUES(64, 266);  -- Aliens of the Deep (2005) tagged with 'at-sea'
INSERT INTO tag_given_to VALUES(1168, 59);  -- The Twilight Saga: New Moon (2009) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(1168, 58);  -- The Twilight Saga: New Moon (2009) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(499, 59);  -- The Twilight Saga: Eclipse (2010) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(499, 58);  -- The Twilight Saga: Eclipse (2010) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3392, 59);  -- The Twilight Saga: Breaking Dawn Part 1 (2011) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3392, 58);  -- The Twilight Saga: Breaking Dawn Part 1 (2011) tagged with 'based-on-something'
INSERT INTO tag_given_to VALUES(3453, 59);  -- The Twilight Saga: Breaking Dawn Part 2 (2012) tagged with 'based-on-previously-written-material'
INSERT INTO tag_given_to VALUES(3453, 58);  -- The Twilight Saga: Breaking Dawn Part 2 (2012) tagged with 'based-on-something'
