INSERT INTO tyler VALUES (1, 'Best Picture');
INSERT INTO tyler VALUES (2, 'Best Actor');
INSERT INTO tyler VALUES (3, 'Best Actress');
INSERT INTO tyler VALUES (4, 'Best Supporting Actor');
INSERT INTO tyler VALUES (5, 'Best Supporting Actress');
INSERT INTO tyler VALUES (6, 'Best Director');
INSERT INTO tyler VALUES (7, 'Best Documentary');
INSERT INTO tyler VALUES (8, 'Best Cinematography');
INSERT INTO tyler VALUES (9, 'Best Adapted Screenplay');
INSERT INTO tyler VALUES (10, 'Best Original Screenplay');
INSERT INTO tyler VALUES (11, 'Best Animated Feature');
INSERT INTO tyler VALUES (12, 'Best Scene');
INSERT INTO tyler VALUES (13, 'Worst Picture');
INSERT INTO tyler VALUES (14, 'Best Foreign Language Film');
