INSERT INTO worked_on VALUES(28, 2244, 'Actor');  -- Hugh Grant for About a Boy (2002)
INSERT INTO worked_on VALUES(28, 1023, 'Actress');  -- Toni Collette for About a Boy (2002)
INSERT INTO worked_on VALUES(28, 2009, 'Director');  -- Chris Weitz for About a Boy (2002)
INSERT INTO worked_on VALUES(28, 2010, 'Director');  -- Paul Weitz for About a Boy (2002)
INSERT INTO worked_on VALUES(29, 338, 'Director');  -- Alexander Payne for About Schmidt (2002)
INSERT INTO worked_on VALUES(29, 338, 'Screenwriter');  -- Alexander Payne for About Schmidt (2002)
INSERT INTO worked_on VALUES(29, 1980, 'Screenwriter');  -- Jim Taylor for About Schmidt (2002)
INSERT INTO worked_on VALUES(29, 2245, 'Actress');  -- Hope Davis for About Schmidt (2002)
INSERT INTO worked_on VALUES(29, 2246, 'Actor');  -- Dermot Mulroney for About Schmidt (2002)
INSERT INTO worked_on VALUES(29, 2082, 'Actress');  -- June Squibb for About Schmidt (2002)
INSERT INTO worked_on VALUES(30, 91, 'Actress');  -- Penelope Cruz for Abre Los Ojos (1997)
INSERT INTO worked_on VALUES(30, 2247, 'Director');  -- Alejandro Amenabar for Abre Los Ojos (1997)
INSERT INTO worked_on VALUES(30, 2247, 'Screenwriter');  -- Alejandro Amenabar for Abre Los Ojos (1997)
INSERT INTO worked_on VALUES(30, 2248, 'Screenwriter');  -- Mateo Gil for Abre Los Ojos (1997)
INSERT INTO worked_on VALUES(31, 262, 'Director');  -- James Cameron for The Abyss (1989)
INSERT INTO worked_on VALUES(31, 262, 'Screenwriter');  -- James Cameron for The Abyss (1989)
INSERT INTO worked_on VALUES(31, 229, 'Actor');  -- Ed Harris for The Abyss (1989)
INSERT INTO worked_on VALUES(31, 963, 'Actress');  -- Mary Elizabeth Mastrantonio for The Abyss (1989)
INSERT INTO worked_on VALUES(32, 202, 'Actor');  -- William Hurt for The Accidental Tourist (1988)
INSERT INTO worked_on VALUES(32, 960, 'Actress');  -- Kathleen Turner for The Accidental Tourist (1988)
INSERT INTO worked_on VALUES(32, 304, 'Director');  -- Lawrence Kasdan for The Accidental Tourist (1988)
INSERT INTO worked_on VALUES(32, 2249, 'Actor');  -- Bill Pullman for The Accidental Tourist (1988)
INSERT INTO worked_on VALUES(33, 2250, 'Actress');  -- Kelly McGillis for The Accused (1988)
INSERT INTO worked_on VALUES(34, 73, 'Actor');  -- Jim Carrey for Ace Ventura: Pet Detective (1994)
INSERT INTO worked_on VALUES(34, 2251, 'Actress');  -- Courteney Cox for Ace Ventura: Pet Detective (1994)
INSERT INTO worked_on VALUES(34, 2252, 'Actress');  -- Sean Young for Ace Ventura: Pet Detective (1994)
INSERT INTO worked_on VALUES(35, 118, 'Actor');  -- Spencer Tracy for Adam's Rib (1949)
INSERT INTO worked_on VALUES(35, 21, 'Actress');  -- Katharine Hepburn for Adam's Rib (1949)
INSERT INTO worked_on VALUES(35, 1070, 'Director');  -- George Cukor for Adam's Rib (1949)
INSERT INTO worked_on VALUES(36, 302, 'Director');  -- Spike Jonze for Adaptation (2002)
INSERT INTO worked_on VALUES(36, 1052, 'Actress');  -- Tilda Swinton for Adaptation (2002)
INSERT INTO worked_on VALUES(37, 20, 'Actor');  -- Matt Damon for The Adjustment Bureau (2011)
INSERT INTO worked_on VALUES(37, 2127, 'Actress');  -- Emily Blunt for The Adjustment Bureau (2011)
INSERT INTO worked_on VALUES(37, 2253, 'Actor');  -- Anthony Mackie for The Adjustment Bureau (2011)
INSERT INTO worked_on VALUES(38, 289, 'Director');  -- Terry Gilliam for The Adventures of Baron Munchausen (1989)
INSERT INTO worked_on VALUES(38, 289, 'Screenwriter');  -- Terry Gilliam for The Adventures of Baron Munchausen (1989)
INSERT INTO worked_on VALUES(38, 1879, 'Screenwriter');  -- Charles McKeown for The Adventures of Baron Munchausen (1989)
INSERT INTO worked_on VALUES(38, 995, 'Actress');  -- Uma Thurman for The Adventures of Baron Munchausen (1989)
INSERT INTO worked_on VALUES(38, 2254, 'Actor');  -- Eric Idle for The Adventures of Baron Munchausen (1989)
INSERT INTO worked_on VALUES(38, 2255, 'Actor');  -- John Neville for The Adventures of Baron Munchausen (1989)
INSERT INTO worked_on VALUES(38, 2256, 'Actor');  -- Jonathan Pryce for The Adventures of Baron Munchausen (1989)
INSERT INTO worked_on VALUES(40, 2257, 'Actor');  -- Errol Flynn for The Adventures of Robin Hood (1938)
INSERT INTO worked_on VALUES(40, 717, 'Actress');  -- Olivia de Havilland for The Adventures of Robin Hood (1938)
INSERT INTO worked_on VALUES(40, 426, 'Actor');  -- Claude Rains for The Adventures of Robin Hood (1938)
INSERT INTO worked_on VALUES(41, 918, 'Actress');  -- Sissy Spacek for Affliction (1998)
INSERT INTO worked_on VALUES(41, 620, 'Actor');  -- Willem Dafoe for Affliction (1998)
INSERT INTO worked_on VALUES(41, 374, 'Director');  -- Paul Schrader for Affliction (1998)
INSERT INTO worked_on VALUES(41, 374, 'Screenwriter');  -- Paul Schrader for Affliction (1998)
INSERT INTO worked_on VALUES(42, 297, 'Director');  -- John Huston for The African Queen (1951)
INSERT INTO worked_on VALUES(43, 351, 'Director');  -- Martin Scorsese for After Hours (1985)
INSERT INTO worked_on VALUES(43, 2258, 'Screenwriter');  -- Joseph Minion for After Hours (1985)
INSERT INTO worked_on VALUES(43, 2259, 'Actor');  -- Griffin Dunne for After Hours (1985)
INSERT INTO worked_on VALUES(43, 2260, 'Actress');  -- Rosanna Arquette for After Hours (1985)
INSERT INTO worked_on VALUES(43, 943, 'Actress');  -- Teri Garr for After Hours (1985)
INSERT INTO worked_on VALUES(43, 2261, 'Actress');  -- Catherine O'Hara for After Hours (1985)
INSERT INTO worked_on VALUES(43, 2262, 'Actor');  -- Will Patton for After Hours (1985)
INSERT INTO worked_on VALUES(44, 2263, 'Director');  -- Charles S. Dutton for Against the Ropes (2004)
INSERT INTO worked_on VALUES(44, 2264, 'Actress');  -- Meg Ryan for Against the Ropes (2004)
INSERT INTO worked_on VALUES(44, 2263, 'Actor');  -- Charles S. Dutton for Against the Ropes (2004)
INSERT INTO worked_on VALUES(44, 2265, 'Actor');  -- Tony Shalhoub for Against the Ropes (2004)
INSERT INTO worked_on VALUES(44, 2266, 'Actress');  -- Kerry Washington for Against the Ropes (2004)
INSERT INTO worked_on VALUES(44, 2267, 'Actor');  -- Omar Epps for Against the Ropes (2004)
INSERT INTO worked_on VALUES(44, 2268, 'Actor');  -- Tim Daly for Against the Ropes (2004)
INSERT INTO worked_on VALUES(45, 351, 'Director');  -- Martin Scorsese for The Age of Innocence (1993)
INSERT INTO worked_on VALUES(45, 17, 'Actor');  -- Daniel Day-Lewis for The Age of Innocence (1993)
INSERT INTO worked_on VALUES(45, 973, 'Actress');  -- Michelle Pfeiffer for The Age of Innocence (1993)
INSERT INTO worked_on VALUES(46, 294, 'Director');  -- Werner Herzog for Aguirre, Wrath of God (1972)
INSERT INTO worked_on VALUES(46, 294, 'Screenwriter');  -- Werner Herzog for Aguirre, Wrath of God (1972)
INSERT INTO worked_on VALUES(46, 2269, 'Actor');  -- Klaus Kinski for Aguirre, Wrath of God (1972)
INSERT INTO worked_on VALUES(47, 2183, 'Actor');  -- Adam Sandler for Airheads (1994)
INSERT INTO worked_on VALUES(47, 2270, 'Actor');  -- Steve Buscemi for Airheads (1994)
INSERT INTO worked_on VALUES(47, 2271, 'Actor');  -- Brendan Fraser for Airheads (1994)
INSERT INTO worked_on VALUES(47, 2272, 'Actor');  -- Chris Farley for Airheads (1994)
INSERT INTO worked_on VALUES(47, 2273, 'Actor');  -- Michael Richards for Airheads (1994)
INSERT INTO worked_on VALUES(47, 158, 'Actor');  -- Michael McKean for Airheads (1994)
INSERT INTO worked_on VALUES(47, 2274, 'Actor');  -- Joe Mantegna for Airheads (1994)
INSERT INTO worked_on VALUES(47, 2275, 'Actor');  -- David Arquette for Airheads (1994)
INSERT INTO worked_on VALUES(47, 2276, 'Actor');  -- Judd Nelson for Airheads (1994)
INSERT INTO worked_on VALUES(48, 2277, 'Lead Actor');  -- Robert Hays for Airplane! (1980)
INSERT INTO worked_on VALUES(48, 2278, 'Lead Actor');  -- Leslie Nielsen for Airplane! (1980)
INSERT INTO worked_on VALUES(48, 502, 'Supporting Actor');  -- Robert Stack for Airplane! (1980)
INSERT INTO worked_on VALUES(48, 2279, 'Supporting Actor');  -- Lloyd Bridges for Airplane! (1980)
INSERT INTO worked_on VALUES(48, 2280, 'Lead Actress');  -- Julie Hagerty for Airplane! (1980)
INSERT INTO worked_on VALUES(49, 1103, 'Director');  -- George Seaton for Airport (1970)
INSERT INTO worked_on VALUES(49, 183, 'Lead Actor');  -- Burt Lancaster for Airport (1970)
INSERT INTO worked_on VALUES(49, 2281, 'Supporting Actor');  -- Dean Martin for Airport (1970)
INSERT INTO worked_on VALUES(51, 2282, 'Director');  -- John Lee Hancock for The Alamo (2004)
INSERT INTO worked_on VALUES(51, 2282, 'Screenwriter');  -- John Lee Hancock for The Alamo (2004)
INSERT INTO worked_on VALUES(51, 1988, 'Screenwriter');  -- Stephen Gaghan for The Alamo (2004)
INSERT INTO worked_on VALUES(51, 2283, 'Screenwriter');  -- Leslie Bohem for The Alamo (2004)
INSERT INTO worked_on VALUES(51, 2284, 'Lead Actor');  -- Dennis Quaid for The Alamo (2004)
INSERT INTO worked_on VALUES(51, 211, 'Supporting Actor');  -- Billy Bob Thornton for The Alamo (2004)
INSERT INTO worked_on VALUES(51, 2285, 'Supporting Actor');  -- Jason Patric for The Alamo (2004)
INSERT INTO worked_on VALUES(52, 2286, 'Director');  -- Lewis Gilbert for Alfie (1966)
INSERT INTO worked_on VALUES(52, 777, 'Supporting Actress');  -- Shelley Winters for Alfie (1966)
INSERT INTO worked_on VALUES(52, 619, 'Supporting Actor');  -- Denholm Elliott for Alfie (1966)
INSERT INTO worked_on VALUES(52, 2286, 'Producer');  -- Lewis Gilbert for Alfie (1966)
INSERT INTO worked_on VALUES(53, 327, 'Director');  -- Michael Mann for Ali (2001)
INSERT INTO worked_on VALUES(53, 327, 'Screenwriter');  -- Michael Mann for Ali (2001)
INSERT INTO worked_on VALUES(53, 1960, 'Screenwriter');  -- Stephen J. Rivele for Ali (2001)
INSERT INTO worked_on VALUES(53, 1961, 'Screenwriter');  -- Christopher Wilkinson for Ali (2001)
INSERT INTO worked_on VALUES(53, 380, 'Screenwriter');  -- Eric Roth for Ali (2001)
INSERT INTO worked_on VALUES(53, 218, 'Supporting Actor');  -- Jamie Foxx for Ali (2001)
INSERT INTO worked_on VALUES(53, 2184, 'Supporting Actress');  -- Jada Pinkett Smith for Ali (2001)
INSERT INTO worked_on VALUES(54, 2287, 'Director');  -- Rainer Werner Fassbinder for Ali: Fear Eats the Soul (1974)
INSERT INTO worked_on VALUES(54, 2287, 'Screenwriter');  -- Rainer Werner Fassbinder for Ali: Fear Eats the Soul (1974)
INSERT INTO worked_on VALUES(55, 245, 'Director');  -- Woody Allen for Alice (1990)
INSERT INTO worked_on VALUES(55, 2288, 'Lead Actress');  -- Mia Farrow for Alice (1990)
INSERT INTO worked_on VALUES(55, 202, 'Supporting Actor');  -- William Hurt for Alice (1990)
INSERT INTO worked_on VALUES(55, 2274, 'Supporting Actor');  -- Joe Mantegna for Alice (1990)
INSERT INTO worked_on VALUES(55, 2082, 'Supporting Actress');  -- June Squibb for Alice (1990)
INSERT INTO worked_on VALUES(55, 2289, 'Supporting Actress');  -- Julie Kavner for Alice (1990)
INSERT INTO worked_on VALUES(55, 949, 'Supporting Actress');  -- Judy Davis for Alice (1990)
INSERT INTO worked_on VALUES(55, 2290, 'Supporting Actress');  -- Cybill Shepherd for Alice (1990)
INSERT INTO worked_on VALUES(55, 656, 'Supporting Actor');  -- Alec Baldwin for Alice (1990)
INSERT INTO worked_on VALUES(55, 2138, 'Supporting Actor');  -- Bob Balaban for Alice (1990)
INSERT INTO worked_on VALUES(55, 2291, 'Cinematographer');  -- Carlo Di Palma for Alice (1990)
INSERT INTO worked_on VALUES(56, 351, 'Director');  -- Martin Scorsese for Alice Doesn't Live Here Anymore (1974)
INSERT INTO worked_on VALUES(56, 53, 'Supporting Actor');  -- Harvey Keitel for Alice Doesn't Live Here Anymore (1974)
INSERT INTO worked_on VALUES(56, 2292, 'Supporting Actor');  -- Kris Kristofferson for Alice Doesn't Live Here Anymore (1974)
INSERT INTO worked_on VALUES(58, 261, 'Director');  -- Tim Burton for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 2293, 'Lead Actress');  -- Mia Wasikowska for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 14, 'Supporting Actor');  -- Johnny Depp for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 124, 'Supporting Actress');  -- Helena Bonham Carter for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 167, 'Supporting Actress');  -- Anne Hathaway for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 2200, 'Supporting Actor');  -- Crispin Glover for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 40, 'Character Voice');  -- Michael Sheen for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 123, 'Character Voice');  -- Alan Rickman for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 2294, 'Character Voice');  -- Timothy Spall for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 1037, 'Character Voice');  -- Imelda Staunton for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(58, 2228, 'Character Voice');  -- Christopher Lee for Alice in Wonderland (2010)
INSERT INTO worked_on VALUES(59, 352, 'Director');  -- Ridley Scott for Alien (1979)
INSERT INTO worked_on VALUES(59, 2295, 'Supporting Actor');  -- Tom Skerritt for Alien (1979)
INSERT INTO worked_on VALUES(59, 958, 'Lead Actress');  -- Sigourney Weaver for Alien (1979)
INSERT INTO worked_on VALUES(59, 2296, 'Supporting Actor');  -- Harry Dean Stanton for Alien (1979)
INSERT INTO worked_on VALUES(59, 226, 'Supporting Actor');  -- John Hurt for Alien (1979)
INSERT INTO worked_on VALUES(59, 599, 'Supporting Actor');  -- Ian Holm for Alien (1979)
INSERT INTO worked_on VALUES(60, 352, 'Director');  -- Ridley Scott for Alien: The Director's Cut (2003)
INSERT INTO worked_on VALUES(60, 2295, 'Supporting Actor');  -- Tom Skerritt for Alien: The Director's Cut (2003)
INSERT INTO worked_on VALUES(60, 958, 'Lead Actress');  -- Sigourney Weaver for Alien: The Director's Cut (2003)
INSERT INTO worked_on VALUES(60, 2296, 'Supporting Actor');  -- Harry Dean Stanton for Alien: The Director's Cut (2003)
INSERT INTO worked_on VALUES(60, 226, 'Supporting Actor');  -- John Hurt for Alien: The Director's Cut (2003)
INSERT INTO worked_on VALUES(60, 599, 'Supporting Actor');  -- Ian Holm for Alien: The Director's Cut (2003)
INSERT INTO worked_on VALUES(61, 958, 'Lead Actress');  -- Sigourney Weaver for Alien Resurrection (1998)
INSERT INTO worked_on VALUES(61, 992, 'Supporting Actress');  -- Winona Ryder for Alien Resurrection (1998)
INSERT INTO worked_on VALUES(61, 581, 'Supporting Actor');  -- Brad Dourif for Alien Resurrection (1998)
INSERT INTO worked_on VALUES(61, 300, 'Director');  -- Jean-Pierre Jeunet for Alien Resurrection (1998)
INSERT INTO worked_on VALUES(63, 262, 'Director');  -- James Cameron for Aliens (1986)
INSERT INTO worked_on VALUES(63, 262, 'Screenwriter');  -- James Cameron for Aliens (1986)
INSERT INTO worked_on VALUES(63, 2128, 'Supporting Actor');  -- Bill Paxton for Aliens (1986)
INSERT INTO worked_on VALUES(64, 262, 'Director');  -- James Cameron for Aliens of the Deep (2005)
INSERT INTO worked_on VALUES(3582, 2282, 'Director');  -- John Lee Hancock for Saving Mr. Banks (2013)
INSERT INTO worked_on VALUES(3582, 94, 'Lead Actress');  -- Emma Thompson for Saving Mr. Banks (2013)
INSERT INTO worked_on VALUES(3582, 4, 'Supporting Actor');  -- Tom Hanks for Saving Mr. Banks (2013)
INSERT INTO worked_on VALUES(3582, 108, 'Supporting Actor');  -- Paul Giamatti for Saving Mr. Banks (2013)
INSERT INTO worked_on VALUES(3582, 1018, 'Small Part');  -- Rachel Griffiths for Saving Mr. Banks (2013)
INSERT INTO worked_on VALUES(3582, 50, 'Supporting Actor');  -- Colin Farrell for Saving Mr. Banks (2013)
INSERT INTO worked_on VALUES(3582, 2156, 'Supporting Actor');  -- Jason Schwartzman for Saving Mr. Banks (2013)
INSERT INTO worked_on VALUES(2185, 320, 'Director');  -- Sidney Lumet for Serpico (1973)
INSERT INTO worked_on VALUES(2185, 200, 'Small Part');  -- F. Murray Abraham for Serpico (1973)
INSERT INTO worked_on VALUES(65, 2297, 'Director');  -- Frank Marshall for Alive (1993)
INSERT INTO worked_on VALUES(65, 1900, 'Screenwriter');  -- John Patrick Shanley for Alive (1993)
INSERT INTO worked_on VALUES(65, 654, 'Lead Actor');  -- Ethan Hawke for Alive (1993)
INSERT INTO worked_on VALUES(66, 2298, 'Small Part');  -- Marilyn Monroe for All About Eve (1950)
INSERT INTO worked_on VALUES(67, 1172, 'Director');  -- Pedro Almodovar for All About My Mother (1999)
INSERT INTO worked_on VALUES(67, 1172, 'Screenwriter');  -- Pedro Almodovar for All About My Mother (1999)
INSERT INTO worked_on VALUES(68, 315, 'Director');  -- Mike Leigh for All or Nothing (2002)
INSERT INTO worked_on VALUES(68, 315, 'Screenwriter');  -- Mike Leigh for All or Nothing (2002)
INSERT INTO worked_on VALUES(68, 2294, 'Lead Actor');  -- Timothy Spall for All or Nothing (2002)
INSERT INTO worked_on VALUES(68, 2108, 'Supporting Actress');  -- Sally Hawkins for All or Nothing (2002)
INSERT INTO worked_on VALUES(68, 2299, 'Lead Actress');  -- Lesley Manville for All or Nothing (2002)
INSERT INTO worked_on VALUES(70, 940, 'Supporting Actress');  -- Jessica Lange for All That Jazz (1979)
INSERT INTO worked_on VALUES(71, 76, 'Lead Actor');  -- Robert Redford for All the President's Men (1976)
INSERT INTO worked_on VALUES(71, 5, 'Lead Actor');  -- Dustin Hoffman for All the President's Men (1976)
INSERT INTO worked_on VALUES(71, 668, 'Supporting Actor');  -- Hal Holbrook for All the President's Men (1976)
INSERT INTO worked_on VALUES(71, 587, 'Supporting Actor');  -- Ned Beatty for All the President's Men (1976)
INSERT INTO worked_on VALUES(71, 200, 'Small Part');  -- F. Murray Abraham for All the President's Men (1976)
INSERT INTO worked_on VALUES(71, 583, 'Supporting Actor');  -- Jack Warden for All the President's Men (1976)
INSERT INTO worked_on VALUES(71, 540, 'Supporting Actor');  -- Martin Balsam for All the President's Men (1976)
INSERT INTO worked_on VALUES(72, 292, 'Director');  -- David Gordon Green for All the Real Girls (2003)
INSERT INTO worked_on VALUES(72, 292, 'Screenwriter');  -- David Gordon Green for All the Real Girls (2003)
INSERT INTO worked_on VALUES(72, 2300, 'Lead Actor');  -- Paul Schneider for All the Real Girls (2003)
INSERT INTO worked_on VALUES(72, 2301, 'Lead Actress');  -- Zooey Deschanel for All the Real Girls (2003)
INSERT INTO worked_on VALUES(72, 2117, 'Supporting Actor');  -- Danny McBride for All the Real Girls (2003)
INSERT INTO worked_on VALUES(72, 1034, 'Supporting Actress');  -- Patricia Clarkson for All the Real Girls (2003)
INSERT INTO worked_on VALUES(72, 2302, 'Supporting Actor');  -- Shea Whigham for All the Real Girls (2003)
INSERT INTO worked_on VALUES(73, 273, 'Director');  -- Cameron Crowe for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 273, 'Screenwriter');  -- Cameron Crowe for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 2303, 'Lead Actor');  -- Patrick Fugit for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 15, 'Lead Actor');  -- Billy Crudup for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 6, 'Small Part');  -- Philip Seymour Hoffman for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 2301, 'Small Part');  -- Zooey Deschanel for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 2304, 'Supporting Actor');  -- Jason Lee for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 991, 'Small Part');  -- Anna Paquin for Almost Famous (2000)
INSERT INTO worked_on VALUES(73, 2130, 'Supporting Actor');  -- Noah Taylor for Almost Famous (2000)
INSERT INTO worked_on VALUES(74, 202, 'Lead Actor');  -- William Hurt for Altered States (1980)
INSERT INTO worked_on VALUES(74, 2138, 'Supporting Actor');  -- Bob Balaban for Altered States (1980)
INSERT INTO worked_on VALUES(75, 2305, 'Supporting Actor');  -- Jeffrey Jones for Amadeus (1984)
INSERT INTO worked_on VALUES(77, 300, 'Director');  -- Jean-Pierre Jeunet for Amelie (2001)
INSERT INTO worked_on VALUES(77, 2306, 'Lead Actress');  -- Audrey Tautou for Amelie (2001)
INSERT INTO worked_on VALUES(78, 2307, 'Supporting Actress');  -- Thora Birch for American Beauty (1999)
INSERT INTO worked_on VALUES(78, 2308, 'Supporting Actor');  -- Wes Bentley for American Beauty (1999)
INSERT INTO worked_on VALUES(78, 655, 'Supporting Actor');  -- Chris Cooper for American Beauty (1999)
INSERT INTO worked_on VALUES(79, 5, 'Lead Actor');  -- Dustin Hoffman for American Buffalo (1996)
INSERT INTO worked_on VALUES(79, 2309, 'Lead Actor');  -- Dennis Franz for American Buffalo (1996)
INSERT INTO worked_on VALUES(79, 325, 'Screenwriter');  -- David Mamet for American Buffalo (1996)
INSERT INTO worked_on VALUES(80, 1048, 'Lead Actress');  -- Ellen Page for An American Crime (2007)
INSERT INTO worked_on VALUES(80, 153, 'Lead Actress');  -- Catherine Keener for An American Crime (2007)
INSERT INTO worked_on VALUES(81, 308, 'Director');  -- Barbara Kopple for American Dream (1990)
INSERT INTO worked_on VALUES(81, 2310, 'Director');  -- Cathy Caplan for American Dream (1990)
INSERT INTO worked_on VALUES(81, 2311, 'Director');  -- Tom Haneke for American Dream (1990)
INSERT INTO worked_on VALUES(81, 2312, 'Director');  -- Lawrence Silk for American Dream (1990)
INSERT INTO worked_on VALUES(82, 163, 'Lead Actor');  -- Richard Dreyfuss for American Graffiti (1973)
INSERT INTO worked_on VALUES(82, 296, 'Lead Actor');  -- Ron Howard for American Graffiti (1973)
INSERT INTO worked_on VALUES(82, 26, 'Small Part');  -- Harrison Ford for American Graffiti (1973)
INSERT INTO worked_on VALUES(82, 2313, 'Supporting Actor');  -- Charles Martin Smith for American Graffiti (1973)
INSERT INTO worked_on VALUES(83, 2314, 'Director');  -- Tony Kaye for American History X (1998)
INSERT INTO worked_on VALUES(83, 2314, 'Cinematographer');  -- Tony Kaye for American History X (1998)
INSERT INTO worked_on VALUES(83, 2315, 'Lead Actor');  -- Edward Furlong for American History X (1998)
INSERT INTO worked_on VALUES(83, 556, 'Supporting Actor');  -- Elliott Gould for American History X (1998)
INSERT INTO worked_on VALUES(83, 2083, 'Supporting Actor');  -- Stacy Keach for American History X (1998)
INSERT INTO worked_on VALUES(83, 2316, 'Supporting Actress');  -- Beverly D'Angelo for American History X (1998)
INSERT INTO worked_on VALUES(83, 2317, 'Supporting Actor');  -- Ethan Suplee for American History X (1998)
INSERT INTO worked_on VALUES(84, 452, 'Lead Actor');  -- Gene Kelly for An American in Paris (1951)
INSERT INTO worked_on VALUES(85, 2318, 'Director');  -- Chris Smith for American Movie (1999)
INSERT INTO worked_on VALUES(86, 345, 'Director');  -- Rob Reiner for The American President (1995)
INSERT INTO worked_on VALUES(86, 2319, 'Screenwriter');  -- Aaron Sorkin for The American President (1995)
INSERT INTO worked_on VALUES(86, 79, 'Lead Actor');  -- Michael Douglas for The American President (1995)
INSERT INTO worked_on VALUES(86, 140, 'Lead Actress');  -- Annette Bening for The American President (1995)
INSERT INTO worked_on VALUES(86, 38, 'Supporting Actor');  -- Martin Sheen for The American President (1995)
INSERT INTO worked_on VALUES(86, 82, 'Supporting Actor');  -- Michael J. Fox for The American President (1995)
INSERT INTO worked_on VALUES(86, 163, 'Supporting Actor');  -- Richard Dreyfuss for The American President (1995)
INSERT INTO worked_on VALUES(87, 2320, 'Director');  -- Mary Harron for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 2320, 'Screenwriter');  -- Mary Harron for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 2321, 'Screenwriter');  -- Guinevere Turner for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 1, 'Lead Actor');  -- Christian Bale for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 2322, 'Supporting Actor');  -- Josh Lucas for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 2323, 'Supporting Actor');  -- Justin Theroux for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 1022, 'Supporting Actress');  -- Chloe Sevigny for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 60, 'Supporting Actress');  -- Reese Witherspoon for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 144, 'Supporting Actor');  -- Jared Leto for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 620, 'Supporting Actor');  -- Willem Dafoe for American Psycho (2000)
INSERT INTO worked_on VALUES(87, 2321, 'Small Part');  -- Guinevere Turner for American Psycho (2000)
